import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 4900;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 17: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 9º Ed. Física - Atletismo (9)
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O Atletismo é considerado o 'Esporte Base' porque seus movimentos derivam de:", options: ["Habilidades naturais humanas (correr, saltar, arremessar)", "Movimentos de máquinas industriais", "Passos de dança clássica", "Lutas medievais"], answer: "Habilidades naturais humanas (correr, saltar, arremessar)", explanation: "O atletismo sistematiza as ações motoras fundamentais do ser humano.", skill: "Atletismo" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual prova do atletismo é a mais rápida de todas (prova nobre)?", options: ["100 metros rasos", "Maratona", "Salto em altura", "Arremesso de peso"], answer: "100 metros rasos", explanation: "É a prova de velocidade máxima, durando cerca de 10 segundos no masculino.", skill: "Atletismo" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A prova de longa distância (42,195 km) no atletismo chama-se:", options: ["Maratona", "Decatlo", "Marcha Atlética", "Revezamento"], answer: "Maratona", explanation: "Inspirada no feito heróico do soldado grego Fidípides.", skill: "Atletismo" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "No salto em distância, o que determina a marca final do atleta?", options: ["A marca mais próxima da tábua deixada no tanque de areia", "A altura que ele atingiu no ar", "O tempo que ele levou para correr", "O barulho que ele fez ao cair"], answer: "A marca mais próxima da tábua deixada no tanque de areia", explanation: "A medição é feita da linha de impulsão até a última pegada na areia.", skill: "Atletismo" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual objeto os corredores entregam um ao outro nas provas de REVEZAMENTO?", options: ["Bastão", "Bola", "Bandeira", "Troféu"], answer: "Bastão", explanation: "O bastão deve ser passado dentro de uma zona específica de 20 metros.", skill: "Atletismo" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A Marcha Atlética diferencia-se da corrida porque o atleta deve sempre:", options: ["Manter um dos pés em contato com o solo", "Correr de costas", "Saltar obstáculos no caminho", "Usar sapatos pesados"], answer: "Manter um dos pés em contato com o solo", explanation: "Na marcha não pode haver a fase de voo (ambos os pés no ar).", skill: "Atletismo" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual destas é uma prova de LANÇAMENTO no atletismo?", options: ["Dardo", "Salto Triplo", "110m com barreiras", "Meia maratona"], answer: "Dardo", explanation: "O objetivo é atingir a maior distância jogando o dardo.", skill: "Atletismo" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O 'Bloco de Partida' é usado em quais provas?", options: ["Provas de velocidade (curta distância)", "Maratona apenas", "Salto com vara", "Arremesso de disco"], answer: "Provas de velocidade (curta distância)", explanation: "Ajuda na propulsão inicial e reação ao tiro de largada.", skill: "Atletismo" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "As provas combinadas do atletismo para homens (10 provas) e mulheres (7 provas) são:", options: ["Decatlo e Heptatlo", "Triatlo", "Pentatlo Moderno", "Octatlo apenas"], answer: "Decatlo e Heptatlo", explanation: "Testam a versatilidade do atleta em diversos tipos de provas.", skill: "Atletismo" },

  // 9º Ed. Física - Ética no Esporte (9)
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O termo 'Fair Play' no esporte significa:", options: ["Jogo limpo / Respeito às regras e adversários", "Ganhar a qualquer custo", "Brincar durante a partida", "Jogar apenas por diversão sem regras"], answer: "Jogo limpo / Respeito às regras e adversários", explanation: "A ética esportiva valoriza a integridade e o respeito.", skill: "Ética no Esporte" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O que é considerado 'Doping' no esporte?", options: ["Uso de substâncias proibidas para aumentar o desempenho", "Beber muita água", "Dormir 8 horas por dia", "Usar chuteiras novas"], answer: "Uso de substâncias proibidas para aumentar o desempenho", explanation: "O doping é desonesto e prejudicial à saúde do atleta.", skill: "Ética no Esporte" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual atitude demonstra Falta de Ética em uma competição?", options: ["Fingir uma falta para enganar o árbitro", "Ajudar um adversário caído", "Respeitar a decisão do juiz mesmo discordando", "Parabenizar o vencedor"], answer: "Fingir uma falta para enganar o árbitro", explanation: "Simulação e trapaça ferem o espírito do esporte.", skill: "Ética no Esporte" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A discriminação ou racismo nos estádios e quadras é:", options: ["Inaceitável e punível por lei e federações", "Uma tradição permitida", "Apenas parte da torcida 'nervosa'", "Direito de liberdade de expressão"], answer: "Inaceitável e punível por lei e federações", explanation: "O esporte deve ser espaço de inclusão e respeito humano.", skill: "Ética no Esporte" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O 'Espírito Olímpico' prega que mais importante que vencer é:", options: ["Participar e dar o seu melhor com dignidade", "Ter os melhores equipamentos", "Ser famoso e rico", "Comprar medalhas"], answer: "Participar e dar o seu melhor com dignidade", explanation: "A jornada e o esforço individual e coletivo são o foco.", skill: "Ética no Esporte" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Manipulação de resultados (combinar placares para apostas) é:", options: ["Crime contra a integridade do esporte", "Estratégia inteligente de negócio", "Sorte das equipes", "Segredo de vestiário"], answer: "Crime contra a integridade do esporte", explanation: "Destrói a credibilidade das competições e é ilegal.", skill: "Ética no Esporte" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual o papel do árbitro na perspectiva da ética esportiva?", options: ["Garantir a justiça e a aplicação das regras", "Ajudar o time da casa", "Ser o centro das atenções", "Ganhar dinheiro"], answer: "Garantir a justiça e a aplicação das regras", explanation: "O árbitro é o juiz imparcial do cumprimento da norma esportiva.", skill: "Ética no Esporte" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O respeito ao hino nacional e bandeira do adversário é:", options: ["Um dever de civilidade e respeito entre povos", "Desnecessário", "Proibido por lei", "Zombaria estratégica"], answer: "Um dever de civilidade e respeito entre povos", explanation: "O esporte é ferramenta de paz e diplomacia cultural.", skill: "Ética no Esporte" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O que um atleta deve fazer ao perceber que o árbitro errou a seu favor?", options: ["Sendo ético, reconhecer o ocorrido (como o 'Gesto de Fair Play')", "Ficar quieto e aproveitar o erro", "Rir do adversário", "Pagar o árbitro"], answer: "Sendo ético, reconhecer o ocorrido (como o 'Gesto de Fair Play')", explanation: "Honestidade acima da vantagem imediata.", skill: "Ética no Esporte" },

  // 6º Ed. Física - Saúde e Corpo (9)
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Para manter a saúde do corpo, a atividade física deve ser:", options: ["Regular e equilibrada", "Apenas uma vez por mês", "Feita até sentir dor extrema", "Totalmente evitada"], answer: "Regular e equilibrada", explanation: "A constância traz benefícios cardíacos, musculares e mentais.", skill: "Saúde e Corpo" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual hábito alimentar é ESSENCIAL para quem pratica esportes?", options: ["Beber muita água e ter dieta variada", "Comer apenas doces e frituras", "Ficar sem comer por 2 dias", "Beber apenas refrigerante"], answer: "Beber muita água e ter dieta variada", explanation: "Hidratação e nutrientes são o combustível do corpo.", skill: "Saúde e Corpo" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O 'Sedentarismo' (falta de exercícios) pode causar:", options: ["Obesidade e doenças do coração", "Superpoderes de inteligência", "Crescimento acelerado", "Visão noturna"], answer: "Obesidade e doenças do coração", explanation: "A inatividade física é fator de risco para muitas doenças.", skill: "Saúde e Corpo" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "A higiene pessoal após a atividade física serve para:", options: ["Prevenir doenças de pele e odores e manter o bem-estar", "Gastar água à toa", "Ficar com frio", "Pintar o corpo"], answer: "Prevenir doenças de pele e odores e manter o bem-estar", explanation: "O suor e o contato com superfícies exigem limpeza posterior.", skill: "Saúde e Corpo" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Dormir cerca de 8 a 9 horas por dia ajuda o atleta a:", options: ["Recuperar as energias e crescer com saúde", "Ficar mais cansado", "Perder tempo de jogo", "Esquecer as regras"], answer: "Recuperar as energias e crescer com saúde", explanation: "O sono é fundamental para a recuperação muscular e cognitiva.", skill: "Saúde e Corpo" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O que é o IMC (Índice de Massa Corporal)?", options: ["Uma conta que relaciona peso e altura", "O nome de um esporte novo", "A velocidade máxima de corrida", "O número de batimentos"], answer: "Uma conta que relaciona peso e altura", explanation: "Ajuda a identificar se o peso está adequado para a estatura.", skill: "Saúde e Corpo" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "A prática de exercícios liberam substâncias no cérebro que geram:", options: ["Sensação de bem-estar e felicidade (endorfina)", "Raiva e estresse constantes", "Sono imediato durante a aula", "Falta de memória"], answer: "Sensação de bem-estar e felicidade (endorfina)", explanation: "O exercício é um excelente remédio natural contra ansiedade.", skill: "Saúde e Corpo" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Ter uma boa postura ao sentar e carregar a mochila protege o(a):", options: ["Coluna vertebral", "Cérebro", "Ouvido", "Estômago"], answer: "Coluna vertebral", explanation: "Evita dores e desvios nas costas a longo prazo.", skill: "Saúde e Corpo" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Quem deve ser consultado antes de iniciar atividades físicas intensas?", options: ["Médico", "Vizinho", "Apenas o Google", "Ninguém"], answer: "Médico", explanation: "A avaliação médica garante que o corpo está apto ao esforço.", skill: "Saúde e Corpo" },

  // 6º Ed. Física - Preparação Física (9)
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O que deve ser feito ANTES de qualquer esporte para evitar lesões?", options: ["Aquecimento", "Dormir", "Comer uma feijoada", "Tomar banho gelado"], answer: "Aquecimento", explanation: "O aquecimento prepara os músculos e o coração para o esforço.", skill: "Preparação Física" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O alongamento tem como principal objetivo aumentar a:", options: ["Flexibilidade muscular", "Força dos ossos", "Audição", "Visão"], answer: "Flexibilidade muscular", explanation: "Melhora a amplitude dos movimentos.", skill: "Preparação Física" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Exercícios constantes de corrida e natação desenvolvem a resistência:", options: ["Cardiorrespiratória", "Mental apenas", "De equilíbrio", "Totalmente estática"], answer: "Cardiorrespiratória", explanation: "Melhoram a capacidade do coração e pulmões.", skill: "Preparação Física" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O uso de roupas adequadas (leves e tênis) na aula serve para:", options: ["Conforto, segurança e liberdade de movimento", "Ficar na moda apenas", "Poder dormir depois", "Apenas uniforme"], answer: "Conforto, segurança e liberdade de movimento", explanation: "Roupas inadequadas podem causar quedas ou assaduras.", skill: "Preparação Física" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Descansar entre as séries de exercícios é importante para:", options: ["Não sobrecarregar o corpo e permitir a recuperação", "Poder mexer no celular", "Desistir do exercício", "Apenas para beber água"], answer: "Não sobrecarregar o corpo e permitir a recuperação", explanation: "O descanso faz parte do treinamento correto.", skill: "Preparação Física" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual a importância de beber água DURANTE os exercícios?", options: ["Manter o corpo hidratado e regular a temperatura", "Ficar mais pesado", "Fazer o exercício parar", "Dar sorte"], answer: "Manter o corpo hidratado e regular a temperatura", explanation: "Perdemos água através do suor.", skill: "Preparação Física" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "A progressão no treinamento significa que devemos:", options: ["Aumentar a dificuldade aos poucos, conforme o corpo acostuma", "Fazer o mais difícil logo no primeiro dia", "Fazer sempre o mesmo sem mudar nada", "Parar assim que cansar 1 minuto"], answer: "Aumentar a dificuldade aos poucos, conforme o corpo acostuma", explanation: "Respeitar o limite do corpo evita lesões graves.", skill: "Preparação Física" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Controlar a respiração durante o esforço físico ajuda a:", options: ["Manter o fôlego e oxigenar o sangue melhor", "Ficar tonto rápido", "Falar mais alto", "Cantar melhor"], answer: "Manter o fôlego e oxigenar o sangue melhor", explanation: "A respiração correta otimiza o desempenho.", skill: "Preparação Física" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O desaquecimento (volta à calma) ao final serve para:", options: ["Fazer os batimentos voltarem ao normal suavemente", "Poder ir embora correndo", "Ganhar massa muscular na hora", "Nada, é perda de tempo"], answer: "Fazer os batimentos voltarem ao normal suavemente", explanation: "Evita tonturas e ajuda na remoção de resíduos musculares.", skill: "Preparação Física" },

  // 8º Ed. Física - Capacidades Físicas (9)
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A capacidade de realizar movimentos com a maior amplitude possível chama-se:", options: ["Flexibilidade", "Força", "Velocidade", "Agilidade"], answer: "Flexibilidade", explanation: "Vem da elasticidade muscular e articular.", skill: "Capacidades Físicas" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A capacidade física de vencer uma resistência através da contração muscular é a:", options: ["Força", "Resistência", "Equilíbrio", "Ritmo"], answer: "Força", explanation: "Essencial para levantar pesos ou empurrar objetos.", skill: "Capacidades Físicas" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A capacidade de realizar ações motoras no menor tempo possível é a:", options: ["Velocidade", "Coordenação", "Flexibilidade", "Força Explosiva"], answer: "Velocidade", explanation: "Rapidez de deslocamento ou reação.", skill: "Capacidades Físicas" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Mudar a direção do corpo rapidamente enquanto corre define a:", options: ["Agilidade", "Velocidade linear", "Força pura", "Resistência"], answer: "Agilidade", explanation: "Combinada com a velocidade e o equilíbrio.", skill: "Capacidades Físicas" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Manter o corpo em uma posição estável, parado ou em movimento, é o:", options: ["Equilíbrio", "Ritmo", "Coordenação motora", "Velocidade"], answer: "Equilíbrio", explanation: "Pode ser estático (parado) ou dinâmico (movendo).", skill: "Capacidades Físicas" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A capacidade de sustentar um esforço físico por um longo tempo é a:", options: ["Resistência", "Velocidade", "Força", "Potência"], answer: "Resistência", explanation: "Pode ser aeróbica ou anaeróbica.", skill: "Capacidades Físicas" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A capacidade de combinar vários movimentos complexos de forma eficiente é a:", options: ["Coordenação Motora", "Agilidade apenas", "Força bruta", "Flexibilidade"], answer: "Coordenação Motora", explanation: "Ex: fazer embaixadinhas ou tocar piano.", skill: "Capacidades Físicas" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Qual capacidade é mais exigida de um velocista de 100 metros?", options: ["Velocidade e Força Explosiva", "Resistência de maratona", "Flexibilidade total", "Equilíbrio estático"], answer: "Velocidade e Força Explosiva", explanation: "Precisa de muita energia em muito pouco tempo.", skill: "Capacidades Físicas" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "O treinamento das capacidades físicas serve para:", options: ["Melhorar a saúde, a estética e o desempenho esportivo", "Apenas para atletas olímpicos", "Não serve para nada", "Apenas para emagrecer"], answer: "Melhorar a saúde, a estética e o desempenho esportivo", explanation: "Desenvolve o corpo de forma integral.", skill: "Capacidades Físicas" },

  // 8º Ed. Física - Capoeira (9)
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A Capoeira é uma manifestação cultural brasileira que mistura:", options: ["Luta, dança, música e jogo", "Apenas futebol e basquete", "Luta livre e balé clássico", "Boxe e canto coral"], answer: "Luta, dança, música e jogo", explanation: "Criada por escravizados africanos no Brasil como forma de resistência.", skill: "Capoeira" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Qual o nome do movimento básico da capoeira, que serve de base para todos os outros?", options: ["Ginga", "Rasteira", "Aú", "Cutilada"], answer: "Ginga", explanation: "A ginga mantém o capoeirista em constante movimento e desequilibra o oponente.", skill: "Capoeira" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "O principal instrumento musical da capoeira, que comanda o ritmo, é o:", options: ["Berimbau", "Violão", "Flauta", "Piano"], answer: "Berimbau", explanation: "O toque do berimbau determina a velocidade e o tipo do jogo.", skill: "Capoeira" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "O local onde os capoeiristas se reúnem para jogar chama-se:", options: ["Roda de Capoeira", "Arena de luta", "Campo de batalha", "Pista de dança"], answer: "Roda de Capoeira", explanation: "A roda é o espaço sagrado e comunitário da prática.", skill: "Capoeira" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Qual estilo de capoeira é mais lento e focado na tradição e malícia?", options: ["Capoeira Angola", "Capoeira Regional", "Capoeira Contemporânea", "Judô-poeira"], answer: "Capoeira Angola", explanation: "Preservada pelo mestre Pastinha.", skill: "Capoeira" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Mestre Bimba foi o criador de qual estilo de capoeira?", options: ["Capoeira Regional", "Capoeira de Rua", "Capoeira Lenta", "Capoeira Africana pura"], answer: "Capoeira Regional", explanation: "Introduziu métodos de ensino e golpes mais rápidos e altos.", skill: "Capoeira" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "O movimento acrobático de 'dar estrela' na capoeira chama-se:", options: ["Aú", "Meia-lua de compasso", "Macaco", "Cocorinha"], answer: "Aú", explanation: "Movimento de locomoção e esquiva lateral.", skill: "Capoeira" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A capoeira foi reconhecida mundialmente pela UNESCO como:", options: ["Patrimônio Cultural Imaterial da Humanidade", "Crime organizado", "Apenas um esporte escolar", "Manifestação de guerra apenas"], answer: "Patrimônio Cultural Imaterial da Humanidade", explanation: "Pela sua importância histórica e cultural única no mundo.", skill: "Capoeira" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Os cânticos na roda de capoeira (corridos e ladainhas) servem para:", options: ["Contar histórias, saudar mestres e ditar o ritmo", "Incentivar brigas reais", "Pedir silêncio", "Apenas distrair"], answer: "Contar histórias, saudar mestres e ditar o ritmo", explanation: "A música é parte indissociável da luta.", skill: "Capoeira" },

  // 9º Ed. Física - Saúde e Prevenção (9)
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O uso do protetor solar ao praticar esportes ao ar livre previne:", options: ["Câncer de pele e queimaduras", "Quedas e fraturas", "Dores de cabeça apenas", "Cãibras"], answer: "Câncer de pele e queimaduras", explanation: "A radiação UV é nociva acumulativamente.", skill: "Saúde e Prevenção" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual a importância de usar calçados adequados no esporte?", options: ["Evitar lesões nas articulações (tornozelo/joelho) e quedas", "Ficar mais alto que o oponente", "Apenas estética", "Ganhar na corrida garantido"], answer: "Evitar lesões nas articulações (tornozelo/joelho) e quedas", explanation: "O amortecimento e o solado correto são itens de segurança.", skill: "Saúde e Prevenção" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Dores musculares intensas após o exercício indicam que devemos:", options: ["Respeitar o repouso e não exagerar na carga", "Fazer o dobro de exercício no dia seguinte", "Ignorar e tomar remédios fortes", "Parar de fazer exercícios para sempre"], answer: "Respeitar o repouso e não exagerar na carga", explanation: "O excesso pode causar lesões graves ou overtraining.", skill: "Saúde e Prevenção" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A 'Ergonomia' na prática de atividade física foca em:", options: ["Adaptar os movimentos e aparelhos à postura correta do corpo", "Ser o mais forte da turma", "Fazer tudo rápido", "Não usar aparelhos nunca"], answer: "Adaptar os movimentos e aparelhos à postura correta do corpo", explanation: "Busca evitar lesões por repetição ou esforço errado.", skill: "Saúde e Prevenção" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Em dias de muito calor, a prevenção contra a desidratação exige:", options: ["Aumentar a ingestão de água e evitar horários de sol forte", "Não beber nada", "Correr com agasalhos pesados", "Comer sal"], answer: "Aumentar a ingestão de água e evitar horários de sol forte", explanation: "A insolação e desidratação podem ser fatais.", skill: "Saúde e Prevenção" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O exame de 'Check-up' esportivo serve para detectar:", options: ["Problemas cardíacos ou físicos silenciosos", "Se o atleta vai ganhar o jogo", "A cor dos olhos", "Apenas a altura"], answer: "Problemas cardíacos ou físicos silenciosos", explanation: "Evita o risco de morte súbita e outras complicações.", skill: "Saúde e Prevenção" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Quais comportamentos de risco devem ser evitados por jovens atletas?", options: ["Uso de anabolizantes, álcool e drogas", "Beber água gelada", "Dormir demais", "Estudar"], answer: "Uso de anabolizantes, álcool e drogas", explanation: "Prejudicam permanentemente o desenvolvimento físico e mental.", skill: "Saúde e Prevenção" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O uso de equipamentos de proteção (capacete, joelheira) é obrigatório em:", options: ["Skate, Ciclismo e outros esportes de impacto/rodas", "Xadrez", "Natação recreativa", "Caminhada lenta"], answer: "Skate, Ciclismo e outros esportes de impacto/rodas", explanation: "Reduzem drasticamente os traumas em quedas.", skill: "Saúde e Prevenção" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A prevenção da obesidade infantil e juvenil é feita através da:", options: ["Combinação de alimentação saudável e exercícios físicos", "Apenas dietas da internet", "Uso de remédios para emagrecer", "Cirurgia imediata"], answer: "Combinação de alimentação saudável e exercícios físicos", explanation: "Balanço energético equilibrado.", skill: "Saúde e Prevenção" },

  // 7º Geografia - Ciclo Hidrológico (9)
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "No ciclo da água, a transformação da água líquida em vapor pelo sol chama-se:", options: ["Evaporação", "Condensação", "Precipitação", "Infiltração"], answer: "Evaporação", explanation: "Ocorre principalmente nos oceanos, rios e lagos.", skill: "Ciclo Hidrológico" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "Quando o vapor de água esfria na atmosfera e forma as nuvens, ocorre a:", options: ["Condensação", "Transpiração", "Sublimação", "Fusão"], answer: "Condensação", explanation: "Mudança do estado gasoso para o líquido em pequenas gotas.", skill: "Ciclo Hidrológico" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "Como chamamos a queda de água da atmosfera (chuva, neve ou granizo)?", options: ["Precipitação", "Infiltração", "Escoamento", "Erosão"], answer: "Precipitação", explanation: "É a forma como a água retorna à superfície terrestre.", skill: "Ciclo Hidrológico" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "A água que penetra no solo e alimenta os lençóis freáticos sofre o processo de:", options: ["Infiltração", "Evaporação", "Radiação", "Navegação"], answer: "Infiltração", explanation: "O solo funciona como uma esponja e filtro natural.", skill: "Ciclo Hidrológico" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "O que é 'Evapotranspiração'?", options: ["Soma da evaporação do solo com a transpiração das plantas", "O suor das pessoas nas ruas", "A subida da maré", "O gelo derretendo"], answer: "Soma da evaporação do solo com a transpiração das plantas", explanation: "Processo vital vindo das florestas e vegetação.", skill: "Ciclo Hidrológico" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "A maior parte da água doce do planeta está localizada em:", options: ["Geleiras e calotas polares", "Rios e lagos", "Atmosfera", "Atrás das casas"], answer: "Geleiras e calotas polares", explanation: "Embora seja difícil o acesso, é o maior reservatório de água doce.", skill: "Ciclo Hidrológico" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "A água que corre sobre a superfície da terra até chegar aos rios e mares é o:", options: ["Escoamento superficial", "Magma", "Vento", "Lava"], answer: "Escoamento superficial", explanation: "Pode causar erosão se não houver cobertura vegetal.", skill: "Ciclo Hidrológico" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "O ciclo da água é considerado um ciclo 'fechado' porque:", options: ["A quantidade total de água na Terra permanece quase a mesma", "A água desaparece depois da chuva", "Só acontece no inverno", "As nuvens não deixam a água sair do planeta"], answer: "A quantidade total de água na Terra permanece quase a mesma", explanation: "Ela apenas muda de estado físico e lugar.", skill: "Ciclo Hidrológico" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "Qual o principal motor (energia) que faz o ciclo da água funcionar?", options: ["Sol (Calor)", "Vento", "Gravidade apenas", "Luz da lua"], answer: "Sol (Calor)", explanation: "O sol fornece o calor necessário para a evaporação.", skill: "Ciclo Hidrológico" },

  // 8º Arte - Gravura (9)
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A 'Gravura' é uma técnica artística que consiste em:", options: ["Produzir múltiplas cópias a partir de uma matriz", "Pintar uma tela única apenas", "Cantar em coro", "Esculpir em mármore original"], answer: "Produzir múltiplas cópias a partir de uma matriz", explanation: "A matriz pode ser de madeira, metal, pedra, etc.", skill: "Gravura" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A técnica de gravura em madeira chama-se:", options: ["Xilogravura", "Litografia", "Serigrafia", "Calcogravura"], answer: "Xilogravura", explanation: "Muito comum em literatura de cordel no Nordeste brasileiro.", skill: "Gravura" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Na 'Litografia', a matriz utilizada para a impressão é de:", options: ["Pedra", "Plástico", "Vidro", "Tecido"], answer: "Pedra", explanation: "Usa a repulsão entre água e gordura para criar a imagem.", skill: "Gravura" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual técnica de gravura utiliza o metal (como cobre) como matriz?", options: ["Calcogravura (Engraving)", "Xilogravura", "Isogravura", "Desenho a caneta"], answer: "Calcogravura (Engraving)", explanation: "O desenho é feito com ferramentas que sulcam o metal.", skill: "Gravura" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A 'Serigrafia' (ou Silkscreen) usa qual material para transferir a tinta?", options: ["Uma tela de tecido (seda ou nylon)", "Um carimbo de borracha", "Uma chapa de concreto", "Apenas as mãos"], answer: "Uma tela de tecido (seda ou nylon)", explanation: "Muito usada em camisetas e pôsteres.", skill: "Gravura" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O instrumento usado para entalhar a madeira na xilogravura é o(a):", options: ["Goiva", "Pincel", "Lápis", "Martelo pneumático"], answer: "Goiva", explanation: "Ferramenta de metal com ponta afiada em 'V' ou 'U'.", skill: "Gravura" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A principal vantagem da gravura na história foi:", options: ["Democratizar a arte (permitindo que mais pessoas tivessem acesso)", "Ser mais cara que a pintura", "Ser impossível de copiar", "Não precisar de tinta"], answer: "Democratizar a arte (permitindo que mais pessoas tivessem acesso)", explanation: "Uma obra podia ser reproduzida centenas de vezes.", skill: "Gravura" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Como se chama o ato de passar tinta na matriz e pressionar no papel?", options: ["Impressão ou Estampagem", "Desenho cego", "Colagem", "Erosão"], answer: "Impressão ou Estampagem", explanation: "É a fase final da criação da gravura.", skill: "Gravura" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "As ilustrações de folhetos de Cordel no Brasil são tradicionalmente feitas em:", options: ["Xilogravura", "Foto digital", "Pintura a óleo", "Aquarela"], answer: "Xilogravura", explanation: "Marca visual inconfundível da cultura nordestina.", skill: "Gravura" },

  // 9º Arte - Dadaísmo (9)
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O Dadaísmo surgiu como uma reação de protesto contra qual evento?", options: ["Primeira Guerra Mundial", "Descobrimento da América", "Queda do Império Romano", "Invenção do Computador"], answer: "Primeira Guerra Mundial", explanation: "Os artistas achavam que a lógica da sociedade levou ao caos da guerra.", skill: "Dadaísmo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Uma característica fundamental do movimento Dadaísta é o uso do:", options: ["Absurdo, deboche e 'Nonsense' (falta de sentido)", "Beleza clássica perfeita", "Realismo extremo", "Religiosidade intensa"], answer: "Absurdo, deboche e 'Nonsense' (falta de sentido)", explanation: "Queriam chocar a sociedade e questionar a própria arte.", skill: "Dadaísmo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Qual o nome do artista dadá que transformou um mictório em obra de arte ('A Fonte')?", options: ["Marcel Duchamp", "Salvador Dalí", "Anita Malfatti", "Van Gogh"], answer: "Marcel Duchamp", explanation: "Introduziu o conceito de 'Ready-made'.", skill: "Dadaísmo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O conceito de 'Ready-made' consiste em:", options: ["Pegar um objeto cotidiano de fábrica e declará-lo arte", "Pintar um quadro em 5 minutos", "Vender arte pronta em supermercado", "Fazer esculturas de bolo"], answer: "Pegar um objeto cotidiano de fábrica e declará-lo arte", explanation: "Questiona o valor da técnica e o papel do artista.", skill: "Dadaísmo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Por que o nome 'Dadá' foi escolhido?", options: ["Escolha aleatória de uma palavra sem sentido em um dicionário", "Homenagem ao pai do líder", "Significa arte em grego", "Refere-se a um tipo de tinta"], answer: "Escolha aleatória de uma palavra sem sentido em um dicionário", explanation: "Reflete o princípio da aleatoriedade do grupo.", skill: "Dadaísmo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A técnica de colar recortes de jornais e fotos de forma caótica no Dadaísmo é a:", options: ["Fotomontagem / Colagem", "Pintura a óleo", "Afresco", "Mosaico"], answer: "Fotomontagem / Colagem", explanation: "Usada para fazer críticas políticas e sociais irônicas.", skill: "Dadaísmo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O Dadaísmo é considerado um movimento de 'Anti-arte' porque:", options: ["Desejava destruir as regras tradicionais do que era considerado artístico", "As pessoas não sabiam desenhar", "Era proibido pelo governo", "Só existia em segredo"], answer: "Desejava destruir as regras tradicionais do que era considerado artístico", explanation: "Buscavam a liberdade total, livre de padrões burgueses.", skill: "Dadaísmo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Onde os dadaístas costumavam se reunir inicialmente em Zurique?", options: ["Cabaret Voltaire", "Museu do Louvre", "Palácio Real", "Estádio de futebol"], answer: "Cabaret Voltaire", explanation: "Local de performances bizarras e ruidosas.", skill: "Dadaísmo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Qual movimento artístico posterior foi muito influenciado pelos sonhos e pelo Dadaísmo?", options: ["Surrealismo", "Impressionismo", "Cubismo", "Barroco"], answer: "Surrealismo", explanation: "Muitos dadaístas migraram para o surrealismo depois.", skill: "Dadaísmo" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 17 com ${batch.length} questões adicionado.`);
