import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 4800;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 16: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 8º Português - Conjunções (9)
  { grade: "8º", discipline: "Português", type: "multiple", text: "As conjunções 'e', 'nem', 'mas também' são classificadas como:", options: ["Aditivas", "Adversativas", "Conclusivas", "Explicativas"], answer: "Aditivas", explanation: "As conjunções aditivas ligam orações ou palavras, expressando a ideia de acréscimo.", skill: "Conjunções" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Na frase 'Eu queria sair, MAS está chovendo', a conjunção expressa:", options: ["Oposição/Contraste", "Adição", "Causa", "Finalidade"], answer: "Oposição/Contraste", explanation: "'Mas' é uma conjunção adversativa.", skill: "Conjunções" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Qual destas frases possui uma conjunção CONCLUSIVA?", options: ["Estudei muito, portanto fui bem.", "Vou se você for.", "Saí porque estava cansado.", "Comi pão e queijo."], answer: "Estudei muito, portanto fui bem.", explanation: "'Portanto' introduz uma conclusão lógica.", skill: "Conjunções" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "As conjunções 'ou... ou', 'ora... ora' são chamadas de:", options: ["Alternativas", "Explicativas", "Integrantes", "Temporais"], answer: "Alternativas", explanation: "Expressam exclusão ou alternância entre os fatos.", skill: "Conjunções" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Complete: 'Não saímos de casa ________ estava ventando muito.'", options: ["porque", "portanto", "entretanto", "conforme"], answer: "porque", explanation: "'Porque' funciona como conjunção explicativa ou causal aqui.", skill: "Conjunções" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "A conjunção 'Embora' introduz uma ideia de:", options: ["Concessão (contraste que não impede a ação)", "Tempo", "Comparação", "Condição"], answer: "Concessão (contraste que não impede a ação)", explanation: "'Embora' é a principal conjunção concessiva.", skill: "Conjunções" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Na frase 'SE chover, não haverá jogo', a palavra SE é:", options: ["Conjunção Condicional", "Pronome", "Substantivo", "Adjetivo"], answer: "Conjunção Condicional", explanation: "Estabelece uma condição necessária para o fato ocorrer.", skill: "Conjunções" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Qual conjunção estabelece uma RELAÇÃO DE TEMPO?", options: ["Quando", "Como", "Se", "Talvez"], answer: "Quando", explanation: "Indica o momento em que a ação ocorre.", skill: "Conjunções" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "As conjunções que ligam orações independentes entre si são chamadas:", options: ["Coordenativas", "Subordinativas", "Modais", "Inexistentes"], answer: "Coordenativas", explanation: "Ex: Aditivas, Adversativas, Alternativas, Conclusivas e Explicativas.", skill: "Conjunções" },

  // 9º Português - Argumentação (9)
  { grade: "9º", discipline: "Português", type: "multiple", text: "Qual o objetivo principal de um texto argumentativo?", options: ["Convencer o leitor sobre um ponto de vista", "Apenas contar uma história engraçada", "Descrever um objeto detalhadamente", "Ensinar a fazer uma receita"], answer: "Convencer o leitor sobre um ponto de vista", explanation: "Baseia-se na defesa de uma tese através de argumentos.", skill: "Argumentação" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "A 'Tese' em uma argumentação é:", options: ["A ideia central ou opinião defendida", "O nome do autor", "A conclusão final apenas", "O primeiro parágrafo"], answer: "A ideia central ou opinião defendida", explanation: "É a afirmação que o autor pretende provar ser válida.", skill: "Argumentação" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Citar especialistas ou autoridades no assunto para reforçar o texto chama-se:", options: ["Argumento de Autoridade", "Fofoca", "Exemplificação apenas", "Ironia"], answer: "Argumento de Autoridade", explanation: "Dá credibilidade ao texto através do saber de outrem.", skill: "Argumentação" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "O uso de dados estatísticos em um texto serve para:", options: ["Dar base científica e comprovação aos fatos", "Deixar o texto mais bonito", "Confundir o leitor", "Aumentar o número de palavras"], answer: "Dar base científica e comprovação aos fatos", explanation: "Dados são argumentos de prova concreta.", skill: "Argumentação" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "A 'Contra-argumentação' consiste em:", options: ["Apresentar e rebater ideias contrárias à sua", "Aceitar tudo o que o outro diz", "Parar de escrever", "Gritar com o oponente"], answer: "Apresentar e rebater ideias contrárias à sua", explanation: "Fortalece a tese ao mostrar que as objeções não se sustentam.", skill: "Argumentação" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Um argumento fundamentado em 'causa e consequência' busca mostrar:", options: ["O motivo e o resultado de um fato", "Apenas o passado", "Uma mentira", "A opinião do autor sem provas"], answer: "O motivo e o resultado de um fato", explanation: "Estabelece uma lógica racional de conexão entre eventos.", skill: "Argumentação" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Em um artigo de opinião, o autor deve usar linguagem:", options: ["Clara, objetiva e persuasiva", "Totalmente informal e cheia de gírias", "Poética e sem sentido lógico", "Proibida para menores"], answer: "Clara, objetiva e persuasiva", explanation: "O foco é a clareza para garantir a adesão do leitor.", skill: "Argumentação" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Qual elemento é essencial para ligar os argumentos de forma lógica?", options: ["Operadores argumentativos (conjunções/advérbios)", "Muitas exclamações", "Letras maiúsculas em tudo", "Desenhos explicativos"], answer: "Operadores argumentativos (conjunções/advérbios)", explanation: "Marcam a progressão lógica do pensamento (mas, portanto, além disso).", skill: "Argumentação" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "A conclusão de um texto argumentativo deve:", options: ["Retomar a tese e sintetizar os argumentos", "Criar um novo problema inesperado", "Falar de outro assunto", "Terminar sem ponto final"], answer: "Retomar a tese e sintetizar os argumentos", explanation: "Fecha o raciocínio, reforçando o que foi proposto inicialmente.", skill: "Argumentação" },

  // 7º Português - Tipos de Texto (9)
  { grade: "7º", discipline: "Português", type: "multiple", text: "O texto que conta uma história com personagens, tempo e espaço chama-se:", options: ["Narrativo", "Descritivo", "Injuntivo", "Expositivo"], answer: "Narrativo", explanation: "Exemplos: contos, romances, fábulas.", skill: "Tipos de Texto" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Textos como receitas de bolo ou manuais de instrução são classificados como:", options: ["Injuntivos (Instrucionais)", "Poéticos", "Argumentativos", "Científicos"], answer: "Injuntivos (Instrucionais)", explanation: "Sua função é orientar uma ação passo a passo.", skill: "Tipos de Texto" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Qual a função principal de um texto DESCRITIVO?", options: ["Apresentar características de seres, objetos ou lugares", "Contar uma piada", "Dar ordens", "Defender uma ideia política"], answer: "Apresentar características de seres, objetos ou lugares", explanation: "É um retrato feito com palavras.", skill: "Tipos de Texto" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "O 'Relato de Viagem' é um exemplo de texto predominantemente:", options: ["Narrativo", "Poético", "Teatral", "Publicitário"], answer: "Narrativo", explanation: "Conta os acontecimentos vividos em uma sequência temporal.", skill: "Tipos de Texto" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "A 'Notícia' de jornal tem como objetivo principal:", options: ["Informar o leitor sobre um fato real e atual", "Fazer o leitor chorar", "Vender produtos", "Ensinar geografia"], answer: "Informar o leitor sobre um fato real e atual", explanation: "Texto informativo e objetivo (gênero jornalístico).", skill: "Tipos de Texto" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "A crônica é um gênero textual que mistura:", options: ["Literatura e observação do cotidiano", "Matemática e Biologia", "Apenas leis pesadas", "Códigos secretos"], answer: "Literatura e observação do cotidiano", explanation: "Parte de fatos simples do dia a dia para uma reflexão artística.", skill: "Tipos de Texto" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "O texto que utiliza diálogos para ser encenado por atores é o:", options: ["Dramático (Teatral)", "Epistolar (Carta)", "Ensaio", "Charge"], answer: "Dramático (Teatral)", explanation: "Dividido em atos e cenas, com rubricas para os atores.", skill: "Tipos de Texto" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Um dicionário é composto por textos do tipo:", options: ["Expositivo (Informativo)", "Narrativo fictício", "Poético", "Argumentativo"], answer: "Expositivo (Informativo)", explanation: "Busca explicar e informar o significado direto das palavras.", skill: "Tipos de Texto" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "O que caracteriza a 'Poesia'?", options: ["Uso de versos, estrofes e frequentemente rimas", "Apenas a presença de dados reais", "O uso obrigatório de desenhos", "Ser escrita apenas em parágrafos longos"], answer: "Uso de versos, estrofes e frequentemente rimas", explanation: "Focada na sonoridade e na estética da linguagem.", skill: "Tipos de Texto" },

  // 6º Geografia - Espaço Rural (9)
  { grade: "6º", discipline: "Geografia", type: "multiple", text: "A principal atividade econômica desenvolvida no espaço rural é:", options: ["Agropecuária", "Indústria automobilística", "Comércio de eletrônicos", "Serviços bancários"], answer: "Agropecuária", explanation: "Envolve agricultura (plantas) e pecuária (animais).", skill: "Espaço Rural" },
  { grade: "6º", discipline: "Geografia", type: "multiple", text: "O que caracteriza a 'Agricultura de Subsistência'?", options: ["Produção voltada para o consumo da própria família", "Grande exportação para outros países", "Uso intensivo de máquinas pesadas", "Cultivo de apenas um produto"], answer: "Produção voltada para o consumo da própria família", explanation: "O excedente pode ser trocado ou vendido localmente.", skill: "Espaço Rural" },
  { grade: "6º", discipline: "Geografia", type: "multiple", text: "As grandes propriedades rurais monocultoras são chamadas de:", options: ["Latifúndios", "Minifúndios", "Chácaras", "Lotes urbanos"], answer: "Latifúndios", explanation: "Grandes extensões de terra geralmente pertencentes a um dono.", skill: "Espaço Rural" },
  { grade: "6º", discipline: "Geografia", type: "multiple", text: "O processo de substituição de trabalhadores por máquinas no campo chama-se:", options: ["Mecanização agrícola", "Urbanização", "Industrialização", "Extermínio"], answer: "Mecanização agrícola", explanation: "Aumenta a produtividade, mas pode causar desemprego no campo.", skill: "Espaço Rural" },
  { grade: "6º", discipline: "Geografia", type: "multiple", text: "O 'Êxodo Rural' é o movimento de:", options: ["Pessoas do campo para as cidades", "Turistas para as fazendas", "Animais fugindo da floresta", "Água evaporando"], answer: "Pessoas do campo para as cidades", explanation: "Ocorre pela mecanização e busca de melhores condições de vida.", skill: "Espaço Rural" },
  { grade: "6º", discipline: "Geografia", type: "multiple", text: "Qual o principal impacto ambiental do uso excessivo de agrotóxicos no campo?", options: ["Contaminação do solo e dos lençóis freáticos", "Melhora na qualidade da água", "Aumento da biodiversidade", "Fim da seca"], answer: "Contaminação do solo e dos lençóis freáticos", explanation: "Os produtos químicos penetram na terra e atingem a água.", skill: "Espaço Rural" },
  { grade: "6º", discipline: "Geografia", type: "multiple", text: "O agronegócio moderno caracteriza-se por:", options: ["Uso de alta tecnologia e produção em grande escala", "Uso apenas de ferramentas manuais", "Não visar lucro", "Não usar transporte"], answer: "Uso de alta tecnologia e produção em grande escala", explanation: "É a integração entre campo, indústria e tecnologia.", skill: "Espaço Rural" },
  { grade: "6º", discipline: "Geografia", type: "multiple", text: "A produção de frutas, legumes e verduras feita em pequenas propriedades próximas às cidades é o:", options: ["Cinturão Verde", "Deserto produtivo", "Latifúndio exportador", "Agronegócio de soja"], answer: "Cinturão Verde", explanation: "Abastece os mercados locais urbanos diariamente.", skill: "Espaço Rural" },
  { grade: "6º", discipline: "Geografia", type: "multiple", text: "A pecuária EXTENSIVA é aquela onde os animais:", options: ["São criados soltos em grandes pastagens", "Ficam confinados em pequenos espaços", "Só comem ração especial", "Não precisam de água"], answer: "São criados soltos em grandes pastagens", explanation: "Baixa tecnologia e uso de grandes áreas.", skill: "Espaço Rural" },

  // 8º Geografia - Geografia da América (9)
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A América é dividida fisicamente em quantas partes principais?", options: ["3 (Norte, Central e Sul)", "2 (Norte e Sul)", "4", "5"], answer: "3 (Norte, Central e Sul)", explanation: "Divisão baseada na estrutura de massa de terra do continente.", skill: "Geografia da América" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Culturalmente, a América divide-se em:", options: ["América Anglo-Saxônica e América Latina", "América Rica e América Pobre", "América de Cima e de Baixo", "América Inglesa e Francesa"], answer: "América Anglo-Saxônica e América Latina", explanation: "Divisão baseada na colonização e línguas predominantes.", skill: "Geografia da América" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual a maior cadeia de montanhas localizada na América do Sul?", options: ["Cordilheira dos Andes", "Montanhas Rochosas", "Montes Apalaches", "Himalaia"], answer: "Cordilheira dos Andes", explanation: "Atravessa sete países sul-americanos.", skill: "Geografia da América" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A 'América Anglo-Saxônica' é composta predominantemente por:", options: ["EUA e Canadá", "Brasil e Argentina", "México e Cuba", "Paraguai e Chile"], answer: "EUA e Canadá", explanation: "Países colonizados majoritariamente por ingleses.", skill: "Geografia da América" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Um dos grandes problemas ambientais da América do Sul é o desmatamento da:", options: ["Floresta Amazônica", "Sibéria", "Deserto do Saara", "Savana Africana"], answer: "Floresta Amazônica", explanation: "Maior floresta tropical do mundo, essencial para o clima.", skill: "Geografia da América" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual país é o elo de ligação terrestre entre a América do Norte e o Sul (istmo)?", options: ["Panamá", "Porto Rico", "Jamaica", "Groenlândia"], answer: "Panamá", explanation: "Famoso pelo canal que liga os oceanos Atlântico e Pacífico.", skill: "Geografia da América" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "As Montanhas Rochosas localizam-se na porção oeste da:", options: ["América do Norte", "América do Sul", "Antártida", "Europa"], answer: "América do Norte", explanation: "Serra que atravessa Canadá e EUA.", skill: "Geografia da América" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual língua é majoritária nos países da América Latina?", options: ["Espanhol e Português", "Inglês e Alemão", "Francês e Italiano", "Japonês"], answer: "Espanhol e Português", explanation: "Derivadas do Latim (colonização ibérica).", skill: "Geografia da América" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O Alasca, localizado no extremo noroeste da América, pertence ao:", options: ["EUA", "Rússia", "Canadá", "México"], answer: "EUA", explanation: "Estado americano separado fisicamente por conta do Canadá.", skill: "Geografia da América" },

  // 8º Geografia - Indicadores Sociais (9)
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O que o IDH (Índice de Desenvolvimento Humano) avalia?", options: ["Saúde, Educação e Renda", "Apenas a quantidade de ouro", "O número de carros por pessoa", "A beleza das praias"], answer: "Saúde, Educação e Renda", explanation: "Mede o bem-estar e não apenas o crescimento econômico.", skill: "Indicadores Sociais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A 'Expectativa de Vida' refere-se a:", options: ["Média de anos que uma população vive ao nascer", "Tamanho das pessoas", "Número de filhos por mulher", "Sorte das pessoas na vida"], answer: "Média de anos que uma população vive ao nascer", explanation: "Indica a qualidade da saúde e saneamento de um país.", skill: "Indicadores Sociais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A taxa de 'Mortalidade Infantil' mede o número de mortes de crianças antes de completarem:", options: ["1 ano de idade", "10 anos", "5 anos", "18 anos"], answer: "1 ano de idade", explanation: "Dato crucial sobre a qualidade da assistência pré-natal e básica.", skill: "Indicadores Sociais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O 'Índice de Gini' serve para medir a:", options: ["Desigualdade social/distribuição de renda", "Temperatura das cidades", "Velocidade da internet", "Produção de grãos"], answer: "Desigualdade social/distribuição de renda", explanation: "Quanto mais próximo de 1, maior a desigualdade.", skill: "Indicadores Sociais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O que significa 'Taxa de Analfabetismo'?", options: ["Porcentagem de pessoas que não sabem ler e escrever", "Número de pessoas desempregadas", "Pessoas que vivem no exterior", "Número de escolas abandonadas"], answer: "Porcentagem de pessoas que não sabem ler e escrever", explanation: "Dato fundamental para medir o nível educacional.", skill: "Indicadores Sociais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Países com IDH próximo a 1,000 são considerados:", options: ["Muito desenvolvido", "Pobres e desordenados", "Em guerra", "Desabitados"], answer: "Muito desenvolvido", explanation: "Exemplos: Noruega, Suíça, Alemanha.", skill: "Indicadores Sociais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A 'Renda Per Capita' é calculada através da:", options: ["Divisão do PIB pela população total", "Soma de todos os salários fixos", "Multiplicação da renda pelo número de idosos", "Pelo valor do salário mínimo"], answer: "Divisão do PIB pela população total", explanation: "Indica uma média teórica de renda por habitante.", skill: "Indicadores Sociais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A melhoria do saneamento básico impacta diretamente qual indicador?", options: ["Redução da mortalidade e aumento da expectativa de vida", "Aumento do PIB industrial", "Número de partidos políticos", "Cor do solo"], answer: "Redução da mortalidade e aumento da expectativa de vida", explanation: "Água tratada e esgoto evitam diversas doenças.", skill: "Indicadores Sociais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual destes países historicamente apresenta os melhores indicadores sociais da América Latina?", options: ["Uruguai / Chile", "Haiti", "Venezuela", "Nicarágua"], answer: "Uruguai / Chile", explanation: "Países com maiores índices de escolaridade e saúde na região.", skill: "Indicadores Sociais" },

  // 6º Arte - Gêneros da Pintura (9)
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Uma pintura de uma pessoa feita por ela mesma chama-se:", options: ["Autorretrato", "Paisagem", "Natureza-morta", "Pintura Abstrata"], answer: "Autorretrato", explanation: "Gênero onde o artista é o próprio modelo.", skill: "Gêneros da Pintura" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Pinturas que retratam objetos inanimados (frutas, flores, vasos) são chamadas de:", options: ["Natureza-morta", "Pintura Rupestre", "Retrato", "Marinha"], answer: "Natureza-morta", explanation: "Focada na beleza das formas silenciadas da vida cotidiana.", skill: "Gêneros da Pintura" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O gênero que representa ambientes externos como montanhas, florestas ou cidades é a:", options: ["Paisagem", "Escultura", "Pintura histórica", "Grafite"], answer: "Paisagem", explanation: "Explora o espaço geográfico e a atmosfera natural ou urbana.", skill: "Gêneros da Pintura" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A pintura que retrata o mar e atividades marítimas é a:", options: ["Marinha", "Naturalista", "Abstracta", "Dramática"], answer: "Marinha", explanation: "Especialidade dentro do gênero de paisagem focada nas águas.", skill: "Gêneros da Pintura" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Pinturas que narram eventos importantes (guerras, posses de reis) são do gênero:", options: ["Pintura Histórica", "Surrealismo", "Pop Art", "Mineração"], answer: "Pintura Histórica", explanation: "Tinha grande valor educativo e político no passado.", skill: "Gêneros da Pintura" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A pintura 'Abstrata' é aquela que:", options: ["Não representa formas reais do mundo visível", "Parece uma fotografia exata", "Só usa tinta branca", "É feita apenas com lápis"], answer: "Não representa formas reais do mundo visível", explanation: "Foca em cores, linhas e emoções sem formas figurativas.", skill: "Gêneros da Pintura" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O 'Gênero de Costumes' retrata:", options: ["Cenas do dia a dia das pessoas", "Apenas as roupas do futuro", "Os sonhos do artista", "Apenas deuses gregos"], answer: "Cenas do dia a dia das pessoas", explanation: "Mostra como o povo vivia, trabalhava e se divertia.", skill: "Gêneros da Pintura" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Uma pintura de um grupo de pessoas ricas e importantes posando é um:", options: ["Retrato coletivo", "Charge", "Grafite", "Mural"], answer: "Retrato coletivo", explanation: "Gênero comercial comum na aristocracia antiga.", skill: "Gêneros da Pintura" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A 'Pintura Sacra/Religiosa' tem como tema principal:", options: ["Divindades, santos e cenas bíblicas/sagradas", "As máquinas da revolução industrial", "Esportes antigos", "Animais da savana"], answer: "Divindades, santos e cenas bíblicas/sagradas", explanation: "Usada para ensinar e decorar espaços de culto.", skill: "Gêneros da Pintura" },

  // 8º Arte - Renascimento (9)
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Em qual país europeu nasceu o movimento Renascentista?", options: ["Itália", "Inglaterra", "Rússia", "Portugal"], answer: "Itália", explanation: "As cidades de Florença, Roma e Veneza foram os centros principais.", skill: "Renascimento" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O Renascimento buscou inspiração nas culturas da:", options: ["Antiguidade Clássica (Grécia e Roma)", "Idade Moderna Americana", "China Medieval", "Povos astecas"], answer: "Antiguidade Clássica (Grécia e Roma)", explanation: "Houve um 'renascer' dos ideais de beleza e ciência grego-romanos.", skill: "Renascimento" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual destes artistas pintou a 'Mona Lisa' e 'A Última Ceia'?", options: ["Leonardo da Vinci", "Michelangelo", "Pablo Picasso", "Vincent van Gogh"], answer: "Leonardo da Vinci", explanation: "Polímata símbolo do conhecimento renascentista.", skill: "Renascimento" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Michelangelo é famoso por pintar o teto de qual capela?", options: ["Capela Sistina (Vaticano)", "Basília de Aparecida", "Notre Dame", "Catedral da Sé"], answer: "Capela Sistina (Vaticano)", explanation: "Obra monumental que retrata cenas do Gênesis.", skill: "Renascimento" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Uma técnica revolucionária do Renascimento para criar profundidade foi a:", options: ["Perspectiva Linear", "Colagem", "Pintura de dedos", "Escultura de gelo"], answer: "Perspectiva Linear", explanation: "Permitiu calcular matematicamente a ilusão de espaço no quadro.", skill: "Renascimento" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O pensamento que colocava o SER HUMANO no centro do universo é o:", options: ["Antropocentrismo", "Teocentrismo", "Industrialismo", "Globalismo"], answer: "Antropocentrismo", explanation: "Slogan: 'Homem é a medida de todas as coisas'.", skill: "Renascimento" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Quem pintou 'O Nascimento de Vênus'?", options: ["Sandro Botticelli", "Gustav Klimt", "Salvador Dalí", "Anita Malfatti"], answer: "Sandro Botticelli", explanation: "Obra prima que mistura mitologia e beleza clássica.", skill: "Renascimento" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O Renascimento valorizava a harmonia entre a Fé e a:", options: ["Razão/Ciência", "Magia negra", "Política autoritária apenas", "Guerra santa"], answer: "Razão/Ciência", explanation: "Busca de explicações lógicas e anatômicas para o mundo.", skill: "Renascimento" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Os produtores e comerciantes ricos que financiavam os artistas eram os:", options: ["Mecenas", "Trovadores", "Monges", "Guerreiros"], answer: "Mecenas", explanation: "Figuras essenciais para o florescimento das artes (ex: Família Médici).", skill: "Renascimento" },

  // 6º História - Grécia Antiga (9)
  { grade: "6º", discipline: "História", type: "multiple", text: "Como eram chamadas as cidades-estado na Grécia Antiga?", options: ["Pólis", "Impérios", "Favelas", "Casernas"], answer: "Pólis", explanation: "Eram cidades independentes com leis e governos próprios.", skill: "Grécia Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "Em qual cidade grega surgiu a DEMOCRACIA?", options: ["Atenas", "Esparta", "Tebas", "Olímpia"], answer: "Atenas", explanation: "Participação direta dos cidadãos nas decisões da cidade.", skill: "Grécia Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "A cidade grega famosa por sua rigidez e treinamento militar era:", options: ["Esparta", "Atenas", "Corinto", "Roma"], answer: "Esparta", explanation: "Educação focada na formação de guerreiros hoplitas.", skill: "Grécia Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "Os principais deuses gregos habitavam o topo do Monte:", options: ["Olimpo", "Everest", "Himalaia", "Ararat"], answer: "Olimpo", explanation: "Ex: Zeus, Hera, Poseidon e Atena.", skill: "Grécia Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "O evento esportivo mundial que nasceu na Grécia Antiga para honrar Zeus foi:", options: ["Jogos Olímpicos", "Copa do Mundo", "Tour de France", "NBA"], answer: "Jogos Olímpicos", explanation: "Realizados a cada 4 anos na cidade de Olímpia.", skill: "Grécia Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "A Grécia é considerada o berço do pensamento racional chamado:", options: ["Filosofia", "Magia", "Astrologia", "Alquimia"], answer: "Filosofia", explanation: "Busca da verdade através da razão (ex: Sócrates, Platão e Aristóteles).", skill: "Grécia Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "O local público nas pólis onde ocorriam debates e comércio era a:", options: ["Ágora", "Acrópole", "Padaria", "Fórum romano"], answer: "Ágora", explanation: "Coração da vida pública e da democracia ateniense.", skill: "Grécia Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "O filósofo grego que dizia 'Só sei que nada sei' foi:", options: ["Sócrates", "Aristóteles", "Alexandre o Grande", "Hermes"], answer: "Sócrates", explanation: "Focava na busca do conhecimento através do questionamento.", skill: "Grécia Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "A Grécia foi conquistada por qual imperador macedônio que espalhou a cultura helenística?", options: ["Alexandre o Grande", "Júlio César", "Napoleão", "Nero"], answer: "Alexandre o Grande", explanation: "Criou um dos maiores impérios da antiguidade.", skill: "Grécia Antiga" },

  // 7º História - Crise do Século XIV (9)
  { grade: "7º", discipline: "História", type: "multiple", text: "Qual doença devastadora matou cerca de 1/3 da população europeia no século XIV?", options: ["Peste Negra (Bubônica)", "Gripe Espanhola", "Varíola", "Dengue"], answer: "Peste Negra (Bubônica)", explanation: "Transmitida por pulgas de ratos vindo do comércio com o Oriente.", skill: "Crise do Século XIV" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A 'Guerra dos Cem Anos' ocorreu entre quais países?", options: ["França e Inglaterra", "Espanha e Portugal", "Alemanha e Itália", "Grécia e Pérsia"], answer: "França e Inglaterra", explanation: "Longa disputa por territórios e sucessão dinástica.", skill: "Crise do Século XIV" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A escassez de mão de obra após a peste gerou qual reação dos camponeses?", options: ["Revoltas Camponesas (Jacqueries)", "Eles ficaram felizes", "Pararam de comer", "Viraram cavaleiros medievais imediatamente"], answer: "Revoltas Camponesas (Jacqueries)", explanation: "Explosões de violência contra a opressão senhorial e altos impostos.", skill: "Crise do Século XIV" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Qual figura histórica francesa tornou-se símbolo de resistência na Guerra dos Cem Anos?", options: ["Joana d'Arc", "Maria Antonieta", "Catarina de Médici", "Cleópatra"], answer: "Joana d'Arc", explanation: "Camponesa que liderou exércitos e foi queimada na fogueira.", skill: "Crise do Século XIV" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A crise do século XIV marcou o início do declínio de qual sistema?", options: ["Feudalismo", "Capitalismo", "Comunismo", "Escravismo antigo"], answer: "Feudalismo", explanation: "Abalou as estruturas sociais e econômicas da Idade Média.", skill: "Crise do Século XIV" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Além da doença e guerra, qual outro fator causou mortes em massa?", options: ["Grande Fome (mudanças climáticas)", "Ataques de dinossauros", "Falta de internet", "Explosões nucleares"], answer: "Grande Fome (mudanças climáticas)", explanation: "Safras ruins causadas por chuvas intensas e frio.", skill: "Crise do Século XIV" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A Peste Negra abalou o poder de qual instituição na época?", options: ["Igreja Católica", "Associações de moradores", "Escolas públicas", "Indústrias multinacionais"], answer: "Igreja Católica", explanation: "Muitos questionaram a fé diante da morte em massa que as orações não impediam.", skill: "Crise do Século XIV" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A falta de comida e a inflação geraram uma grave crise...", options: ["Econômica", "Tecnológica", "Religiosa apenas", "De entretenimento"], answer: "Econômica", explanation: "O sistema de trocas e produção ruiu com a falta de gente e excesso de gastos militares.", skill: "Crise do Século XIV" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A Peste Negra chegou à Europa através de:", options: ["Navios comerciais vindo da Ásia", "Aviões de carga", "Via caminhões", "Só existia na Europa"], answer: "Navios comerciais vindo da Ásia", explanation: "A Rota da Seda facilitou o transporte da bactéria.", skill: "Crise do Século XIV" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 16 com ${batch.length} questões adicionado.`);
