import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 5100;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 19: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 9º Ed. Física - Ergonomia (9)
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O que é a Ergonomia?", options: ["O estudo da adaptação do trabalho ao homem para garantir saúde e eficiência", "Um tipo de ginástica olímpica", "O estudo dos fósseis humanos", "Uma regra de jogo de basquete"], answer: "O estudo da adaptação do trabalho ao homem para garantir saúde e eficiência", explanation: "Busca evitar lesões e cansaço excessivo no ambiente de trabalho ou estudo.", skill: "Ergonomia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual a postura correta para quem trabalha muitas horas sentado ao computador?", options: ["Costas apoiadas, pés no chão e tela na altura dos olhos", "Deitado na cadeira com os pés na mesa", "Curvado para frente para ver melhor a tela", "Pés pendurados e ombros tensos"], answer: "Costas apoiadas, pés no chão e tela na altura dos olhos", explanation: "Isso evita dores na coluna e fadiga visual.", skill: "Ergonomia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A sigla LER, comum em ambientes de trabalho não ergonômicos, significa:", options: ["Lesão por Esforço Repetitivo", "Lógica de Exercício Rápido", "Leitura e Escrita Regular", "Lentidão em Esportes de Roda"], answer: "Lesão por Esforço Repetitivo", explanation: "Ocorre por movimentos iguais feitos por longos períodos sem pausa.", skill: "Ergonomia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A Ginástica Laboral tem como objetivo principal:", options: ["Prevenir doenças ocupacionais e aliviar o estresse no trabalho", "Treinar atletas para as Olimpíadas", "Fazer as pessoas perderem peso rápido", "Substituir o horário de almoço"], answer: "Prevenir doenças ocupacionais e aliviar o estresse no trabalho", explanation: "São exercícios curtos feitos durante a jornada de trabalho.", skill: "Ergonomia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Para carregar uma mochila pesada sem prejudicar a coluna, deve-se:", options: ["Usar as duas alças e mantê-la ajustada próxima ao corpo", "Usar apenas uma alça de um lado só", "Deixá-la bem solta e balançando", "Segurá-la apenas com uma mão"], answer: "Usar as duas alças e mantê-la ajustada próxima ao corpo", explanation: "Distribui o peso igualmente entre os ombros.", skill: "Ergonomia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual a distância ideal recomendada entre os olhos e o monitor?", options: ["Cerca de 50 a 70 centímetros", "10 centímetros (bem perto)", "2 metros", "A distância de um braço esticado não importa"], answer: "Cerca de 50 a 70 centímetros", explanation: "Evita o esforço excessivo dos músculos oculares.", skill: "Ergonomia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A iluminação inadequada no ambiente de estudo pode causar:", options: ["Fadiga ocular e dor de cabeça", "Aumento da força física", "Melhora na audição", "Nada, os olhos se acostumam"], answer: "Fadiga ocular e dor de cabeça", explanation: "A luz deve ser suficiente para não forçar a visão.", skill: "Ergonomia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Ao levantar um objeto pesado do chão, a forma ergonomicamente correta é:", options: ["Dobrar os joelhos e manter as costas retas", "Dobrar apenas as costas sem dobrar os joelhos", "Levantar o mais rápido possível", "Girar o tronco enquanto levanta"], answer: "Dobrar os joelhos e manter as costas retas", explanation: "Usa a força das pernas e preserva os discos da coluna.", skill: "Ergonomia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Fazer pausas curtas para alongamento durante o estudo ajuda a:", options: ["Melhorar a circulação e reduzir a tensão muscular", "Esquecer a matéria", "Ficar com mais sono", "Gastar tempo à toa"], answer: "Melhorar a circulação e reduzir a tensão muscular", explanation: "Pequenas pausas aumentam a produtividade e o bem-estar.", skill: "Ergonomia" },

  // 6º Ciências - Litosfera (9)
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O que é a Litosfera?", options: ["A camada sólida externa da Terra (Crosta e parte do Manto Superior)", "A camada de gases que envolve o planeta", "Toda a água da Terra", "O núcleo derretido do planeta"], answer: "A camada sólida externa da Terra (Crosta e parte do Manto Superior)", explanation: "É onde vivemos e onde se encontram as rochas e o solo.", skill: "Litosfera" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "As rochas formadas pelo resfriamento do magma são chamadas de:", options: ["Rochas Magmáticas (ou Ígneas)", "Rochas Sedimentares", "Rochas Metamórficas", "Rochas de Vidro"], answer: "Rochas Magmáticas (ou Ígneas)", explanation: "Exemplo: Granito e Basalto.", skill: "Litosfera" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Rochas que se formam pela compactação de restos de outras rochas ou seres vivos são as:", options: ["Sedimentares", "Magmáticas", "Vulcânicas", "Preciosas"], answer: "Sedimentares", explanation: "Ocorrem em camadas e podem conter fósseis.", skill: "Litosfera" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O processo de transformação de uma rocha em outra devido à alta pressão e temperatura é a:", options: ["Metamorfose (Rochas Metamórficas)", "Erosão", "Sedimentação", "Fusão nuclear"], answer: "Metamorfose (Rochas Metamórficas)", explanation: "Exemplo: o Calcário vira Mármore.", skill: "Litosfera" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Os fósseis são geralmente encontrados em qual tipo de rocha?", options: ["Sedimentares", "Magmáticas", "Metamórficas", "Lava fria"], answer: "Sedimentares", explanation: "O processo de sedimentação permite a preservação de restos orgânicos.", skill: "Litosfera" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O desgaste das rochas pela ação da água, vento e seres vivos chama-se:", options: ["Intemperismo e Erosão", "Vulcanismo", "Gravidade", "Fotossíntese"], answer: "Intemperismo e Erosão", explanation: "Isso fragmenta a rocha para formar o solo.", skill: "Litosfera" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "A camada mais interna e quente da Terra chama-se:", options: ["Núcleo", "Crosta", "Manto", "Troposfera"], answer: "Núcleo", explanation: "Dividido em núcleo interno (sólido) e externo (líquido).", skill: "Litosfera" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "As grandes placas que compõem a litosfera e se movem lentamente são as:", options: ["Placas Tectônicas", "Placas de Metal", "Placas Solares", "Placas de Gelo"], answer: "Placas Tectônicas", explanation: "Seus movimentos causam terremotos e vulcões.", skill: "Litosfera" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O solo é formado basicamente por:", options: ["Minerais (rocha moída), matéria orgânica, água e ar", "Apenas areia pura", "Apenas plástico e água", "Cinzas vulcânicas apenas"], answer: "Minerais (rocha moída), matéria orgânica, água e ar", explanation: "É um sistema complexo que sustenta a vida vegetal.", skill: "Litosfera" },

  // 7º Geografia - Hidrografia (9)
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "O que estuda a Hidrografia?", options: ["As águas do planeta (oceanos, rios, lagos, geleiras)", "O relevo das montanhas apenas", "As cidades e sua população", "As estrelas e o universo"], answer: "As águas do planeta (oceanos, rios, lagos, geleiras)", explanation: "Analisa a distribuição e o comportamento das massas de água.", skill: "Hidrografia" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "A área drenada por um rio principal e seus afluentes é chamada de:", options: ["Bacia Hidrográfica", "Vale Seco", "Aterro Sanitário", "Escoamento"], answer: "Bacia Hidrográfica", explanation: "Toda a chuva que cai nessa área corre para o mesmo rio.", skill: "Hidrografia" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "O lugar onde o rio nasce é a sua:", options: ["Nascente", "Foz", "Afluente", "Leito"], answer: "Nascente", explanation: "Pode ser um olho d'água, degelo ou represa.", skill: "Hidrografia" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "O lugar onde o rio deságua em outro rio, lago ou mar é a:", options: ["Foz (Desembocadura)", "Nascente", "Margem", "Meandro"], answer: "Foz (Desembocadura)", explanation: "O ponto final do curso do rio.", skill: "Hidrografia" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "Um rio que nunca seca, mesmo na época de estiagem, é chamado de:", options: ["Perene", "Temporário (Intermitente)", "Subterrâneo", "Morto"], answer: "Perene", explanation: "A maioria dos grandes rios brasileiros são perenes.", skill: "Hidrografia" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "Rios intermitentes são aqueles que:", options: ["Secam durante os períodos de seca prolongada", "Estão sempre cheios de água", "Não possuem peixes", "Só existem no fundo do mar"], answer: "Secam durante os períodos de seca prolongada", explanation: "Comuns em regiões de clima semiárido.", skill: "Hidrografia" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "O Brasil possui a maior bacia hidrográfica do mundo. Qual o seu nome?", options: ["Bacia Amazônica", "Bacia do Rio Prata", "Bacia do Rio São Francisco", "Bacia do Rio Nilo"], answer: "Bacia Amazônica", explanation: "Ocupa quase metade do território brasileiro e se estende por países vizinhos.", skill: "Hidrografia" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "Os rios de PLANALTO são ideais para a construção de:", options: ["Usinas Hidrelétricas", "Portos para navios gigantes", "Canais de irrigação em linha reta", "Plantações de arroz"], answer: "Usinas Hidrelétricas", explanation: "Aproveitam as quedas d'água para gerar energia.", skill: "Hidrografia" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "A água doce subterrânea acumulada em rochas porosas forma os:", options: ["Aquíferos", "Oceanos", "Tsunamis", "Icebergs"], answer: "Aquíferos", explanation: "O Brasil tem o Aquífero Guarani e o Alter do Chão.", skill: "Hidrografia" },

  // 8º Geografia - Rotas Mundiais (9)
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual a função principal dos Canais (como Panamá e Suez) nas rotas mundiais?", options: ["Encurtar distâncias e facilitar o comércio marítimo", "Apenas para turismo de luxo", "Para limpar a água do mar", "Separar os peixes dos oceanos"], answer: "Encurtar distâncias e facilitar o comércio marítimo", explanation: "Evitam que navios deem voltas imensas em continentes.", skill: "Rotas Mundiais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A antiga 'Rota da Seda' ligava comercialmente quais regiões?", options: ["China e Europa", "Brasil e EUA", "África e Austrália", "Polo Norte e Polo Sul"], answer: "China e Europa", explanation: "Importante rota terrestre e marítima para especiarias e tecidos.", skill: "Rotas Mundiais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Atualmente, qual o transporte mais utilizado para o comércio internacional de cargas pesadas?", options: ["Navios Cargueiros (Contêineres)", "Aviões de carga", "Caminhões", "Trens de alta velocidade"], answer: "Navios Cargueiros (Contêineres)", explanation: "O transporte marítimo é o mais barato para grandes volumes.", skill: "Rotas Mundiais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O Canal de SUEZ liga quais mares importantes?", options: ["Mar Mediterrâneo e Mar Vermelho", "Atlântico e Pacífico", "Índico e Antártico", "Mar Morto e Mar Negro"], answer: "Mar Mediterrâneo e Mar Vermelho", explanation: "Rota crucial para o petróleo e comércio entre Ásia e Europa.", skill: "Rotas Mundiais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O Canal do PANAMÁ liga quais oceanos?", options: ["Atlântico e Pacífico", "Atlântico e Índico", "Pacífico e Ártico", "Índico e Antártico"], answer: "Atlântico e Pacífico", explanation: "Atravessa a América Central, sendo vital para o comércio americano.", skill: "Rotas Mundiais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "No mundo globalizado, os 'Hubs' logísticos são:", options: ["Centros de conexão onde mercadorias são distribuídas", "Países que não fazem comércio", "Lojas pequenas de bairro", "Satélites de comunicação apenas"], answer: "Centros de conexão onde mercadorias são distribuídas", explanation: "Ex: grandes portos e aeroportos internacionais.", skill: "Rotas Mundiais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A pirataria moderna em rotas marítimas (como no Chifre da África) causa:", options: ["Aumento de custos e riscos no comércio internacional", "Nenhum problema para os navios", "Melhora na segurança mundial", "Queda no preço do petróleo"], answer: "Aumento de custos e riscos no comércio internacional", explanation: "Exige escoltas militares e seguros mais caros.", skill: "Rotas Mundiais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual país está investindo pesado na 'Nova Rota da Seda' (Belt and Road Initiative)?", options: ["China", "Brasil", "Alemanha", "Canadá"], answer: "China", explanation: "Visa criar infraestrutura de transporte ligando a Ásia ao mundo.", skill: "Rotas Mundiais" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O uso de contêineres padronizados facilitou as rotas porque:", options: ["Podem ser usados em navios, trens e caminhões sem mudar a carga", "São mais coloridos que caixas de madeira", "São feitos de ouro", "Flutuam sozinhos no mar"], answer: "Podem ser usados em navios, trens e caminhões sem mudar a carga", explanation: "Isso é chamado de intermodalidade.", skill: "Rotas Mundiais" },

  // 9º Geografia - Mundo Globalizado (9)
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A 'Globalização' pode ser resumida como:", options: ["A integração econômica, cultural e política do mundo", "O isolamento total dos países", "Apenas a invenção da televisão", "A proibição de viagens internacionais"], answer: "A integração econômica, cultural e política do mundo", explanation: "Encurtou distâncias através da tecnologia e transportes.", skill: "Mundo Globalizado" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Qual tecnologia foi o principal motor da globalização no final do século XX?", options: ["Internet e comunicações por satélite", "Máquina a vapor", "Carruagens tracionadas por cavalos", "Rádio AM apenas"], answer: "Internet e comunicações por satélite", explanation: "Permitiu a troca de informações em tempo real pelo globo.", skill: "Mundo Globalizado" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "As empresas que atuam em diversos países ao mesmo tempo são as:", options: ["Multinacionais (Transnacionais)", "Empresas locais de bairro", "Cooperativas de vilas", "Estatais de um só país"], answer: "Multinacionais (Transnacionais)", explanation: "Produzem e vendem em escala global (ex: Coca-Cola, Apple).", skill: "Mundo Globalizado" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A padronização de costumes e consumo (como filmes e fast-food) no mundo é o(a):", options: ["Aculturação / Homogeneização cultural", "Diversidade absoluta", "Isolamento cultural", "Resistência local"], answer: "Aculturação / Homogeneização cultural", explanation: "Há o risco de perda das identidades locais.", skill: "Mundo Globalizado" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A 'Divisão Internacional do Trabalho' (DIT) na globalização define que:", options: ["Cada país se especializa em certas produções na cadeia global", "Todos os países produzem exatamente a mesma coisa", "Não há mais comércio entre países", "Apenas os países pobres produzem tecnologia"], answer: "Cada país se especializa em certas produções na cadeia global", explanation: "Países desenvolvidos focam em tecnologia; subdesenvolvidos em matérias-primas.", skill: "Mundo Globalizado" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Uma consequência NEGATIVA da globalização para o meio ambiente é:", options: ["O aumento do consumo e da poluição em escala mundial", "A preservação total de todas as matas", "O fim do uso de combustíveis fósseis", "A diminuição das viagens"], answer: "O aumento do consumo e da poluição em escala mundial", explanation: "A produção em massa exige muitos recursos do planeta.", skill: "Mundo Globalizado" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O termo 'Aldeia Global' sugere que o mundo hoje está:", options: ["Interconectado como se todos fossem vizinhos em uma pequena vila", "Dividido por muros instransponíveis", "Cada vez mais vazio e desabitado", "Voltando a viver em cavernas"], answer: "Interconectado como se todos fossem vizinhos em uma pequena vila", explanation: "As notícias e produtos circulam muito rápido.", skill: "Mundo Globalizado" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A globalização favorece a formação de Blocos Econômicos para:", options: ["Reduzir tarifas de comércio entre países vizinhos", "Proibir a entrada de estrangeiros", "Dificultar a venda de produtos", "Aumentar os impostos internos"], answer: "Reduzir tarifas de comércio entre países vizinhos", explanation: "Ex: Mercosul, União Europeia.", skill: "Mundo Globalizado" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A facilidade de movimento de capitais (dinheiro) pelo mundo pode causar:", options: ["Crises financeiras que se espalham rápido por vários países", "Estabilidade eterna da economia", "O fim do dinheiro", "Apenas lucro para todos sempre"], answer: "Crises financeiras que se espalham rápido por vários países", explanation: "As economias tornaram-se dependentes umas das outras.", skill: "Mundo Globalizado" },

  // 7º Arte - Arte Pré-Histórica (9)
  { grade: "7º", discipline: "Arte", type: "multiple", text: "As pinturas feitas em paredes de cavernas na pré-história chamam-se:", options: ["Pinturas Rupestres", "Grafites modernos", "Afrescos renascentistas", "Pinturas a óleo"], answer: "Pinturas Rupestres", explanation: "Eram feitas com pigmentos naturais (terra, sangue, carvão).", skill: "Arte Pré-Histórica" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "Qual era o tema mais comum nas pinturas rupestres?", options: ["Cenas de caça e animais da época", "Retratos de reis famosos", "Paisagens de cidades futuristas", "Desenhos de aviões"], answer: "Cenas de caça e animais da época", explanation: "Refletiam o dia a dia e rituais de sobrevivência.", skill: "Arte Pré-Histórica" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "No Brasil, qual o local mais famoso por suas pinturas rupestres?", options: ["Parque Nacional da Serra da Capivara (PI)", "Praia de Copacabana", "Avenida Paulista", "Pantanal mato-grossense"], answer: "Parque Nacional da Serra da Capivara (PI)", explanation: "Patrimônio da UNESCO com milhares de sítios arqueológicos.", skill: "Arte Pré-Histórica" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "A técnica de 'Mãos em Negativo' na pré-história era feita:", options: ["Soprando pigmentos sobre a mão encostada na pedra", "Desenhando com lápis de cor", "Esculpindo a pedra com martelo", "Usando carimbos de plástico"], answer: "Soprando pigmentos sobre a mão encostada na pedra", explanation: "Deixava a silhueta da mão contornada pela cor.", skill: "Arte Pré-Histórica" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "As 'Vênus' da pré-história (ex: de Willendorf) eram pequenas esculturas que simbolizavam:", options: ["A Fertilidade", "A Guerra", "A Escrita", "O Medo"], answer: "A Fertilidade", explanation: "Representavam o desejo de continuidade da vida do grupo.", skill: "Arte Pré-Histórica" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "As construções feitas com grandes blocos de pedra (como Stonehenge) são chamadas:", options: ["Monumentos Megalíticos", "Prédios modernos", "Pirâmides de vidro", "Cabanas de palha"], answer: "Monumentos Megalíticos", explanation: "Tinham funções astronômicas ou religiosas.", skill: "Arte Pré-Histórica" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "Que materiais eram usados como 'tinta' pelos homens das cavernas?", options: ["Terra colorida, carvão, minerais e gordura animal", "Aquarela escolar", "Tinta spray", "Esmalte de unha"], answer: "Terra colorida, carvão, minerais e gordura animal", explanation: "Usavam o que estava disponível na natureza bruta.", skill: "Arte Pré-Histórica" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "Acredita-se que a arte rupestre tinha uma função 'mágica' para:", options: ["Atrair uma boa caçada facilitando o abate do animal", "Assustar outros grupos", "Apenas por diversão artística", "Vender para museus"], answer: "Atrair uma boa caçada facilitando o abate do animal", explanation: "O desenho seria uma forma de 'dominar' o animal antes da caça.", skill: "Arte Pré-Histórica" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "Qual a diferença entre a arte do Paleolítico e do Neolítico?", options: ["No Neolítico os desenhos tornaram-se mais esquemáticos e sugeriam movimento", "No Paleolítico usavam apenas computadores", "Não há diferença nenhuma", "No Neolítico pararam de desenhar"], answer: "No Neolítico os desenhos tornaram-se mais esquemáticos e sugeriam movimento", explanation: "Ocorreu com o surgimento da agricultura e aldeias fixas.", skill: "Arte Pré-Histórica" },

  // 8º Arte - Idade Média (9)
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A arte na Idade Média Europeia era fortemente dominada pela:", options: ["Religião (Igreja Católica)", "Indústria pesada", "Filosofia Grega Antiga apenas", "Cultura dos shoppings"], answer: "Religião (Igreja Católica)", explanation: "A arte servia para educar e glorificar o sagrado.", skill: "Idade Média" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O estilo arquitetônico das igrejas com arcos redondos e paredes grossas é o:", options: ["Estilo Românico", "Estilo Gótico", "Estilo Barroco", "Estilo Futurista"], answer: "Estilo Românico", explanation: "Pareciam fortalezas de Deus, com pouca luz e solidez.", skill: "Idade Média" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual estilo medieval é marcado por catedrais altas, vitrais coloridos e arcos ogivais (pontiagudos)?", options: ["Estilo Gótico", "Estilo Românico", "Estilo Renascentista", "Grafismo"], answer: "Estilo Gótico", explanation: "Buscava a verticalidade e a luz para simbolizar o céu.", skill: "Idade Média" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Os desenhos e pinturas que decoravam os livros (manuscritos) feitos por monges eram as:", options: ["Iluminuras", "Fotogramas", "Charges", "Pichações"], answer: "Iluminuras", explanation: "Feitas à mão com ouro e cores vibrantes.", skill: "Idade Média" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Os painéis de vidro colorido que contavam histórias bíblicas nas janelas góticas chamam-se:", options: ["Vitrais", "Mosaicos de chão", "Telas a óleo", "Espelhos teatrais"], answer: "Vitrais", explanation: "Filtravam a luz e ensinavam a Bíblia aos analfabetos.", skill: "Idade Média" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Como eram representadas as figuras humanas na pintura medieval (antes do Renascimento)?", options: ["Sem profundidade (imagem plana) e com tamanhos baseados na importância", "Pareciam fotografias reais em 3D", "Eram apenas borrões de cor", "Sempre de cabeça para baixo"], answer: "Sem profundidade (imagem plana) e com tamanhos baseados na importância", explanation: "A simbologia era mais importante que o realismo anatômico.", skill: "Idade Média" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O 'Canto Gregoriano' era o estilo musical predominante de qual local?", options: ["Igrejas e mosteiros medievais", "Estádios de futebol", "Palácios de reis da Babilônia", "Feiras de artesanato"], answer: "Igrejas e mosteiros medievais", explanation: "Canto monofônico e sagrado, sem instrumentos.", skill: "Idade Média" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual a função dos 'Gárgulas' nas catedrais góticas?", options: ["Escoar água da chuva e simbolizar a proteção divina contra o mal", "Apenas por diversão das crianças", "Para servirem de candelabros", "Para esconderem o tesouro do rei"], answer: "Escoar água da chuva e simbolizar a proteção divina contra o mal", explanation: "Figuras monstruosas que funcionavam como calhas.", skill: "Idade Média" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual das artes abaixo era considerada a 'primeira' na Idade Média, guiando as outras?", options: ["Arquitetura", "Dança contemporânea", "Cinema", "Grafite"], answer: "Arquitetura", explanation: "Construir a 'Casa de Deus' envolvia as outras artes (escultura, pintura, vitral).", skill: "Idade Média" },

  // 9º Arte - Cubismo (9)
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O Cubismo rompeu com a tradição artística ao:", options: ["Representar objetos de diversos pontos de vista ao mesmo tempo", "Tentar copiar a realidade exatamente como uma foto", "Pintar apenas o que sentiam sem nenhuma forma", "Desistir das cores e usar apenas preto"], answer: "Representar objetos de diversos pontos de vista ao mesmo tempo", explanation: "A imagem é decomposta em formas geométricas e remontada.", skill: "Cubismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Quem é o artista mais famoso do Cubismo, autor de 'Guernica' e 'Les Demoiselles d'Avignon'?", options: ["Pablo Picasso", "Leonardo da Vinci", "Claude Monet", "Andy Warhol"], answer: "Pablo Picasso", explanation: "Líder do movimento junto com Georges Braque.", skill: "Cubismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O Cubismo que utiliza colagem de materiais reais (jornais, papéis) é o:", options: ["Cubismo Sintético", "Cubismo Analítico", "Cubismo Futurista", "Cubismo de Vidro"], answer: "Cubismo Sintético", explanation: "Introduz elementos do mundo real na obra.", skill: "Cubismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "No 'Cubismo Analítico', as figuras eram:", options: ["Decompostas em tantos pedaços que ficavam quase irreconhecíveis", "Desenhadas com curvas perfeitas", "Pintadas com cores muito vibrantes e neon", "Apenas fotografias coladas"], answer: "Decompostas em tantos pedaços que ficavam quase irreconhecíveis", explanation: "Foco na análise da forma pura em tons sóbrios (cinza/marrom).", skill: "Cubismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Qual a principal influência cultural para os rostos das figuras no início do Cubismo?", options: ["Máscaras africanas", "Templos egípcios", "Animes japoneses", "Moda parisiense"], answer: "Máscaras africanas", explanation: "Picasso ficou fascinado pela estilização das formas nas artes da África.", skill: "Cubismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Na visão cubista, o tempo é representado pois vemos o objeto de:", options: ["Diferentes ângulos simultaneamente", "Apenas por trás", "Por dentro apenas", "Em uma única luz fixa"], answer: "Diferentes ângulos simultaneamente", explanation: "Dá a sensação de que o espectador se moveu em torno do objeto.", skill: "Cubismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Além de Picasso, outro grande nome do Cubismo foi:", options: ["Georges Braque", "Vincent van Gogh", "Michelangelo", "Banksy"], answer: "Georges Braque", explanation: "Trabalhou tão próximo de Picasso que suas obras iniciais se confundem.", skill: "Cubismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A obra 'Guernica' de Picasso é um protesto contra:", options: ["O bombardeio de uma cidade durante a Guerra Civil Espanhola", "O cansaço dos artistas franceses", "A poluição dos mares", "O preço das tintas na época"], answer: "O bombardeio de uma cidade durante a Guerra Civil Espanhola", explanation: "Obra monumental carregada de dor e denúncia política.", skill: "Cubismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O cubismo influenciou profundamente qual área do design moderno?", options: ["Arquitetura e artes gráficas", "Gastronomia apenas", "Natação", "Agricultura"], answer: "Arquitetura e artes gráficas", explanation: "As formas geométricas puras mudaram a estética do século XX.", skill: "Cubismo" },

  // 6º Ed. Física - Xadrez (9)
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O Xadrez é considerado um 'Esporte da Mente'. Qual sua principal peça?", options: ["Rei", "Rainha", "Peão", "Bispo"], answer: "Rei", explanation: "O objetivo final do jogo é capturar (atacar) o rei adversário.", skill: "Xadrez" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Como se chama o movimento final que termina a partida de xadrez?", options: ["Xeque-mate", "Nocaute", "Gol contra", "Fim de jogo"], answer: "Xeque-mate", explanation: "Ocorre quando o rei está sob ataque e não tem para onde fugir.", skill: "Xadrez" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual peça movimenta-se apenas em 'L' no tabuleiro?", options: ["Cavalo", "Torre", "Rainha", "Peão"], answer: "Cavalo", explanation: "O cavalo é a única peça que pode 'pular' sobre as outras.", skill: "Xadrez" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "A peça que pode andar qualquer número de casas em linha reta (horiz./vertic.) é a:", options: ["Torre", "Bispo", "Rei", "Peão"], answer: "Torre", explanation: "Movimenta-se como uma cruz no tabuleiro.", skill: "Xadrez" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O Bispo movimenta-se sempre nas:", options: ["Diagonais", "Retas laterais", "Apenas uma casa", "Pula sobre as outras"], answer: "Diagonais", explanation: "Um bispo sempre ficará nas casas da mesma cor em que começou.", skill: "Xadrez" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual a peça mais poderosa do tabuleiro pela sua mobilidade?", options: ["Dama (Rainha)", "Rei", "Torre", "Bispo"], answer: "Dama (Rainha)", explanation: "Pode andar em qualquer direção e qualquer número de casas.", skill: "Xadrez" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O 'Peão' captura as peças adversárias movimentando-se em:", options: ["Diagonal (uma casa)", "Linha reta", "L", "Qualquer direção"], answer: "Diagonal (uma casa)", explanation: "O peão anda para frente, mas captura na diagonal.", skill: "Xadrez" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O movimento especial que envolve o Rei e a Torre chama-se:", options: ["Roque", "Gambit", "Promoção", "Captura na passagem"], answer: "Roque", explanation: "Serve para proteger o rei e ativar a torre simultaneamente.", skill: "Xadrez" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O xadrez desenvolve quais capacidades cognitivas no aluno?", options: ["Raciocínio lógico, paciência e tomada de decisão", "Apenas força nos dedos", "Visão de cores apenas", "Memória de músicas"], answer: "Raciocínio lógico, paciência e tomada de decisão", explanation: "É uma excelente ferramenta pedagógica.", skill: "Xadrez" },

  // 7º Ed. Física - Esportes Gerais (9)
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Esportes de 'Invasão' são aqueles onde o objetivo é:", options: ["Levar um objeto ao campo adversário para marcar pontos/gols", "Ficar parado no centro e não deixar ninguém passar", "Jogar o objeto para o mais longe possível sem sair do lugar", "Apenas fugir"], answer: "Levar um objeto ao campo adversário para marcar pontos/gols", explanation: "Exemplos: Futebol, Basquete, Handebol.", skill: "Esportes Gerais" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Qual destes é um esporte de REDE/PAREDE?", options: ["Vôlei", "Rugby", "Luta livre", "Maratona"], answer: "Vôlei", explanation: "O objetivo é lançar a bola sobre a rede para o campo adversário.", skill: "Esportes Gerais" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "No Basquete, quantos pontos vale um arremesso feito de fora da linha semicircular?", options: ["3 pontos", "2 pontos", "1 ponto", "5 pontos"], answer: "3 pontos", explanation: "A linha de três valoriza os arremessos de longa distância.", skill: "Esportes Gerais" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "O Handebol é um esporte jogado predominantemente com as:", options: ["Mãos", "Pés", "Cabeças", "Bastões"], answer: "Mãos", explanation: "É um jogo de invasão muito rápido e dinâmico.", skill: "Esportes Gerais" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "O esporte de 'Marca' caracteriza-se por:", options: ["Superar marcas de tempo, distância ou peso", "Marcar o adversário com as mãos", "Pintar uma marca no chão", "Ser o melhor dançarino"], answer: "Superar marcas de tempo, distância ou peso", explanation: "Ex: Natação, Atletismo, Halterofilismo.", skill: "Esportes Gerais" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Esportes de CONBATE são:", options: ["Lutas e artes marciais", "Corrida de cavalos", "Vela e canoagem", "Tênis de mesa"], answer: "Lutas e artes marciais", explanation: "Envolvem enfrentamento direto entre dois oponentes (ex: Judô).", skill: "Esportes Gerais" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "O que caracteriza os Esportes de PRECISÃO?", options: ["Acertar um alvo com o menor número de tentativas", "Correr o mais rápido possível", "Fazer gols em campo de grama", "Lutar contra cinco pessoas"], answer: "Acertar um alvo com o menor número de tentativas", explanation: "Ex: Tiro com arco, Golf, Boliche.", skill: "Esportes Gerais" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "O 'Fair Play' (Jogo Limpo) deve ser praticado em:", options: ["Todos os esportes e competições", "Apenas no futebol profissional", "Apenas quando estamos ganhando", "Em nenhum esporte real"], answer: "Todos os esportes e competições", explanation: "Ética e respeito são a base do esporte em qualquer nível.", skill: "Esportes Gerais" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Qual esporte é conhecido como o 'Rei dos Esportes' no Brasil?", options: ["Futebol", "Vôlei", "Tênis", "Xadrez"], answer: "Futebol", explanation: "Pela sua enorme popularidade e tradição cultural.", skill: "Esportes Gerais" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 19 com ${batch.length} questões adicionado.`);
