import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 4500;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 13: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 8º Geografia - Geografia Mundial (9)
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O que caracteriza um país como 'Desenvolvido'?", options: ["Alto IDH e industrialização avançada", "Grande população apenas", "Muitas florestas preservadas", "Dependência total da agricultura"], answer: "Alto IDH e industrialização avançada", explanation: "Países desenvolvidos possuem alta qualidade de vida e economia diversificada.", skill: "Geografia Mundial" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual continente é conhecido como o 'Berço da Humanidade'?", options: ["África", "Europa", "Ásia", "América"], answer: "África", explanation: "Evidências fósseis indicam que os primeiros ancestrais humanos surgiram na África.", skill: "Geografia Mundial" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A 'Crescente Fértil' é uma região histórica importante localizada no:", options: ["Oriente Médio", "Sul da África", "América Central", "Norte da Europa"], answer: "Oriente Médio", explanation: "Região entre os rios Tigre e Eufrates onde surgiu a agricultura.", skill: "Geografia Mundial" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual o maior oceano do planeta em extensão?", options: ["Pacífico", "Atlântico", "Índico", "Ártico"], answer: "Pacífico", explanation: "Oceano Pacífico cobre cerca de um terço da superfície terrestre.", skill: "Geografia Mundial" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Países 'Emergentes' (como os BRICS) são aqueles que:", options: ["Estão em rápido crescimento econômico", "São os mais pobres do mundo", "Não têm indústrias", "São ilhas isoladas"], answer: "Estão em rápido crescimento econômico", explanation: "Possuem economias em transição para o desenvolvimento pleno.", skill: "Geografia Mundial" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual fenômeno natural explica a formação das grandes cordilheiras como o Himalaia?", options: ["Tectonismo (movimento de placas)", "Erosão eólica apenas", "Grandes tempestades", "Queda de meteoritos"], answer: "Tectonismo (movimento de placas)", explanation: "O choque entre placas tectônicas soergue a crosta terrestre.", skill: "Geografia Mundial" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A 'Globalização' pode ser definida como:", options: ["O aumento da integração econômica e cultural mundial", "O fechamento das fronteiras", "O fim da tecnologia", "A unificação de todos os governos"], answer: "O aumento da integração econômica e cultural mundial", explanation: "Processo que encurta distâncias através da tecnologia e comércio.", skill: "Geografia Mundial" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual país possui a maior população do mundo atualmente?", options: ["Índia", "China", "EUA", "Brasil"], answer: "Índia", explanation: "A Índia ultrapassou a China em número de habitantes recentemente.", skill: "Geografia Mundial" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O 'Círculo de Fogo do Pacífico' é famoso por sua intensa atividade:", options: ["Sísmica e vulcânica", "De pesca apenas", "De turismo solar", "De extração de madeira"], answer: "Sísmica e vulcânica", explanation: "Zona de encontro de muitas placas, causando terremotos e vulcões.", skill: "Geografia Mundial" },

  // 9º Geografia - Economia Global (9)
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O que significa a sigla PIB na economia?", options: ["Produto Interno Bruto", "População Interna Baixa", "Plano Industrial Brasileiro", "Poder Individual de Bens"], answer: "Produto Interno Bruto", explanation: "Soma de todos os bens e serviços produzidos por um país.", skill: "Economia Global" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Empresas 'Transnacionais' são aquelas que:", options: ["Operam em vários países simultaneamente", "Pertencem apenas ao governo", "Só vendem pela internet", "Não visam lucro"], answer: "Operam em vários países simultaneamente", explanation: "Expandem suas fábricas e vendas para o mercado global.", skill: "Economia Global" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Qual a função principal da Organização Mundial do Comércio (OMC)?", options: ["Regular e facilitar o comércio entre as nações", "Fazer empréstimos para países pobres", "Proibir a internet", "Organizar as Olimpíadas"], answer: "Regular e facilitar o comércio entre as nações", explanation: "Busca reduzir barreiras e resolver disputas comerciais.", skill: "Economia Global" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O que caracteriza uma 'Commodity'?", options: ["Produtos brutos/matérias-primas com preço internacional", "Software de alta tecnologia", "Obras de arte únicas", "Veículos de luxo"], answer: "Produtos brutos/matérias-primas com preço internacional", explanation: "Exemplos: soja, petróleo, minério de ferro.", skill: "Economia Global" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A Divisão Internacional do Trabalho (DIT) clássica separava o mundo entre:", options: ["Fornecedores de matéria-prima e fornecedores de industrializados", "Pescadores e caçadores", "Norte e Sul geográfico apenas", "Ricos e pobres aleatórios"], answer: "Fornecedores de matéria-prima e fornecedores de industrializados", explanation: "Relação desigual de trocas entre colônias e metrópoles ou países.", skill: "Economia Global" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O 'Neoliberalismo' econômico defende principalmente:", options: ["A menor intervenção do Estado na economia", "O controle total do governo nos preços", "A proibição de empresas estrangeiras", "O fim do uso do dinheiro"], answer: "A menor intervenção do Estado na economia", explanation: "Privilegia o livre mercado e privatizações.", skill: "Economia Global" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O que é um 'Bloco Econômico'?", options: ["União de países para facilitar o comércio mútua", "Uma construção de concreto", "Uma barreira física entre países", "Um grupo de empresas rivais"], answer: "União de países para facilitar o comércio mútua", explanation: "Exemplos: Mercosul, União Europeia.", skill: "Economia Global" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Qual moeda é a principal referência nas transações globais?", options: ["Dólar americano", "Real", "Peso", "Iene"], answer: "Dólar americano", explanation: "É a moeda de reserva e troca dominante no mundo.", skill: "Economia Global" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A 'Obsolescência Programada' refere-se a:", options: ["Produtos feitos para durar pouco e forçar nova compra", "Garantia vitalícia", "Redução de preços", "Melhoria na qualidade do produto"], answer: "Produtos feitos para durar pouco e forçar nova compra", explanation: "Estratégia industrial para estimular o consumo contínuo.", skill: "Economia Global" },

  // 9º Geografia - Europa (9)
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Qual cordilheira separa a Europa da Ásia a Leste?", options: ["Montes Urais", "Andes", "Himalaia", "Alpes"], answer: "Montes Urais", explanation: "Fronteira natural clássica entre os dois continentes.", skill: "Europa" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A União Europeia (UE) é um exemplo de:", options: ["Bloco Econômico e Político", "Aliança Militar apenas", "Grupo de países africanos", "Organização apenas religiosa"], answer: "Bloco Econômico e Político", explanation: "É a integração mais avançada do mundo, com moeda e leis comuns.", skill: "Europa" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Qual país europeu é famoso pelos seus 'Fiordes' (entradas de mar entre montanhas)?", options: ["Noruega", "Espanha", "Itália", "Grécia"], answer: "Noruega", explanation: "A costa norueguesa é marcada por estas formações glaciais.", skill: "Europa" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A Europa é banhada ao Sul por qual mar?", options: ["Mar Mediterrâneo", "Mar Morto", "Mar Cáspio", "Mar de Bering"], answer: "Mar Mediterrâneo", explanation: "Importante rota comercial e histórica que separa Europa da África.", skill: "Europa" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A maior economia da Europa e uma das maiores do mundo é a:", options: ["Alemanha", "Portugal", "Suécia", "Bulgária"], answer: "Alemanha", explanation: "Líder industrial e financeiro do continente europeu.", skill: "Europa" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O que é o 'Brexit'?", options: ["A saída do Reino Unido da União Europeia", "Um novo prato típico", "A entrada da Turquia na UE", "Uma guerra civil europeia"], answer: "A saída do Reino Unido da União Europeia", explanation: "Processo político finalizado em 2020.", skill: "Europa" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O clima predominante na maior parte do centro-norte europeu é o:", options: ["Temperado", "Equatorial", "Desértico", "Tropical"], answer: "Temperado", explanation: "Estações bem definidas com invernos frios e verões brandos.", skill: "Europa" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Qual península europeia abriga Portugal e Espanha?", options: ["Península Ibérica", "Península Itálica", "Península Balcânica", "Península Escandinava"], answer: "Península Ibérica", explanation: "Localizada no extremo sudoeste da Europa.", skill: "Europa" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Os Alpes são uma importante cadeia de montanhas localizada no:", options: ["Centro-Sul da Europa", "Norte da Rússia", "Litoral de Portugal", "Sul da Inglaterra"], answer: "Centro-Sul da Europa", explanation: "Atravessam países como França, Suíça e Áustria.", skill: "Europa" },

  // 6º Arte - Formas de Expressão (9)
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Qual forma de expressão artística utiliza o corpo e o movimento no espaço?", options: ["Dança", "Escultura", "Arquitetura", "Gravura"], answer: "Dança", explanation: "A dança é a arte de mover o corpo de forma ritmada.", skill: "Formas de Expressão" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A 'Fotografia' é uma forma de arte que utiliza:", options: ["A luz captada em uma superfície sensível", "Apenas tintas a óleo", "O som ambiente", "A manipulação de argila"], answer: "A luz captada em uma superfície sensível", explanation: "Etimologicamente significa 'escrever com a luz'.", skill: "Formas de Expressão" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Qual arte é conhecida como a 'Sétima Arte'?", options: ["Cinema", "Pintura", "Literatura", "Música"], answer: "Cinema", explanation: "O cinema une imagem, movimento e som em uma narrativa.", skill: "Formas de Expressão" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A arte de misturar sons e silêncio de forma organizada é a:", options: ["Música", "Pantomima", "Culinária", "Tecelagem"], answer: "Música", explanation: "A música utiliza ritmo, melodia e harmonia.", skill: "Formas de Expressão" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O Teatro é uma forma de expressão baseada na:", options: ["Representação/Atuação diante de um público", "Apenas na leitura silenciosa", "Pintura de quadros", "Construção de prédios"], answer: "Representação/Atuação diante de um público", explanation: "Envolve atores interpretando personagens e histórias.", skill: "Formas de Expressão" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A Literatura expressa a arte através de:", options: ["Palavras e linguagem escrita/falada", "Cores primárias apenas", "Passos de balé", "Instrumentos de sopro"], answer: "Palavras e linguagem escrita/falada", explanation: "Utiliza a língua como matéria-prima para a criação estética.", skill: "Formas de Expressão" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Arquitetura é a arte de:", options: ["Projetar e construir espaços e edifícios", "Fazer estátuas pequenas", "Desenhar roupas", "Cantar em coro"], answer: "Projetar e construir espaços e edifícios", explanation: "Une funcionalidade e estética no ambiente construído.", skill: "Formas de Expressão" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O que caracteriza as artes visuais?", options: ["Sua apreciação ocorre principalmente pela visão", "São feitas apenas para serem ouvidas", "Não podem ter cores", "Só existem no computador"], answer: "Sua apreciação ocorre principalmente pela visão", explanation: "Exemplos: pintura, desenho, escultura.", skill: "Formas de Expressão" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "As Histórias em Quadrinhos (HQs) são uma mistura de:", options: ["Desenho e Texto (Narrativa visual)", "Apenas música instrumental", "Escultura de mármore", "Teatro de sombras"], answer: "Desenho e Texto (Narrativa visual)", explanation: "Combinam elementos das artes visuais e da literatura.", skill: "Formas de Expressão" },

  // 7º Arte - Técnicas de Desenho (9)
  { grade: "7º", discipline: "Arte", type: "multiple", text: "A técnica de 'Hachura' no desenho consiste em:", options: ["Criar sombras usando linhas paralelas ou cruzadas", "Usar apenas borracha para desenhar", "Pintar com os dedos", "Fazer colagem de papel"], answer: "Criar sombras usando linhas paralelas ou cruzadas", explanation: "As linhas juntas criam tons de cinza e volume.", skill: "Técnicas de Desenho" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "O desenho de 'Observação' exige que o artista:", options: ["Desenhe exatamente o que está vendo à sua frente", "Invente monstros", "Feche os olhos", "Use apenas o computador"], answer: "Desenhe exatamente o que está vendo à sua frente", explanation: "Treina a percepção real das formas, luz e sombra.", skill: "Técnicas de Desenho" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "A 'Perspectiva' no desenho serve para:", options: ["Criar a ilusão de profundidade e distância", "Colorir mais rápido", "Apagar erros", "Misturar as tintas"], answer: "Criar a ilusão de profundidade e distância", explanation: "Permite representar objetos 3D em uma superfície 2D.", skill: "Técnicas de Desenho" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "Qual material de desenho é feito de carbono e permite vários tons?", options: ["Grafite (lápis)", "Caneta esferográfica", "Gelo", "Plástico"], answer: "Grafite (lápis)", explanation: "Lápis H são mais duros/claros e B são mais macios/escuros.", skill: "Técnicas de Desenho" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "O desenho de 'Esboço' (ou croqui) é:", options: ["Um desenho rápido e inicial para captar a ideia", "A obra de arte finalizada e emoldurada", "Um desenho feito com os pés", "Apenas uma mancha de tinta"], answer: "Um desenho rápido e inicial para captar a ideia", explanation: "Serve como base para o desenvolvimento do desenho final.", skill: "Técnicas de Desenho" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "O que é o 'Eixo de Simetria' no desenho?", options: ["Uma linha imaginária que divide o desenho em partes iguais", "A cor principal", "O nome do artista", "O tamanho do papel"], answer: "Uma linha imaginária que divide o desenho em partes iguais", explanation: "Garante equilíbrio e proporção bilateral.", skill: "Técnicas de Desenho" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "A técnica 'Sfumato' (fumaça) serve para:", options: ["Suavizar a transição entre as cores e sombras", "Fazer o desenho pegar fogo", "Aumentar o brilho", "Limpar o papel"], answer: "Suavizar a transição entre as cores e sombras", explanation: "Técnica famosa usada por Leonardo da Vinci na Mona Lisa.", skill: "Técnicas de Desenho" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "O desenho 'Gestual' foca principalmente na:", options: ["Captura da ação e energia do movimento do modelo", "Perfeição dos detalhes anatômicos", "Cor do cenário", "Assinatura do desenhista"], answer: "Captura da ação e energia do movimento do modelo", explanation: "É um desenho rápido que foca na pose e fluidez.", skill: "Técnicas de Desenho" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "Qual papel é mais indicado para técnicas secas como grafite e carvão?", options: ["Papéis com alguma textura (gramatura)", "Papel manteiga", "Papel alumínio", "Papel higiênico"], answer: "Papéis com alguma textura (gramatura)", explanation: "A porosidade ajuda o pigmento a fixar na superfície.", skill: "Técnicas de Desenho" },

  // 8º Arte - Dança (9)
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O que define a 'Coreografia' em uma dança?", options: ["A sequência planejada de passos e movimentos", "Apenas a roupa dos bailarinos", "O lanche após a apresentação", "O nome do teatro"], answer: "A sequência planejada de passos e movimentos", explanation: "É a composição artística da dança.", skill: "Dança" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O 'Balé Clássico' originou-se em qual período histórico?", options: ["Renascimento (cortes europeias)", "Idade da Pedra", "Século XXI", "Futuro"], answer: "Renascimento (cortes europeias)", explanation: "Surgiu na Itália e se desenvolveu na França e Rússia.", skill: "Dança" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual estilo de dança surgiu nas ruas dos EUA como parte da cultura Hip Hop?", options: ["Breakdance", "Valsa", "Samba de Gafieira", "Flamenco"], answer: "Breakdance", explanation: "Inclui movimentos acrobáticos e de chão.", skill: "Dança" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Na dança contemporânea, o foco principal é na:", options: ["Expressividade e liberdade de movimento", "Rigidez total dos passos", "Uso obrigatório de sapatilhas de ponta", "Imitação de animais apenas"], answer: "Expressividade e liberdade de movimento", explanation: "Questiona os padrões clássicos e foca na autonomia do corpo.", skill: "Dança" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O que é o 'Ritmo' na dança?", options: ["A organização do movimento no tempo conforme a música", "A cor do palco", "O tamanho do sapato", "O número de espectadores"], answer: "A organização do movimento no tempo conforme a música", explanation: "É a pulsação que guia o dançarino.", skill: "Dança" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Danças 'Folclóricas' são aquelas que:", options: ["Preservam a cultura e tradição de um povo", "São proibidas para crianças", "Não usam música", "Só existem na televisão"], answer: "Preservam a cultura e tradição de um povo", explanation: "Passadas de geração em geração (ex: Frevo, Quadrilha).", skill: "Dança" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O termo 'Espetáculo' na dança refere-se ao momento de:", options: ["Apresentação para um público", "Ensaio solitário", "Compra de figurinos", "Descanso dos artistas"], answer: "Apresentação para um público", explanation: "É a obra de arte sendo compartilhada visualmente.", skill: "Dança" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual instrumento é frequentemente associado ao sapateado (Tap Dance)?", options: ["As placas de metal nos sapatos", "O violão", "A flauta doce", "O piano"], answer: "As placas de metal nos sapatos", explanation: "O próprio dançarino cria o som percussivo com os pés.", skill: "Dança" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A expressão corporal na dança serve para:", options: ["Transmitir emoções e contar histórias sem palavras", "Apenas exercitar os músculos", "Ficar mais alto", "Esconder o rosto"], answer: "Transmitir emoções e contar histórias sem palavras", explanation: "O corpo é o canal de comunicação do artista.", skill: "Dança" },

  // 6º Ed. Física - Jogos de Tabuleiro (9)
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual jogo de tabuleiro é conhecido como 'O Jogo dos Reis'?", options: ["Xadrez", "Dama", "Ludo", "Trilha"], answer: "Xadrez", explanation: "Jogo de alta estratégia milenar que simula uma batalha medieval.", skill: "Jogos de Tabuleiro" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No jogo de Damas, o movimento das peças ocorre apenas:", options: ["Nas diagonais", "Andando para trás a qualquer momento", "Em linha reta vertical", "Saltando sobre as próprias peças"], answer: "Nas diagonais", explanation: "As peças comuns só andam para frente em diagonal.", skill: "Jogos de Tabuleiro" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No Xadrez, qual peça tem o movimento em formato de 'L'?", options: ["Cavalo", "Bispo", "Torre", "Rainha"], answer: "Cavalo", explanation: "O cavalo é a única peça que pode 'pular' sobre as outras.", skill: "Jogos de Tabuleiro" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O objetivo final do Xadrez é dar o:", options: ["Xeque-Mate no Rei", "Comer todas as peças", "Chegar ao fim do campo", "Capturar a Rainha e pronto"], answer: "Xeque-Mate no Rei", explanation: "A vitória ocorre quando o rei não tem para onde fugir.", skill: "Jogos de Tabuleiro" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O jogo 'Mancala' tem origem em qual continente?", options: ["África", "Europa", "Antártida", "América do Norte"], answer: "África", explanation: "É um dos jogos mais antigos do mundo, focado em semear e colher.", skill: "Jogos de Tabuleiro" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Jogos de tabuleiro ajudam no desenvolvimento de quais habilidades?", options: ["Raciocínio lógico e paciência", "Apenas força muscular", "Velocidade de corrida", "Natação"], answer: "Raciocínio lógico e paciência", explanation: "São considerados esportes da mente.", skill: "Jogos de Tabuleiro" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No jogo de trilha, o objetivo é formar uma linha de três peças para:", options: ["Remover uma peça do adversário", "Ganhar o jogo na hora", "Mudar a cor do tabuleiro", "Dobrar os pontos"], answer: "Remover uma peça do adversário", explanation: "Formar o 'moinho' permite a captura estratégica.", skill: "Jogos de Tabuleiro" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Quantas casas tem um tabuleiro clássico de Xadrez ou Dama?", options: ["64 casas", "100 casas", "24 casas", "12 casas"], answer: "64 casas", explanation: "Tabuleiro de 8x8 casas alternadas em cores.", skill: "Jogos de Tabuleiro" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No Xadrez, qual peça pode se mover em qualquer direção e qualquer número de casas?", options: ["Rainha (Dama)", "Rei", "Peão", "Bispo apenas diagonal"], answer: "Rainha (Dama)", explanation: "A Rainha é a peça mais poderosa do tabuleiro.", skill: "Jogos de Tabuleiro" },

  // 6º Ed. Física - Danças Típicas (9)
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual dança é símbolo das festas juninas no Brasil?", options: ["Quadrilha", "Samba", "Balé", "Jazz"], answer: "Quadrilha", explanation: "Dança coletiva coreografada com temas rurais.", skill: "Danças Típicas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O 'Frevo' é uma dança típica de qual estado brasileiro?", options: ["Pernambuco", "Rio Grande do Sul", "São Paulo", "Mato Grosso"], answer: "Pernambuco", explanation: "Caracterizada pelo ritmo acelerado e sombrinhas coloridas.", skill: "Danças Típicas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual dança gaúcha utiliza lenços e roupas típicas como a bombacha?", options: ["Chula / Vanerão", "Funk", "Forró", "Lambada"], answer: "Chula / Vanerão", explanation: "Danças tradicionais do Sul do Brasil.", skill: "Danças Típicas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O 'Samba de Roda' é considerado patrimônio cultural originário de qual estado?", options: ["Bahia", "Paraná", "Amazonas", "Espirito Santo"], answer: "Bahia", explanation: "Raiz do samba brasileiro vinda do Recôncavo Baiano.", skill: "Danças Típicas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O 'Carimbó' é uma dança típica da região:", options: ["Norte (Pará)", "Nordeste", "Centro-Oeste", "Sudeste"], answer: "Norte (Pará)", explanation: "Dança de roda dos pescadores com saias rodadas.", skill: "Danças Típicas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "A 'Catira' é uma dança marcada pelo batido de:", options: ["Pés e mãos no ritmo da viola", "Tambores gigantes", "Palitos de madeira", "Metais pesados"], answer: "Pés e mãos no ritmo da viola", explanation: "Típica do interior do Brasil (Cultura Caipira).", skill: "Danças Típicas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Danças típicas ajudam a preservar:", options: ["A identidade e história de uma comunidade", "O preço dos alimentos", "O clima global", "As leis de trânsito"], answer: "A identidade e história de uma comunidade", explanation: "São manifestações da cultura popular.", skill: "Danças Típicas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual destas é uma característica comum em danças populares?", options: ["Serem dançadas em grupos/comunidades", "Terem regras secretas", "Serem proibidas no interior", "Não terem música"], answer: "Serem dançadas em grupos/comunidades", explanation: "Promovem a integração social.", skill: "Danças Típicas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O 'Bumba-meu-boi' mistura dança com:", options: ["Teatro e música dramática", "Natação sincronizada", "Luta de boxe", "Arquitetura barroca"], answer: "Teatro e música dramática", explanation: "Conta a história do boi que morre e ressuscita.", skill: "Danças Típicas" },

  // 7º Ed. Física - Ginástica (9)
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "A 'Ginástica Artística' utiliza quais aparelhos?", options: ["Trave, solo, barras e salto", "Bolas de boliche", "Ramos de árvores", "Veículos motorizados"], answer: "Trave, solo, barras e salto", explanation: "Exige força, equilíbrio e flexibilidade.", skill: "Ginástica" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Qual ginástica foca em movimentos rítmicos com aparelhos como fita e corda?", options: ["Ginástica Rítmica", "Ginástica Laboral", "Crossfit", "Sumo"], answer: "Ginástica Rítmica", explanation: "Exigência estética e coordenação fina com aparelhos manuais.", skill: "Ginástica" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "O objetivo da 'Ginástica para Todos' (GPT) é:", options: ["Inclusão e diversão sem foco em competição", "Ganhar medalhas de ouro apenas", "Excluir quem não faz espacate", "Ser o mais forte da academia"], answer: "Inclusão e diversão sem foco em competição", explanation: "Valoriza a expressão corporal livre de pressões competitivas.", skill: "Ginástica" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Qual capacidade física é essencial para um ginasta se manter na trave?", options: ["Equilíbrio", "Velocidade de corrida", "Potência vocal", "Paciência"], answer: "Equilíbrio", explanation: "Manter o centro de gravidade estável.", skill: "Ginástica" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "A 'Ginástica de Trampolim' envolve saltos em qual equipamento?", options: ["Cama elástica / Trampolim", "Piscina olímpica", "Pista de gelo", "Colchão de molas comuns"], answer: "Cama elástica / Trampolim", explanation: "Execução de acrobacias no ar.", skill: "Ginástica" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Fazer alongamento ajuda a melhorar a:", options: ["Flexibilidade", "Força explosiva", "Audição", "Visão"], answer: "Flexibilidade", explanation: "Permite maior amplitude de movimento das articulações.", skill: "Ginástica" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Qual modalidade de ginástica une acrobacias corporais e pirâmides humanas?", options: ["Ginástica Acrobática", "Aeróbica", "Meditação", "Caminhada"], answer: "Ginástica Acrobática", explanation: "Focada no trabalho em dupla ou grupo e confiança.", skill: "Ginástica" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "A ginástica praticada no local de trabalho para evitar lesões é a:", options: ["Ginástica Laboral", "Ginástica Olímpica", "Musculação", "Ioga"], answer: "Ginástica Laboral", explanation: "Séries curtas de exercícios durante o expediente.", skill: "Ginástica" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Um benefício da prática regular de ginástica é:", options: ["Melhora da coordenação motora e saúde", "Crescimento de asas", "Ficar invisível", "Não precisar dormir mais"], answer: "Melhora da coordenação motora e saúde", explanation: "Desenvolve o controle do próprio corpo.", skill: "Ginástica" },

  // 8º Ed. Física - Aventura (9)
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Esportes de aventura na natureza são aqueles praticados em:", options: ["Ambientes naturais (ar, terra, água)", "Shopping centers", "Bibliotecas", "Dentro de elevadores"], answer: "Ambientes naturais (ar, terra, água)", explanation: "Envolvem incerteza do ambiente e adrenalina.", skill: "Aventura" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Qual esporte de aventura utiliza uma corda elástica para saltos de grandes alturas?", options: ["Bungee Jump", "Surfe", "Xadrez", "Caminhada"], answer: "Bungee Jump", explanation: "Salto livre com retenção elástica.", skill: "Aventura" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "O 'Rafting' é praticado em qual ambiente?", options: ["Corredeiras de rios (em bote)", "Topo de prédios", "Pista de skate", "Fundo do mar"], answer: "Corredeiras de rios (em bote)", explanation: "Descida coletiva de rios com obstáculos naturais.", skill: "Aventura" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Como chamamos a prática de caminhar por trilhas naturais?", options: ["Trilha / Trekking", "Maratona urbana", "Desfile de moda", "Pelada de rua"], answer: "Trilha / Trekking", explanation: "Caminhadas de curta ou longa duração em áreas preservadas.", skill: "Aventura" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "O 'Parkour' é uma prática de aventura urbana que consiste em:", options: ["Superar obstáculos da cidade com o corpo", "Andar de bicicleta de mãos dadas", "Pintar paredes com spray", "Dançar valsa na praça"], answer: "Superar obstáculos da cidade com o corpo", explanation: "Usa o ambiente urbano para saltos, corridas e escaladas.", skill: "Aventura" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Qual equipamento é ESSENCIAL para a prática segura de Rapel?", options: ["Corda, cadeirinha e mosquetão", "Guarda-chuva", "Patins", "Bola de futebol"], answer: "Corda, cadeirinha e mosquetão", explanation: "Garantem a segurança na descida vertical.", skill: "Aventura" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "O respeito ao meio ambiente nos esportes de aventura é importante para:", options: ["Preservar os locais de prática e a fauna/flora", "Ganhar patrocinio", "Ficar bonito na foto", "Não pagar multa apenas"], answer: "Preservar os locais de prática e a fauna/flora", explanation: "Sustentabilidade é pilar dos esportes de natureza.", skill: "Aventura" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Slide/Tiroliza consiste em:", options: ["Deslizar por um cabo de aço entre dois pontos", "Cair de costas na água", "Correr em círculos", "Fazer malabarismo"], answer: "Deslizar por um cabo de aço entre dois pontos", explanation: "Travessia aérea segura por cabos.", skill: "Aventura" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Muitos esportes de aventura ajudam a desenvolver o:", options: ["Autocontrole e coragem", "Medo de sair de casa", "Desrespeito às regras", "Egoísmo"], answer: "Autocontrole e coragem", explanation: "Lidar com riscos calculados fortalece a mente.", skill: "Aventura" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 13 com ${batch.length} questões adicionado.`);
