import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 4600;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 14: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 6º Ensino Religioso - Símbolos Religiosos (9)
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O que os 'Símbolos Religiosos' representam primordialmente?", options: ["Ideias e verdades da fé de forma visual", "Apenas decoração para templos", "Marcas de empresas famosas", "Sinais de trânsito antigos"], answer: "Ideias e verdades da fé de forma visual", explanation: "Os símbolos são linguagens visuais que comunicam o sagrado.", skill: "Símbolos Religiosos" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A Cruz é o símbolo principal de qual religião?", options: ["Cristianismo", "Islamismo", "Budismo", "Hinduísmo"], answer: "Cristianismo", explanation: "Representa o sacrifício e a ressurreição de Jesus Cristo.", skill: "Símbolos Religiosos" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Crescente com uma Estrela' é frequentemente associado ao:", options: ["Islamismo", "Judaísmo", "Espiritismo", "Xintoísmo"], answer: "Islamismo", explanation: "Símbolo muito comum em bandeiras de países de maioria muçulmana.", skill: "Símbolos Religiosos" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Estrela de Davi' (seis pontas) identifica qual tradição religiosa?", options: ["Judaísmo", "Catolicismo", "Protestantismo", "Umbanda"], answer: "Judaísmo", explanation: "Símbolo milenar do povo e da religião judaica.", skill: "Símbolos Religiosos" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O símbolo 'Om' (Aum) é considerado o som primordial no:", options: ["Hinduísmo", "Luteranismo", "Anglicanismo", "Mormonismo"], answer: "Hinduísmo", explanation: "É o mantra mais sagrado das tradições indianas.", skill: "Símbolos Religiosos" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Roda do Dharma' (Dharmachakra) representa os ensinamentos do:", options: ["Budismo", "Sikhismo", "Taoísmo", "Jainismo"], answer: "Budismo", explanation: "Representa o caminho para a iluminação ensinado por Buda.", skill: "Símbolos Religiosos" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Qual destes elementos é um símbolo comum de purificação em várias religiões?", options: ["Água", "Pedra", "Ferro", "Plástico"], answer: "Água", explanation: "Usada em batismos, abluções e rituais de limpeza espiritual.", skill: "Símbolos Religiosos" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Torii' é um portal tradicional que marca a entrada de santuários no:", options: ["Xintoísmo (Japão)", "Egito Antigo", "Grécia Clássica", "Império Asteca"], answer: "Xintoísmo (Japão)", explanation: "Sinaliza a transição do mundo comum para o sagrado.", skill: "Símbolos Religiosos" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Respeitar o símbolo de uma religião diferente da nossa é:", options: ["Um dever de cidadania e respeito", "Proibido por lei", "Faltar com a própria fé", "Um sinal de fraqueza"], answer: "Um dever de cidadania e respeito", explanation: "O respeito à diversidade cultural é base para a convivência pacífica.", skill: "Símbolos Religiosos" },

  // 6º Ensino Religioso - Símbolos e Valores (9)
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Além de representar fés, símbolos religiosos costumam carregar:", options: ["Valores morais e éticos", "Apenas preços de mercado", "Códigos de barras", "Datas de feriado apenas"], answer: "Valores morais e éticos", explanation: "Os símbolos inspiram comportamentos positivos e virtudes.", skill: "Símbolos e Valores" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A pomba branca é um símbolo universal de qual valor?", options: ["Paz", "Guerra", "Ganância", "Inveja"], answer: "Paz", explanation: "Utilizada tanto em contextos religiosos quanto laicos para representar a não-violência.", skill: "Símbolos e Valores" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A luz (vela, lamparina) nas religiões simboliza frequentemente:", options: ["Sabedoria e presença divina", "Fogo perigoso", "Falta de eletricidade", "O fim do dia apenas"], answer: "Sabedoria e presença divina", explanation: "A luz dissipa as trevas da ignorância e guia o fiel.", skill: "Símbolos e Valores" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O ato de partilhar o pão em diversas tradições simboliza:", options: ["Generosidade e fraternidade", "Comércio de alimentos", "Fome", "Egoísmo"], answer: "Generosidade e fraternidade", explanation: "A partilha é um valor central de cuidado com o próximo.", skill: "Símbolos e Valores" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Coração' como símbolo religioso expressa o valor do:", options: ["Amor e compaixão", "Ódio", "Medo", "Cansaço físico"], answer: "Amor e compaixão", explanation: "Representa o centro dos sentimentos e da entrega espiritual.", skill: "Símbolos e Valores" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A flor de lótus, que nasce na lama mas é pura, simboliza:", options: ["Superação e pureza espiritual", "Sujeira", "Morte", "Apenas decoração"], answer: "Superação e pureza espiritual", explanation: "Muito comum no Budismo e Hinduísmo para representar a evolução da alma.", skill: "Símbolos e Valores" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Qual valor é incentivado quando os fiéis se reúnem em comunidade?", options: ["União e pertencimento", "Isolamento", "Disputa", "Indiferença"], answer: "União e pertencimento", explanation: "As religiões promovem o senso de grupo e apoio mútuo.", skill: "Símbolos e Valores" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Vandalizar ou zombar de símbolos religiosos alheios fere o valor da:", options: ["Tolerância e respeito", "Coragem", "Liberdade de expressão total", "Amizade"], answer: "Tolerância e respeito", explanation: "O respeito ao sagrado do outro é fundamental para a ética social.", skill: "Símbolos e Valores" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Símbolos de mãos dadas ou unidas costumam representar:", options: ["Oração e concordância", "Briga", "Fuga", "Segredo"], answer: "Oração e concordância", explanation: "Mãos postas ou unidas indicam reverência e união de propósitos.", skill: "Símbolos e Valores" },

  // 7º Ensino Religioso - Textos Sagrados (9)
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Qual é o livro sagrado do Cristianismo?", options: ["Bíblia", "Alcorão", "Torá", "Vedas"], answer: "Bíblia", explanation: "Composta pelo Antigo e Novo Testamento.", skill: "Textos Sagrados" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "O livro sagrado dos muçulmanos chama-se:", options: ["Alcorão (Corão)", "Talmude", "Bíblia", "Livro dos Mortos"], answer: "Alcorão (Corão)", explanation: "Considerado a palavra de Deus revelada ao profeta Maomé.", skill: "Textos Sagrados" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Torá' (Pentateuco) é o texto central de qual religião?", options: ["Judaísmo", "Budismo", "Espiritismo", "Xintoísmo"], answer: "Judaísmo", explanation: "Contém as leis e ensinamentos fundamentais do povo judeu.", skill: "Textos Sagrados" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Tripitaka' (Três Cestos) contém os ensinamentos sagrados do:", options: ["Budismo", "Hinduísmo", "Islamismo", "Sikhismo"], answer: "Budismo", explanation: "Coleção de escrituras fundamentais da tradição budista.", skill: "Textos Sagrados" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Os 'Vedas' são os textos sagrados mais antigos de qual tradição?", options: ["Hinduísmo", "Catolicismo", "Umbanda", "Luteranismo"], answer: "Hinduísmo", explanation: "Escritos em sânscrito, formam a base da cultura espiritual indiana.", skill: "Textos Sagrados" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "O que caracteriza um 'Texto Sagrado'?", options: ["Ser considerado de origem ou inspiração divina", "Ser apenas um livro de histórias comuns", "Não ter autor", "Ser proibido para leitura"], answer: "Ser considerado de origem ou inspiração divina", explanation: "As religiões veem neles a vontade e a sabedoria superior.", skill: "Textos Sagrados" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "O Espiritismo tem como uma de suas bases principais o livro:", options: ["O Livro dos Espíritos", "Bíblia de Gutenberg", "Popol Vuh", "Bhagavad Gita"], answer: "O Livro dos Espíritos", explanation: "Obra fundamental codificada por Allan Kardec.", skill: "Textos Sagrados" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Os textos sagrados servem para:", options: ["Orientar a fé, a moral e os ritos dos fiéis", "Apenas contar fatos científicos", "Vender muitos exemplares", "Prever o tempo"], answer: "Orientar a fé, a moral e os ritos dos fiéis", explanation: "São bússolas espirituais para os praticantes.", skill: "Textos Sagrados" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Muitas tradições orais (indígenas, africanas) não têm textos escritos porque:", options: ["Sua sabedoria é transmitida de viva voz", "Eles não sabem falar", "A escrita é proibida", "Não existem histórias"], answer: "Sua sabedoria é transmitida de viva voz", explanation: "A oralidade é a forma sagrada de preservação da memória nessas culturas.", skill: "Textos Sagrados" },

  // 8º Ensino Religioso - Ética e Moral (9)
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Moral' religiosa geralmente se refere a:", options: ["O conjunto de regras sobre o que é certo e errado", "O lanche do templo", "A música preferida", "A cor das roupas"], answer: "O conjunto de regras sobre o que é certo e errado", explanation: "Moral são as normas de conduta aceitas por um grupo.", skill: "Ética e Moral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Ética' é a parte da filosofia que estuda:", options: ["O comportamento humano e os valores", "Os planetas", "Os dinossauros", "A culinária"], answer: "O comportamento humano e os valores", explanation: "A ética reflete sobre os princípios por trás da moral.", skill: "Ética e Moral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Qual destes é um princípio ético comum a quase todas as religiões?", options: ["A compaixão e o amor ao próximo", "A vingança", "A preguiça", "A intolerância"], answer: "A compaixão e o amor ao próximo", explanation: "É a base para o tratamento humano e digno.", skill: "Ética e Moral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Um dilema moral ocorre quando:", options: ["Temos que escolher entre dois valores difíceis", "Ganhamos um presente", "Estamos com sono", "Lemos um livro"], answer: "Temos que escolher entre dois valores difíceis", explanation: "É um conflito de decisão sobre qual o melhor caminho a seguir.", skill: "Ética e Moral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Para a ética religiosa, a liberdade deve vir acompanhada da:", options: ["Responsabilidade", "Fuga", "Confusão", "Ignorância"], answer: "Responsabilidade", explanation: "Somos responsáveis pelas consequências de nossas escolhas.", skill: "Ética e Moral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A honestidade é um valor moral que defende:", options: ["Falar a verdade e agir com integridade", "Enganar para ganhar", "Ficar calado sempre", "Esconder os erros"], answer: "Falar a verdade e agir com integridade", explanation: "É ser verdadeiro consigo e com os outros.", skill: "Ética e Moral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Dizer que 'os fins justificam os meios' costuma ser:", options: ["Questionado pela ética (não se deve fazer o mal para ter o bem)", "O lema de todas as religiões", "Uma regra matemática", "Apenas uma rima"], answer: "Questionado pela ética (não se deve fazer o mal para ter o bem)", explanation: "A ética foca tanto no caminho quanto no objetivo.", skill: "Ética e Moral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "O respeito aos idosos é um valor moral focado na:", options: ["Sabedoria e gratidão", "Inutilidade", "Exclusão", "Curiosidade apenas"], answer: "Sabedoria e gratidão", explanation: "Muitas tradições honram quem veio antes e transmitiu a vida.", skill: "Ética e Moral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Agir de forma ética em momentos de pressão revela:", options: ["O verdadeiro caráter da pessoa", "Que a pessoa é boba", "Medo de castigo apenas", "Sorte"], answer: "O verdadeiro caráter da pessoa", explanation: "A ética é testada nos momentos difíceis.", skill: "Ética e Moral" },

  // 8º Ensino Religioso - Valores e Ação (9)
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Solidariedade' manifestada em ações religiosas busca:", options: ["Aliviar o sofrimento do próximo", "Apenas tirar fotos", "Ganhar dinheiro", "Trocar favores"], answer: "Aliviar o sofrimento do próximo", explanation: "Muitas instituições religiosas mantêm obras sociais importantes.", skill: "Valores e Ação" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Voluntariado' é uma forma de colocar em prática o valor do(a):", options: ["Altruísmo (ajudar sem esperar nada em troca)", "Egoísmo", "Comércio", "Dívida"], answer: "Altruísmo (ajudar sem esperar nada em troca)", explanation: "É doar tempo e talento para o bem comum.", skill: "Valores e Ação" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "O valor da 'Empatia' na prática significa:", options: ["Colocar-se no lugar do outro e sentir sua dor/alegria", "Sentir inveja", "Ignorar o problema alheio", "Criticar o outro"], answer: "Colocar-se no lugar do outro e sentir sua dor/alegria", explanation: "É a base para a compreensão e o apoio humano.", skill: "Valores e Ação" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Qual destas é uma ação social comum incentivada pelas religiões?", options: ["Doação de alimentos e agasalhos", "Venda de ingressos caros", "Disputas políticas violentas", "Exclusão de estrangeiros"], answer: "Doação de alimentos e agasalhos", explanation: "Atendimento às necessidades básicas dos mais pobres.", skill: "Valores e Ação" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "O valor da 'Paciência' ajuda a:", options: ["Lidar com as dificuldades sem perder a calma", "Ficar com raiva rápido", "Fugir das responsabilidades", "Dormir demais"], answer: "Lidar com as dificuldades sem perder a calma", explanation: "É a virtude de suportar incômodos com serenidade.", skill: "Valores e Ação" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Agir com 'Justiça' significa:", options: ["Dar a cada um o que lhe é de direito", "Favorecer apenas os amigos", "Punir sem provas", "Ignorar as leis"], answer: "Dar a cada um o que lhe é de direito", explanation: "Equidade e imparcialidade são pilares da justiça.", skill: "Valores e Ação" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "O valor do 'Perdão' nas religiões serve para:", options: ["Libertar o coração de mágoas e restaurar a paz", "Esquecer que a pessoa existe", "Ganhar uma competição", "Ser superior ao outro"], answer: "Libertar o coração de mágoas e restaurar a paz", explanation: "O perdão cura relacionamentos e promove a reconciliação.", skill: "Valores e Ação" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Respeitar a natureza é um valor de ação chamado:", options: ["Ecologia Integral / Cuidado com a criação", "Destruição planejada", "Medo de bichos", "Folclore apenas"], answer: "Ecologia Integral / Cuidado com a criação", explanation: "Zelar pelo planeta como lar comum de todos.", skill: "Valores e Ação" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "O valor da 'Humildade' opõe-se ao(à):", options: ["Arrogância e orgulho excessivo", "Pobreza", "Tristeza", "Coragem"], answer: "Arrogância e orgulho excessivo", explanation: "A humildade reconhece limitações e valoriza os outros.", skill: "Valores e Ação" },

  // 9º Ensino Religioso - Direito e Religião (9)
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O que garante que todas as pessoas no Brasil possam ter sua religião?", options: ["A Constituição Federal (Liberdade de Crença)", "O dono da rua", "A televisão", "Apenas a vontade do Papa"], answer: "A Constituição Federal (Liberdade de Crença)", explanation: "É um direito fundamental garantido por lei máxima.", skill: "Direito e Religião" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Um 'Estado Laico' deve ser:", options: ["Neutro em relação às religiões, garantindo a todas o mesmo direito", "A favor de apenas uma religião", "Contra todas as religiões", "Comandado por um líder religioso"], answer: "Neutro em relação às religiões, garantindo a todas o mesmo direito", explanation: "Laicidade não é ateísmo, mas neutralidade estatal.", skill: "Direito e Religião" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Intolerância Religiosa' no Brasil é considerada:", options: ["Crime", "Usa coisa normal", "Uma piada permitida", "Um elogio"], answer: "Crime", explanation: "A lei brasileira pune quem discrimina ou agride por motivos religiosos.", skill: "Direito e Religião" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Qual documento internacional defende a liberdade de pensamento e religião?", options: ["Declaração Universal dos Direitos Humanos", "Regulamento da Escola", "Código de Trânsito", "Manual de Instruções"], answer: "Declaração Universal dos Direitos Humanos", explanation: "Artigo 18 da Declaração da ONU de 1948.", skill: "Direito e Religião" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O direito de 'não ter religião' (ateísmo/agnosticismo) também é protegido?", options: ["Sim, a liberdade inclui crer ou não crer", "Não, todos devem acreditar em algo", "Apenas se pagar multa", "Somente nos finais de semana"], answer: "Sim, a liberdade inclui crer ou não crer", explanation: "A liberdade de consciência é absoluta no Estado democrático.", skill: "Direito e Religião" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Garantir o livre exercício dos cultos religiosos é:", options: ["Um dever do Estado e um direito do cidadão", "Proibido em locais públicos", "Apenas para religiões grandes", "Passível de impostos extras"], answer: "Um dever do Estado e um direito do cidadão", explanation: "O Estado deve proteger os templos e as cerimônias.", skill: "Direito e Religião" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O ensino religioso nas escolas públicas brasileiras deve ser:", options: ["De matrícula facultativa e sem proselitismo (converter)", "Obrigatório para todos sem exceção", "Focado apenas na Bíblia", "Proibido por lei"], answer: "De matrícula facultativa e sem proselitismo (converter)", explanation: "Deve respeitar a diversidade e a escolha do aluno/família.", skill: "Direito e Religião" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O que é 'Escusa de Consciência' por motivos religiosos?", options: ["Direito de não realizar certas obrigações que firam sua fé", "Poder faltar à escola todo dia", "Não pagar impostos", "Poder andar em qualquer lado da rua"], answer: "Direito de não realizar certas obrigações que firam sua fé", explanation: "Permite alternativas para obrigações legais em conflito com a crença.", skill: "Direito e Religião" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O diálogo entre as religiões e o Direito visa evitar:", options: ["Conflitos sociais e perseguições", "O nascimento de novas fés", "O uso de livros", "A construção de templos coloridos"], answer: "Conflitos sociais e perseguições", explanation: "A lei existe para harmonizar as diferenças e proteger a paz.", skill: "Direito e Religião" },

  // 9º Ensino Religioso - Cultura de Paz (9)
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Cultura de Paz' baseia-se primordialmente no(a):", options: ["Diálogo, respeito e não-violência", "Guerra santa", "Uso da força para convencer", "Isolamento total"], answer: "Diálogo, respeito e não-violência", explanation: "Promovida pela ONU/UNESCO como modo de vida global.", skill: "Cultura de Paz" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Quem foi o líder indiano que pregou a resistência pacífica (Ahimsa)?", options: ["Mahatma Gandhi", "Nelson Mandela", "Martin Luther King", "Dalai Lama"], answer: "Mahatma Gandhi", explanation: "Libertou a Índia sem disparar uma única arma.", skill: "Cultura de Paz" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O diálogo inter-religioso contribui para a paz porque:", options: ["Reduz preconceitos e gera entendimento", "Transforma todos na mesma fé", "Gera lucro para as igrejas", "Cria regras de trânsito"], answer: "Reduz preconceitos e gera entendimento", explanation: "Conhecer o outro diminui o medo e o ódio.", skill: "Cultura de Paz" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Martin Luther King Jr. lutou pelos direitos civis nos EUA usando:", options: ["Palavras e protestos não-violentos", "Armas pesadas", "Fuga para outros países", "Silêncio total"], answer: "Palavras e protestos não-violentos", explanation: "Inspirado por sua fé cristã e pelos ideais de Gandhi.", skill: "Cultura de Paz" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Qual o papel do perdão na construção de uma cultura de paz?", options: ["Quebrar o ciclo de ódio e vingança", "Mostrar que somos melhores", "Esquecer que o problema existiu", "Apenas uma formalidade"], answer: "Quebrar o ciclo de ódio e vingança", explanation: "O perdão permite que as sociedades se reconstruam após conflitos.", skill: "Cultura de Paz" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Diálogo' é diferente de um 'Debate' porque busca:", options: ["Entendimento mútuo em vez de vencer o outro", "Gritar mais alto", "Ter a última palavra", "Ganhar um troféu"], answer: "Entendimento mútuo em vez de vencer o outro", explanation: "No diálogo, todos crescem com a troca de ideias.", skill: "Cultura de Paz" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Um exemplo de atitude para promover a paz na escola é:", options: ["Mediar conflitos conversando e respeitando as opiniões", "Fazer fofocas", "Excluir quem é diferente", "Resolver na briga"], answer: "Mediar conflitos conversando e respeitando as opiniões", explanation: "A paz começa nas pequenas ações do dia a dia.", skill: "Cultura de Paz" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A justiça social é necessária para a paz duradoura porque:", options: ["Onde há desigualdade extrema e fome, há conflitos", "Justiça é apenas punição", "Os juízes mandam em tudo", "Não tem relação"], answer: "Onde há desigualdade extrema e fome, há conflitos", explanation: "A paz é fruto da justiça e da dignidade para todos.", skill: "Cultura de Paz" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O Prêmio Nobel da Paz é entregue a pessoas que:", options: ["Trabalham pela fraternidade entre as nações e direitos humanos", "Ganham muitas corridas", "Escrevem os melhores livros de terror", "Fazem as maiores descobertas químicas apenas"], answer: "Trabalham pela fraternidade entre as nações e direitos humanos", explanation: "Reconhecimento global de esforços pela harmonia mundial.", skill: "Cultura de Paz" },

  // 6º/7º Inglês - Vocabulary: Colors (9)
  { grade: "7º", discipline: "Inglês", type: "multiple", text: "Which color do you get if you mix BLUE and YELLOW?", options: ["Green", "Purple", "Orange", "Red"], answer: "Green", explanation: "Blue + Yellow = Green.", skill: "Vocabulary: Colors" },
  { grade: "7º", discipline: "Inglês", type: "multiple", text: "The color of the sky on a sunny day is:", options: ["Blue", "Green", "Pink", "Black"], answer: "Blue", explanation: "Sky is blue.", skill: "Vocabulary: Colors" },
  { grade: "7º", discipline: "Inglês", type: "multiple", text: "An apple is usually RED or...", options: ["Green", "Purple", "Blue", "Gray"], answer: "Green", explanation: "Apples can be red or green.", skill: "Vocabulary: Colors" },
  { grade: "7º", discipline: "Inglês", type: "multiple", text: "The color of coal and the night is:", options: ["Black", "White", "Yellow", "Clear"], answer: "Black", explanation: "Coal is black.", skill: "Vocabulary: Colors" },
  { grade: "7º", discipline: "Inglês", type: "multiple", text: "Which color represents the sun and lemons?", options: ["Yellow", "Red", "Blue", "Brown"], answer: "Yellow", explanation: "Sun and lemons are yellow.", skill: "Vocabulary: Colors" },
  { grade: "7º", discipline: "Inglês", type: "multiple", text: "Mix RED and WHITE. What color is it?", options: ["Pink", "Purple", "Orange", "Brown"], answer: "Pink", explanation: "Red + White = Pink.", skill: "Vocabulary: Colors" },
  { grade: "7º", discipline: "Inglês", type: "multiple", text: "What color is a chocolate bar usually?", options: ["Brown", "Green", "Silver", "Yellow"], answer: "Brown", explanation: "Chocolate is brown.", skill: "Vocabulary: Colors" },
  { grade: "7º", discipline: "Inglês", type: "multiple", text: "The grass in a garden is:", options: ["Green", "Red", "Blue", "Gold"], answer: "Green", explanation: "Grass is green.", skill: "Vocabulary: Colors" },
  { grade: "7º", discipline: "Inglês", type: "multiple", text: "ORANGE is also the name of a...", options: ["Fruit", "Car", "City", "Animal"], answer: "Fruit", explanation: "Orange is both a color and a fruit.", skill: "Vocabulary: Colors" },

  // 8º Inglês - Grammar: Comparatives (9)
  { grade: "8º", discipline: "Inglês", type: "multiple", text: "What is the comparative form of the adjective 'BIG'?", options: ["Bigger", "Bigest", "More big", "Bigly"], answer: "Bigger", explanation: "Short adjectives double the final consonant and add -er.", skill: "Grammar: Comparatives" },
  { grade: "8º", discipline: "Inglês", type: "multiple", text: "Complete: English is ________ than math for me.", options: ["easier", "more easy", "easyer", "easyest"], answer: "easier", explanation: "Adjectives ending in Y change to I + er.", skill: "Grammar: Comparatives" },
  { grade: "8º", discipline: "Inglês", type: "multiple", text: "The comparative form of 'BEAUTIFUL' is:", options: ["More beautiful", "Beautifuler", "Beautifulest", "Beautifuller"], answer: "More beautiful", explanation: "Long adjectives use 'more' before the word.", skill: "Grammar: Comparatives" },
  { grade: "8º", discipline: "Inglês", type: "multiple", text: "Which one is an IRREGULAR comparative?", options: ["Better (from Good)", "Smarter", "Slower", "Happier"], answer: "Better (from Good)", explanation: "Good becomes Better, Bad becomes Worse.", skill: "Grammar: Comparatives" },
  { grade: "8º", discipline: "Inglês", type: "multiple", text: "Complete: A car is ________ than a bicycle.", options: ["faster", "fastest", "more fast", "fastly"], answer: "faster", explanation: "Fast + er = faster.", skill: "Grammar: Comparatives" },
  { grade: "8º", discipline: "Inglês", type: "multiple", text: "The comparative of 'BAD' is:", options: ["Worse", "Bader", "Worst", "More bad"], answer: "Worse", explanation: "Bad is irregular.", skill: "Grammar: Comparatives" },
  { grade: "8º", discipline: "Inglês", type: "multiple", text: "Complete: This book is ________ than that one.", options: ["more interesting", "interestinger", "interestingest", "interestier"], answer: "more interesting", explanation: "Long adjective + more.", skill: "Grammar: Comparatives" },
  { grade: "8º", discipline: "Inglês", type: "multiple", text: "To compare two things, we usually use the word ________ after the adjective.", options: ["than", "that", "then", "like"], answer: "than", explanation: "Example: Bigger than...", skill: "Grammar: Comparatives" },
  { grade: "8º", discipline: "Inglês", type: "multiple", text: "What is the comparative of 'TALL'?", options: ["Taller", "Talleres", "More tall", "Tallist"], answer: "Taller", explanation: "Tall + er = taller.", skill: "Grammar: Comparatives" },

  // 9º Inglês - Present Perfect (9)
  { grade: "9º", discipline: "Inglês", type: "multiple", text: "Which auxiliary verbs are used in the Present Perfect?", options: ["Have / Has", "Do / Does", "Did", "Will"], answer: "Have / Has", explanation: "Subject + have/has + Past Participle.", skill: "Present Perfect" },
  { grade: "9º", discipline: "Inglês", type: "multiple", text: "Complete: I ________ never ________ to London.", options: ["have / been", "has / went", "have / went", "has / be"], answer: "have / been", explanation: "I use 'have'. The past participle of 'be' is 'been'.", skill: "Present Perfect" },
  { grade: "9º", discipline: "Inglês", type: "multiple", text: "She ________ just ________ her homework.", options: ["has / finished", "have / finishing", "has / finish", "have / finishes"], answer: "has / finished", explanation: "She uses 'has'.", skill: "Present Perfect" },
  { grade: "9º", discipline: "Inglês", type: "multiple", text: "Which sentence is in the Present Perfect?", options: ["They have played soccer.", "They played soccer.", "They are playing soccer.", "They play soccer."], answer: "They have played soccer.", explanation: "Structure: Have + Past Participle.", skill: "Present Perfect" },
  { grade: "9º", discipline: "Inglês", type: "multiple", text: "The past participle of the verb 'GO' is:", options: ["Gone", "Went", "Goed", "Goning"], answer: "Gone", explanation: "Go (present) - Went (simple past) - Gone (past participle).", skill: "Present Perfect" },
  { grade: "9º", discipline: "Inglês", type: "multiple", text: "Complete: We ________ lived here for ten years.", options: ["have", "has", "are", "do"], answer: "have", explanation: "We uses 'have'.", skill: "Present Perfect" },
  { grade: "9º", discipline: "Inglês", type: "multiple", text: "The Present Perfect is often used for:", options: ["Experience or actions with no specific time", "Habits in the present only", "Actions that finished yesterday with time stated", "Future plans only"], answer: "Experience or actions with no specific time", explanation: "Used for life experiences and connecting past to present.", skill: "Present Perfect" },
  { grade: "9º", discipline: "Inglês", type: "multiple", text: "Have you ________ sushi?", options: ["ever eaten", "never eat", "always eating", "been eat"], answer: "ever eaten", explanation: "Ever is used in questions about experience.", skill: "Present Perfect" },
  { grade: "9º", discipline: "Inglês", type: "multiple", text: "Complete: He ________ ________ his keys.", options: ["has lost", "have lose", "is lost", "has losed"], answer: "has lost", explanation: "He uses 'has'. Past participle of lose is lost.", skill: "Present Perfect" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 14 com ${batch.length} questões adicionado.`);
