import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 4400;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 12: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 8º Matemática - Estatística Básica (9)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que é a 'Média Aritmética' de um conjunto de valores?", options: ["A soma de todos os valores dividida pela quantidade de valores", "O valor que mais se repete", "O valor central de uma lista ordenada", "A diferença entre o maior e o menor valor"], answer: "A soma de todos os valores dividida pela quantidade de valores", explanation: "Média = soma dos termos / número de termos.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Em um conjunto de dados, o valor que aparece com maior frequência é chamado de:", options: ["Moda", "Mediana", "Média", "Desvio"], answer: "Moda", explanation: "Moda é o valor mais frequente em uma distribuição.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual a mediana dos valores: 2, 5, 8, 10, 12?", options: ["5", "8", "10", "12"], answer: "8", explanation: "A mediana é o valor central em uma lista já ordenada.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Se as notas de um aluno são 7, 8 e 9, qual a sua média?", options: ["7", "8", "9", "7,5"], answer: "8", explanation: "(7 + 8 + 9) / 3 = 24 / 3 = 8.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A 'Amplitude' de um conjunto de dados é calculada como:", options: ["Maior valor menos o menor valor", "A soma de todos os valores", "A média dos valores", "O dobro da moda"], answer: "Maior valor menos o menor valor", explanation: "A amplitude indica a variação total dos dados.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Para calcular a mediana de uma lista com número par de termos, devemos:", options: ["Fazer a média dos dois termos centrais", "Escolher o primeiro termo", "Escolher o último termo", "Somar todos"], answer: "Fazer a média dos dois termos centrais", explanation: "Em listas pares, a mediana é a média aritmética do par central.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Em um gráfico de setores (pizza), a soma das partes sempre representa:", options: ["100%", "50%", "360 unidades", "O valor da moda"], answer: "100%", explanation: "O gráfico de setores representa o total (100%) da amostra.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A frequência absoluta representa:", options: ["O número de vezes que um valor aparece", "A porcentagem do valor", "A média do valor", "O valor acumulado"], answer: "O número de vezes que um valor aparece", explanation: "É a contagem direta de ocorrências de um dado.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual a moda no conjunto: 10, 12, 10, 15, 10, 18?", options: ["10", "12", "15", "18"], answer: "10", explanation: "O número 10 repete-se 3 vezes, mais que os outros.", skill: "Estatística Básica" },

  // 8º Matemática - Volumes (9)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Como se calcula o volume de um paralelepípedo reto-retângulo?", options: ["Comprimento x Largura x Altura", "Base x Altura / 2", "Lado x Lado", "2 x (Comprimento + Largura)"], answer: "Comprimento x Largura x Altura", explanation: "O volume é o produto das três dimensões.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o volume de um cubo com aresta de 3 cm?", options: ["9 cm³", "18 cm³", "27 cm³", "12 cm³"], answer: "27 cm³", explanation: "V = 3 x 3 x 3 = 27.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "1 decímetro cúbico (1 dm³) é equivalente a quantos litros?", options: ["0,1 litro", "1 litro", "10 litros", "100 litros"], answer: "1 litro", explanation: "Relação fundamental: 1 dm³ = 1 L.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Para calcular o volume de um cilindro, precisamos da área da base multiplicada pela:", options: ["Altura", "Largura", "Raio", "Circunferência"], answer: "Altura", explanation: "V = Area da base * Altura.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Se dobrarmos a altura de uma caixa, mas mantivermos a base igual, o volume:", options: ["Dobra", "Triplica", "Fica igual", "Cai pela metade"], answer: "Dobra", explanation: "O volume é diretamente proporcional à altura.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual a unidade de medida padrão para volume no Sistema Internacional?", options: ["Metro cúbico (m³)", "Metro quadrado (m²)", "Litro", "Centímetro"], answer: "Metro cúbico (m³)", explanation: "O m³ é a unidade SI derivada para volume.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Uma piscina tem 10m de comprimento, 5m de largura e 2m de profundidade. Qual seu volume?", options: ["100 m³", "50 m³", "200 m³", "17 m³"], answer: "100 m³", explanation: "10 * 5 * 2 = 100.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Quantos centímetros cúbicos (cm³) existem em 1 litro?", options: ["100", "1.000", "10.000", "1"], answer: "1.000", explanation: "1 L = 1 dm³ = 1000 cm³.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O volume de um prisma é dado pela fórmula:", options: ["V = Área da Base x Altura", "V = Base x Altura", "V = (Base + Altura) / 2", "V = Lado²"], answer: "V = Área da Base x Altura", explanation: "Válido para qualquer prisma reto.", skill: "Volumes" },

  // 7º Português - Sintaxe: Predicado (9)
  { grade: "7º", discipline: "Português", type: "multiple", text: "O que é o 'Predicado' em uma oração?", options: ["Tudo o que se diz sobre o sujeito", "Quem realiza a ação", "O sinal de pontuação final", "A palavra que rima"], answer: "Tudo o que se diz sobre o sujeito", explanation: "O predicado expressa a ação, estado ou fenômeno relacionado ao sujeito.", skill: "Sintaxe: Predicado" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Na frase 'Os alunos estudaram muito', qual o predicado?", options: ["Os alunos", "estudaram muito", "muito", "estudaram"], answer: "estudaram muito", explanation: "O sujeito é 'Os alunos', o resto é o predicado.", skill: "Sintaxe: Predicado" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "O predicado verbal é aquele que tem como núcleo:", options: ["Um substantivo", "Um adjetivo", "Um verbo significativo", "Um pronome"], answer: "Um verbo significativo", explanation: "Verbos de ação ou fenômeno da natureza são núcleos de predicados verbais.", skill: "Sintaxe: Predicado" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Qual das frases possui um predicado nominal?", options: ["A Luiza correu", "O dia está lindo", "O gato dormiu", "Choveu ontem"], answer: "O dia está lindo", explanation: "Predicado nominal indica estado ou qualidade e usa verbo de ligação.", skill: "Sintaxe: Predicado" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "No predicado nominal, a palavra mais importante (núcleo) é o:", options: ["Verbo de ligação", "Sujeito", "Predicativo do sujeito", "Objeto direto"], answer: "Predicativo do sujeito", explanation: "O núcleo é o nome (adjetivo ou substantivo) que caracteriza o sujeito.", skill: "Sintaxe: Predicado" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Em 'Fiquei cansado', o verbo 'fiquei' é um verbo de:", options: ["Ação", "Ligação", "Fenômeno", "Intransitivo"], answer: "Ligação", explanation: "Indica uma mudança de estado, ligando o sujeito ao seu estado.", skill: "Sintaxe: Predicado" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "O predicado verbo-nominal possui quantos núcleos?", options: ["Um", "Dois", "Três", "Nenhum"], answer: "Dois", explanation: "Possui um núcleo verbal (ação) e um núcleo nominal (característica).", skill: "Sintaxe: Predicado" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Identifique o predicado na frase: 'A natureza é sábia'.", options: ["é sábia", "A natureza", "sábia", "é"], answer: "é sábia", explanation: "Tudo o que se afirma sobre a natureza.", skill: "Sintaxe: Predicado" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Na frase 'Eles chegaram satisfeitos', o predicado é:", options: ["Nominal", "Verbal", "Verbo-nominal", "Inexistente"], answer: "Verbo-nominal", explanation: "Indica uma ação (chegaram) e um estado (satisfeitos).", skill: "Sintaxe: Predicado" },

  // 8º Ciências - Reprodução (9)
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Qual a principal vantagem da reprodução sexuada?", options: ["Maior variabilidade genética", "Rapidez na reprodução", "Não precisa de parceiro", "Gera clones idênticos"], answer: "Maior variabilidade genética", explanation: "A mistura de genes permite melhor adaptação e evolução da espécie.", skill: "Reprodução" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A reprodução assexuada gera descendentes que são:", options: ["Diferentes dos pais", "Geneticamente idênticos (clones)", "Apenas machos", "Apenas fêmeas"], answer: "Geneticamente idênticos (clones)", explanation: "Não há troca de material genético, apenas divisão ou brotamento.", skill: "Reprodução" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O encontro do espermatozoide com o óvulo chama-se:", options: ["Fecundação", "Ovulação", "Gestação", "Menstruação"], answer: "Fecundação", explanation: "É a união dos gametas masculino e feminino.", skill: "Reprodução" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Animais que se desenvolvem dentro de ovos fora do corpo materno são chamados:", options: ["Ovíparos", "Vivíparos", "Ovovivíparos", "Marsupiais"], answer: "Ovíparos", explanation: "Exemplo: aves e répteis.", skill: "Reprodução" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A reprodução por 'Brotamento' é comum em qual destes organismos?", options: ["Hidras e leveduras", "Cachorros", "Árvores frutíferas", "Pássaros"], answer: "Hidras e leveduras", explanation: "Um novo indivíduo cresce a partir do corpo do genitor.", skill: "Reprodução" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Quais são as células reprodutoras humanas?", options: ["Gametas", "Neurônios", "Hemácias", "Leucócitos"], answer: "Gametas", explanation: "Espermatozoides no homem e ovócitos na mulher.", skill: "Reprodução" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A gestação é o período em que o embrião se desenvolve dentro do:", options: ["Útero", "Ovário", "Estômago", "Coração"], answer: "Útero", explanation: "Órgão do sistema reprodutor feminino preparado para abrigar o feto.", skill: "Reprodução" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A polinização é fundamental para a reprodução de:", options: ["Plantas com flores", "Peixes", "Fungos", "Vírus"], answer: "Plantas com flores", explanation: "O transporte do pólen permite a formação de sementes e frutos.", skill: "Reprodução" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A clonagem natural ocorre em qual destes casos humanos?", options: ["Gêmeos univitelinos", "Irmãos de idades diferentes", "Gêmeos bivitelinos", "Primos de primeiro grau"], answer: "Gêmeos univitelinos", explanation: "Vêm do mesmo óvulo e espermatozoide, partilhando o mesmo DNA.", skill: "Reprodução" },

  // 6º História - Modos de Vida (9)
  { grade: "6º", discipline: "História", type: "multiple", text: "Povos que não têm habitação fixa e se mudam constantemente são chamados de:", options: ["Nômades", "Sedentários", "Agricultores", "Urbanos"], answer: "Nômades", explanation: "No Paleolítico, os humanos mudavam-se conforme a oferta de alimentos.", skill: "Modos de Vida" },
  { grade: "6º", discipline: "História", type: "multiple", text: "O que permitiu ao homem antigo tornar-se 'Sedentário'?", options: ["A descoberta da agricultura", "A invenção do foguete", "O fim das chuvas", "A domesticação do leão"], answer: "A descoberta da agricultura", explanation: "Plantar permitiu fixar residência e criar vilas.", skill: "Modos de Vida" },
  { grade: "6º", discipline: "História", type: "multiple", text: "As primeiras grandes civilizações surgiram próximas a:", options: ["Grandes rios", "Cumes de montanhas", "Cratas vulcânicas", "Desertos de areia"], answer: "Grandes rios", explanation: "Água era essencial para agricultura e transporte (Nilo, Tigre, Eufrates).", skill: "Modos de Vida" },
  { grade: "6º", discipline: "História", type: "multiple", text: "No modo de vida da Pré-história, as moradias eram feitas de:", options: ["Pedras, peles e cavernas", "Cimento e ferro", "Vidro translúcido", "Plástico reciclado"], answer: "Pedras, peles e cavernas", explanation: "Materiais disponíveis na natureza de fácil acesso ou montagem.", skill: "Modos de Vida" },
  { grade: "6º", discipline: "História", type: "multiple", text: "Qual atividade era base da sobrevivência dos povos nômades?", options: ["Caça e coleta", "Indústria", "Comércio digital", "Arquitetura"], answer: "Caça e coleta", explanation: "Dependiam dos recursos naturais móveis.", skill: "Modos de Vida" },
  { grade: "6º", discipline: "História", type: "multiple", text: "O controle de qual elemento natural mudou o modo de vida humano na Pré-história?", options: ["Fogo", "Eletricidade", "Petróleo", "Energia nuclear"], answer: "Fogo", explanation: "Permitiu cozinhar, aquecer e afastar predadores.", skill: "Modos de Vida" },
  { grade: "6º", discipline: "História", type: "multiple", text: "A domesticação de animais proporcionou ao homem:", options: ["Alimento e força de trabalho estáveis", "Apenas companhia", "Perigo constante", "Extinção imediata"], answer: "Alimento e força de trabalho estáveis", explanation: "Carne, leite, lã e ajuda no transporte e lavoura.", skill: "Modos de Vida" },
  { grade: "6º", discipline: "História", type: "multiple", text: "Como chamamos o processo de surgimento das primeiras cidades?", options: ["Urbanização", "Globalização", "Industrialização", "Nacionalismo"], answer: "Urbanização", explanation: "A organização social em aglomerados fixos e complexos.", skill: "Modos de Vida" },
  { grade: "6º", discipline: "História", type: "multiple", text: "A divisão de tarefas entre homens (caça) e mulheres (coleta) é um exemplo de:", options: ["Divisão social do trabalho", "Escola de artes", "Feriado prolongado", "Torneio esportivo"], answer: "Divisão social do trabalho", explanation: "Organização das funções dentro de uma comunidade antiga.", skill: "Modos de Vida" },

  // 7º História - Reforma Protestante (9)
  { grade: "7º", discipline: "História", type: "multiple", text: "Quem foi o monge alemão que iniciou a Reforma Protestante?", options: ["Martinho Lutero", "João Calvino", "Henrique VIII", "Papa Leão X"], answer: "Martinho Lutero", explanation: "Em 1517, publicou as 95 Teses criticando a Igreja Católica.", skill: "Reforma Protestante" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Qual prática da Igreja Católica Lutero mais criticava?", options: ["Venda de Indulgências (perdão)", "Uso de velas", "O latim nas missas", "A caridade"], answer: "Venda de Indulgências (perdão)", explanation: "A Igreja cobrava pelo perdão dos pecados para financiar obras.", skill: "Reforma Protestante" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A doutrina de João Calvino que dizia que Deus já escolheu quem será salvo é a:", options: ["Predestinação", "Justificação pela fé", "Salvação pelas obras", "Livre arbítrio"], answer: "Predestinação", explanation: "Calvinismo pregava que o destino da alma era decidido por Deus.", skill: "Reforma Protestante" },
  { grade: "7º", discipline: "História", type: "multiple", text: "O rei Henrique VIII criou o Anglicanismo na Inglaterra principalmente para:", options: ["Anular seu casamento e aumentar seu poder", "Proteger Lutero", "Expandir a Bíblia", "Criar universidades"], answer: "Anular seu casamento e aumentar seu poder", explanation: "O Ato de Supremacia tornou o Rei chefe da igreja inglesa.", skill: "Reforma Protestante" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A invenção da imprensa por Gutenberg ajudou a Reforma pois:", options: ["Permitiu a impressão e leitura da Bíblia por mais pessoas", "Proibiu a leitura", "Era muito cara", "Só imprimia desenhos"], answer: "Permitiu a impressão e leitura da Bíblia por mais pessoas", explanation: "Aumentou a circulação de ideias e a tradução das escrituras.", skill: "Reforma Protestante" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Como a Igreja Católica reagiu à Reforma Protestante?", options: ["Com a Contrarreforma", "Pedindo desculpas oficiais", "Fechando todas as igrejas", "Acabando com o Papa"], answer: "Com a Contrarreforma", explanation: "Concílio de Trento reafirmou dogmas e criou a Companhia de Jesus.", skill: "Reforma Protestante" },
  { grade: "7º", discipline: "História", type: "multiple", text: "O 'Index Librorum Prohibitorum' era uma lista de:", options: ["Livros proibidos pela Igreja", "Novas músicas protestantes", "Receitas de cozinha", "Membros da corte"], answer: "Livros proibidos pela Igreja", explanation: "Parte da Contrarreforma para evitar a circulação de ideias heréticas.", skill: "Reforma Protestante" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Qual destes princípios é base do Luteranismo?", options: ["A salvação vem apenas pela fé", "O Papa é infalível", "Adoração intensa de santos", "Missas obrigatoriamente em latim"], answer: "A salvação vem apenas pela fé", explanation: "Lutero focava na relação direta do fiel com Deus através das escrituras.", skill: "Reforma Protestante" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Os Jesuítas, criados na Contrarreforma, tinham como missão:", options: ["Expandir a fé católica e o ensino", "Destruir a Bíblia", "Fazer guerras na Europa", "Apenas rezar em silêncio"], answer: "Expandir a fé católica e o ensino", explanation: "A Companhia de Jesus foi fundamental na catequisação das Américas.", skill: "Reforma Protestante" },

  // 7º História - Estados Modernos (9)
  { grade: "7º", discipline: "História", type: "multiple", text: "O sistema político onde o rei detém todo o poder é o:", options: ["Absolutismo", "Democracia", "Parlamentarismo", "Anarquia"], answer: "Absolutismo", explanation: "O monarca tinha poder absoluto, muitas vezes visto como de origem divina.", skill: "Estados Modernos" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A frase 'O Estado sou eu' é atribuída ao rei absolutista:", options: ["Luís XIV da França", "Henrique VIII", "Dom Pedro I", "Carlos Magno"], answer: "Luís XIV da França", explanation: "O 'Rei Sol' simbolizava o auge do poder centralizado.", skill: "Estados Modernos" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Qual classe social apoiou os reis na formação dos Estados Modernos?", options: ["Burguesia", "Camponeses", "Clero", "Operários"], answer: "Burguesia", explanation: "Desejavam leis unificadas, mesma moeda e mais segurança para o comércio.", skill: "Estados Modernos" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A teoria do 'Direito Divino dos Reis' dizia que o poder do monarca vinha de:", options: ["Deus", "Votação popular", "Sorteio", "Guerra santa"], answer: "Deus", explanation: "Rebelar-se contra o rei seria rebelar-se contra o próprio Deus.", skill: "Estados Modernos" },
  { grade: "7º", discipline: "História", type: "multiple", text: "O Mercantilismo era a prática econômica dos Estados Modernos que buscava:", options: ["Acumular metais preciosos (ouro/prata)", "Distribuir riqueza para todos", "Não ter comércio", "Vender apenas para si mesmo"], answer: "Acumular metais preciosos (ouro/prata)", explanation: "Riqueza de uma nação era medida pelo estoque de metais (Metalismo).", skill: "Estados Modernos" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Uma característica importante da formação das nações modernas foi a criação de:", options: ["Exércitos permanentes e moedas nacionais", "Várias moedas em cada vila", "Nenhuma lei oficial", "Apenas exércitos mercenários"], answer: "Exércitos permanentes e moedas nacionais", explanation: "Fortaleceu a autoridade do Rei sobre o território.", skill: "Estados Modernos" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Quem escreveu 'O Príncipe', obra que analisa a manutenção do poder político?", options: ["Maquiavel", "Shakespeare", "Dante Alighieri", "Leonardo da Vinci"], answer: "Maquiavel", explanation: "Obra clássica sobre ciência política e realismo governamental.", skill: "Estados Modernos" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A 'Balança Comercial Favorável' consistia em:", options: ["Exportar mais do que importar", "Importar mais que exportar", "Proibir o comércio", "Ter o mesmo peso de mercadorias"], answer: "Exportar mais do que importar", explanation: "Garante a entrada de mais riqueza na nação.", skill: "Estados Modernos" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Qual foi um dos primeiros países a centralizar o poder no Estado Moderno?", options: ["Portugal", "Alemanha", "Itália", "Grécia"], answer: "Portugal", explanation: "Devido à precoce expulsão dos mouros e unificação dinástica.", skill: "Estados Modernos" },

  // 9º História - Mundo Bipolar (9)
  { grade: "9º", discipline: "História", type: "multiple", text: "O período de tensão entre EUA e URSS após a 2ª Guerra Mundial chama-se:", options: ["Guerra Fria", "Guerra Civil", "Guerra Bipolar", "Guerra Total"], answer: "Guerra Fria", explanation: "Pois nunca houve um combate direto e armado entre as duas potências.", skill: "Mundo Bipolar" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Quais eram os dois sistemas econômicos em disputa na Guerra Fria?", options: ["Capitalismo e Socialismo", "Monarquia e República", "Barter e Moeda", "Escravismo e Feudalismo"], answer: "Capitalismo e Socialismo", explanation: "EUA (Capitalista) vs URSS (Socialista/Comunista).", skill: "Mundo Bipolar" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O 'Muro de Berlim' foi construído para:", options: ["Dividir a Alemanha em duas zonas de influência", "Proteger contra invasão alienígena", "Fazer um estádio mundial", "Cercar um parque"], answer: "Dividir a Alemanha em duas zonas de influência", explanation: "Símbolo máximo da divisão do mundo (Cortina de Ferro).", skill: "Mundo Bipolar" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A corrida espacial teve como marco histórico os EUA levando o homem à:", options: ["Lua", "Marte", "Vênus", "Sol"], answer: "Lua", explanation: "Em 1969, Neil Armstrong foi o primeiro humano a pisar na Lua.", skill: "Mundo Bipolar" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A aliança militar liderada pelos EUA durante a Guerra Fria era a:", options: ["OTAN", "Pacto de Varsóvia", "ONU", "MERCOSUL"], answer: "OTAN", explanation: "Organização do Tratado do Atlântico Norte.", skill: "Mundo Bipolar" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O Pacto de Varsóvia era a aliança militar liderada pela:", options: ["União Soviética (URSS)", "China", "Inglaterra", "França"], answer: "União Soviética (URSS)", explanation: "Resposta comunista à criação da OTAN.", skill: "Mundo Bipolar" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A crise que quase levou o mundo a uma guerra nuclear em 1962 foi a:", options: ["Crise dos Mísseis em Cuba", "Queda do Muro", "Guerra do Vietnã", "Guerra da Coreia"], answer: "Crise dos Mísseis em Cuba", explanation: "EUA descobriu mísseis soviéticos apontados em Cuba.", skill: "Mundo Bipolar" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O fim simbólico da Guerra Fria foi marcado pela:", options: ["Queda do Muro de Berlim em 1989", "Invenção da Internet", "Chegada à Lua", "Morte de Hitler"], answer: "Queda do Muro de Berlim em 1989", explanation: "Início da desintegração do bloco socialista na Europa.", skill: "Mundo Bipolar" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O Plano Marshall foi uma iniciativa dos EUA para:", options: ["Reconstruir economicamente a Europa Ocidental", "Invadir a China", "Proibir o cinema russo", "Comprar o Alasca"], answer: "Reconstruir economicamente a Europa Ocidental", explanation: "Evitava que países pobres por causa da guerra aderissem ao comunismo.", skill: "Mundo Bipolar" },

  // 7º Geografia - Território Brasileiro (9)
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "O Brasil é dividido administrativamente em quantas Regiões Oficiais pelo IBGE?", options: ["5", "4", "6", "3"], answer: "5", explanation: "Norte, Nordeste, Centro-Oeste, Sudeste e Sul.", skill: "Território Brasileiro" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "Qual a capital federal do Brasil, localizada no Centro-Oeste?", options: ["Brasília", "São Paulo", "Rio de Janeiro", "Salvador"], answer: "Brasília", explanation: "Inaugurada em 1960 para integrar o interior do país.", skill: "Território Brasileiro" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "O Brasil é banhado por qual oceano?", options: ["Atlântico", "Pacífico", "Índico", "Glacial Ártico"], answer: "Atlântico", explanation: "Toda a nossa vasta costa litorânea dá para o Oceano Atlântico.", skill: "Território Brasileiro" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "Qual destes estados pertence à Região Sul?", options: ["Paraná", "Bahia", "Pará", "Goiás"], answer: "Paraná", explanation: "PR, SC e RS formam a região Sul.", skill: "Território Brasileiro" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "O Brasil é considerado o maior país em extensão da:", options: ["América do Sul", "Europa", "América do Norte", "África"], answer: "América do Sul", explanation: "Ocupa quase metade da superfície sul-americana.", skill: "Território Brasileiro" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "Qual país da América do Sul NÃO faz fronteira com o Brasil?", options: ["Chile", "Argentina", "Uruguai", "Colômbia"], answer: "Chile", explanation: "Apenas Chile e Equador não fazem fronteira terrestre com o Brasil.", skill: "Território Brasileiro" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "As 'Terras Indígenas' e 'Quilombolas' no território brasileiro são áreas de:", options: ["Proteção cultural e direitos territoriais", "Livre construção de indústrias", "Mineração obrigatória", "Uso apenas militar"], answer: "Proteção cultural e direitos territoriais", explanation: "Áreas reservadas para preservação do modo de vida desses povos.", skill: "Território Brasileiro" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "A maior parte do território brasileiro está situada em qual zona climática?", options: ["Intertropical", "Polar", "Temperada do Norte", "Desértica"], answer: "Intertropical", explanation: "Entre o Equador e os trópicos, garantindo calor na maior parte do ano.", skill: "Território Brasileiro" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "Como chamamos as linhas imaginárias verticais que cruzam a Terra?", options: ["Meridianos", "Paralelos", "Equadores", "Eixos"], answer: "Meridianos", explanation: "Cruciais para definir fusos horários e localização.", skill: "Território Brasileiro" },

  // 8º Geografia - Coordenadas Geográficas (9)
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O conjunto de linhas imaginárias (paralelos e meridianos) serve para:", options: ["Localizar qualquer ponto na Terra", "Medir a temperatura", "Ver o clima", "Dividir as correntes marinas"], answer: "Localizar qualquer ponto na Terra", explanation: "Formam uma rede de referência geográfica.", skill: "Coordenadas Geográficas" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A linha imaginária que divide a Terra em Hemisfério Norte e Sul é:", options: ["Equador", "Meridiano de Greenwich", "Trópico de Câncer", "Linha Internacional da Data"], answer: "Equador", explanation: "É o paralelo de latitude 0°.", skill: "Coordenadas Geográficas" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O Meridiano de Greenwich divide a Terra em:", options: ["Hemisfério Leste (Oriental) e Oeste (Ocidental)", "Norte e Sul", "Diagonal", "Apenas por países"], answer: "Hemisfério Leste (Oriental) e Oeste (Ocidental)", explanation: "É a linha de longitude 0°.", skill: "Coordenadas Geográficas" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A 'Latitude' é a distância em graus medida a partir de qual linha?", options: ["Equador", "Greenwich", "Trópico", "Polo Norte"], answer: "Equador", explanation: "Latitude varia de 0° a 90° Norte ou Sul.", skill: "Coordenadas Geográficas" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A 'Longitude' é a distância em graus medida a partir de qual linha?", options: ["Meridiano de Greenwich", "Equador", "Círculo Polar", "Fronteira Seca"], answer: "Meridiano de Greenwich", explanation: "Longitude varia de 0° a 180° Leste ou Oeste.", skill: "Coordenadas Geográficas" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Um ponto localizado a 0° de Latitude e 0° de Longitude está no cruzamento do:", options: ["Equador com Greenwich", "Polo Sul com Polo Norte", "Brasil com Japão", "Sol com a Lua"], answer: "Equador com Greenwich", explanation: "Ponto central do sistema de coordenadas mundial.", skill: "Coordenadas Geográficas" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "As coordenadas são dadas em quais unidades?", options: ["Graus, minutos e segundos", "Metros e quilômetros", "Litros e gramas", "Horas e minutos apenas"], answer: "Graus, minutos e segundos", explanation: "Unidades angulares para precisão no mapa.", skill: "Coordenadas Geográficas" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Ao nos movermos de Greenwich para o Leste, as longitudes são:", options: ["Positivas/Leste", "Negativas/Oeste", "Sempre zero", "Inexistentes"], answer: "Positivas/Leste", explanation: "Até 180° no sentido horário.", skill: "Coordenadas Geográficas" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O GPS utiliza qual sistema para nos guiar?", options: ["Coordenadas Geográficas e Satélites", "Apenas bússolas magnéticas", "Sinais de fumaça", "Mapas de papel apenas"], answer: "Coordenadas Geográficas e Satélites", explanation: "Satélites calculam latitude, longitude e altitude em tempo real.", skill: "Coordenadas Geográficas" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 12 com ${batch.length} questões adicionado.`);
