import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 5400;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 23: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 9º História - Guerras Mundiais (9)
  { grade: "9º", discipline: "História", type: "multiple", text: "Qual foi o estopim (fato gerador) para o início da Primeira Guerra Mundial?", options: ["O assassinato do arquiduque Francisco Ferdinando", "A invasão da Polônia pela Alemanha", "O ataque a Pearl Harbor", "A queda da Bolsa de Valores"], answer: "O assassinato do arquiduque Francisco Ferdinando", explanation: "O crime ocorreu em Sarajevo e ativou um sistema de alianças militares.", skill: "Guerras Mundiais" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A Primeira Guerra Mundial (1914-1918) ficou marcada por qual tipo de estratégia militar em terra?", options: ["Guerra de Trincheiras", "Guerra de Movimento rápido (Blitzkrieg)", "Guerra de Guerrilha nas selvas", "Combates apenas aéreos"], answer: "Guerra de Trincheiras", explanation: "Os soldados ficavam meses protegidos em buracos cavados no solo por centenas de quilômetros.", skill: "Guerras Mundiais" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Qual país saiu da Primeira Guerra Mundial em 1917 devido a uma revolução interna?", options: ["Rússia", "EUA", "França", "Alemanha"], answer: "Rússia", explanation: "A Revolução Russa de 1917 levou o país a assinar o tratado de paz para resolver questões internas.", skill: "Guerras Mundiais" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O fato que iniciou oficialmente a Segunda Guerra Mundial (1939) foi a:", options: ["Invasão da Polônia pela Alemanha", "Ataque japonês à China", "Fundação da ONU", "Queda do Muro de Berlim"], answer: "Invasão da Polônia pela Alemanha", explanation: "Liderada por Hitler, a ação fez a França e Inglaterra declararem guerra à Alemanha.", skill: "Guerras Mundiais" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Quais eram as duas alianças principais que se enfrentaram na Segunda Guerra Mundial?", options: ["Eixo (Alemanha, Itália, Japão) e Aliados (França, Inglaterra, URSS, EUA)", "Tríplice Aliança e Tríplice Entente", "OTAN e Pacto de Varsóvia", "Socialistas e Capitalistas"], answer: "Eixo (Alemanha, Itália, Japão) e Aliados (França, Inglaterra, URSS, EUA)", explanation: "O Eixo representava os regimes totalitários e expansionistas.", skill: "Guerras Mundiais" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O 'Dia D' marcou qual momento decisivo da Segunda Guerra Mundial?", options: ["O desembarque das tropas aliadas na Normandia (França)", "O dia em que a Alemanha se rendeu", "O lançamento da primeira bomba atômica", "O ataque a Pearl Harbor"], answer: "O desembarque das tropas aliadas na Normandia (França)", explanation: "Foi o início da retomada da Europa Ocidental ocupada pelos nazistas.", skill: "Guerras Mundiais" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O massacre sistemático de milhões de judeus e outros grupos pelos nazistas é conhecido como:", options: ["Holocausto", "Gulag", "Inquisição", "Pogrom"], answer: "Holocausto", explanation: "Um dos crimes mais terríveis contra a humanidade na história moderna.", skill: "Guerras Mundiais" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Qual evento marcou o fim da Segunda Guerra Mundial no Pacífico?", options: ["Lançamento de bombas atômicas em Hiroshima e Nagasaki", "A morte de Adolf Hitler", "A libertação de Paris", "A Batalha de Stalingrado"], answer: "Lançamento de bombas atômicas em Hiroshima e Nagasaki", explanation: "Os EUA usaram a nova arma para forçar a rendição incondicional do Japão.", skill: "Guerras Mundiais" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Qual organização internacional foi criada após a 2ª Guerra para manter a paz mundial?", options: ["ONU (Organização das Nações Unidas)", "Liga das Nações", "União Europeia", "Mercosul"], answer: "ONU (Organização das Nações Unidas)", explanation: "Substituiu a extinta Liga das Nações com o objetivo de evitar novos conflitos globais.", skill: "Guerras Mundiais" },

  // 9º Geografia - Urbanização (9)
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O que caracteriza o processo de 'Urbanização'?", options: ["O crescimento da população das cidades em ritmo maior que a do campo", "O aumento das plantações de soja", "A saída das pessoas das cidades para morar no sítio", "O plantio de árvores em parques nacionais"], answer: "O crescimento da população das cidades em ritmo maior que a do campo", explanation: "Está ligado ao êxodo rural e à industrialização.", skill: "Urbanização" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O termo 'Metropolização' refere-se ao:", options: ["Crescimento e integração de cidades em torno de um grande centro urbano", "Fim das grandes cidades", "Criação de vilas de pescadores", "Uso de metrôs apenas"], answer: "Crescimento e integração de cidades em torno de um grande centro urbano", explanation: "A metrópole influencia econômica e politicamente as cidades vizinhas.", skill: "Urbanização" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O fenômeno de união física de duas ou mais cidades que cresceram até se juntarem é a:", options: ["Conurbação", "Favelação", "Verticalização", "Gentrificação"], answer: "Conurbação", explanation: "Ocorre quando não se percebe mais o limite rural entre cidades vizinhas.", skill: "Urbanização" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O que é uma 'Megacidade' segundo a ONU?", options: ["Uma cidade com mais de 10 milhões de habitantes", "Uma cidade que tem o prédio mais alto do mundo", "Uma cidade onde todos falam a mesma língua", "Qualquer capital de país"], answer: "Uma cidade com mais de 10 milhões de habitantes", explanation: "Ex: São Paulo, Tóquio, Nova York, Pequim.", skill: "Urbanização" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Cidades Globais são aquelas que:", options: ["Exercem influência econômica e financeira em escala mundial", "Têm o maior tamanho territorial do mundo", "Não possuem indústrias", "São cidades flutuantes no mar"], answer: "Exercem influência econômica e financeira em escala mundial", explanation: "Ex: Londres, Nova York, São Paulo, Tóquio.", skill: "Urbanização" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A 'Macrocefalia Urbana' é um problema comum em países subdesenvolvidos que consiste na:", options: ["Concentração excessiva de população e serviços em uma única grande cidade", "Falta de pessoas nas capitais", "Aumento da inteligência dos moradores urbanos", "Nenhuma das anteriores"], answer: "Concentração excessiva de população e serviços em uma única grande cidade", explanation: "Isso gera caos urbano, falta de infraestrutura e favelização.", skill: "Urbanização" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O processo de valorização de uma área urbana central que expulsa os moradores pobres é a:", options: ["Gentrificação", "Ruralização", "Urbanismo de rede", "Especulação imobiliária apenas"], answer: "Gentrificação", explanation: "O custo de vida aumenta e a classe média/alta substitui as classes populares e suas tradições.", skill: "Urbanização" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Um dos maiores problemas ambientais das grandes metrópoles, causado pelo excesso de concreto, é a:", options: ["Ilha de Calor", "Nevasca urbana", "Derretimento de icebergs", "Furações constantes"], answer: "Ilha de Calor", explanation: "As temperaturas no centro são bem maiores que nas áreas periféricas e rurais.", skill: "Urbanização" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "As 'Cidades Colares' em torno de uma metrópole formam o(a):", options: ["Região Metropolitana", "Estado Independente", "Litoral Urbano", "Megalópole Mundial"], answer: "Região Metropolitana", explanation: "Compartilham serviços públicos como transporte e saneamento.", skill: "Urbanização" },

  // 8º Arte - Século XX (9)
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O movimento de vanguarda que valorizava a velocidade, as máquinas e o futuro era o:", options: ["Futurismo", "Impressionismo", "Realismo", "Rococó"], answer: "Futurismo", explanation: "Surgiu na Itália e exaltava a modernidade tecnológica.", skill: "Século XX" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual o principal conceito do movimento 'Dadaísmo'?", options: ["A anti-arte e o questionamento do valor da arte tradicional", "A perfeição da anatomia humana", "A pintura exata da natureza ao ar livre", "A construção de estátuas de bronze gigantes"], answer: "A anti-arte e o questionamento do valor da arte tradicional", explanation: "Surgiu como protesto contra a 1ª Guerra usando o acaso e o absurdo.", skill: "Século XX" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Marcel Duchamp ficou famoso por seus 'Ready-mades'. O que são eles?", options: ["Objetos prontos retirados do cotidiano e expostos como arte", "Pinturas feitas por robôs", "Esculturas de barro queimado", "Fotos coloridas à mão"], answer: "Objetos prontos retirados do cotidiano e expostos como arte", explanation: "Ex: A Fonte (o urinol) e Roda de Bicicleta. O conceito importa mais que o objeto.", skill: "Século XX" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O 'Surrealismo' buscava representar em suas obras:", options: ["O mundo dos sonhos, do inconsciente e o irracional", "A vida real dos operários nas fábricas", "Cenas de batalhas históricas reais", "Desenhos técnicos de engenharia"], answer: "O mundo dos sonhos, do inconsciente e o irracional", explanation: "Influenciado pelas teorias de Freud, teve Salvador Dalí como destaque.", skill: "Século XX" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A escola alemã que uniu arte, design e indústria, buscando funcionalidade, foi a:", options: ["Bauhaus", "Modernismo Brasileiro", "Pop Art", "Expressionismo"], answer: "Bauhaus", explanation: "Defendia a simplicidade e que a forma deve seguir a função.", skill: "Século XX" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual movimento artístico utilizava imagens da cultura de massa e propaganda (ex: latas de sopa)?", options: ["Pop Art", "Abstracionismo", "Barroco", "Futurismo"], answer: "Pop Art", explanation: "Andy Warhol foi o maior ícone, ironizando o consumismo.", skill: "Século XX" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A 'Semana de Arte Moderna' de 1922 foi o marco inicial do:", options: ["Modernismo no Brasil", "Dadaísmo europeu", "Cinema falado", "Balé clássico"], answer: "Modernismo no Brasil", explanation: "Ocorreu em São Paulo e chocou o público conservador da época.", skill: "Século XX" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "No 'Abstracionismo Geométrico', as obras são compostas basicamente por:", options: ["Linhas, planos e cores primárias (como Mondrian)", "Rostos humanos distorcidos", "Imagens de sonhos profundos", "Fotografias coladas"], answer: "Linhas, planos e cores primárias (como Mondrian)", explanation: "Buscava a ordem matemática e a pureza visual.", skill: "Século XX" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O 'Expressionismo' tem como foco principal:", options: ["Expressar a angústia e os sentimentos internos do artista", "Pintar exatamente o que os olhos veem", "Criar ilusão de ótica", "Desenhar apenas objetos geométricos"], answer: "Expressar a angústia e os sentimentos internos do artista", explanation: "Usa cores fortes e formas distorcidas para emocionar.", skill: "Século XX" },

  // 9º Arte - Cinetismo (9)
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O que define a 'Arte Cinética' (ou Cinetismo)?", options: ["A inclusão do movimento (real ou ilusório) na obra de arte", "A pintura apenas de cenas de cinema", "O uso exclusivo de cores azuis", "A escultura de figuras em miniatura"], answer: "A inclusão do movimento (real ou ilusório) na obra de arte", explanation: "A obra deixa de ser estática e interage com o espectador ou o vento.", skill: "Cinetismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Quem é o artista norte-americano famoso por inventar os 'Móbiles'?", options: ["Alexander Calder", "Pablo Picasso", "Andy Warhol", "Vik Muniz"], answer: "Alexander Calder", explanation: "Suas esculturas suspensas moviam-se com as correntes de ar.", skill: "Cinetismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Diferente dos móbiles, os 'Estábiles' de Calder são obras que:", options: ["Ficam fixas no chão, embora tenham formas dinâmicas", "Mudam de cor sozinhas", "Flutuam na água", "São feitas de papel apenas"], answer: "Ficam fixas no chão, embora tenham formas dinâmicas", explanation: "Esculturas monumentais de metal que não se mexem realmente.", skill: "Cinetismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O Cinetismo que utiliza efeitos visuais para criar a ilusão de movimento é a:", options: ["Op Art (Optical Art)", "Pop Art", "Land Art", "Body Art"], answer: "Op Art (Optical Art)", explanation: "O olho do espectador cria o movimento ao olhar para padrões geométricos.", skill: "Cinetismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Qual destes materiais foi muito explorado por artistas cinéticos para criar reflexos e movimento?", options: ["Metal, acrílico e motores elétricos", "Barro e argila apenas", "Lápis de cor sobre papel", "Tecidos de lã"], answer: "Metal, acrílico e motores elétricos", explanation: "A tecnologia ajudou a criar obras que mudam com a luz e o toque.", skill: "Cinetismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O artista brasileiro Abraham Palatnik foi pioneiro em qual tipo de arte tecnológica?", options: ["Aparelhos Cinecromáticos (luz e movimento)", "Grafites de rua gigantes", "Esculturas de pedra sabão", "Vídeo games educativos"], answer: "Aparelhos Cinecromáticos (luz e movimento)", explanation: "Criou caixas que mudavam de cor e forma através de mecanismos internos.", skill: "Cinetismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Na arte cinética, a participação do espectador é importante porque:", options: ["Muitas obras só 'acontecem' quando o espectador se move ou toca nelas", "O espectador precisa comprar o quadro", "O espectador tem que tirar uma foto", "O espectador decide o preço"], answer: "Muitas obras só 'acontecem' quando o espectador se move ou toca nelas", explanation: "A experiência estética é dinâmica e temporal.", skill: "Cinetismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Victor Vasarely é considerado o pai de qual vertente cinética?", options: ["Op Art", "Surrealismo", "Action Painting", "Cubismo"], answer: "Op Art", explanation: "Suas pinturas parecem vibrar e saltar da tela.", skill: "Cinetismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A arte cinética rompe com a ideia tradicional de que a escultura deve ser sempre:", options: ["Fixa e imutável", "Feita de ouro", "Representar um herói famoso", "Pequena e discreta"], answer: "Fixa e imutável", explanation: "Ela introduz o tempo e a mutabilidade na arte tridimensional.", skill: "Cinetismo" },

  // 8º Matemática - Aritmética (9)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual é o valor de √144 (Raiz quadrada de 144)?", options: ["12", "14", "10", "24"], answer: "12", explanation: "Porque 12 * 12 = 144.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Como se calcula o valor de 2 elevado à quinta potência (2⁵)?", options: ["32", "10", "16", "25"], answer: "32", explanation: "2 * 2 * 2 * 2 * 2 = 32.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que é um número 'Iracional'?", options: ["Número com infinitas casas decimais não periódicas (ex: Pi)", "Número que pode ser escrito como fração", "Número que é sempre positivo", "Número que termina sempre em zero"], answer: "Número com infinitas casas decimais não periódicas (ex: Pi)", explanation: "Não pode ser representado como a razão entre dois inteiros.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de (-5) * (-4) seguindo a regra de sinais?", options: ["+20", "-20", "-9", "+9"], answer: "+20", explanation: "Menos com menos na multiplicação resulta em mais.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Quanto vale 15% de 200?", options: ["30", "15", "20", "45"], answer: "30", explanation: "0,15 * 200 = 30.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que significa 'Inverso de um número' (ex: o inverso de 3)?", options: ["1/3", "-3", "30", "0,3"], answer: "1/3", explanation: "Ao multiplicar o número pelo seu inverso, o resultado é sempre 1.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Na expressão 3 + 4 * 2, qual operação deve ser feita primeiro?", options: ["Multiplicação (4 * 2)", "Adição (3 + 4)", "Não importa a ordem", "Ambas ao mesmo tempo"], answer: "Multiplicação (4 * 2)", explanation: "Na hierarquia matemática, multiplicação e divisão vêm antes de adição e subtração.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O Mínimo Múltiplo Comum (MMC) entre 4 e 6 é:", options: ["12", "24", "2", "10"], answer: "12", explanation: "Múltiplos de 4: 4, 8, 12... Múltiplos de 6: 6, 12... 12 é o menor comum.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Como se escreve o número 0,0005 em Notação Científica?", options: ["5 * 10⁻⁴", "5 * 10⁴", "0,5 * 10³", "50 * 10⁻⁵"], answer: "5 * 10⁻⁴", explanation: "Movemos a vírgula 4 casas para a direita.", skill: "Aritmética" },

  // 6º Matemática - Subtração (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Na operação 150 - 45 = 105, o número 150 é chamado de:", options: ["Minuendo", "Subtraendo", "Resto ou Diferença", "Parcela"], answer: "Minuendo", explanation: "É a quantidade da qual vamos retirar outra parte.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Em uma conta de menos, o resultado final chama-se:", options: ["Resto ou Diferença", "Soma", "Produto", "Quociente"], answer: "Resto ou Diferença", explanation: "É o que sobra após a retirada.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de 1.000 - 357?", options: ["643", "743", "653", "647"], answer: "643", explanation: "Fazendo a conta com 'pedir emprestado' nas ordens superiores.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "A subtração é a operação inversa da:", options: ["Adição", "Multiplicação", "Divisão", "Potenciação"], answer: "Adição", explanation: "Se 10 - 4 = 6, então 6 + 4 = 10.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Se eu tinha R$ 50,00 e gastei R$ 12,50, quanto me sobrou?", options: ["R$ 37,50", "R$ 38,50", "R$ 40,00", "R$ 32,50"], answer: "R$ 37,50", explanation: "50 - 12,50 = 37,50.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Ao subtrair o mesmo número de si mesmo (ex: 8 - 8), o resultado é sempre:", options: ["Zero", "O próprio número", "Um", "O dobro"], answer: "Zero", explanation: "Retirar tudo o que existe deixa o conjunto vazio.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Em uma subtração, se aumentarmos o minuendo em 10, o resto:", options: ["Aumenta em 10", "Diminui em 10", "Não se altera", "Fica igual a zero"], answer: "Aumenta em 10", explanation: "O resto é diretamente proporcional ao minuendo.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual é a diferença entre o sucessor de 100 e o antecessor de 50?", options: ["52", "50", "51", "49"], answer: "52", explanation: "101 (sucessor de 100) - 49 (antecessor de 50) = 52.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Como verificamos se uma conta de subtração está correta?", options: ["Somando o resto com o subtraendo para ver se dá o minuendo", "Multiplicando os números", "Dividindo o total por dez", "Não tem como verificar"], answer: "Somando o resto com o subtraendo para ver se dá o minuendo", explanation: "É a prova real da subtração.", skill: "Subtração" },

  // 7º Matemática - Números (9)
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O conjunto dos números INTEIROS (Z) é formado por:", options: ["Números positivos, negativos e o zero", "Apenas números positivos", "Apenas frações", "Apenas números de 0 a 9"], answer: "Números positivos, negativos e o zero", explanation: "Expandem os naturais para representar perdas, dívidas ou profundidade.", skill: "Números" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor absoluto (módulo) do número -15?", options: ["15", "-15", "0", "1/15"], answer: "15", explanation: "O módulo é a distância do número até o zero, sendo sempre positivo.", skill: "Números" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Números 'Opostos' ou 'Simétricos' são aqueles que:", options: ["Estão à mesma distância do zero, mas em lados opostos", "Um é o dobro do outro", "A soma deles é sempre 10", "São escritos de trás para frente"], answer: "Estão à mesma distância do zero, mas em lados opostos", explanation: "Ex: +4 e -4.", skill: "Números" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Na reta numérica, quanto mais à ESQUERDA um número negativo está do zero, ele é:", options: ["Menor", "Maior", "Igual no valor", "Inexistente"], answer: "Menor", explanation: "Ex: -10 é menor que -2.", skill: "Números" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de (-7) + (+3)?", options: ["-4", "+4", "-10", "+10"], answer: "-4", explanation: "Devo 7 e pago 3, continuo devendo 4.", skill: "Números" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "A multiplicação de dois números NEGATIVOS resulta em um número:", options: ["Positivo", "Negativo", "Zero sempre", "Imaginário"], answer: "Positivo", explanation: "Regra de sinais: (-) * (-) = (+).", skill: "Números" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O conjunto dos números Racionais (Q) engloba todos os números que:", options: ["Podem ser representados como fração de dois inteiros", "São apenas dízimas periódicas", "São todos maiores que mil", "Não podem ser escritos"], answer: "Podem ser representados como fração de dois inteiros", explanation: "Inclui inteiros, decimais exatos e dízimas.", skill: "Números" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Quanto vale 2,5 + 1/4 (em decimal)?", options: ["2,75", "2,60", "3,00", "2,25"], answer: "2,75", explanation: "1/4 = 0,25. 2,5 + 0,25 = 2,75.", skill: "Números" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "A dízima periódica 0,333... é igual a qual fração?", options: ["1/3", "3/10", "3/100", "3/3"], answer: "1/3", explanation: "Fração geratriz simples.", skill: "Números" },

  // 9º Ens. Religioso - Mestiçagem (9)
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O que significa 'Mestiçagem Cultural e Religiosa' no Brasil?", options: ["A mistura de crenças, ritos e valores de diferentes origens (Indígenas, Africanas, Europeias)", "A proibição de todas as religiões estrangeiras", "Um único pensamento vindo de Portugal apenas", "A separação total das pessoas por cor"], answer: "A mistura de crenças, ritos e valores de diferentes origens (Indígenas, Africanas, Europeias)", explanation: "É a base da diversidade e riqueza cultural brasileira.", skill: "Mestiçagem" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Sincretismo Religioso' ocorre quando:", options: ["Elementos de duas ou mais religiões se fundem ou convivem em uma nova prática", "As pessoas param de ter religião", "Uma religião destrói a outra completamente", "A ciência substitui a fé"], answer: "Elementos de duas ou mais religiões se fundem ou convivem em uma nova prática", explanation: "Comum no Brasil entre santos católicos e orixás africanos.", skill: "Mestiçagem" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A Umbanda é considerada uma religião 'genuinamente brasileira' porque:", options: ["Surgiu no Brasil misturando espiritismo, tradições africanas e catolicismo", "Foi criada pelos governantes do Brasil", "Apenas brasileiros podem frequentar", "Não tem nenhuma influência externa"], answer: "Surgiu no Brasil misturando espiritismo, tradições africanas e catolicismo", explanation: "É um exemplo clássico de mestiçagem espiritual positiva.", skill: "Mestiçagem" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "As 'Fatas de Largo' e procissões no Brasil são exemplos de:", options: ["Religiosidade popular que mistura fé oficial com festas de influência africana", "Eventos puramente europeus sem mudanças", "Apenas eventos comerciais modernos", "Proibições religiosas antigas"], answer: "Religiosidade popular que mistura fé oficial com festas de influência africana", explanation: "Ex: Lavagem do Bonfim em Salvador.", skill: "Mestiçagem" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A culinária religiosa brasileira (como o acarajé ou o vatapá) demonstra a:", options: ["Presença de saberes africanos integrados à cultura cotidiana e espiritual", "Falta de opção alimentar no passado", "Importação de comida da Ásia apenas", "Nenhuma ligação com a religião"], answer: "Presença de saberes africanos integrados à cultura cotidiana e espiritual", explanation: "Muitos pratos típicos têm origem em oferendas rituais.", skill: "Mestiçagem" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Reconhecer a mestiçagem religiosa é importante para combater o:", options: ["Preconceito e a intolerância religiosa", "Desenvolvimento tecnológico", "Conhecimento de outras línguas", "Crescimento das cidades"], answer: "Preconceito e a intolerância religiosa", explanation: "Valorizar todas as raízes gera respeito mútuo.", skill: "Mestiçagem" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A influência indígena na mestiçagem brasileira aparece principalmente na:", options: ["Conexão espiritual com a natureza e ervas medicinais", "Construção de templos de pedra gigantes", "Adoração de ídolos de ouro como os maias", "Uso de línguas orientais"], answer: "Conexão espiritual com a natureza e ervas medicinais", explanation: "O saber vegetal e o respeito pajelança são bases profundas.", skill: "Mestiçagem" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O termo 'Mestiço' em sentido cultural deve ser visto como:", options: ["Um símbolo de riqueza e união de saberes diversos", "Algo que deve ser evitado", "Uma falta de identidade pura", "Uma característica apenas biológica sem valor social"], answer: "Um símbolo de riqueza e união de saberes diversos", explanation: "É a síntese que torna o Brasil único no mundo.", skill: "Mestiçagem" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O diálogo inter-religioso no Brasil é facilitado pela:", options: ["Convivência histórica de diferentes fés no mesmo território", "Obrigatoriedade de ser católico", "Extinção das fés minoritárias", "Apenas pela internet"], answer: "Convivência histórica de diferentes fés no mesmo território", explanation: "A mestiçagem gerou uma proximidade cultural entre os fiéis.", skill: "Mestiçagem" },

  // 6º Ens. Religioso - Narrativas (9)
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O que são 'Narrativas Religiosas'?", options: ["Relatos sagrados que transmitem ensinamentos, mitos e a história de uma fé", "Apenas notícias de jornal sobre as igrejas", "Contos de terror inventados para assustar", "Manuais técnicos de construção de templos"], answer: "Relatos sagrados que transmitem ensinamentos, mitos e a história de uma fé", explanation: "Elas dão sentido à vida e explicam o sagrado para os fiéis.", skill: "Narrativas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "As parábolas contadas por Jesus tinham qual função principal?", options: ["Ensinar valores morais através de exemplos simples da vida", "Fazer as pessoas dormirem", "Enganar os inimigos", "Apenas divertir as crianças"], answer: "Ensinar valores morais através de examples simples da vida", explanation: "Ex: Parábola do Bom Samaritano, do Filho Pródigo.", skill: "Narrativas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Muitas narrativas religiosas explicam a 'Origem do Mundo'. Como elas são chamadas?", options: ["Mitos de Criação (Cosmogonias)", "Noticias do passado", "Contos de fadas modernos", "Relatórios científicos"], answer: "Mitos de Criação (Cosmogonias)", explanation: "Ex: O Gênesis na Bíblia ou o surgimento do mundo pela dança de Shiva.", skill: "Narrativas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Na tradição oral, quem é responsável por manter vivas as narrativas religiosas?", options: ["Os anciãos, mestres e líderes espirituais (Griots, Pajés, Sábios)", "Apenas as crianças pequenas", "As máquinas de gravação automática", "Ninguém, elas se mantêm sozinhas"], answer: "Os anciãos, mestres e líderes espirituais (Griots, Pajés, Sábios)", explanation: "Eles são os 'livros vivos' das comunidades tradicionais.", skill: "Narrativas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Qual a diferença entre uma narrativa religiosa e uma história de ficção?", options: ["A narrativa religiosa é considerada sagrada e portadora de verdade para quem crê", "Não há nenhuma diferença", "As narrativas religiosas são sempre mais curtas", "As histórias de ficção são proibidas"], answer: "A narrativa religiosa é considerada sagrada e portadora de verdade para quem crê", explanation: "O sagrado envolve fé e compromisso de vida.", skill: "Narrativas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Ramayana' e o 'Mahabharata' são grandes narrativas épicas de qual tradição?", options: ["Hinduísmo", "Catolicismo", "Budismo", "Espiritismo"], answer: "Hinduísmo", explanation: "Contam histórias de deuses e heróis fundamentais para o pensamento indiano.", skill: "Narrativas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "As narrativas dos Orixás nas religiões de matriz africana chamam-se:", options: ["Itãs", "Provérbios", "Leis", "Evangelhos"], answer: "Itãs", explanation: "Explicam a personalidade e os feitos de cada divindade.", skill: "Narrativas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Ouvir e respeitar as narrativas sagradas do outro ajuda a:", options: ["Entender a diversidade cultural e praticar a tolerância", "Desistir da própria religião", "Saber quem está mentindo", "Aumentar as brigas entre vizinhos"], answer: "Entender a diversidade cultural e praticar a tolerância", explanation: "As narrativas nos mostram o que é importante para o próximo.", skill: "Narrativas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Muitas narrativas trazem a figura do 'Herói' ou 'Profeta' que serve como:", options: ["Modelo de conduta e fé a ser seguido pelos fiéis", "Apenas uma celebridade rica", "Um vilão que deve ser temido", "Um personagem que não existe de forma nenhuma"], answer: "Modelo de conduta e fé a ser seguido pelos fiéis", explanation: "Inspiram as pessoas a serem melhores seres humanos.", skill: "Narrativas" },

  // 9º Ens. Religioso - Sociedade (9)
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Qual o papel das religiões na construção da 'Ética Social'?", options: ["Promover valores como justiça, paz, solidariedade e respeito", "Impor leis que favoreçam apenas os líderes religiosos enriquecerem", "Incentivar a guerra contra quem pensa diferente", "Não ter nenhum papel na sociedade"], answer: "Promover valores como justiça, paz, solidariedade e respeito", explanation: "As fés influenciam a moral e as leis civis de muitos países.", skill: "Sociedade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Altruísmo', valor pregado por muitas fés, significa:", options: ["Ajudar o próximo sem esperar nada em troca (amor desinteressado)", "Gostar apenas de si mesmo acima de tudo", "Acumular riqueza sozinho", "Não falar com ninguém"], answer: "Ajudar o próximo sem esperar nada em troca (amor desinteressado)", explanation: "É a aplicação prática da caridade e compaixão.", skill: "Sociedade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Religião e Política em um Estado Laico devem:", options: ["Ser separadas, garantindo que nenhuma fé governe sobre as outras", "Ser a mesma coisa para todos seguirem", "Obrigar o presidente a ser de uma igreja específica", "Proibir as pessoas religiosas de votarem"], answer: "Ser separadas, garantindo que nenhuma fé governe sobre as outras", explanation: "A laicidade protege a liberdade de todas as fés (e descrênças).", skill: "Sociedade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "As obras sociais (filantropia) das religiões ajudam a sociedade ao:", options: ["Oferecer auxílio a pobres, doentes e necessitados suprindo falhas do Estado", "Substituir o pagamento de impostos pessoais", "Apenas ganhar propaganda na TV", "Ocultar crimes financeiros"], answer: "Oferecer auxílio a pobres, doentes e necessitados suprindo falhas do Estado", explanation: "É a dimensão de serviço e caridade atuando na realidade social.", skill: "Sociedade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O que é 'Justiça Social' na perspectiva religiosa?", options: ["A luta pela igualdade de direitos e dignidade para todas as pessoas", "A punição cruel de quem não respeita a lei divina", "O direito de ser mais rico que o vizinho", "Apenas rezar nos templos sem fazer nada fora"], answer: "A luta pela igualdade de direitos e dignidade para todas as pessoas", explanation: "Cuidar dos vulneráveis é um imperativo ético de muitas fés.", skill: "Sociedade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O diálogo entre religiões e sociedade civil é importante para resolver problemas como:", options: ["Fome, violência, racismo e degradação ambiental", "Apenas o horário dos cultos", "O preço dos transportes", "Nenhuma das alternativas"], answer: "Fome, violência, racismo e degradação ambiental", explanation: "Une forças para o bem comum da humanidade.", skill: "Sociedade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A liberdade de expressão e a liberdade religiosa são:", options: ["Direitos Humanos Fundamentais que devem conviver em harmonia", "Coisas que não podem existir juntas", "Proibidas em democracias reais", "Privilégios apenas de quem tem dinheiro"], answer: "Direitos Humanos Fundamentais que devem conviver em harmonia", explanation: "Uma garante o direito de crer e a outra o de falar.", skill: "Sociedade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O fenômeno do 'Fanatismo Religioso' causa na sociedade:", options: ["Intolerância, extremismo e violência", "Aumento da inteligência coletiva", "Paz absoluta e amor", "Desenvolvimento da ciência facilitado"], answer: "Intolerância, extremismo e violência", explanation: "O fanatismo cega para o respeito ao outro.", skill: "Sociedade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A religião pode ajudar a preservar o meio ambiente através da:", options: ["Ecoteologia (cuidado com a criação como sagrada)", "Venda de terras das igrejas", "Exploração total dos recursos para o fim do mundo", "Construção de templos de cimento em florestas"], answer: "Ecoteologia (cuidado com a criação como sagrada)", explanation: "Vê a natureza como um presente divino a ser zelado.", skill: "Sociedade" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 23 com ${batch.length} questões adicionado.`);
