import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 5600;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 25: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 6º História - Roma Antiga (9)
  { grade: "6º", discipline: "História", type: "multiple", text: "Segundo a lenda, Roma foi fundada por quais irmãos gêmeos amamentados por uma loba?", options: ["Rômulo e Remo", "Caim e Abel", "Cástor e Pólux", "Aquiles e Heitor"], answer: "Rômulo e Remo", explanation: "A lenda diz que Rômulo fundou a cidade após matar seu irmão Remo.", skill: "Roma Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "Qual era a principal classe social privilegiada da Roma Antiga, composta por grandes proprietários de terra?", options: ["Patrícios", "Plebeus", "Escravos", "Clerigato"], answer: "Patrícios", explanation: "Os patrícios dominavam o Senado e o poder político inicial.", skill: "Roma Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "A 'República Romana' era governada principalmente por qual instituição?", options: ["Senado", "Um único Rei absoluto", "Uma assembleia de escravos", "Um Papa"], answer: "Senado", explanation: "O Senado era o órgão máximo de decisão na República.", skill: "Roma Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "As 'Guerras Púnicas' foram disputadas entre Roma e Cartago pelo controle de qual região?", options: ["Mar Mediterrâneo", "Rio Nilo", "Grécia", "Norte da Europa"], answer: "Mar Mediterrâneo", explanation: "A vitória romana consolidou seu domínio sobre as rotas comerciais marítimas.", skill: "Roma Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "Quem foi o famoso general e político que se tornou ditador perpétuo de Roma e foi assassinado no Senado?", options: ["Júlio César", "Otávio Augusto", "Nero", "Calígula"], answer: "Júlio César", explanation: "Sua morte marcou o fim da República e o início da transição para o Império.", skill: "Roma Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "A 'Pax Romana' foi um período de:", options: ["Relativa paz, estabilidade e prosperidade no Império", "Guerra civil constante em todas as cidades", "Fim da escravidão em Roma", "Invenção da democracia direta"], answer: "Relativa paz, estabilidade e prosperidade no Império", explanation: "Iniciada por Augusto, durou cerca de 200 anos.", skill: "Roma Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "A política do 'Pão e Circo' era usada pelos imperadores para:", options: ["Distrair a plebe com comida e diversão para evitar revoltas", "Educar todos os cidadãos em artes e filosofia", "Acabar com o desemprego através da agricultura", "Transformar escravos em soldados"], answer: "Distrair a plebe com comida e diversão para evitar revoltas", explanation: "Ofereciam trigo e espetáculos de gladiadores no Coliseu.", skill: "Roma Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "Qual era a língua oficial falada no Império Romano, que deu origem ao Português?", options: ["Latim", "Grego", "Aramaico", "Celta"], answer: "Latim", explanation: "O latim vulgar falado pelo povo deu origem às línguas neolatinas.", skill: "Roma Antiga" },
  { grade: "6º", discipline: "História", type: "multiple", text: "O Cristianismo passou de religião perseguida a religião oficial do Império por decisão de qual imperador?", options: ["Teodósio", "Constantino", "Nero", "Marco Aurélio"], answer: "Teodósio", explanation: "Constantino deu liberdade de culto, mas Teodósio a tornou oficial.", skill: "Roma Antiga" },

  // 7º Ciências - Sistema Excretor (9)
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual a função principal do Sistema Excretor?", options: ["Eliminar resíduos tóxicos do metabolismo e manter o equilíbrio de água", "Transformar alimento em energia", "Levar oxigênio para os pulmões", "Produzir hormônios do crescimento"], answer: "Eliminar resíduos tóxicos do metabolismo e manter o equilíbrio de água", explanation: "Elimina principalmente a ureia do sangue.", skill: "Sistema Excretor" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Quais órgãos são responsáveis por filtrar o sangue para formar a urina?", options: ["Rins", "Fígado", "Pulmões", "Baço"], answer: "Rins", explanation: "Possuímos dois rins que funcionam como filtros constantes.", skill: "Sistema Excretor" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "A unidade funcional do rim, onde ocorre a filtragem real, chama-se:", options: ["Néfron", "Alvéolo", "Neurônio", "Plaqueta"], answer: "Néfron", explanation: "Existem milhões de néfrons em cada rim.", skill: "Sistema Excretor" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O canal que transporta a urina do rim até a bexiga é o(a):", options: ["Ureter", "Uretra", "Esôfago", "Vasa deferente"], answer: "Ureter", explanation: "Temos dois ureteres, um para cada rim.", skill: "Sistema Excretor" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Onde a urina fica armazenada antes de ser eliminada do corpo?", options: ["Bexiga urinária", "Vesícula biliar", "Intestino grosso", "Estômago"], answer: "Bexiga urinária", explanation: "É um órgão muscular elástico.", skill: "Sistema Excretor" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual canal comunica a bexiga com o meio externo para a micção?", options: ["Uretra", "Ureter", "Intestino delgado", "Brônquio"], answer: "Uretra", explanation: "É o último canal do sistema excretor.", skill: "Sistema Excretor" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Ao filtrarmos o sangue, substâncias importantes que não devem ser perdidas são:", options: ["Glicose, água e sais minerais necessários", "Apenas a ureia", "O gás carbônico apenas", "Pedaços de ossos"], answer: "Glicose, água e sais minerais necessários", explanation: "Elas são reabsorvidas pelos rins de volta para o sangue.", skill: "Sistema Excretor" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual hábito ajuda a prevenir a formação de 'pedras nos rins' (cálculo renal)?", options: ["Beber bastante água ao longo do dia", "Comer muito sal", "Não urinar por longos períodos", "Beber apenas refrigerantes"], answer: "Beber bastante água ao longo do dia", explanation: "A água dilui as substâncias que podem cristalizar nos rins.", skill: "Sistema Excretor" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Além dos rins, qual outro órgão participa da excreção eliminando sais e água?", options: ["Pele (suor)", "Músculos", "Ossos", "Olhos"], answer: "Pele (suor)", explanation: "O suor também ajuda a eliminar algumas substâncias do metabolismo.", skill: "Sistema Excretor" },

  // 9º Matemática - Álgebra (9)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual é o valor de 'x' na equação 2x + 10 = 30?", options: ["10", "20", "5", "15"], answer: "10", explanation: "2x = 30 - 10 => 2x = 20 => x = 10.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Uma equação do 2º grau (ax² + bx + c = 0) pode ser resolvida pela fórmula de:", options: ["Bhaskara", "Pitágoras", "Tales", "Arquimedes"], answer: "Bhaskara", explanation: "Utiliza o cálculo do discriminante (Delta).", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o valor de 'Delta' (Δ) na equação x² - 5x + 6 = 0?", options: ["1", "-1", "25", "49"], answer: "1", explanation: "Δ = b² - 4ac => (-5)² - 4*1*6 = 25 - 24 = 1.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que representa o 'Domínio' de uma função?", options: ["O conjunto de todos os valores possíveis para a variável independente (x)", "O resultado final da conta (y)", "Apenas o número zero", "O nome do matemático que a inventou"], answer: "O conjunto de todos os valores possíveis para a variável independente (x)", explanation: "São as entradas da função.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Uma função do 1º grau (y = ax + b) é representada graficamente por uma:", options: ["Reta", "Parábola", "Círculo", "Onda"], answer: "Reta", explanation: "Onde 'a' é o coeficiente angular e 'b' o linear.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O ponto onde a parábola de uma função do 2º grau atinge seu valor máximo ou mínimo é o:", options: ["Vértice", "Raiz", "Foco", "Tangente"], answer: "Vértice", explanation: "Calculado pelas fórmulas xV = -b/2a e yV = -Δ/4a.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de (x + 3)² usando produtos notáveis?", options: ["x² + 6x + 9", "x² + 9", "x² + 3x + 9", "2x + 6"], answer: "x² + 6x + 9", explanation: "Quadrado do primeiro + duas vezes o primeiro pelo segundo + quadrado do segundo.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que significa 'Fatorar' uma expressão algébrica?", options: ["Transformar uma soma em um produto de fatores", "Somar todos os números", "Mudar o sinal de todos os termos", "Escrevê-la em latim"], answer: "Transformar uma soma em um produto de fatores", explanation: "Facilita a simplificação de cálculos.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Se y = 2x - 5, qual o valor de y quando x = 4?", options: ["3", "13", "8", "-1"], answer: "3", explanation: "y = 2(4) - 5 => y = 8 - 5 = 3.", skill: "Álgebra" },

  // 9º Português - Crase (9)
  { grade: "9º", discipline: "Português", type: "multiple", text: "O que é, gramaticalmente, a 'Crase'?", options: ["A fusão de duas vogais 'a' (preposição + artigo ou pronome)", "Um acento agudo ao contrário", "Uma pausa na leitura", "O mesmo que vírgula"], answer: "A fusão de duas vogais 'a' (preposição + artigo ou pronome)", explanation: "É a união do 'a' preposição com o 'a' artigo feminino.", skill: "Crase" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Qual o sinal gráfico que indica a ocorrência da crase?", options: ["Acento Grave ( ` )", "Acento Agudo ( ´ )", "Til ( ~ )", "Circunflexo ( ^ )"], answer: "Acento Grave ( ` )", explanation: "Ex: Fui à escola.", skill: "Crase" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Em qual destes casos a crase é PROIBIDA?", options: ["Antes de palavras masculinas", "Antes de nomes de cidades que aceitam artigo", "Em locuções adverbiais femininas", "Antes de nomes próprios femininos"], answer: "Antes de palavras masculinas", explanation: "Não há artigo feminino antes de substantivos masculinos. Ex: 'Andar a cavalo'.", skill: "Crase" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Escolha a frase correta quanto ao uso da crase:", options: ["Fui à feira comprar maçãs.", "Diga à ele a verdade.", "Chegamos à dez horas da manhã.", "Compramos o carro à prazo."], answer: "Fui à feira comprar maçãs.", explanation: "Quem vai, vai A algum lugar. Feira é substantivo feminino que aceita artigo.", skill: "Crase" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Usa-se crase na indicação de horas exatas. Qual das opções está correta?", options: ["A aula começa às 19 horas.", "Fui a escola as 10 horas.", "O show é à partir das 21h.", "Saímos as pressas."], answer: "A aula começa às 19 horas.", explanation: "Indicação de horas determinadas sempre leva crase.", skill: "Crase" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "A crase é OBRIGATÓRIA antes de expressões como:", options: ["À moda de / À maneira de (mesmo subentendidas)", "A cada momento", "A disposição de apenas", "A pé"], answer: "À moda de / À maneira de (mesmo subentendidas)", explanation: "Ex: 'Bife à milanesa' (à moda de Milão).", skill: "Crase" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Em 'Fui a casa de meus avós', ocorre crase? Se sim, como ficaria?", options: ["Sim, 'Fui à casa de meus avós'", "Não ocorre", "Opcional", "Apenas se a casa for longe"], answer: "Sim, 'Fui à casa de meus avós'", explanation: "Quando a palavra 'casa' vier especificada, ocorre a crase.", skill: "Crase" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Antes de verbos, o uso da crase é:", options: ["Proibido", "Obrigatório", "Opcional", "Sempre aceito"], answer: "Proibido", explanation: "Verbos não admitem artigo feminino.", skill: "Crase" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Em qual caso a crase é OPCIONAL?", options: ["Antes de nomes próprios femininos", "Antes de palavras masculinas", "Antes de numerais cardinais", "Nunca é opcional"], answer: "Antes de nomes próprios femininos", explanation: "Ex: 'Entreguei o livro a Maria' ou 'Entreguei o livro à Maria'.", skill: "Crase" },

  // 6º Matemática - Unidades (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual a unidade fundamental de comprimento no Sistema Internacional?", options: ["Metro", "Centímetro", "Kilômetro", "Polegada"], answer: "Metro", explanation: "O metro (m) é a base para as outras medidas de comprimento.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quantos centímetros existem em 1,5 metros?", options: ["150 cm", "15 cm", "1.500 cm", "1,5 cm"], answer: "150 cm", explanation: "Para passar de metro para centímetro, multiplicamos por 100.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quantas gramas formam 1 quilograma (kg)?", options: ["1.000 g", "100 g", "10.000 g", "10 g"], answer: "1.000 g", explanation: "Kilo significa mil.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Para medir a largura de um caderno, qual unidade é a mais adequada?", options: ["Centímetros", "Kilômetros", "Milímetros apenas", "Metros"], answer: "Centímetros", explanation: "Facilita a leitura em objetos pequenos.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "A unidade de medida de volume (capacidade) para líquidos em garrafas costuma ser:", options: ["Litro (L)", "Metro quadrado (m²)", "Grama (g)", "Segundo (s)"], answer: "Litro (L)", explanation: "O litro é a medida padrão de capacidade.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quantos mililitros (ml) existem em meio litro (0,5 L)?", options: ["500 ml", "50 ml", "1.000 ml", "5 ml"], answer: "500 ml", explanation: "1 L = 1.000 ml, logo metade é 500 ml.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Para medir a área de uma sala, usamos unidades de:", options: ["Metro quadrado (m²)", "Metro linear (m)", "Metro cúbico (m³)", "Kilograma (kg)"], answer: "Metro quadrado (m²)", explanation: "Área envolve duas dimensões (largura x comprimento).", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quantos segundos existem em 5 minutos?", options: ["300 s", "50 s", "60 s", "120 s"], answer: "300 s", explanation: "5 * 60 = 300.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O 'quilômetro' (km) equivale a quantos metros?", options: ["1.000 metros", "100 metros", "10.000 metros", "10 metros"], answer: "1.000 metros", explanation: "Usado para grandes distâncias.", skill: "Unidades" },

  // 7º Arte - Gravura (9)
  { grade: "7º", discipline: "Arte", type: "multiple", text: "O que é a técnica da 'Gravura' na arte?", options: ["Criação de imagens a partir da impressão de uma matriz", "Pintura direta na parede", "Escultura em mármore", "Fotografia digital"], answer: "Criação de imagens a partir da impressão de uma matriz", explanation: "O artista cria a imagem em uma base e a transfere para o papel.", skill: "Gravura" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "A técnica de gravar em relevo sobre uma base de MADEIRA é a:", options: ["Xilogravura", "Calcogravura", "Litografia", "Serigrafia"], answer: "Xilogravura", explanation: "É a forma mais antiga de gravura.", skill: "Gravura" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "Na Xilogravura, a parte da madeira que foi ESCULPIDA com a goiva fica:", options: ["Branca (sem tinta) na impressão", "Preta (com tinta)", "Colorida automaticamente", "Transparente"], answer: "Branca (sem tinta) na impressão", explanation: "A tinta pega apenas na parte alta da madeira que restou.", skill: "Gravura" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "A gravura feita em placas de METAL (como cobre ou latão) é a:", options: ["Calcogravura (ou Gravura em Metal)", "Pintura a óleo", "Afresco", "Colagem"], answer: "Calcogravura (ou Gravura em Metal)", explanation: "Utiliza ácidos ou ponta-seca para criar sulcos.", skill: "Gravura" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "Qual tipo de gravura utiliza uma PEDRA de calcário para a impressão?", options: ["Litografia", "Estêncil", "Grafite", "Nanquim"], answer: "Litografia", explanation: "Baseia-se na repulsão entre água e gordura.", skill: "Gravura" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "A 'Serigrafia' (ou Silk-screen) utiliza qual tipo de matriz?", options: ["Uma tela de tecido (seda ou nylon)", "Placa de ferro", "Tronco de árvore", "Vidro soprado"], answer: "Uma tela de tecido (seda ou nylon)", explanation: "Muito usada para estampar camisetas e cartazes.", skill: "Gravura" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "Por que a gravura é considerada uma forma de arte democrática?", options: ["Permite a reprodução de várias cópias da mesma obra", "É feita apenas por pessoas pobres", "Não usa cores caras", "Pode ser feita na rua"], answer: "Permite a reprodução de várias cópias da mesma obra", explanation: "A tiragem múltipla torna a arte mais acessível.", skill: "Gravura" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "A 'Linoleogravura' utiliza qual material como matriz?", options: ["Linóleo (um tipo de borracha sintética)", "Pedra sabão", "Papelão", "Gelo"], answer: "Linóleo (um tipo de borracha sintética)", explanation: "É mais macio e fácil de cortar que a madeira.", skill: "Gravura" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "O conjunto de cópias produzidas a partir de uma mesma matriz chama-se:", options: ["Tiragem (Edição)", "Coleção", "Rascunho", "Mosaico"], answer: "Tiragem (Edição)", explanation: "O artista numera cada cópia (ex: 1/50).", skill: "Gravura" },

  // 8º Arte - Contemporânea (9)
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O que caracteriza a 'Arte Contemporânea'?", options: ["A diversidade de linguagens, o foco no conceito e a quebra de suportes tradicionais", "A busca pela perfeição da imagem como nas fotos", "O uso exclusivo de tinta a óleo", "A proibição de temas políticos"], answer: "A diversidade de linguagens, o foco no conceito e a quebra de suportes tradicionais", explanation: "Ocorre da segunda metade do século XX até hoje.", skill: "Contemporânea" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Uma obra de arte que ocupa um espaço tridimensional e convida o espectador a entrar nela é uma:", options: ["Instalação", "Escultura clássica", "Miniatura", "Pintura mural"], answer: "Instalação", explanation: "Foca na experiência espacial do visitante.", skill: "Contemporânea" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A 'Performance' na arte contemporânea utiliza qual elemento principal?", options: ["O próprio corpo do artista", "Apenas bonecos de cera", "Câmeras escondidas apenas", "Nenhum elemento físico"], answer: "O próprio corpo do artista", explanation: "O artista realiza uma ação diante do público ou câmera.", skill: "Contemporânea" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "No 'Happening', qual a característica mais importante?", options: ["A participação imprevisível do público e o acaso", "O silêncio absoluto", "O roteiro decorado perfeitamente", "A venda imediata da obra"], answer: "A participação imprevisível do público e o acaso", explanation: "Busca apagar a distância entre arte e vida.", skill: "Contemporânea" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A 'Land Art' utiliza qual ambiente como suporte para a criação?", options: ["A própria natureza (terra, pedras, praias)", "Galerias de shoppings", "Páginas de internet apenas", "Estúdios de TV"], answer: "A própria natureza (terra, pedras, praias)", explanation: "Obras muitas vezes efêmeras ou monumentais no meio ambiente.", skill: "Contemporânea" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A 'Videoarte' utiliza a tecnologia do vídeo para:", options: ["Expressar conceitos artísticos, fugindo do cinema comercial", "Gravar apenas festas de aniversário", "Vender produtos na TV", "Substituir a pintura a mão"], answer: "Expressar conceitos artísticos, fugindo do cinema comercial", explanation: "Explora o tempo, a imagem e o som de forma experimental.", skill: "Contemporânea" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O conceito de 'Arte Efêmera' refere-se a obras que:", options: ["Duram pouco tempo (são transitórias)", "São feitas para durar mil anos", "São feitas de ouro e diamantes", "São invisíveis ao olho humano"], answer: "Duram pouco tempo (são transitórias)", explanation: "Ex: desenhos na areia, esculturas de gelo.", skill: "Contemporânea" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A 'Ready-made', técnica que usa objetos do dia a dia, influenciou o surgimento da:", options: ["Arte Conceitual", "Arte Renascentista", "Cerâmica tradicional", "Tecelagem de lã"], answer: "Arte Conceitual", explanation: "Defende que a ideia por trás da obra é o mais importante.", skill: "Contemporânea" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O museu de Inhotim, em Minas Gerais, é famoso mundialmente por seu acervo de:", options: ["Arte Contemporânea instalada em um jardim botânico", "Antiguidades egípcias", "Moedas de ouro coloniais", "Fósseis de dinossauros"], answer: "Arte Contemporânea instalada em um jardim botânico", explanation: "É um dos maiores museus a céu aberto do mundo.", skill: "Contemporânea" },

  // 7º Ed. Física - Flexibilidade (9)
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "O que é a 'Flexibilidade' física?", options: ["A capacidade de realizar movimentos com grande amplitude articular", "A força máxima de um músculo", "A velocidade de corrida", "O tempo que se consegue ficar sem respirar"], answer: "A capacidade de realizar movimentos com grande amplitude articular", explanation: "Envolve a elasticidade dos músculos e tendões.", skill: "Flexibilidade" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Qual a importância de treinar a flexibilidade?", options: ["Melhora o desempenho esportivo e previne lesões musculares", "Dificulta a respiração", "Aumenta o peso corporal", "Não tem nenhuma utilidade real"], answer: "Melhora o desempenho esportivo e previne lesões musculares", explanation: "Um corpo flexível tem movimentos mais fluidos e seguros.", skill: "Flexibilidade" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Atividades que buscam esticar as fibras musculares para aumentar a amplitude são os:", options: ["Alongamentos", "Treinos de força pesada", "Tiros de velocidade", "Massagens apenas"], answer: "Alongamentos", explanation: "Podem ser feitos antes (leve) ou depois (compensatório) do treino.", skill: "Flexibilidade" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Qual desses esportes exige níveis EXTREMOS de flexibilidade dos atletas?", options: ["Ginástica Artística", "Sumô", "Halterofilismo", "Xadrez"], answer: "Ginástica Artística", explanation: "Movimentos como espacates e pontes exigem muita amplitude.", skill: "Flexibilidade" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "A flexibilidade costuma diminuir com o passar dos anos (idade). Por quê?", options: ["Perda natural de colágeno e menor atividade física", "O corpo fica mais forte automaticamente", "Os ossos diminuem de tamanho", "A gravidade puxa os músculos para baixo"], answer: "Perda natural de colágeno e menor atividade física", explanation: "Por isso é importante manter o treino ao longo da vida.", skill: "Flexibilidade" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "A prática de Yoga e Pilates foca muito em:", options: ["Flexibilidade e força de estabilização (Core)", "Velocidade explosiva", "Lutas de contato", "Levantamento de peso máximo"], answer: "Flexibilidade e força de estabilização (Core)", explanation: "Buscam o equilíbrio corporal total.", skill: "Flexibilidade" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Um alongamento 'Estático' consiste em:", options: ["Manter uma posição de estiramento por 20 a 30 segundos", "Pular enquanto se estica", "Correr e parar de repente", "Fazer caretas"], answer: "Manter uma posição de estiramento por 20 a 30 segundos", explanation: "É a forma mais comum e segura de alongar.", skill: "Flexibilidade" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "A má postura ao sentar pode prejudicar a flexibilidade de qual região?", options: ["Coluna vertebral e quadril", "Dedo mindinho", "Orelhas", "Cabelo"], answer: "Coluna vertebral e quadril", explanation: "Gera encurtamento muscular e dores lombares.", skill: "Flexibilidade" },
  { grade: "7º", discipline: "Educação Física", type: "multiple", text: "Hormônios podem influenciar a flexibilidade. Geralmente, as mulheres são:", options: ["Mais flexíveis que os homens devido à estrutura física e hormônios", "Menos flexíveis em todos os casos", "Iguais aos homens sem diferença nenhuma", "Impossibilitadas de serem flexíveis"], answer: "Mais flexíveis que os homens devido à estrutura física e hormônios", explanation: "A relaxina é um exemplo de hormônio que facilita a frouxidão ligamentar.", skill: "Flexibilidade" },

  // 6º Ens. Religioso - Espaços (9)
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O que define um 'Espaço Sagrado'?", options: ["Um lugar onde os fiéis sentem a presença do divino e praticam sua fé", "Qualquer shopping ou supermercado", "Apenas a sala do diretor da escola", "Um lugar proibido para todas as pessoas"], answer: "Um lugar onde os fiéis sentem a presença do divino e praticam sua fé", explanation: "Pode ser um prédio (templo) ou um elemento da natureza.", skill: "Espaços" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Exemplos de espaços sagrados CONSTRUÍDOS (Arquitetura) são:", options: ["Igrejas, Mesquitas, Templos, Sinagogas e Terreiros", "Parques de diversão e Estádios", "Fábricas e Escritórios", "Cinemas e Teatros apenas"], answer: "Igrejas, Mesquitas, Templos, Sinagogas e Terreiros", explanation: "São erguidos especificamente para o rito religioso.", skill: "Espaços" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Para muitas religiões indígenas e de matriz africana, o espaço sagrado pode ser:", options: ["A própria natureza (matas, cachoeiras, rios)", "Apenas grandes palácios de ouro", "Salas secretas de internet", "Cidades subterrâneas de metal"], answer: "A própria natureza (matas, cachoeiras, rios)", explanation: "A divindade se manifesta nos elementos naturais.", skill: "Espaços" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O que os fiéis costumam fazer ao entrar em um espaço sagrado em sinal de respeito?", options: ["Atitudes como tirar o chapéu, os sapatos ou manter o silêncio", "Falar muito alto e correr", "Comer lanches rápidos", "Pichar as paredes"], answer: "Atitudes como tirar o chapéu, os sapatos ou manter o silêncio", explanation: "Cada religião tem seu código de postura no espaço sagrado.", skill: "Espaços" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Uma 'Mesquita' é o espaço sagrado de qual religião?", options: ["Islamismo", "Judaísmo", "Catolicismo", "Hinduísmo"], answer: "Islamismo", explanation: "Focada na direção da cidade sagrada de Meca.", skill: "Espaços" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Sinagoga' é o local de culto de qual tradição religiosa?", options: ["Judaísmo", "Espiritismo", "Budismo", "Protestantismo"], answer: "Judaísmo", explanation: "Onde se lê a Torá e se realizam as orações comunitárias.", skill: "Espaços" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Muitos espaços sagrados possuem símbolos. Qual o símbolo comum no topo das Igrejas Cristãs?", options: ["Cruz", "Estrela de Davi", "Crescente com Estrela", "Roda do Dharma"], answer: "Cruz", explanation: "Representa o sacrifício e a ressurreição de Jesus.", skill: "Espaços" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Um espaço sagrado pode se tornar um local de peregrinação. O que é isso?", options: ["Viagens de longas distâncias feitas por devotos para visitar o local", "O abandono do local", "Transformar o lugar em estacionamento", "A destruição do espaço por guerras"], answer: "Viagens de longas distâncias feitas por devotos para visitar o local", explanation: "Ex: Aparecida do Norte, Meca, Jerusalém.", skill: "Espaços" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Respeitar o espaço sagrado do outro é importante para:", options: ["A convivência pacífica e a tolerância religiosa", "Provar que sua religião é melhor", "Apenas obedecer as leis de trânsito", "Ganhar dinheiro em sorteios"], answer: "A convivência pacífica e a tolerância religiosa", explanation: "O respeito ao espaço é o respeito à própria fé do próximo.", skill: "Espaços" },

  // 7º Ens. Religioso - Rituais (9)
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "O que são 'Rituais' na religião?", options: ["Ações simbólicas repetidas que conectam o fiel ao sagrado", "Apenas festas com muita comida sem significado", "Leis de trânsito religiosas", "Fatos que acontecem por acaso uma única vez"], answer: "Ações simbólicas repetidas que conectam o fiel ao sagrado", explanation: "Os ritos organizam a vida religiosa do indivíduo e do grupo.", skill: "Rituais" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Um 'Rito de Passagem' serve para celebrar e marcar:", options: ["A mudança de uma fase da vida para outra (nascimento, puberdade, casamento)", "O fim de uma promoção de supermercado", "Apenas a troca de um ano para o outro no calendário", "A compra de um objeto novo"], answer: "A mudança de uma fase da vida para outra (nascimento, puberdade, casamento)", explanation: "Integra o indivíduo em seu novo papel na comunidade.", skill: "Rituais" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Batismo' no cristianismo é um ritual que simboliza a:", options: ["Purificação e entrada do fiel na comunidade religiosa", "Apenas a escolha do nome civil", "A formatura na escola", "A vitória em uma competição de natação"], answer: "Purificação e entrada do fiel na comunidade religiosa", explanation: "Geralmente utiliza o símbolo da água.", skill: "Rituais" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "O ritual fúnebre (enterro, cremação) tem como função religiosa:", options: ["Honrar o morto, consolar a família e refletir sobre a vida após a morte", "Apenas esconder o corpo", "Fazer de conta que nada aconteceu", "Derrubar árvores em volta"], answer: "Honrar o morto, consolar a família e refletir sobre a vida após a morte", explanation: "É um momento de luto e espiritualidade.", skill: "Rituais" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "A oração individual ou coletiva é um tipo de ritual de:", options: ["Comunicação e conexão com a divindade", "Apenas exercício vocal", "Sorteio de prêmios", "Descanso do corpo"], answer: "Comunicação e conexão com a divindade", explanation: "Pode ser feita através de palavras, silêncio ou cantos.", skill: "Rituais" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Ritual que envolve a partilha de alimentos sagrados é comum em muitas fés. Na Igreja Católica é a:", options: ["Eucaristia (Pão e Vinho)", "Confissão", "Crisma", "Casamento"], answer: "Eucaristia (Pão e Vinho)", explanation: "Lembrança da última ceia de Jesus.", skill: "Rituais" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Muitos rituais utilizam elementos da natureza. Qual o papel do Fogo em muitos ritos?", options: ["Purificação, iluminação e presença divina", "Apenas para cozinhar para os convidados", "Aquecer apenas se estiver fazendo frio", "Destruir a natureza"], answer: "Purificação, iluminação e presença divina", explanation: "Velas e fogueiras são símbolos sagrados potentes.", skill: "Rituais" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "O Bar Mitzvah (para meninos) e Bat Mitzvah (para meninas) são ritos do:", options: ["Judaísmo", "Islamismo", "Hinduísmo", "Budismo"], answer: "Judaísmo", explanation: "Celebram a maturidade religiosa dos jovens aos 12/13 anos.", skill: "Rituais" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "A repetição dos rituais é importante porque:", options: ["Reforça a fé, a identidade e une os praticantes em uma tradição", "Porque sim, sem nenhum motivo", "Para cansar as pessoas até elas desistirem", "Para economizar tempo de estudo"], answer: "Reforça a fé, a identidade e une os praticantes em uma tradição", explanation: "Manter a tradição viva através da prática constante.", skill: "Rituais" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 25 com ${batch.length} questões adicionado.`);
