import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 6100;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 30: Injeção de 90 questões de Matemática a partir do ID: ${startId}`);

const batch = [
  // 8º Matemática - Geometria (10)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que diz a propriedade fundamental da soma dos ângulos internos de um triângulo?", options: ["A soma é sempre 180°", "A soma é sempre 360°", "A soma depende do tamanho dos lados", "A soma é sempre 90°"], answer: "A soma é sempre 180°", explanation: "Vale para qualquer triângulo plano.", skill: "Geometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Dois ângulos que possuem o mesmo vértice e lados opostos são chamados de:", options: ["Opostos pelo vértice (OPV)", "Complementares", "Suplementares", "Adjacentes"], answer: "Opostos pelo vértice (OPV)", explanation: "Ângulos OPV possuem sempre a mesma medida.", skill: "Geometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Um triângulo que possui um ângulo de 90° é classificado como:", options: ["Retângulo", "Acutângulo", "Obtusângulo", "Equilátero"], answer: "Retângulo", explanation: "O ângulo reto caracteriza o triângulo retângulo.", skill: "Geometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A soma dos ângulos internos de um quadrilátero é sempre:", options: ["360°", "180°", "540°", "720°"], answer: "360°", explanation: "Um quadrilátero pode ser dividido em dois triângulos.", skill: "Geometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que é um polígono regular?", options: ["Possui todos os lados e ângulos iguais", "Possui apenas lados iguais", "Possui apenas ângulos iguais", "Tem formato redondo"], answer: "Possui todos os lados e ângulos iguais", explanation: "Exemplo: quadrado e triângulo equilátero.", skill: "Geometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Como se chama o segmento que liga o centro de um círculo a qualquer ponto da sua extremidade?", options: ["Raio", "Diâmetro", "Corda", "Tangente"], answer: "Raio", explanation: "O raio é a metade do diâmetro.", skill: "Geometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A soma dos ângulos externos de qualquer polígono convexo é sempre:", options: ["360°", "180°", "Varia com os lados", "90°"], answer: "360°", explanation: "Propriedade invariante para polígonos convexos.", skill: "Geometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o nome do triângulo que possui dois lados iguais?", options: ["Isósceles", "Equilátero", "Escaleno", "Retângulo"], answer: "Isósceles", explanation: "Possui também dois ângulos da base iguais.", skill: "Geometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que são retas paralelas?", options: ["Retas que nunca se cruzam e mantêm a mesma distância", "Retas que se cruzam forming 90°", "Retas que se cruzam em um ponto", "Retas que estão no mesmo ponto"], answer: "Retas que nunca se cruzam e mantêm a mesma distância", explanation: "O coeficiente angular delas é igual.", skill: "Geometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Como calculamos o perímetro de uma figura?", options: ["Somando todos os seus lados", "Multiplicando a base pela altura", "Elevando o lado ao quadrado", "Dividindo a área por dois"], answer: "Somando todos os seus lados", explanation: "Perímetro é o contorno da figura.", skill: "Geometria" },

  // 6º Matemática - Divisibilidade (10)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um número é divisível por 2 quando:", options: ["Ele é par (termina em 0, 2, 4, 6 ou 8)", "Ele termina em 5", "A soma dos algarismos é par", "Ele é maior que 10"], answer: "Ele é par (termina em 0, 2, 4, 6 ou 8)", explanation: "Critério básico de paridade.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Para um número ser divisível por 3, a regra é:", options: ["A soma de seus algarismos deve ser divisível por 3", "Ele deve terminar em 3", "Ele deve ser um número ímpar", "Ele deve ser maior que 30"], answer: "A soma de seus algarismos deve ser divisível por 3", explanation: "Exemplo: 123 (1+2+3=6), que é divisível por 3.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o critério de divisibilidade por 5?", options: ["O número deve terminar em 0 ou 5", "O número deve ser par", "O número deve ter 5 algarismos", "O número deve ser múltiplo de 10"], answer: "O número deve terminar em 0 ou 5", explanation: "Regra prática para múltiplos de 5.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um número é divisível por 10 se:", options: ["Ele terminar em 0", "Ele terminar em 5", "Ele for par", "A soma dos algarismos for 10"], answer: "Ele terminar em 0", explanation: "Regra básica do sistema decimal.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um número é divisível por 6 se ele for:", options: ["Divisível por 2 e por 3 ao mesmo tempo", "Divisível apenas por 3", "Divisível apenas por 2", "Um número maior que 60"], answer: "Divisível por 2 e por 3 ao mesmo tempo", explanation: "Como 6=2x3, ele deve atender aos dois critérios.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual destes números é divisível por 9?", options: ["81", "12", "23", "30"], answer: "81", explanation: "8+1=9. Se a soma dos algarismos é múltiplo de 9, o número também é.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que é o resto em uma divisão exata?", options: ["Zero", "Um", "O mesmo valor do divisor", "Qualquer número negativo"], answer: "Zero", explanation: "Divisão exata significa que não há sobra.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um número é divisível por 4 se:", options: ["Os seus dois últimos algarismos formarem um número divisível por 4", "Ele for divisível por 2 apenas", "Ele terminar em 4", "A soma dos algarismos for par"], answer: "Os seus dois últimos algarismos formarem um número divisível por 4", explanation: "Critério comum para múltiplos de 4.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Números que possuem apenas dois divisores (1 e ele mesmo) são chamados de:", options: ["Primos", "Compostos", "Pares", "Nulos"], answer: "Primos", explanation: "Definição de número primo.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O número 0 é divisível por:", options: ["Todos os números diferentes de zero", "Apenas por ele mesmo", "Nenhum número", "Apenas pelo 1"], answer: "Todos os números diferentes de zero", explanation: "0 dividido por qquer número é 0 (exata).", skill: "Divisibilidade" },

  // 8º Matemática - Estatística Básica (10)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que é a 'Média Aritmética' de um conjunto de dados?", options: ["A soma de todos os valores dividida pela quantidade de valores", "O valor que mais se repete", "O valor que fica no meio da lista organizada", "A diferença entre o maior e o menor valor"], answer: "A soma de todos os valores dividida pela quantidade de valores", explanation: "É a medida de tendência central mais comum.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Em estatística, o valor que aparece com maior frequência em um conjunto é a:", options: ["Moda", "Mediana", "Média", "Amplitude"], answer: "Moda", explanation: "Pode haver conjuntos amodais ou plurimodais.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Para encontrar a 'Mediana', a primeira coisa a fazer é:", options: ["Organizar os dados em ordem crescente ou decrescente (Rol)", "Somar todos os valores", "Dividir o maior pelo menor", "Multiplicar os dados"], answer: "Organizar os dados em ordem crescente ou decrescente (Rol)", explanation: "A mediana é a posição central da lista ordenada.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual a média das notas 6, 8 e 10?", options: ["8", "7", "9", "24"], answer: "8", explanation: "(6+8+10)/3 = 24/3 = 8.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Se em um conjunto de 5 números a mediana é 10, isso significa que:", options: ["10 é o valor central após ordenar os dados", "10 é a soma dos números", "Todos os números são 10", "10 é o número que mais se repete"], answer: "10 é o valor central após ordenar os dados", explanation: "Define o meio da amostra.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que é 'Amplitude' de uma amostra?", options: ["A diferença entre o maior valor e o menor valor", "O tamanho do gráfico", "A soma de todos os dados", "O nome do pesquisador"], answer: "A diferença entre o maior valor e o menor valor", explanation: "Indica o grau de dispersão inicial.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Um gráfico de setores (pizza) é ideal para mostrar:", options: ["Proporções e partes de um todo", "Evolução do tempo apenas", "Medidas exatas de altura", "Listas de nomes"], answer: "Proporções e partes de um todo", explanation: "As fatias facilitam a visualização percentual.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que é 'População' em uma pesquisa estatística?", options: ["O grupo total de indivíduos sobre o qual se deseja obter informações", "Apenas as pessoas que moram em cidades", "O número de alunos de uma sala", "O resultado final da média"], answer: "O grupo total de indivíduos sobre o qual se deseja obter informações", explanation: "A amostra é uma parte dessa população.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual a moda no conjunto {2, 3, 3, 5, 8, 10}?", options: ["3", "5", "10", "2"], answer: "3", explanation: "É o único valor que se repete.", skill: "Estatística Básica" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A estatística é a ciência que se ocupa de:", options: ["Coletar, organizar, analisar e interpretar dados", "Estudar apenas as células humanas", "Criar novas línguas", "Medir planetas"], answer: "Coletar, organizar, analisar e interpretar dados", explanation: "Ferramenta essencial para tomada de decisões.", skill: "Estatística Básica" },

  // 8º Matemática - Volumes (10)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que mede o 'Volume' de um objeto?", options: ["O espaço tridimensional ocupado por ele", "O tamanho do seu contorno", "O peso em quilos", "A cor da superfície"], answer: "O espaço tridimensional ocupado por ele", explanation: "Medido em unidades cúbicas (m³, cm³).", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual a fórmula para o volume de um paralelepípedo (caixa)?", options: ["Comprimento * Largura * Altura", "Base * Altura apenas", "Lado * 4", "Raiz quadrada da área"], answer: "Comprimento * Largura * Altura", explanation: "Multiplicação das três dimensões.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A unidade padrão de volume no Sistema Internacional é o:", options: ["Metro cúbico (m³)", "Litro", "Quilo", "Metro quadrado"], answer: "Metro cúbico (m³)", explanation: "Corresponde ao volume de um cubo de 1m de aresta.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o volume de um cubo com aresta de 2 cm?", options: ["8 cm³", "4 cm³", "6 cm³", "12 cm³"], answer: "8 cm³", explanation: "2 * 2 * 2 = 8.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Sabendo que 1 decímetro cúbico (dm³) equivale a 1 litro, um balde de 5000 cm³ tem quantos litros?", options: ["5 litros", "50 litros", "0,5 litros", "500 litros"], answer: "5 litros", explanation: "5000 cm³ = 5 dm³ = 5 litros.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Como se calcula o volume de um cilindro?", options: ["Área da base * Altura (π * r² * h)", "Base * Altura / 2", "2 * π * r", "Lado ao cubo"], answer: "Área da base * Altura (π * r² * h)", explanation: "É o empilhamento das bases circulares.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Se dobrarmos a altura de um reservatório mantendo a base igual, o volume:", options: ["Dobra", "Quadruplica", "Fica igual", "Diminui pela metade"], answer: "Dobra", explanation: "O volume é diretamente proporcional à altura.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Um prisma triangular tem volume calculado por:", options: ["Área da base triangular * Altura do prisma", "Lado * Lado * Lado", "Base * Altura", "Soma dos lados"], answer: "Área da base triangular * Altura do prisma", explanation: "Regra geral para prismas: V = Ab * h.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o volume de uma piscina infantil retangular de 2m x 3m x 0,5m?", options: ["3 m³", "6 m³", "1,5 m³", "5 m³"], answer: "3 m³", explanation: "2 * 3 * 0,5 = 3.", skill: "Volumes" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A capacidade de um recipiente refere-se a:", options: ["Quanto de líquido ele pode conter (geralmente em litros)", "Quanto ele pesa vazio", "O material de que é feito", "O preço do recipiente"], answer: "Quanto de líquido ele pode conter (geralmente em litros)", explanation: "Capacidade e volume são conceitos relacionados.", skill: "Volumes" },

  // 8º Matemática - Trigonometria (10)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A trigonometria estuda a relação entre:", options: ["Os lados e os ângulos de um triângulo", "As cores e as formas", "A história das pirâmides apenas", "Apenas círculos perfeitos"], answer: "Os lados e os ângulos de um triângulo", explanation: "Fundamental para medir distâncias inacessíveis.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "No triângulo retângulo, o 'Seno' de um ângulo agudo é a razão entre:", options: ["Cateto Oposto / Hipotenusa", "Cateto Adjacente / Hipotenusa", "Cateto Oposto / Cateto Adjacente", "Hipotenusa / Cateto"], answer: "Cateto Oposto / Hipotenusa", explanation: "Definição básica de Seno.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O 'Cosseno' de um ângulo é definido por:", options: ["Cateto Adjacente / Hipotenusa", "Cateto Oposto / Hipotenusa", "Hipotenusa / Adjacente", "Tangente * Seno"], answer: "Cateto Adjacente / Hipotenusa", explanation: "Definição básica de Cosseno.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A 'Tangente' de um ângulo é a razão entre:", options: ["Cateto Oposto / Cateto Adjacente", "Seno + Cosseno", "Hipotenusa / Cateto Oposto", "Um / Seno"], answer: "Cateto Oposto / Cateto Adjacente", explanation: "Também pode ser definida como Seno / Cosseno.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o valor do Seno de 30°?", options: ["1/2 (0,5)", "√3/2", "1", "0"], answer: "1/2 (0,5)", explanation: "Seno de 30° é um valor notável.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A Hipotenusa é sempre o lado que fica:", options: ["Oposto ao ângulo de 90°", "Entre os dois catetos", "Posicionado na horizontal", "O lado mais curto do triângulo"], answer: "Oposto ao ângulo de 90°", explanation: "É sempre o maior lado do triângulo retângulo.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Quanto vale o Cosseno de 60°?", options: ["1/2 (0,5)", "√2/2", "√3/2", "1"], answer: "1/2 (0,5)", explanation: "O cosseno de 60° é igual ao seno de 30°.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que é um 'Triângulo Pitagórico'?", options: ["Um triângulo cujos lados são números inteiros e obedecem a a² = b² + c²", "Qualquer triângulo com ângulos iguais", "Um triângulo desenhado por Pitágoras", "Um círculo com três pontas"], answer: "Um triângulo cujos lados são números inteiros e obedecem a a² = b² + c²", explanation: "Exemplo clássico: 3, 4 e 5.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A Tangente de 45° é igual a:", options: ["1", "0", "√3", "Infinita"], answer: "1", explanation: "Num triângulo de 45°, os catetos são iguais, logo a razão é 1.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A soma dos quadrados dos catetos é igual ao quadrado da hipotenusa. Esse é o:", options: ["Teorema de Pitágoras", "Teorema de Tales", "Lei dos Senos", "Fórmula de Bhaskara"], answer: "Teorema de Pitágoras", explanation: "Base de toda a trigonometria retilínea.", skill: "Trigonometria" },

  // 9º Matemática - Geometria Espacial (10)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Quais são as três dimensões estudadas na Geometria Espacial?", options: ["Comprimento, Largura e Profundidade (Altura)", "Apenas largura e cor", "Peso, Tempo e Espaço", "Linha, Ponto e Plano apenas"], answer: "Comprimento, Largura e Profundidade (Altura)", explanation: "Estuda objetos no espaço 3D.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual destes sólidos NÃO é um poliedro?", options: ["Esfera", "Cubo", "Pirâmide", "Prisma"], answer: "Esfera", explanation: "Poliedros têm faces planas; a esfera é um corpo redondo.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "A fórmula de Euler para poliedros convexos é:", options: ["V - A + F = 2", "V + A + F = 10", "A + F = V", "V * F = A"], answer: "V - A + F = 2", explanation: "Relaciona vértices, arestas e faces.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Um sólido geométrico que possui duas bases circulares paralelas e iguais é o:", options: ["Cilindro", "Cone", "Esfera", "Cubo"], answer: "Cilindro", explanation: "Pode ser gerado pela rotação de um retângulo.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O ponto mais alto de uma pirâmide ou de um cone é chamado de:", options: ["Vértice (ou Ápice)", "Base", "Aresta lateral", "Face"], answer: "Vértice (ou Ápice)", explanation: "Onde as arestas laterais ou geratrizes se encontram.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O sólido geométrico que possui 6 faces quadradas idênticas é o:", options: ["Cubo (Hexaedro Regular)", "Tetraedro", "Pirâmide", "Cilindro"], answer: "Cubo (Hexaedro Regular)", explanation: "Um dos 5 sólidos de Platão.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que é a 'Planificação' de um sólido?", options: ["Representar a superfície do sólido em um plano 2D", "Transformar o sólido em um círculo", "Medir quanto o sólido pesa", "Desenhar o sólido bem devagar"], answer: "Representar a superfície do sólido em um plano 2D", explanation: "Como 'abrir' uma caixa de papelão.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Um 'Cone' tem como base qual figura geométrica?", options: ["Círculo", "Triângulo", "Quadrado", "Trapézio"], answer: "Círculo", explanation: "Possui uma base circular e um vértice fora dela.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Quantas arestas possui um cubo?", options: ["12", "6", "8", "4"], answer: "12", explanation: "4 na base de baixo, 4 na de cima e 4 ligando as duas.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Um polímero de faces planas, arestas e vértices é um:", options: ["Poliedro", "Círculo", "Ponto", "Vetor"], answer: "Poliedro", explanation: "Poli (muitas) + edro (faces).", skill: "Geometria Espacial" },

  // 9º Matemática - Logaritmos (10)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que o logaritmo busca encontrar?", options: ["O expoente ao qual a base deve ser elevada para resultar em um número", "A raiz quadrada de um número negativo", "A soma de dois números primos", "O valor de pi ao cubo"], answer: "O expoente ao qual a base deve ser elevada para resultar em um número", explanation: "Log_a(b) = x significa a^x = b.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Quanto vale o logaritmo de 100 na base 10 (log 100)?", options: ["2", "10", "1", "100"], answer: "2", explanation: "Pois 10² = 100.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O logaritmo de 1 em qualquer base (positiva e diferente de 1) é sempre:", options: ["0", "1", "A própria base", "Infinito"], answer: "0", explanation: "Qualquer número elevado a 0 é 1.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a propriedade correta: o logaritmo de um produto log(a * b) é igual a:", options: ["log a + log b", "log a * log b", "log a / log b", "(log a)^b"], answer: "log a + log b", explanation: "Logaritmo do produto é a soma dos logaritmos.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Quanto vale log₂ 8?", options: ["3", "4", "2", "6"], answer: "3", explanation: "2³ = 8.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O logaritmo cuja base é o número irracional 'e' (aprox. 2,71) é chamado de:", options: ["Logaritmo Natural (ou Neperiano)", "Logaritmo Comum", "Logaritmo Decimal", "Logaritmo Circular"], answer: "Logaritmo Natural (ou Neperiano)", explanation: "Simbolizado por ln(x).", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "A propriedade log(a / b) é igual a:", options: ["log a - log b", "log a + log b", "log (a-b)", "log a * log b"], answer: "log a - log b", explanation: "Logaritmo do quociente é a diferença dos logaritmos.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O logaritmo de uma potência log(a^n) é igual a:", options: ["n * log a", "log (a * n)", "(log a)^n", "log a / n"], answer: "n * log a", explanation: "O expoente 'tomba' multiplicando o logaritmo.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a base do logaritmo comum (quando a base não está escrita)?", options: ["10", "2", "1", "e"], answer: "10", explanation: "Convenção para logaritmos decimais.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O logaritmo da base na própria base (log_a a) é:", options: ["1", "0", "a", "a²"], answer: "1", explanation: "Pois a¹ = a.", skill: "Logaritmos" },

  // 7º Matemática - Conjuntos (10)
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Como se chama o conjunto que não possui nenhum elemento?", options: ["Conjunto Vazio", "Conjunto Zero", "Conjunto Nulo", "Conjunto Unitário"], answer: "Conjunto Vazio", explanation: "Representado por { } ou Ø.", skill: "Conjuntos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O símbolo '∈' significa:", options: ["Pertence", "Não pertence", "Está contido", "É igual"], answer: "Pertence", explanation: "Usado para relacionar elemento e conjunto.", skill: "Conjuntos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O conjunto dos números Naturais (N) inclui:", options: ["{0, 1, 2, 3...}", "Apenas números negativos", "Apenas frações", "{...-2, -1, 0, 1, 2...}"], answer: "{0, 1, 2, 3...}", explanation: "Números usados para contagem.", skill: "Conjuntos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O que é a 'Interseção' (∩) de dois conjuntos?", options: ["Os elementos que pertencem aos dois conjuntos ao mesmo tempo", "A soma de todos os elementos", "Apenas os elementos do primeiro", "Os elementos que não pertencem a nenhum dos dois"], answer: "Os elementos que pertencem aos dois conjuntos ao mesmo tempo", explanation: "Representa o que há de comum entre eles.", skill: "Conjuntos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O conjunto dos números Inteiros (Z) é formado por:", options: ["Naturais, seus opostos negativos e o zero", "Apenas números positivos", "Apenas números de 1 a 10", "Números decimais infinitos"], answer: "Naturais, seus opostos negativos e o zero", explanation: "Engloba os naturais e os negativos inteiros.", skill: "Conjuntos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "A 'União' (∪) de dois conjuntos A e B resulta em:", options: ["Um novo conjunto com todos os elementos de A e de B", "Apenas os elementos repetidos", "A subtração de B de A", "Um conjunto vazio sempre"], answer: "Um novo conjunto com todos os elementos de A e de B", explanation: "Junta-se tudo sem repetir os elementos comuns.", skill: "Conjuntos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O que significa dizer que A ⊂ B (A está contido em B)?", options: ["Todos os elementos de A também pertencem a B", "B é menor que A", "A e B não têm nada em comum", "A é um número e B é uma cor"], answer: "Todos os elementos de A também pertencem a B", explanation: "Indica que A é um subconjunto de B.", skill: "Conjuntos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Números que podem ser escritos como fração de dois inteiros são os:", options: ["Racionais (Q)", "Irracionais", "Naturais apenas", "Pares"], answer: "Racionais (Q)", explanation: "Q vem de 'Quociente'.", skill: "Conjuntos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual destes é um número Irracional famoso?", options: ["π (Pi)", "1/2", "0", "-5"], answer: "π (Pi)", explanation: "Não pode ser escrito como fração exata de dois inteiros.", skill: "Conjuntos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Um conjunto com apenas um elemento é chamado de:", options: ["Conjunto Unitário", "Conjunto Vazio", "Subconjunto", "Conjunto Global"], answer: "Conjunto Unitário", explanation: "Exemplo: { 5 }.", skill: "Conjuntos" },

  // 9º Matemática - Geral (10)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que estuda a Álgebra?", options: ["Operações matemáticas com números e símbolos (letras)", "Apenas o formato das estrelas", "A história dos números romanos", "Apenas desenhos de triângulos"], answer: "Operações matemáticas com números e símbolos (letras)", explanation: "Generaliza a aritmética.", skill: "Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a utilidade do sistema de coordenadas cartesianas?", options: ["Localizar pontos no plano usando um par ordenado (x, y)", "Medir a temperatura da água", "Contar quanto tempo o sol demora para se pôr", "Pintar quadros abstratos"], answer: "Localizar pontos no plano usando um par ordenado (x, y)", explanation: "Criado por René Descartes.", skill: "Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Um número Real é aquele que:", options: ["Pode ser racional ou irracional", "Só existe na imaginação", "É sempre positivo", "Deve ser sempre um número redondo"], answer: "Pode ser racional ou irracional", explanation: "O conjunto R abrange quase todos os números estudados na escola.", skill: "Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que representa o símbolo '%'?", options: ["Uma divisão por 100", "Uma multiplicação por 10", "Uma raiz quadrada", "O número zero dobrado"], answer: "Uma divisão por 100", explanation: "Porcentagem significa 'por cada cem'.", skill: "Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Na ciência, a 'Notação Científica' serve para:", options: ["Escrever números muito grandes ou muito pequenos de forma simplificada", "Dar nomes difíceis aos cálculos", "Falar sobre química", "Esconder os resultados"], answer: "Escrever números muito grandes ou muito pequenos de forma simplificada", explanation: "Usa potências de base 10 (ex: 3 x 10⁸).", skill: "Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que é 'Probabilidade'?", options: ["O estudo das chances de um evento ocorrer", "O cálculo da área de um círculo", "A soma de todos os números primos", "O peso de um objeto"], answer: "O estudo das chances de um evento ocorrer", explanation: "Vai de 0 (impossível) a 1 ou 100% (certo).", skill: "Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "A palavra 'Geometria' vem do grego e significa:", options: ["Medida da Terra", "Muitos Ângulos", "Contagem de Pedras", "Caminho da Lógica"], answer: "Medida da Terra", explanation: "Geo (Terra) + Metria (Medida).", skill: "Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Em matemática, um 'Axioma' ou 'Postulado' é:", options: ["Uma verdade aceita sem necessidade de demonstração", "Uma mentira descoberta", "O nome de um matemático famoso", "Um tipo de divisão"], answer: "Uma verdade aceita sem necessidade de demonstração", explanation: "Base para a construção de teorias.", skill: "Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que é uma 'Inequação'?", options: ["Uma desigualdade entre expressões (usa <, >, ≤, ≥)", "Uma conta errada", "Uma equação sem x", "Um desenho sem régua"], answer: "Uma desigualdade entre expressões (usa <, >, ≤, ≥)", explanation: "Diferente da equação, que usa o sinal de igual.", skill: "Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "A matemática é muitas vezes chamada de 'Linguagem Universal' porque:", options: ["Suas leis e símbolos são os mesmos em qualquer lugar do mundo", "Todos os países falam o mesmo idioma matemático", "Ela foi inventada no espaço", "Os números são coloridos para crianças de todos os países"], answer: "Suas leis e símbolos são os mesmos em qualquer lugar do mundo", explanation: "Independe da cultura ou idioma falado.", skill: "Geral" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 30 com ${batch.length} questões de Matemática adicionado.`);
