import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 5900;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 28: Injeção de 90 questões de Matemática a partir do ID: ${startId}`);

const batch = [
  // 9º Matemática - Círculo (9)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a diferença entre 'Círculo' e 'Circunferência'?", options: ["Circunferência é a linha (borda) e Círculo é a superfície interna", "São exatamente a mesma coisa", "Círculo é a linha e Circunferência é o preenchimento", "Círculo é 3D e Circunferência é 2D"], answer: "Circunferência é a linha (borda) e Círculo é a superfície interna", explanation: "A circunferência é o contorno; o círculo inclui o interior.", skill: "Círculo" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O 'Raio' de um círculo é definido como:", options: ["A distância do centro até qualquer ponto da circunferência", "A distância entre dois pontos quaisquer da borda", "O dobro do diâmetro", "A área total da figura"], answer: "A distância do centro até qualquer ponto da circunferência", explanation: "O raio é a metade do diâmetro.", skill: "Círculo" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Se o raio de um círculo mede 5 cm, qual o comprimento do seu Diâmetro?", options: ["10 cm", "2,5 cm", "25 cm", "5 cm"], answer: "10 cm", explanation: "Diâmetro = 2 * Raio.", skill: "Círculo" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a fórmula para calcular o COMPRIMENTO de uma circunferência?", options: ["C = 2 * π * r", "A = π * r²", "C = d²", "C = π + r"], answer: "C = 2 * π * r", explanation: "O comprimento é proporcional ao raio e ao número pi.", skill: "Círculo" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O valor aproximado da constante irracional π (Pi) é:", options: ["3,14", "2,71", "1,41", "0,5"], answer: "3,14", explanation: "Pi é a razão entre o comprimento e o diâmetro de qualquer círculo.", skill: "Círculo" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Uma reta que toca a circunferência em apenas um único ponto é chamada de:", options: ["Reta Tangente", "Reta Secante", "Corda", "Diâmetro"], answer: "Reta Tangente", explanation: "A tangente é sempre perpendicular ao raio no ponto de contato.", skill: "Círculo" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Uma 'Corda' em um círculo é um segmento de reta que:", options: ["Liga dois pontos quaisquer da circunferência", "Passa obrigatoriamente pelo centro", "Fica do lado de fora do círculo", "Mede sempre o mesmo que o raio"], answer: "Liga dois pontos quaisquer da circunferência", explanation: "O diâmetro é a maior corda possível de um círculo.", skill: "Círculo" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que é um 'Setor Circular'?", options: ["Uma fatia do círculo (como uma fatia de pizza)", "A borda completa do círculo", "O ponto central exato", "Um quadrado dentro do círculo"], answer: "Uma fatia do círculo (como uma fatia de pizza)", explanation: "É a parte do círculo limitada por dois raios e um arco.", skill: "Círculo" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Se aumentarmos o raio de um círculo em 2 vezes, sua ÁREA aumentará em:", options: ["4 vezes", "2 vezes", "8 vezes", "Ficará igual"], answer: "4 vezes", explanation: "Como a área depende do raio ao quadrado (r²), o aumento é quadrático (2² = 4).", skill: "Círculo" },

  // 6º Matemática - Tabuada (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de 7 x 8?", options: ["56", "54", "64", "49"], answer: "56", explanation: "Fato básico da tabuada do 7 e do 8.", skill: "Tabuada" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual número multiplicado por 9 resulta em 81?", options: ["9", "8", "7", "10"], answer: "9", explanation: "9 * 9 = 81.", skill: "Tabuada" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quanto é 6 x 7?", options: ["42", "36", "48", "45"], answer: "42", explanation: "6 * 7 = 42.", skill: "Tabuada" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o produto de 4 x 9?", options: ["36", "32", "40", "28"], answer: "36", explanation: "4 * 9 = 36.", skill: "Tabuada" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Multiplicar um número por 10 é o mesmo que:", options: ["Acrescentar um zero à direita (se for inteiro)", "Dividir por 2 e somar 5", "Mudar o número para negativo", "Dobrar o número 10 vezes"], answer: "Acrescentar um zero à direita (se for inteiro)", explanation: "Regra prática do sistema decimal.", skill: "Tabuada" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de 8 x 9?", options: ["72", "64", "81", "73"], answer: "72", explanation: "8 * 9 = 72.", skill: "Tabuada" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Zero multiplicado por qualquer número resulta sempre em:", options: ["0", "O próprio número", "1", "Infinito"], answer: "0", explanation: "Propriedade do elemento nulo da multiplicação.", skill: "Tabuada" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o valor de 6 x 8?", options: ["48", "42", "54", "56"], answer: "48", explanation: "6 * 8 = 48.", skill: "Tabuada" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Em '5 x 4 = 20', os números 5 e 4 são chamados de:", options: ["Fatores", "Lados", "Quocientes", "Restos"], answer: "Fatores", explanation: "Fatos da multiplicação: Fator * Fator = Produto.", skill: "Tabuada" },

  // 7º Matemática - Raiz (9)
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual a raiz quadrada de 144?", options: ["12", "14", "10", "24"], answer: "12", explanation: "12 * 12 = 144.", skill: "Raiz" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "A raiz quadrada de um número negativo no conjunto dos números Reais:", options: ["Não existe", "É sempre positiva", "É zero", "É o dobro do número"], answer: "Não existe", explanation: "Não há número real que elevado ao quadrado dê resultado negativo.", skill: "Raiz" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor da √81?", options: ["9", "8", "7", "18"], answer: "9", explanation: "9 * 9 = 81.", skill: "Raiz" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "A operação inversa da radiciação (extrair raiz) é a:", options: ["Potenciação", "Divisão", "Multiplicação", "Subtração"], answer: "Potenciação", explanation: "Raiz quadrada inverte o quadrado de um número.", skill: "Raiz" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor aproximado da √2?", options: ["1,41", "1,73", "1,10", "2,00"], answer: "1,41", explanation: "A raiz de 2 é um número irracional muito comum.", skill: "Raiz" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O número que fica 'dentro' do símbolo da raiz (√) é chamado de:", options: ["Radicando", "Índice", "Coeficiente", "Potência"], answer: "Radicando", explanation: "O símbolo é o radical e o número interno é o radicando.", skill: "Raiz" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual a √400?", options: ["20", "40", "100", "2"], answer: "20", explanation: "20 * 20 = 400.", skill: "Raiz" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Um 'Quadrado Perfeito' é um número cuja raiz quadrada é:", options: ["Um número inteiro", "Um número decimal infinito", "Sempre ímpar", "O número 2"], answer: "Um número inteiro", explanation: "Ex: 1, 4, 9, 16, 25...", skill: "Raiz" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor de √1 + √9?", options: ["4", "10", "3", "2"], answer: "4", explanation: "1 + 3 = 4.", skill: "Raiz" },

  // 9º Matemática - Radiciação (9)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Como podemos escrever a √x em forma de potência com expoente fracionário?", options: ["x^(1/2)", "x²", "x / 2", "2x"], answer: "x^(1/2)", explanation: "O índice da raiz torna-se o denominador do expoente.", skill: "Radiciação" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Simplificando a expressão √50, obtemos:", options: ["5√2", "2√5", "25√2", "10√5"], answer: "5√2", explanation: "√50 = √(25 * 2) = 5√2.", skill: "Radiciação" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de (√3) * (√3)?", options: ["3", "√6", "9", "√9 (que é 3)"], answer: "3", explanation: "Multiplicar uma raiz por ela mesma elimina o radical.", skill: "Radiciação" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O processo de eliminar a raiz do denominador de uma fração é chamado de:", options: ["Racionalização de Denominadores", "Fatoração", "Simplificação de Potência", "Divisão de Radicais"], answer: "Racionalização de Denominadores", explanation: "Multiplica-se numerador e denominador pelo fator racionalizante.", skill: "Radiciação" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o valor da raiz cúbica de 27 (∛27)?", options: ["3", "9", "2", "6"], answer: "3", explanation: "3 * 3 * 3 = 27.", skill: "Radiciação" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Resolva: 2√x = 10. Qual o valor de x?", options: ["25", "5", "100", "20"], answer: "25", explanation: "√x = 5 => x = 5² = 25.", skill: "Radiciação" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a propriedade correta: √(a * b) é igual a:", options: ["(√a) * (√b)", "√a + √b", "a * √b", "(a * b)²"], answer: "(√a) * (√b)", explanation: "A raiz do produto é o produto das raízes.", skill: "Radiciação" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que acontece ao elevar uma raiz quadrada ao quadrado? Ex: (√7)²", options: ["O resultado é o próprio radicando (7)", "O resultado é 49", "O resultado é √14", "O número torna-se negativo"], answer: "O resultado é o próprio radicando (7)", explanation: "Operações inversas se anulam.", skill: "Radiciação" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o valor de ∛(-64)?", options: ["-4", "+4", "Não existe em R", "-8"], answer: "-4", explanation: "Raízes de índice ímpar admitem radicandos negativos. (-4)³ = -64.", skill: "Radiciação" },

  // 8º Matemática - Soma (9)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Na soma de números com sinais diferentes, a regra correta é:", options: ["Subtrair os valores absolutos e manter o sinal do maior", "Somar os números e manter o sinal de menos sempre", "O resultado é sempre positivo", "Multiplicar os sinais e somar"], answer: "Subtrair os valores absolutos e manter o sinal do maior", explanation: "Ex: -10 + 15 = +5.", skill: "Soma" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de (-12) + (-8)?", options: ["-20", "+20", "-4", "+4"], answer: "-20", explanation: "Soma de negativos resulta em um valor mais negativo.", skill: "Soma" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O elemento neutro da ADIÇÃO é o número:", options: ["0", "1", "-1", "10"], answer: "0", explanation: "Qualquer número somado com 0 permanece inalterado.", skill: "Soma" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A propriedade associativa da soma diz que:", options: ["(a + b) + c = a + (b + c)", "a + b = b + a", "a + 0 = a", "a - b = b - a"], answer: "(a + b) + c = a + (b + c)", explanation: "A ordem dos agrupamentos não altera o resultado final da soma.", skill: "Soma" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual a soma de três números consecutivos sabendo que o menor é 10?", options: ["33", "30", "13", "36"], answer: "33", explanation: "10 + 11 + 12 = 33.", skill: "Soma" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Quanto é 1,5 + 2,75?", options: ["4,25", "3,25", "4,50", "3,80"], answer: "4,25", explanation: "1,50 + 2,75 = 4,25.", skill: "Soma" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A soma de um número com seu oposto (ex: 7 + (-7)) é sempre:", options: ["0", "1", "14", "-14"], answer: "0", explanation: "Números opostos se anulam na soma.", skill: "Soma" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que é 'Comutar' em uma operação de soma?", options: ["Trocar a ordem das parcelas sem mudar o resultado (a+b = b+a)", "Mudar o sinal dos números", "Dividir as parcelas ao meio", "Transformar soma em conta de vezes"], answer: "Trocar a ordem das parcelas sem mudar o resultado (a+b = b+a)", explanation: "Propriedade Comutativa.", skill: "Soma" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o resultado da soma de todos os ângulos internos de um quadrilátero?", options: ["360°", "180°", "90°", "540°"], answer: "360°", explanation: "Um quadrilátero pode ser dividido em dois triângulos (180+180).", skill: "Soma" },

  // 7º Matemática - Regra de Três (9)
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O que é 'Regra de Três Simples'?", options: ["Uma técnica para achar um quarto valor proporcional conhecendo três", "Uma regra sobre como somar três números iguais", "O nome de um triângulo com três lados", "Uma divisão por três feita três vezes"], answer: "Uma técnica para achar um quarto valor proporcional conhecendo três", explanation: "Baseia-se na igualdade entre razões.", skill: "Regra de Três" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Se 2 pães custam R$ 1,00, quanto custarão 10 pães?", options: ["R$ 5,00", "R$ 4,00", "R$ 10,00", "R$ 2,00"], answer: "R$ 5,00", explanation: "Proporção direta: 5 vezes mais pães, 5 vezes mais preço.", skill: "Regra de Três" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Grandezas 'Diretamente Proporcionais' são aquelas que:", options: ["Quando uma aumenta, a outra aumenta na mesma proporção", "Quando uma aumenta, a outra diminui", "Sempre resultam em zero", "Não possuem relação"], answer: "Grandezas 'Diretamente Proporcionais' são aquelas que:", explanation: "Ex: Velocidade constante -> mais tempo, mais distância percorrida.", skill: "Regra de Três" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Se uma máquina produz 50 peças em 2 horas, em quanto tempo produzirá 150 peças?", options: ["6 horas", "4 horas", "3 horas", "10 horas"], answer: "6 horas", explanation: "Produção triplicou, tempo triplica: 2 * 3 = 6.", skill: "Regra de Três" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O que são grandezas 'Inversamente Proporcionais'?", options: ["Quando uma aumenta, a outra diminui na mesma proporção", "Quando as duas aumentam juntas", "Quando os números são negativos", "Quando a conta não dá certo"], answer: "Quando uma aumenta, a outra diminui na mesma proporção", explanation: "Ex: Mais operários, menos tempo para terminar a obra.", skill: "Regra de Três" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Para resolver uma regra de três direta, multiplicamos os valores em:", options: ["Cruz (X)", "Linha Reta", "Círculo", "Não multiplicamos"], answer: "Cruz (X)", explanation: "Propriedade fundamental das proporções (meios por extremos).", skill: "Regra de Três" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Um carro percorre 100 km com 10 litros. Quantos km ele fará com 25 litros?", options: ["250 km", "200 km", "150 km", "300 km"], answer: "250 km", explanation: "Razão: 10 km por litro. 25 * 10 = 250.", skill: "Regra de Três" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Se 4 pintores pintam um muro em 12 horas, 8 pintores (trabalhando igual) levarão:", options: ["6 horas", "24 horas", "12 horas", "10 horas"], answer: "6 horas", explanation: "Proporção inversa: dobrou os pintores, divide o tempo por 2.", skill: "Regra de Três" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Na regra de três, a primeira coisa a fazer é:", options: ["Identificar as grandezas e conferir se são diretas ou inversas", "Multiplicar todos os números logo", "Somar os valores conhecidos", "Escolher o maior número"], answer: "Identificar as grandezas e conferir se são diretas ou inversas", explanation: "A lógica da montagem depende dessa classificação.", skill: "Regra de Três" },

  // 7º Matemática - Ângulos (9)
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "A unidade de medida padrão para ângulos é o:", options: ["Grau (°)", "Metro", "Quilo", "Segundo"], answer: "Grau (°)", explanation: "Um círculo completo tem 360 graus.", skill: "Ângulos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Como se chama um ângulo que mede exatamente 90 graus?", options: ["Ângulo Reta", "Ângulo Agudo", "Ângulo Obtuso", "Ângulo Raso"], answer: "Ângulo Reta", explanation: "Representado muitas vezes por um quadradinho com um ponto.", skill: "Ângulos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Ângulos 'Complementares' são dois ângulos que somados resultam em:", options: ["90°", "180°", "360°", "0°"], answer: "90°", explanation: "Eles completam um ângulo reto.", skill: "Ângulos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Um ângulo 'Obtuso' é aquele que mede:", options: ["Entre 90° e 180°", "Menos que 90°", "Exatamente 180°", "Mais que 360°"], answer: "Entre 90° e 180°", explanation: "É um ângulo 'aberto'.", skill: "Ângulos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Dois ângulos que somados resultam em 180° são chamados de:", options: ["Suplementares", "Complementares", "Adjacentes", "Opostos"], answer: "Suplementares", explanation: "Eles formam uma linha reta (meia volta).", skill: "Ângulos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O instrumento utilizado para medir e desenhar ângulos é o:", options: ["Transferidor", "Compasso", "Régua", "Esquadro"], answer: "Transferidor", explanation: "Existem de 180° e 360°.", skill: "Ângulos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Um ângulo de 180 graus também é conhecido como ângulo:", options: ["Raso", "Completo", "Nulo", "Agudo"], answer: "Raso", explanation: "Representa meia volta completa.", skill: "Ângulos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "A semirreta que divide um ângulo em duas partes exatamente iguais é a:", options: ["Bissetriz", "Mediatriz", "Hipotenusa", "Corda"], answer: "Bissetriz", explanation: "Se o ângulo era 60°, a bissetriz cria dois de 30°.", skill: "Ângulos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O que são ângulos 'OPV' (Opostos Pelo Vértice)?", options: ["Ângulos formados por duas retas que se cruzam, tendo medidas iguais", "Ângulos que moram longe um do outro", "Ângulos que somados dão 360°", "Ângulos de cores invertidas"], answer: "Ângulos formados por duas retas que se cruzam, tendo medidas iguais", explanation: "Eles compartilham o mesmo vértice e são congruentes.", skill: "Ângulos" },

  // 6º Matemática - Divisão (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Na operação 20 / 4 = 5, o número 5 é chamado de:", options: ["Quociente", "Divisor", "Dividendo", "Resto"], answer: "Quociente", explanation: "Quociente é o resultado da divisão.", skill: "Divisão" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de 156 / 12?", options: ["13", "12", "14", "15"], answer: "13", explanation: "12 * 10 = 120; sobra 36. 12 * 3 = 36. 10 + 3 = 13.", skill: "Divisão" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que acontece quando dividimos um número por ZERO?", options: ["A operação não é possível (inexistente na matemática)", "O resultado é sempre zero", "O resultado é 1", "O número fica igual"], answer: "A operação não é possível (inexistente na matemática)", explanation: "A divisão por zero não é definida.", skill: "Divisão" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O 'Resto' em uma divisão exata deve ser sempre:", options: ["0", "1", "O próprio divisor", "Menor que zero"], answer: "0", explanation: "Exata significa que não sobrou nada.", skill: "Divisão" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Como chamamos o número que será dividido?", options: ["Dividendo", "Quociente", "Divisor", "Fator"], answer: "Dividendo", explanation: "Dividendo / Divisor = Quociente.", skill: "Divisão" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o quociente de 1000 / 8?", options: ["125", "250", "100", "80"], answer: "125", explanation: "1000 / 2 = 500 / 2 = 250 / 2 = 125.", skill: "Divisão" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Se em uma divisão o dividendo é 50 e o divisor é 6, o resto será:", options: ["2", "8", "1", "0"], answer: "2", explanation: "6 * 8 = 48. 50 - 48 = 2.", skill: "Divisão" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Para conferir se uma divisão está correta, usamos a fórmula:", options: ["(Quociente * Divisor) + Resto = Dividendo", "Quociente + Divisor = Dividendo", "Dividendo * Resto = Quociente", "Todos somados devem dar 100"], answer: "(Quociente * Divisor) + Resto = Dividendo", explanation: "É a prova real da divisão.", skill: "Divisão" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quanto é 0,6 dividido por 2?", options: ["0,3", "0,03", "3,0", "0,6"], answer: "0,3", explanation: "Metade de 6 décimos são 3 décimos.", skill: "Divisão" },

  // 7º Matemática - Polígonos (9)
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Um polígono é chamado de 'Côncavo' quando:", options: ["Possui pelo menos um ângulo interno maior que 180°", "Todos os ângulos são iguais", "Ele tem o formato de uma bola", "Todos os lados são retos"], answer: "Possui pelo menos um ângulo interno maior que 180°", explanation: "Um segmento que liga dois pontos internos pode passar por fora da figura.", skill: "Polígonos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Como se chama o polígono de 12 lados?", options: ["Dodecágono", "Decágono", "Undecágono", "Icoságono"], answer: "Dodecágono", explanation: "Do (2) + Deca (10).", skill: "Polígonos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O que são 'Diagonais' de um polígono?", options: ["Segmentos de reta que ligam dois vértices não vizinhos", "As linhas que formam a borda", "Os ângulos de fora", "A cor do desenho"], answer: "Segmentos de reta que ligam dois vértices não vizinhos", explanation: "O triângulo é o único polígono que não possui diagonais.", skill: "Polígonos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "A soma dos ângulos internos de um PENTÁGONO regular é:", options: ["540°", "360°", "180°", "720°"], answer: "540°", explanation: "Fórmula: (n - 2) * 180. (5 - 2) * 180 = 3 * 180 = 540.", skill: "Polígonos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual a diferença entre um Polígono e um Poliedro?", options: ["Polígono é plano (2D) e Poliedro é sólido (3D)", "São sinônimos", "Polígono tem lados curvos", "Poliedro só pode ter 4 lados"], answer: "Polígono é plano (2D) e Poliedro é sólido (3D)", explanation: "O poliedro é formado por várias faces que são polígonos.", skill: "Polígonos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Um polígono de 20 lados é um:", options: ["Icoságono", "Dodecágono", "Octógono", "Pentágono"], answer: "Icoságono", explanation: "Icosa refere-se a vinte.", skill: "Polígonos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O que significa 'Polígono Regular'?", options: ["Equilátero (lados iguais) e Equiângulo (ângulos iguais)", "Que ele é desenhado sempre com régua", "Que ele tem número par de lados", "Que ele é muito comum na escola"], answer: "Equilátero (lados iguais) e Equiângulo (ângulos iguais)", explanation: "Possui simetria total.", skill: "Polígonos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o polígono que possui o número de lados igual ao número de diagonais?", options: ["Pentágono", "Quadrado", "Triângulo", "Hexágono"], answer: "Pentágono", explanation: "Tem 5 lados e 5 diagonais.", skill: "Polígonos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Polígonos que possuem a mesma forma mas tamanhos diferentes são chamados de:", options: ["Semelhantes", "Igualados", "Unidos", "Congruentes"], answer: "Semelhantes", explanation: "Seus ângulos são iguais e os lados são proporcionais.", skill: "Polígonos" },

  // 8º Matemática - Ângulos (9)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Ângulos 'Alternos Internos' formados por retas paralelas cortadas por uma transversal são:", options: ["Iguais (Congruentes)", "Suplementares (somam 180°)", "Complementares", "Diferentes"], answer: "Iguais (Congruentes)", explanation: "Estão em lados opostos da transversal, mas 'dentro' das paralelas.", skill: "Ângulos" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Se dois ângulos são opositores pelo vértice (OPV) e um mede 75°, quanto mede o outro?", options: ["75°", "105°", "180°", "150°"], answer: "75°", explanation: "Ângulos OPV são sempre iguais.", skill: "Ângulos" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A soma dos ângulos EXTERNOS de qualquer polígono convexo é sempre:", options: ["360°", "180°", "Depende do número de lados", "90°"], answer: "360°", explanation: "Independente se é triângulo ou decágono, a soma externa é constante.", skill: "Ângulos" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Em um triângulo isósceles, os ângulos da base são sempre:", options: ["Iguais", "Diferentes", "De 90 graus", "De 180 graus"], answer: "Iguais", explanation: "Lados iguais se opõem a ângulos iguais.", skill: "Ângulos" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o valor de cada ângulo interno de um HEXÁGONO regular?", options: ["120°", "108°", "60°", "90°"], answer: "120°", explanation: "Soma = 720. 720 / 6 = 120.", skill: "Ângulos" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Ângulos 'Colaterais Internos' (mesmo lado da transversal e dentro das paralelas) somam:", options: ["180°", "90°", "360°", "0°"], answer: "180°", explanation: "São suplementares.", skill: "Ângulos" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que é um 'Ângulo Central' em um polígono regular?", options: ["360° dividido pelo número de lados (n)", "A soma de todos os ângulos", "O ângulo da base", "O ângulo do vértice"], answer: "360° dividido pelo número de lados (n)", explanation: "É o ângulo com vértice no centro do polígono.", skill: "Ângulos" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Se um ângulo mede 40°, qual o seu Suplemento?", options: ["140°", "50°", "320°", "60°"], answer: "140°", explanation: "180 - 40 = 140.", skill: "Ângulos" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A soma dos ângulos internos de um polígono de 'n' lados é dada pela fórmula:", options: ["(n - 2) * 180", "n * 180", "(n + 2) * 90", "n * 360"], answer: "(n - 2) * 180", explanation: "Determina o total de graus acumulados no interior.", skill: "Ângulos" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 28 com ${batch.length} questões de Matemática adicionado.`);
