import fs from 'fs';
const filePath = 'questions.js';
function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const ids = content.match(/id:\s*(\d+)/g).map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}
const startId = getNextId();
console.log(`Sprint 8 a partir do ID: ${startId}`);
const batch = [
  // MATEMÁTICA (6º) - Geometria Básica (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quantos lados tem um triângulo?", options: ["2", "3", "4", "5"], answer: "3", explanation: "Tri = três.", skill: "Geometria Básica" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um retângulo possui quantos ângulos retos (90°)?", options: ["2", "3", "4", "5"], answer: "4", explanation: "Todos os 4 ângulos medem 90°.", skill: "Geometria Básica" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual figura geométrica possui todos os lados iguais e 4 ângulos retos?", options: ["Triângulo", "Círculo", "Quadrado", "Trapézio"], answer: "Quadrado", explanation: "Lados iguais e ângulos de 90°.", skill: "Geometria Básica" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "A distância ao redor de uma figura plana é chamada de:", options: ["Área", "Perímetro", "Volume", "Diagonal"], answer: "Perímetro", explanation: "É a soma de todos os lados.", skill: "Geometria Básica" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O círculo é formado por todos os pontos que estão à mesma distância do:", options: ["Vértice", "Lado", "Centro", "Ângulo"], answer: "Centro", explanation: "Essa distância constante é o raio.", skill: "Geometria Básica" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Retas que nunca se encontram são chamadas de:", options: ["Perpendiculares", "Secantes", "Paralelas", "Coincidentes"], answer: "Paralelas", explanation: "Mantêm sempre a mesma distância entre si.", skill: "Geometria Básica" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "A soma dos ângulos internos de qualquer triângulo é:", options: ["90°", "180°", "270°", "360°"], answer: "180°", explanation: "Propriedade fundamental dos triângulos.", skill: "Geometria Básica" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual é o nome do segmento que liga o centro do círculo até a borda?", options: ["Diâmetro", "Corda", "Raio", "Arco"], answer: "Raio", explanation: "O diâmetro é o dobro do raio.", skill: "Geometria Básica" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um hexágono possui quantos lados?", options: ["4", "5", "6", "8"], answer: "6", explanation: "Hexa = seis.", skill: "Geometria Básica" },

  // MATEMÁTICA (8º) - Equações de 1º Grau (9)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Na equação x + 5 = 12, o valor de x é:", options: ["5", "7", "12", "17"], answer: "7", explanation: "x = 12 - 5 = 7.", skill: "Equações de 1º Grau" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Na equação 2x = 10, quanto vale x?", options: ["2", "5", "10", "20"], answer: "5", explanation: "x = 10/2 = 5.", skill: "Equações de 1º Grau" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o valor de x em 3x - 6 = 0?", options: ["0", "2", "3", "6"], answer: "2", explanation: "3x = 6, x = 2.", skill: "Equações de 1º Grau" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Na equação x/4 = 3, o valor de x é:", options: ["3", "4", "7", "12"], answer: "12", explanation: "x = 3 x 4 = 12.", skill: "Equações de 1º Grau" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Se 5x + 10 = 35, quanto vale x?", options: ["3", "5", "7", "10"], answer: "5", explanation: "5x = 25, x = 5.", skill: "Equações de 1º Grau" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual a raiz da equação 4x - 8 = 0?", options: ["0", "2", "4", "8"], answer: "2", explanation: "4x = 8, x = 2.", skill: "Equações de 1º Grau" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Em uma equação, o que fazemos para isolar a incógnita?", options: ["Somamos dos dois lados", "Operações inversas dos dois lados", "Ignoramos os números", "Multiplicamos só de um lado"], answer: "Operações inversas dos dois lados", explanation: "Princípio da equivalência.", skill: "Equações de 1º Grau" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Na equação x - 9 = -3, o valor de x é:", options: ["-12", "-6", "6", "12"], answer: "6", explanation: "x = -3 + 9 = 6.", skill: "Equações de 1º Grau" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Uma equação do 1º grau possui a incógnita com expoente:", options: ["0", "1", "2", "3"], answer: "1", explanation: "É por isso que se chama equação de primeiro grau.", skill: "Equações de 1º Grau" },

  // PORTUGUÊS (8º) - Concordância Verbal (9)
  { grade: "8º", discipline: "Português", type: "multiple", text: "Na frase 'Os alunos estudam bastante', o verbo concorda com:", options: ["O advérbio", "O sujeito 'Os alunos'", "O predicado", "O objeto"], answer: "O sujeito 'Os alunos'", explanation: "Concordância verbal: verbo concorda com o sujeito.", skill: "Concordância Verbal" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Complete corretamente: 'Faz dez anos que não ___ aqui.'", options: ["vou", "vamos", "vai", "venho"], answer: "venho", explanation: "Sujeito oculto 'eu', verbo na 1ª pessoa.", skill: "Concordância Verbal" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Em 'Existem muitas razões para estudar', o verbo 'existem' está no plural porque:", options: ["O verbo é impessoal", "O sujeito 'razões' é plural", "É uma preferência do autor", "Está no infinitivo"], answer: "O sujeito 'razões' é plural", explanation: "O verbo 'existir' é pessoal e concorda com o sujeito.", skill: "Concordância Verbal" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Qual frase apresenta ERRO de concordância verbal?", options: ["Os meninos brincam no parque.", "Eu e ela vamos ao cinema.", "Tu vai ao mercado.", "Nós estudamos para a prova."], answer: "Tu vai ao mercado.", explanation: "O correto seria 'Tu vais ao mercado'.", skill: "Concordância Verbal" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "O verbo 'haver' no sentido de 'existir' fica sempre na 3ª pessoa do:", options: ["Plural", "Singular", "Infinitivo", "Gerúndio"], answer: "Singular", explanation: "Verbo impessoal: 'Há muitas pessoas' (e não 'Hão').", skill: "Concordância Verbal" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Na frase 'Chegaram as encomendas', o sujeito é:", options: ["Chegaram", "As", "As encomendas", "Não há sujeito"], answer: "As encomendas", explanation: "Sujeito posposto ao verbo.", skill: "Concordância Verbal" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Complete: 'A maioria dos alunos ___ na prova.'", options: ["passou/passaram (ambas corretas)", "passaram apenas", "passou apenas", "passarão"], answer: "passou/passaram (ambas corretas)", explanation: "Com expressões partitivas, ambas as concordâncias são aceitas.", skill: "Concordância Verbal" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Em 'Eu e meus amigos fomos ao parque', o verbo está na:", options: ["1ª pessoa do singular", "1ª pessoa do plural", "3ª pessoa do plural", "2ª pessoa do plural"], answer: "1ª pessoa do plural", explanation: "Eu + outros = nós (1ª pessoa do plural).", skill: "Concordância Verbal" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Quando o sujeito é composto e vem DEPOIS do verbo, este pode concordar com:", options: ["Apenas o sujeito inteiro", "O elemento mais próximo ou com todos", "Sempre no singular", "Sempre no infinitivo"], answer: "O elemento mais próximo ou com todos", explanation: "Regra de concordância atrativa.", skill: "Concordância Verbal" },

  // HISTÓRIA (8º) - Iluminismo (9)
  { grade: "8º", discipline: "História", type: "multiple", text: "O Iluminismo foi um movimento intelectual que valorizava a:", options: ["Fé cega", "Razão e o conhecimento científico", "Obediência ao rei", "Tradição medieval"], answer: "Razão e o conhecimento científico", explanation: "Também conhecido como Século das Luzes.", skill: "Iluminismo" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Qual filósofo iluminista defendeu a separação dos três poderes (Executivo, Legislativo, Judiciário)?", options: ["Voltaire", "Rousseau", "Montesquieu", "Locke"], answer: "Montesquieu", explanation: "Na obra 'O Espírito das Leis'.", skill: "Iluminismo" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Rousseau defendi o conceito de 'Contrato Social', que estabelecia:", options: ["O poder divino dos reis", "Um acordo entre governo e povo para garantir direitos", "A escravidão como natural", "O fim de toda religião"], answer: "Um acordo entre governo e povo para garantir direitos", explanation: "Base da democracia moderna.", skill: "Iluminismo" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Voltaire é lembrado por defender principalmente a:", options: ["Monarquia absolutista", "Liberdade de expressão e tolerância religiosa", "Escravidão legalizada", "Guerra permanente"], answer: "Liberdade de expressão e tolerância religiosa", explanation: "Criticava a Igreja e a intolerância.", skill: "Iluminismo" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A grande obra que compilou o conhecimento humano no Iluminismo foi a:", options: ["Bíblia", "Enciclopédia", "Torá", "Constituição"], answer: "Enciclopédia", explanation: "Organizada por Diderot e D'Alembert.", skill: "Iluminismo" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Em qual século o Iluminismo teve seu auge na Europa?", options: ["Século XV", "Século XVI", "Século XVIII", "Século XX"], answer: "Século XVIII", explanation: "O 'Século das Luzes' (1700s).", skill: "Iluminismo" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O Iluminismo influenciou diretamente qual grande evento político na França?", options: ["Cruzadas", "Revolução Francesa", "Guerra dos Cem Anos", "Queda de Roma"], answer: "Revolução Francesa", explanation: "Ideais de liberdade, igualdade e fraternidade.", skill: "Iluminismo" },
  { grade: "8º", discipline: "História", type: "multiple", text: "John Locke, pensador iluminista inglês, defendia que:", options: ["O rei era Deus", "Todos nascem com direitos naturais (vida, liberdade, propriedade)", "A ciência não era importante", "Só os ricos deveriam estudar"], answer: "Todos nascem com direitos naturais (vida, liberdade, propriedade)", explanation: "Base do liberalismo político.", skill: "Iluminismo" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O Despotismo Esclarecido foi quando monarcas absolutistas:", options: ["Ignoraram totalmente o Iluminismo", "Adotaram algumas ideias iluministas sem abrir mão do poder", "Criaram repúblicas democráticas", "Aboliram todas as leis"], answer: "Adotaram algumas ideias iluministas sem abrir mão do poder", explanation: "Reformas de cima para baixo.", skill: "Iluminismo" },

  // GEOGRAFIA (8º) - América do Sul (9)
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual o maior país da América do Sul em extensão territorial?", options: ["Argentina", "Colômbia", "Brasil", "Peru"], answer: "Brasil", explanation: "O Brasil ocupa quase metade do continente.", skill: "América do Sul" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A Cordilheira dos Andes está localizada na costa:", options: ["Leste da América do Sul", "Oeste da América do Sul", "Norte da África", "Sul da Europa"], answer: "Oeste da América do Sul", explanation: "Maior cadeia montanhosa do mundo.", skill: "América do Sul" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual rio é considerado o maior do mundo em volume de água?", options: ["Nilo", "Mississipi", "Amazonas", "Danúbio"], answer: "Amazonas", explanation: "Drena a maior bacia hidrográfica do planeta.", skill: "América do Sul" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A capital da Argentina é:", options: ["Santiago", "Lima", "Buenos Aires", "Bogotá"], answer: "Buenos Aires", explanation: "Principal centro econômico e cultural argentino.", skill: "América do Sul" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual o único país da América do Sul que tem o Português como língua oficial?", options: ["Argentina", "Uruguai", "Brasil", "Paraguai"], answer: "Brasil", explanation: "Os demais falam majoritariamente espanhol.", skill: "América do Sul" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "O Deserto do Atacama, o mais seco do mundo, fica em qual país?", options: ["Brasil", "Chile", "Bolívia", "Equador"], answer: "Chile", explanation: "Localizado na costa oeste.", skill: "América do Sul" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "Qual destas é a principal atividade econômica na região da Amazônia?", options: ["Indústria pesada", "Extrativismo e agropecuária", "Pesca oceânica", "Mineração de diamantes"], answer: "Extrativismo e agropecuária", explanation: "Inclui madeira, minérios e soja.", skill: "América do Sul" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A linha do Equador cruza quais países da América do Sul?", options: ["Argentina e Chile", "Brasil, Colômbia e Equador", "Uruguai e Paraguai", "Peru e Bolívia"], answer: "Brasil, Colômbia e Equador", explanation: "O Equador leva o nome da linha imaginária.", skill: "América do Sul" },
  { grade: "8º", discipline: "Geografia", type: "multiple", text: "A Bolívia é um país:", options: ["Com grande litoral", "Sem saída para o mar (mediterrâneo)", "Uma ilha", "Localizado na Europa"], answer: "Sem saída para o mar (mediterrâneo)", explanation: "Perdeu seu litoral na Guerra do Pacífico para o Chile.", skill: "América do Sul" }
];

const questionsWithIds = batch.map((q, i) => ({ id: startId + i, ...q }));
const str = questionsWithIds.map(q =>
  `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`
).join(',\n');
const content = fs.readFileSync(filePath, 'utf-8');
fs.writeFileSync(filePath, content.replace(/\s*\];\s*$/, ',\n\n' + str + '\n];\n'), 'utf-8');
console.log(`Sucesso! Sprint 8: ${batch.length} questões adicionadas.`);
