import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 4300;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 11: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 6º Matemática - Frações Equivalentes (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual das frações abaixo é equivalente a 1/2?", options: ["2/4", "1/4", "3/4", "2/2"], answer: "2/4", explanation: "Multiplicando o numerador e o denominador de 1/2 por 2, obtemos 2/4.", skill: "Frações Equivalentes" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Para encontrar uma fração equivalente a 3/5 com denominador 10, por qual número devemos multiplicar o numerador?", options: ["2", "3", "5", "10"], answer: "2", explanation: "Como 5 x 2 = 10, multiplique o numerador por 2: 3 x 2 = 6.", skill: "Frações Equivalentes" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual fração é equivalente a 10/20 após simplificar por 10?", options: ["1/2", "2/2", "5/10", "1/10"], answer: "1/2", explanation: "10÷10=1 e 20÷10=2, resultando em 1/2.", skill: "Frações Equivalentes" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "As frações 2/3 e 6/9 são equivalentes?", options: ["Sim, pois 2x3=6 e 3x3=9", "Não, os números são diferentes", "Apenas se somarmos 4", "Sim, pois 2+4=6"], answer: "Sim, pois 2x3=6 e 3x3=9", explanation: "Frações equivalentes são obtidas multiplicando ou dividindo termos pelo mesmo número.", skill: "Frações Equivalentes" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o valor de 'x' na igualdade 4/8 = x/2?", options: ["1", "2", "4", "0"], answer: "1", explanation: "4/8 simplificado por 4 é 1/2. Logo, x=1.", skill: "Frações Equivalentes" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Se multiplicarmos o numerador de uma fração por 5 e o denominador por 5, a nova fração será:", options: ["Equivalente", "Maior", "Menor", "Inversa"], answer: "Equivalente", explanation: "Multiplicar ambos os termos pelo mesmo número mantém a equivalência.", skill: "Frações Equivalentes" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual fração representa 50% de um inteiro?", options: ["1/2", "1/4", "1/5", "1/10"], answer: "1/2", explanation: "50/100 simplificado é igual a 1/2.", skill: "Frações Equivalentes" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que acontece ao dividirmos o numerador e o denominador por um mesmo divisor comum?", options: ["Simplificamos a fração", "Aumentamos o valor", "Invertemos a fração", "Anulamos a fração"], answer: "Simplificamos a fração", explanation: "Simplificar é encontrar uma fração equivalente com números menores.", skill: "Frações Equivalentes" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "A fração 3/4 é equivalente a qual das opções?", options: ["9/12", "6/10", "4/3", "1/2"], answer: "9/12", explanation: "3x3=9 e 4x3=12, portanto 9/12.", skill: "Frações Equivalentes" },

  // 7º Ciências - Ecossistemas/Biomas (9)
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual bioma brasileiro é conhecido como a maior floresta tropical do mundo?", options: ["Amazônia", "Cerrado", "Caatinga", "Pampas"], answer: "Amazônia", explanation: "A Floresta Amazônica possui a maior biodiversidade e extensão tropical do planeta.", skill: "Ecossistemas/Biomas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O bioma caracterizado por árvores de troncos retorcidos e solos ácidos é o:", options: ["Cerrado", "Mata Atlântica", "Pantanal", "Caatinga"], answer: "Cerrado", explanation: "O Cerrado é a savana brasileira com vegetação adaptada ao solo ácido.", skill: "Ecossistemas/Biomas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual bioma é exclusivamente brasileiro e possui vegetação adaptada à seca?", options: ["Caatinga", "Amazônia", "Pampas", "Mata Atlântica"], answer: "Caatinga", explanation: "A Caatinga ocorre no semiárido e é o único bioma 100% nacional.", skill: "Ecossistemas/Biomas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Um ecossistema é formado pela interação entre:", options: ["Fatores bióticos e abióticos", "Apenas animais", "Apenas plantas", "Solo e pedras apenas"], answer: "Fatores bióticos e abióticos", explanation: "É o conjunto de seres vivos e o ambiente físico em interação.", skill: "Ecossistemas/Biomas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O Pantanal é conhecido mundialmente por ser uma das maiores:", options: ["Planícies alagáveis", "Desertos", "Montanhas", "Geleiras"], answer: "Planícies alagáveis", explanation: "O Pantanal sofre inundações periódicas que moldam sua vida selvagem.", skill: "Ecossistemas/Biomas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual fator abiótico é determinante para a vegetação da Caatinga?", options: ["Escassez de chuvas", "Neve constante", "Excesso de umidade", "Solo vulcânico"], answer: "Escassez de chuvas", explanation: "O clima semiárido define a estrutura das plantas (xerófitas).", skill: "Ecossistemas/Biomas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Onde se localizam os Manguezais na biosfera?", options: ["Zonas costeiras/transição", "Topo de montanhas", "Centro de desertos", "Ambientes glaciais"], answer: "Zonas costeiras/transição", explanation: "O manguezal é um ecossistema de transição entre o mar e a terra.", skill: "Ecossistemas/Biomas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Os Pampas são biomas caracterizados predominantemente por:", options: ["Campos e gramíneas", "Florestas fechadas", "Cactos e espinhos", "Pinheiros"], answer: "Campos e gramíneas", explanation: "Localizado no Sul do Brasil, os Pampas possuem grandes áreas de pastagens naturais.", skill: "Ecossistemas/Biomas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "A Mata Atlântica é um bioma que sofreu grande degradação principalmente devido à:", options: ["Urbanização e ocupação humana", "Tsunamis", "Terremotos", "Migração de aves"], answer: "Urbanização e ocupação humana", explanation: "Por estar no litoral, foi o bioma mais devastado desde a colonização.", skill: "Ecossistemas/Biomas" },

  // 8º Arte - Técnicas Artísticas (9)
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A técnica de pintura que utiliza pigmentos diluídos em água sobre reboco úmido é o:", options: ["Afresco", "Óleo", "Guache", "Aquarela"], answer: "Afresco", explanation: "O afresco é feito sobre a argamassa ainda 'fresca'.", skill: "Técnicas Artísticas" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual técnica utiliza pequenos pedaços de pedra, vidro ou cerâmica para formar uma imagem?", options: ["Mosaico", "Escultura", "Gravura", "Colagem"], answer: "Mosaico", explanation: "O mosaico é uma arte decorativa milenar que organiza tesselas.", skill: "Técnicas Artísticas" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A 'Xilogravura' é uma técnica em que a matriz é feita de:", options: ["Madeira", "Metal", "Pedra", "Plástico"], answer: "Madeira", explanation: "Xilo vem do grego 'xylon', que significa madeira.", skill: "Técnicas Artísticas" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Na escultura, a técnica de retirar material de um bloco (como mármore) chama-se:", options: ["Entalhe/Esculpir", "Modelagem", "Fundição", "Montagem"], answer: "Entalhe/Esculpir", explanation: "Esculpir é o ato de subtrair para revelar a forma.", skill: "Técnicas Artísticas" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual técnica de pintura utiliza gema de ovo como aglutinante dos pigmentos?", options: ["Têmpera", "Acrílica", "Pastel", "Encaustica"], answer: "Têmpera", explanation: "A têmpera de ovo foi muito usada antes da popularização da tinta a óleo.", skill: "Técnicas Artísticas" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A técnica de 'Chiaroscuro' (Claro-Escuro) serve para:", options: ["Criar volume e profundidade", "Aumentar as cores", "Fazer colagens", "Desenhar linhas retas"], answer: "Criar volume e profundidade", explanation: "O contraste entre luz e sombra gera a ilusão de tridimensionalidade.", skill: "Técnicas Artísticas" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A técnica de obter várias impressões a partir de uma matriz gravada é a:", options: ["Gravura", "Desenho", "Grafismo", "Escultura"], answer: "Gravura", explanation: "A gravura permite a reprodutibilidade da obra de arte.", skill: "Técnicas Artísticas" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual técnica moderna utiliza materiais variados colados sobre uma superfície?", options: ["Colagem", "Pontilhismo", "Estêncil", "Hachura"], answer: "Colagem", explanation: "Popularizada por cubistas, a colagem incorpora recortes de papel, tecido, etc.", skill: "Técnicas Artísticas" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A técnica que utiliza pontos de cores puras para criar uma imagem na retina é o:", options: ["Pontilhismo", "Expressionismo", "Fauvismo", "Surrealismo"], answer: "Pontilhismo", explanation: "Teoria desenvolvida por Seurat e Signac baseada no sistema ótico.", skill: "Técnicas Artísticas" },

  // 9º Arte - Vanguardas Europeias (9)
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Qual vanguarda buscava retratar o movimento, a velocidade e a tecnologia?", options: ["Futurismo", "Cubismo", "Surrealismo", "Dadaísmo"], answer: "Futurismo", explanation: "O Futurismo italiano exaltava a vida moderna e a máquina.", skill: "Vanguardas Europeias" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O artista Pablo Picasso é o principal expoente do:", options: ["Cubismo", "Fauvismo", "Abstracionismo", "Expressionismo"], answer: "Cubismo", explanation: "O Cubismo decompõe as formas em figuras geométricas.", skill: "Vanguardas Europeias" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Qual movimento artístico valorizava o mundo dos sonhos e o inconsciente?", options: ["Surrealismo", "Impressionismo", "Realismo", "Barroco"], answer: "Surrealismo", explanation: "Salvador Dalí é um dos ícones do Surrealismo.", skill: "Vanguardas Europeias" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O Expressionismo focava principalmente em:", options: ["Expressar sentimentos e angústias", "Geometria perfeita", "Retratar apenas a luz", "Cópia fiel da natureza"], answer: "Expressar sentimentos e angústias", explanation: "Privilegiava a subjetividade e a emoção sobre a realidade técnica.", skill: "Vanguardas Europeias" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O Dadaísmo surgiu como um protesto contra:", options: ["A Primeira Guerra Mundial", "O uso de cores", "A fotografia", "O cinema"], answer: "A Primeira Guerra Mundial", explanation: "Era um movimento anti-arte que questionava a lógica e a sociedade.", skill: "Vanguardas Europeias" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O uso de cores vibrantes e arbitrárias, 'selvagens', é marca do:", options: ["Fauvismo", "Cubismo", "Futurismo", "Realismo"], answer: "Fauvismo", explanation: "Fauve significa 'fera' em francês, devido ao uso explosivo da cor.", skill: "Vanguardas Europeias" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A vanguarda que eliminou qualquer representação de objetos reais foi o:", options: ["Abstracionismo", "Naturalismo", "Humanismo", "Romantismo"], answer: "Abstracionismo", explanation: "O abstracionismo foca em linhas, cores e formas puras.", skill: "Vanguardas Europeias" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Quem pintou a famosa obra 'O Grito', precursora do Expressionismo?", options: ["Edvard Munch", "Van Gogh", "Monet", "Kandinsky"], answer: "Edvard Munch", explanation: "Obra icônica que representa o desespero humano.", skill: "Vanguardas Europeias" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O 'Readymade', tirar um objeto comum e colocá-lo no museu, é obra de:", options: ["Marcel Duchamp", "Andy Warhol", "Diego Rivera", "Tarsila do Amaral"], answer: "Marcel Duchamp", explanation: "Duchamp desafiou os conceitos de arte com objetos como o 'Urinol'.", skill: "Vanguardas Europeias" },

  // 8º Ed. Física - Lutas no Brasil (9)
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Qual destas lutas é considerada um patrimônio imaterial da cultura brasileira?", options: ["Capoeira", "Judô", "Caratê", "Esgrima"], answer: "Capoeira", explanation: "A Capoeira mistura luta, dança e musicalidade de origem africana.", skill: "Lutas no Brasil" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "O instrumento musical fundamental que dita o ritmo da Capoeira é o:", options: ["Berimbau", "Pandeiro", "Atabaque", "Agogô"], answer: "Berimbau", explanation: "O berimbau comanda a roda e define a velocidade do jogo.", skill: "Lutas no Brasil" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "O Jiu-Jitsu Brasileiro (BJJ) foi desenvolvido principalmente pela família:", options: ["Gracie", "Silva", "Oliveira", "Santos"], answer: "Gracie", explanation: "Os Gracie adaptaram o judô japonês para focar em finalizações e solo.", skill: "Lutas no Brasil" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A luta 'Huka-Huka' é tradicional de quais povos?", options: ["Povos indígenas do Xingu", "Pescadores do Maranhão", "Vaqueiros do Nordeste", "Inmigrantes alemães"], answer: "Povos indígenas do Xingu", explanation: "Luta ritual praticada durante o Kuarup no Mato Grosso.", skill: "Lutas no Brasil" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Na Capoeira, o local onde os praticantes realizam o jogo chama-se:", options: ["Roda", "Ringue", "Doer", "Tatame"], answer: "Roda", explanation: "A roda simboliza o círculo da comunidade e cooperação.", skill: "Lutas no Brasil" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Uma característica do Jiu-Jitsu Brasileiro é focar em:", options: ["Luta de solo e alavancas", "Chutes altos", "Uso de espadas", "Luta em pé sem contato"], answer: "Luta de solo e alavancas", explanation: "Permite que um oponente menor vença um maior usando técnica.", skill: "Lutas no Brasil" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Quem era o 'Mestre Bimba' na história da Capoeira?", options: ["Criador da Capoeira Regional", "Um luitador de MMA", "Um cantor de samba", "Um político baiano"], answer: "Criador da Capoeira Regional", explanation: "Mestre Bimba sistematizou o ensino da capoeira e a tirou da ilegalidade.", skill: "Lutas no Brasil" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A Luta Marajoara tem origem em qual estado brasileiro?", options: ["Pará", "Bahia", "Rio de Janeiro", "Goiás"], answer: "Pará", explanation: "Originária da Ilha de Marajó, praticada no chão arenoso.", skill: "Lutas no Brasil" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "As lutas na escola devem focar em:", options: ["Respeito e controle do oponente", "Violência gratuita", "Nocautear o colega", "Exclusão dos mais fracos"], answer: "Respeito e controle do oponente", explanation: "O objetivo pedagógico é a autodisciplina e o autoconhecimento.", skill: "Lutas no Brasil" },

  // 7º Ens. Religioso - Tradição Oral (9)
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Como as tradições religiosas eram passadas antes da escrita?", options: ["Através da fala e contação de histórias", "Por e-mail", "Por livros impressos", "Por rádio"], answer: "Através da fala e contação de histórias", explanation: "A oralidade foi a primeira forma de preservar a memória sagrada.", skill: "Tradição Oral" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "A figura do 'Griot' nas culturas africanas é responsável por:", options: ["Preservar e narrar a história e tradições", "Cuidar da agricultura", "Apenas tocar instrumentos", "Vender mercadorias"], answer: "Preservar e narrar a história e tradições", explanation: "Os griots são os guardiões da memória oral e sabedoria.", skill: "Tradição Oral" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Mitos e lendas nas religiões servem para:", options: ["Explicar a origem do mundo e valores", "Enganar as pessoas", "Apenas divertir crianças", "Ganhar dinheiro"], answer: "Explicar a origem do mundo e valores", explanation: "Mitos carregam significados profundos sobre a existência humana.", skill: "Tradição Oral" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Nas culturas indígenas, a transmissão do saber religioso ocorre geralmente:", options: ["Dos mais velhos para os mais novos", "Através de universidades", "Por manuais de instrução", "Apenas em sonhos"], answer: "Dos mais velhos para os mais novos", explanation: "Os anciãos são vistos como bibliotecas vivas de conhecimento.", skill: "Tradição Oral" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Por que a repetição é importante na tradição oral?", options: ["Para garantir que o ensinamento não seja esquecido nem alterado", "Porque as pessoas são surdas", "Para passar o tempo", "Para cansar os alunos"], answer: "Para garantir que o ensinamento não seja esquecido nem alterado", explanation: "A repetição fixa o conteúdo na memória coletiva.", skill: "Tradição Oral" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "A tradição oral pode existir mesmo após a invenção da escrita?", options: ["Sim, elas coexistem e se complementam", "Não, a escrita apaga a oralidade", "Apenas em aldeias isoladas", "Somente em feriados"], answer: "Sim, elas coexistem e se complementam", explanation: "Muitas religiões mantêm ritos orais junto com seus livros sagrados.", skill: "Tradição Oral" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Um exemplo de transmissão oral nos dias de hoje é:", options: ["Contar histórias de antepassados", "Ler um jornal", "Assistir um filme mudo", "Jogar videogame sozinho"], answer: "Contar histórias de antepassados", explanation: "Relatos familiares mantêm viva a identidade e fé.", skill: "Tradição Oral" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Para a tradição oral, a palavra dita é considerada:", options: ["Sagrada e poderosa", "Inútil", "Mentira", "Vento"], answer: "Sagrada e poderosa", explanation: "A palavra empenhada tem valor de lei e conexão com o divino.", skill: "Tradição Oral" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Os rituais de iniciação costumam usar a oralidade para:", options: ["Ensinar segredos e deveres da religião", "Cantar parabéns", "Vender ingressos", "Fazer silêncio"], answer: "Ensinar segredos e deveres da religião", explanation: "Instruções orais preparam o iniciado para sua nova fase.", skill: "Tradição Oral" },

  // 8º Ens. Religioso - Ética e Dignidade (9)
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "O conceito de dignidade humana diz que todo ser humano:", options: ["Tem valor intrínseco e merece respeito", "Só tem valor se for rico", "Não tem direitos", "Depende da religião para ter valor"], answer: "Tem valor intrínseco e merece respeito", explanation: "A dignidade é um direito fundamental de todos, sem exceção.", skill: "Ética e Dignidade" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Ética nas religiões geralmente se refere a:", options: ["Como devemos agir corretamente com o próximo", "Como ganhar prêmios", "Quais roupas usar", "Apenas fazer orações"], answer: "Como devemos agir corretamente com o próximo", explanation: "Ética é o conjunto de princípios que guiam a conduta humana.", skill: "Ética e Dignidade" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Regra de Ouro' presente em quase todas as religiões diz:", options: ["Não faça aos outros o que não quer para você", "Quem tem ouro manda", "Ouro é para o templo", "Primeiro eu, depois os outros"], answer: "Não faça aos outros o que não quer para você", explanation: "É o princípio da reciprocidade e empatia universal.", skill: "Ética e Dignidade" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Respeitar a liberdade religiosa do outro é um ato de:", options: ["Ética e cidadania", "Falte de fé", "Medo", "Ignorância"], answer: "Ética e cidadania", explanation: "Reconhecer o direito do outro de crer ou não crer é base da paz social.", skill: "Ética e Dignidade" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Quando ajudamos alguém em dificuldade, estamos praticando o valor da:", options: ["Solidariedade", "Inveja", "Preguiça", "Ganância"], answer: "Solidariedade", explanation: "Solidariedade é a união de esforços e sentimentos para o bem comum.", skill: "Ética e Dignidade" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A justiça social, defendida por muitos grupos religiosos, busca:", options: ["Reduzir as desigualdades e garantir direitos", "Punir todos os pecadores", "Aumentar os impostos", "Proibir outras festas"], answer: "Reduzir as desigualdades e garantir direitos", explanation: "Justiça social visa o bem-estar coletivo e igualdade de oportunidades.", skill: "Ética e Dignidade" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A palavra 'Alteridade' significa:", options: ["Reconhecer e respeitar o 'outro' como diferente", "Ser igual a todo mundo", "Pensar apenas em si", "Mudar de religião todo dia"], answer: "Reconhecer e respeitar o 'outro' como diferente", explanation: "É a capacidade de se colocar no lugar do outro e aceitar as diferenças.", skill: "Ética e Dignidade" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Qual destes é um desrespeito à dignidade humana?", options: ["Preconceito e discriminação", "Oração silenciosa", "Compartilhar comida", "Estudar textos sagrados"], answer: "Preconceito e discriminação", explanation: "Qualquer forma de exclusão fere a dignidade da pessoa.", skill: "Ética e Dignidade" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A ética ambiental propõe que devemos cuidar do planeta porque:", options: ["A natureza é essencial para a vida de todos", "Dá lucro para as empresas", "É moda nas redes sociais", "Os animais são perigosos"], answer: "A natureza é essencial para a vida de todos", explanation: "Muitas religiões veem a natureza como criação divina e casa comum.", skill: "Ética e Dignidade" },

  // 9º Ens. Religioso - Diálogo e Diversidade (9)
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Diálogo Inter-religioso' busca:", options: ["O entendimento e a paz entre as religiões", "Converter todos para uma única fé", "Discutir quem é melhor", "Criar novas religiões"], answer: "O entendimento e a paz entre as religiões", explanation: "O diálogo visa o respeito mútuo e a cooperação, não a conversão.", skill: "Diálogo e Diversidade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Diversidade cultural e religiosa é uma característica de sociedades:", options: ["Pluralistas e democráticas", "Ditatoriais", "Isoladas", "Sem leis"], answer: "Pluralistas e democráticas", explanation: "A pluralidade reconhece a coexistência de diferentes visões de mundo.", skill: "Diálogo e Diversidade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O que é Intolerância Religiosa?", options: ["Não aceitar ou perseguir quem crê diferente", "Não gostar de doces", "Frequentar duas igrejas", "Ler livros de história"], answer: "Não aceitar ou perseguir quem crê diferente", explanation: "É o desrespeito e agressão contra práticas e crenças alheias.", skill: "Diálogo e Diversidade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O Brasil é um Estado Laico. Isso significa que:", options: ["O Estado é neutro e garante liberdade para todas as fés", "O Estado proíbe todas as religiões", "O Estado tem uma religião oficial", "Apenas políticos podem ter religião"], answer: "O Estado é neutro e garante liberdade para todas as fés", explanation: "Laicidade protege tanto quem crê quanto quem não crê.", skill: "Diálogo e Diversidade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A empatia no diálogo religioso serve para:", options: ["Sentir e entender a perspectiva do outro", "Mudar de lado", "Ganhar o debate", "Ficar triste"], answer: "Sentir e entender a perspectiva do outro", explanation: "A empatia derruba barreiras e preconceitos.", skill: "Diálogo e Diversidade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Qual o maior desafio de viver em uma sociedade diversa?", options: ["Praticar a tolerância e o respeito diário", "Não ter comida", "Falar línguas diferentes", "Usar uniformes iguais"], answer: "Praticar a tolerância e o respeito diário", explanation: "O convívio exige maturidade e aceitação das diferenças.", skill: "Diálogo e Diversidade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Documentos como a Declaração Universal dos Direitos Humanos protegem:", options: ["A liberdade de crença e pensamento", "Apenas os reis", "Somente um grupo religioso", "O uso de celulares"], answer: "A liberdade de crença e pensamento", explanation: "É um direito humano fundamental escolher sua própria espiritualidade.", skill: "Diálogo e Diversidade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O ecumenismo refere-se especificamente ao diálogo entre:", options: ["Diferentes igrejas cristãs", "Religiões de matriz africana", "Ciência e fé", "Ateus e teístas"], answer: "Diferentes igrejas cristãs", explanation: "Busca a unidade entre as diversas denominações cristãs.", skill: "Diálogo e Diversidade" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Para dialogar, é necessário:", options: ["Saber ouvir o outro com respeito", "Falar mais alto que o outro", "Ter sempre razão", "Saber todos os nomes"], answer: "Saber ouvir o outro com respeito", explanation: "Ouvir é tão importante quanto falar no processo dialógico.", skill: "Diálogo e Diversidade" },

  // 6º Matemática - Números e Operações (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de 1.250 + 750?", options: ["2.000", "1.900", "2.100", "1.850"], answer: "2.000", explanation: "1.250 + 750 = 2.000.", skill: "Números e Operações" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Se você tem R$ 50,00 e gasta R$ 18,50, quanto resta?", options: ["R$ 31,50", "R$ 32,50", "R$ 41,50", "R$ 21,50"], answer: "R$ 31,50", explanation: "50 - 18,50 = 31,50.", skill: "Números e Operações" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o valor do número romano 'XXIV'?", options: ["24", "26", "14", "25"], answer: "24", explanation: "XX (20) + IV (4) = 24.", skill: "Números e Operações" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quanto é 15 x 4?", options: ["60", "45", "75", "55"], answer: "60", explanation: "15 + 15 + 15 + 15 = 60.", skill: "Números e Operações" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o quociente de 100 dividido por 5?", options: ["20", "25", "10", "50"], answer: "20", explanation: "100 ÷ 5 = 20.", skill: "Números e Operações" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que é um número antecessor?", options: ["O número que vem imediatamente antes", "O número que vem depois", "O dobro do número", "O número somado a 10"], answer: "O número que vem imediatamente antes", explanation: "Exemplo: 9 é o antecessor de 10.", skill: "Números e Operações" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Em 4³, o número 3 é chamado de:", options: ["Expoente", "Base", "Produto", "Fator"], answer: "Expoente", explanation: "O expoente indica quantas vezes a base é multiplicada por ela mesma.", skill: "Números e Operações" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de 2 x 5 + 10?", options: ["20", "30", "15", "25"], answer: "20", explanation: "Primeiro multiplica (2x5=10) e depois soma (10+10=20).", skill: "Números e Operações" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o valor posicional do algarismo 7 no número 7.842?", options: ["7.000", "700", "70", "7"], answer: "7.000", explanation: "O 7 está na casa das unidades de milhar.", skill: "Números e Operações" },

  // 6º Matemática - Divisibilidade (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um número é divisível por 2 quando:", options: ["Termina em número par", "Termina em 5", "A soma dos algarismos é par", "É maior que 10"], answer: "Termina em número par", explanation: "Números terminados em 0, 2, 4, 6 e 8 são divisíveis por 2.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual número abaixo é divisível por 5?", options: ["45", "42", "41", "44"], answer: "45", explanation: "Números terminados em 0 ou 5 são divisíveis por 5.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um número é divisível por 3 se:", options: ["A soma de seus algarismos for divisível por 3", "Terminar em 3", "For par", "Terminar em 0"], answer: "A soma de seus algarismos for divisível por 3", explanation: "Exemplo: 12 (1+2=3) é divisível por 3.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual destes números é primo?", options: ["7", "4", "9", "10"], answer: "7", explanation: "Números primos têm apenas dois divisores: 1 e eles mesmos.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um número é divisível por 10 se:", options: ["Terminar em 0", "Terminar em 5", "For ímpar", "A soma for 10"], answer: "Terminar em 0", explanation: "Qualquer número que termina em 0 pode ser dividido por 10 sem deixar resto.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O número 12 é divisível por:", options: ["1, 2, 3, 4, 6 e 12", "Apenas 1 e 12", "Apenas 2 e 6", "1, 5 e 10"], answer: "1, 2, 3, 4, 6 e 12", explanation: "Esses são todos os números que dividem 12 exatamente.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O número 1 é um número primo?", options: ["Não", "Sim", "Às vezes", "Só no domingo"], answer: "Não", explanation: "Por definição, números primos devem ter dois divisores distintos.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o maior divisor comum (MDC) entre 10 e 20?", options: ["10", "2", "5", "20"], answer: "10", explanation: "O maior número que divide ambos ao mesmo tempo é o 10.", skill: "Divisibilidade" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o mínimo múltiplo comum (MMC) entre 2 e 3?", options: ["6", "5", "1", "12"], answer: "6", explanation: "6 é o menor número que é múltiplo de 2 (2, 4, 6) e de 3 (3, 6) ao mesmo tempo.", skill: "Divisibilidade" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 11 com ${batch.length} questões adicionado.`);
