import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 5200;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 20: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 9º Ens. Religioso - Diálogo Inter-religioso (9)
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O que é o 'Consenso Ético Mínimo' no diálogo inter-religioso?", options: ["Valores morais básicos aceitos por quase todas as religiões", "Uma lei obrigatória criada pela ONU", "A união de todas as igrejas em uma só", "O fim de todas as diferenças teológicas"], answer: "Valores morais básicos aceitos por quase todas as religiões", explanation: "Inclui princípios como 'não matar' e 'falar a verdade', essenciais para a paz mundial.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Quem foi o teólogo que criou a famosa frase: 'Não haverá paz entre as nações sem paz entre as religiões'?", options: ["Hans Küng", "Papa Francisco", "Dalai Lama", "Martin Luther King"], answer: "Hans Küng", explanation: "Ele foi um dos maiores promotores da ética mundial e do diálogo entre as fés.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "No diálogo inter-religioso, o que significa 'Escuta Ativa'?", options: ["Ouvir o outro com a intenção real de compreender, sem julgar", "Ouvir apenas para encontrar erros na fala do outro", "Fingir que está prestando atenção", "Ouvir música religiosa enquanto o outro fala"], answer: "Ouvir o outro com a intenção real de compreender, sem julgar", explanation: "É a base para construir pontes de respeito e fraternidade.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Qual destes eventos é um exemplo prático de diálogo inter-religioso no Brasil?", options: ["O Comitê Nacional de Respeito à Diversidade Religiosa", "A escolha de apenas uma religião para as escolas", "A proibição de cultos de matriz africana", "A briga entre pastores e padres na TV"], answer: "O Comitê Nacional de Respeito à Diversidade Religiosa", explanation: "Órgão que reúne representantes de diversas fés para promover a tolerância.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O diálogo inter-religioso combate o 'Preconceito Estrutural' ao:", options: ["Desconstruir estereótipos negativos sobre as religiões do outro", "Proibir as pessoas de terem sua própria religião", "Obrigar todos a frequentarem a mesma igreja", "Dizer que todas as religiões são exatamente iguais"], answer: "Desconstruir estereótipos negativos sobre as religiões do outro", explanation: "O conhecimento mútuo reduz o medo e a agressividade.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O que é o 'Sínodo' ou grandes encontros de líderes mundiais sobre paz?", options: ["Assembleias para discutir soluções comuns para problemas da humanidade", "Competições para ver quem tem mais fiéis", "Festas de gala fechadas ao público", "Manifestações políticas contra a ciência"], answer: "Assembleias para discutir soluções comuns para problemas da humanidade", explanation: "Líderes de fés diferentes unem forças por causas como clima e fome.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A tolerância religiosa é o primeiro passo, mas o objetivo do diálogo é a:", options: ["Acolhida e Cooperação Fraterna", "Aceitação forçada de dogmas alheios", "Indiferença total", "Superioridade de uma fé sobre outra"], answer: "Acolhida e Cooperação Fraterna", explanation: "Tolerar é suportar; dialogar é construir algo juntos.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O diálogo entre Religião e Ciência busca:", options: ["Harmonizar o conhecimento técnico com os valores éticos e espirituais", "Provar que a ciência está sempre errada", "Eliminar a fé do mundo moderno", "Transformar a religião em uma fórmula matemática"], answer: "Harmonizar o conhecimento técnico com os valores éticos e espirituais", explanation: "Busca respostas para questões profundas sobre a vida e a existência.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Na escola, o ensino religioso deve seguir qual modelo para respeitar o diálogo?", options: ["Não confessional (conhecer a diversidade sem doutrinamento)", "Católico obrigatório", "Evangélico exclusivo", "Ateu militante"], answer: "Não confessional (conhecer a diversidade sem doutrinamento)", explanation: "Deve apresentar as diversas visões de mundo de forma imparcial.", skill: "Diálogo Inter-religioso" },

  // 9º Ed. Física - Esportes de Prancha (9)
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual esporte de prancha é praticado no mar, utilizando o impulso das ondas?", options: ["Surf", "Skate", "Snowboard", "Sandboard"], answer: "Surf", explanation: "O surf exige equilíbrio e leitura das correntes e quebras de onda.", skill: "Esportes de Prancha" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O Skate surgiu como uma alternativa para os surfistas quando:", options: ["Não havia ondas no mar (mar calmo)", "As pranchas de madeira acabaram", "As praias foram fechadas", "Eles queriam voar"], answer: "Não havia ondas no mar (mar calmo)", explanation: "Por isso o skate era chamado inicialmente de 'Sidewalk Surfing' (Surf de calçada).", skill: "Esportes de Prancha" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual o equipamento de segurança indispensável para a prática de Skate em pistas?", options: ["Capacete, joelheiras e cotoveleiras", "Apenas óculos de sol", "Luvas de boxe", "Colete salva-vidas"], answer: "Capacete, joelheiras e cotoveleiras", explanation: "Previnem lesões graves em quedas frequentes no aprendizado.", skill: "Esportes de Prancha" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O 'Sandboard' é a prática de deslizar com uma prancha sobre:", options: ["Dunas de areia", "Neve fresca", "Gelo liso", "Cimento quente"], answer: "Dunas de areia", explanation: "Muito comum em regiões litorâneas com dunas, como no Nordeste ou SC.", skill: "Esportes de Prancha" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual modalidade do skate foca em manobras técnicas em obstáculos de rua como corrimãos e escadas?", options: ["Street", "Vertical", "Downhill", "Freestyle"], answer: "Street", explanation: "É a modalidade olímpica que simula o ambiente urbano de calçadas.", skill: "Esportes de Prancha" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "No surf, o que é o 'Leash' (ou cordinha)?", options: ["Corda que prende a prancha ao tornozelo do surfista", "O nome do remo usado para remar", "A vela que empurra a prancha", "Uma gíria para onda grande"], answer: "Corda que prende a prancha ao tornozelo do surfista", explanation: "Garante a segurança, evitando que a prancha se perca ou atinja outros.", skill: "Esportes de Prancha" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O 'Stand Up Paddle' (SUP) diferencia-se do surf por usar um:", options: ["Remo para se deslocar em pé na prancha", "Motor elétrico", "Paraquedas acoplado", "Um par de esquis"], answer: "Remo para se deslocar em pé na prancha", explanation: "Muito praticado em águas calmas para lazer e exercício físico gradual.", skill: "Esportes de Prancha" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Como se chama a manobra básica de salto no skate (bater a cauda da prancha no chão)?", options: ["Ollie", "Flip", "Grind", "Manual"], answer: "Ollie", explanation: "É a base para quase todas as manobras aéreas e de obstáculos.", skill: "Esportes de Prancha" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Os esportes de prancha desenvolvem principalmente quais capacidades físicas?", options: ["Equilíbrio, coordenação motora e força de membros inferiores", "Apenas a flexibilidade dos braços", "Visão noturna", "Paciência para pescar"], answer: "Equilíbrio, coordenação motora e força de membros inferiores", explanation: "Exigem controle constante do centro de gravidade.", skill: "Esportes de Prancha" },

  // 6º Ens. Religioso - Festividades Religiosas (9)
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O que é uma 'Festividade Religiosa'?", options: ["Uma celebração coletiva ligada a crenças, mitos ou datas sagradas", "Uma prova escolar difícil", "Apenas um feriado sem significado nenhum", "Uma reunião de negócios da igreja"], answer: "Uma celebração coletiva ligada a crenças, mitos ou datas sagradas", explanation: "Servem para fortalecer a fé e a identidade da comunidade.", skill: "Festividades Religiosas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A festa do Natal, para os cristãos, celebra:", options: ["O nascimento de Jesus", "A vinda do Papai Noel apenas", "O fim do ano civil", "A criação do mundo"], answer: "O nascimento de Jesus", explanation: "É uma das festas mais importantes do calendário cristão.", skill: "Festividades Religiosas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Ramadã', no Islamismo, é um período sagrado marcado por:", options: ["Jejum, oração e reflexão espiritual", "Grandes churrascos diários", "Competições de dança", "Viagens de férias obrigatórias"], answer: "Jejum, oração e reflexão espiritual", explanation: "Os fiéis buscam autocontrole e aproximação com Deus.", skill: "Festividades Religiosas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A festa judaica de 'Pessach' (Páscoa) recorda:", options: ["A libertação do povo hebreu da escravidão no Egito", "A criação dos Dez Mandamentos", "O início do verão em Israel", "O nascimento de Moisés"], answer: "A libertação do povo hebreu da escravidão no Egito", explanation: "É celebrada com o jantar do Sêder e pães ázimos.", skill: "Festividades Religiosas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Holi' é um festival de cores e alegria muito importante em qual religião?", options: ["Hinduísmo", "Budismo", "Espiritismo", "Xintoísmo"], answer: "Hinduísmo", explanation: "Celebra o triunfo do bem sobre o mal e a chegada da primavera na Índia.", skill: "Festividades Religiosas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Qual festividade de matriz africana é comum no Brasil no dia 2 de fevereiro, com oferendas no mar?", options: ["Festa de Iemanjá", "Corpus Christi", "Dia de Finados", "Oktoberfest"], answer: "Festa de Iemanjá", explanation: "Iemanjá é a Rainha do Mar no Candomblé e na Umbanda.", skill: "Festividades Religiosas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Festa de Reis' (Folia de Reis) no folclore brasileiro homenageia:", options: ["Os três Reis Magos que visitaram Jesus", "Os governantes da cidade", "A independência do Brasil", "Os jogadores de futebol"], answer: "Os três Reis Magos que visitaram Jesus", explanation: "Mistura tradição religiosa com música e dança popular.", skill: "Festividades Religiosas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "As festas juninas no Brasil têm origem em qual tradição religiosa?", options: ["Católica (Sto. Antônio, São João e São Pedro)", "Islâmica antiga", "Budista tibetana", "Evangélica moderna"], answer: "Católica (Sto. Antônio, São João e São Pedro)", explanation: "Homenageiam santos populares com fogueiras, comidas e quadrilhas.", skill: "Festividades Religiosas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O Hanukkah, festa judaica das luzes, dura quantos dias?", options: ["8 dias", "1 dia", "40 dias", "3 dias"], answer: "8 dias", explanation: "Celebra a rededicação do Templo de Jerusalém e o milagre do azeite.", skill: "Festividades Religiosas" },

  // 8º Ens. Religioso - Ecomoral (9)
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "O que defende a 'Ecomoral' (ou Ética Socioambiental)?", options: ["O dever moral do ser humano de cuidar da Terra e de todos os seres vivos", "O direito de destruir a natureza para ficar rico rápido", "Que a natureza não tem nenhuma importância espiritual", "O uso de agrotóxicos em excesso"], answer: "O dever moral do ser humano de cuidar da Terra e de todos os seres vivos", explanation: "As religiões veem o planeta como um presente sagrado confiado ao homem.", skill: "Ecomoral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Qual termo é usado em muitas tradições para descrever a natureza como um lar comum?", options: ["Mãe Terra / Casa Comum", "Zona Industrial", "Reservatório de lucro", "Deserto vazio"], answer: "Mãe Terra / Casa Comum", explanation: "Destaque para a conexão íntima entre humanos e o ecossistema.", skill: "Ecomoral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Na visão da ecomoral, como deve ser o consumo humano?", options: ["Consciente, evitando o desperdício e o excesso", "O maior possível para ajudar a economia a girar", "Ignorando o que acontece com o lixo", "Trocando de celular todo mês sem necessidade"], answer: "Consciente, evitando o desperdício e o excesso", explanation: "O consumo desenfreado esgota os recursos limitados do planeta.", skill: "Ecomoral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A poluição dos rios e do ar, para a ecomoral, é considerada:", options: ["Uma injustiça contra a vida e as futuras gerações", "Um preço pequeno para o progresso das fábricas", "Algo que Deus resolverá sozinho sem ajuda humana", "Dever de cada país poluírem igual"], answer: "Uma injustiça contra a vida e as futuras gerações", explanation: "Afeta a saúde da criação e rouba o futuro dos jovens.", skill: "Ecomoral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Muitas religiões orientais (como Budismo e Hinduísmo) pregam a 'Ahinsa', que significa:", options: ["Não violência contra todos os seres sensíveis", "O sacrifício obrigatório de animais", "A limpeza dos templos com ouro", "A conquista de terras vizinhas"], answer: "Não violência contra todos os seres sensíveis", explanation: "Inclui o respeito e a proteção à vida animal.", skill: "Ecomoral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Para a ecomoral, quem é mais afetado pelas mudanças climáticas?", options: ["As populações mais pobres e vulneráveis", "Apenas os pinguins da Antártida", "As grandes empresas de petróleo", "Ninguém é afetado de verdade"], answer: "As populações mais pobres e vulneráveis", explanation: "Isso gera a necessidade de 'Justiça Climática'.", skill: "Ecomoral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A ideia de 'Sobriedade Feliz' propõe que:", options: ["A felicidade está na simplicidade e no ser, não no ter coisas", "Para ser feliz deve-se ter o carro mais caro", "Beber muita água traz fortuna rápida", "Esquecer os problemas do mundo"], answer: "A felicidade está na simplicidade e no ser, não no ter coisas", explanation: "Menos consumo pode significar mais qualidade de vida e espiritualidade.", skill: "Ecomoral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Qual o papel do ser humano em relação ao jardim da Terra, segundo o Gênesis?", options: ["Cultivar e guardar (cuidar)", "Explorar até o fim sem limites", "Ignorar e viver apenas no céu", "Vender cada pedaço por lucro"], answer: "Cultivar e guardar (cuidar)", explanation: "O ser humano é visto como um 'Zelador' ou 'Mordomo' da criação.", skill: "Ecomoral" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Cuidar da água hoje para que os netos tenham água amanhã é um exemplo de:", options: ["Responsabilidade Intergeracional", "Egoísmo familiar", "Falta de tecnologia de reciclagem", "Apenas economia financeira"], answer: "Responsabilidade Intergeracional", explanation: "Temos o dever moral com quem ainda não nasceu.", skill: "Ecomoral" },

  // 9º Ens. Religioso - Liberdade de Escolha (9)
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O que significa 'Livre-Arbítrio' em termos religiosos e filosóficos?", options: ["A capacidade humana de decidir e escolher seus atos voluntariamente", "O destino traçado que não pode ser mudado", "Fazer apenas o que as autoridades mandam", "Viver como um animal sem pensar"], answer: "A capacidade humana de decidir e escolher seus atos voluntariamente", explanation: "Implica na responsabilidade individual pelas consequências das escolhas.", skill: "Liberdade de Escolha" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A liberdade de escolha religiosa permite que uma pessoa:", options: ["Escolha seguir uma fé, mudar de fé ou não ter fé nenhuma", "Seja obrigada a seguir a religião da sua família para sempre", "Seja punida se não for ao templo", "Não precise seguir nenhuma regra moral"], answer: "Escolha seguir uma fé, mudar de fé ou não ter fé nenhuma", explanation: "É um direito de consciência garantido internacionalmente.", skill: "Liberdade de Escolha" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Em um Estado Laico e Democrático, a liberdade de escolha exige que:", options: ["O Estado proteja todas as manifestações de fé sem privilégios", "Uma religião tenha verba pública maior que as outras", "Ateus não possam trabalhar em cargos públicos", "Escolas ensinem apenas uma verdade sagrada"], answer: "O Estado proteja todas as manifestações de fé sem privilégios", explanation: "O Estado deve ser neutro para garantir a liberdade de todos.", skill: "Liberdade de Escolha" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O que é 'Intolerância Religiosa'?", options: ["Atitude de ódio ou rejeição à escolha religiosa do outro", "Gostar muito da sua própria igreja", "Estudar textos sagrados diferentes", "Não ter tempo para ir ao culto"], answer: "Atitude de ódio ou rejeição à escolha religiosa do outro", explanation: "A intolerância fere a liberdade de escolha individual.", skill: "Liberdade de Escolha" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Toda escolha livre traz consigo uma:", options: ["Responsabilidade Ética", "Medalha de ouro", "Ausência de consequências", "Punição imediata do céu"], answer: "Responsabilidade Ética", explanation: "Somos donos de nossos atos e devemos lidar com seus efeitos.", skill: "Liberdade de Escolha" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Forçar alguém a mudar de religião através de ameaças ou violência é um:", options: ["Crime contra a liberdade de consciência", "Gesto de amizade profunda", "Dever de todo fiel", "Ato de coragem política"], answer: "Crime contra a liberdade de consciência", explanation: "A conversão forçada é uma violação dos direitos humanos.", skill: "Liberdade de Escolha" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Agnóstico' é alguém que prefere escolher:", options: ["Não afirmar nem negar a existência de Deus por falta de provas", "Odiar todas as igrejas", "Criar sua própria religião secreta", "Rezar apenas para as estrelas"], answer: "Não afirmar nem negar a existência de Deus por falta de provas", explanation: "É uma posição filosófica sobre os limites do conhecimento humano.", skill: "Liberdade de Escolha" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A liberdade de escolha é um valor central da:", options: ["Dignidade Humana", "Escravidão", "Ditadura militar absoluta", "Falta de caráter"], answer: "Dignidade Humana", explanation: "Ser humano é ter a potência de se autodeterminar.", skill: "Liberdade de Escolha" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Como o diálogo contribui para a liberdade de escolha?", options: ["Permite conhecer melhor as opções e respeitar quem pensa diferente", "Faz todos escolherem a mesma coisa", "Confunde a cabeça das pessoas", "Não contribui em nada"], answer: "Permite conhecer melhor as opções e respeitar quem pensa diferente", explanation: "Quanto mais informação e respeito, mais livre é a escolha.", skill: "Liberdade de Escolha" },

  // 7º Matemática - Conjuntos Numéricos (9)
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Quais são os números que compõem o conjunto dos NATURAIS (N)?", options: ["Números inteiros não negativos (0, 1, 2, 3...)", "Apenas números negativos", "Fração e dízimas", "Raízes quadradas inexatas"], answer: "Números inteiros não negativos (0, 1, 2, 3...)", explanation: "Usados para contagem básica.", skill: "Conjuntos Numéricos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O conjunto dos números INTEIROS (Z) inclui os naturais e os:", options: ["Inteiros negativos (-1, -2, -3...)", "Frações decimais", "Números romanos apenas", "Números invisíveis"], answer: "Inteiros negativos (-1, -2, -3...)", explanation: "Z = {... -2, -1, 0, 1, 2 ...}.", skill: "Conjuntos Numéricos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Números que podem ser escritos como uma fração (a/b) pertencem ao conjunto dos:", options: ["Racionais (Q)", "Irracionais", "Pares apenas", "Primos apenas"], answer: "Racionais (Q)", explanation: "Incluem decimais exatos e dízimas periódicas.", skill: "Conjuntos Numéricos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual destes é um número Irracional famoso por não ter dízima periódica?", options: ["Pi (π)", "0,5", "1/2", "3,333..."], answer: "Pi (π)", explanation: "Números irracionais têm infinitas casas decimais sem repetição.", skill: "Conjuntos Numéricos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "A união do conjunto dos Racionais com os Irracionais forma o conjunto dos:", options: ["Reais (R)", "Complexos", "Naturais", "Grandes"], answer: "Reais (R)", explanation: "Representa todos os números que usamos na reta numérica comum.", skill: "Conjuntos Numéricos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O número zero (0) pertence a quais conjuntos?", options: ["Naturais, Inteiros, Racionais e Reais", "Apenas aos Inteiros", "Apenas aos Reais", "A nenhum deles"], answer: "Naturais, Inteiros, Racionais e Reais", explanation: "O zero é a base da contagem e divisória entre positivos e negativos.", skill: "Conjuntos Numéricos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o oposto (simétrico) do número inteiro +5?", options: ["-5", "1/5", "0,5", "0"], answer: "-5", explanation: "O simétrico fica à mesma distância do zero na reta, mas no lado oposto.", skill: "Conjuntos Numéricos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O valor absoluto (módulo) de um número, representado por |x|, é sempre:", options: ["Positivo ou zero", "Negativo sempre", "O dobro do número", "A metade do número"], answer: "Positivo ou zero", explanation: "O módulo representa a distância do número até o zero.", skill: "Conjuntos Numéricos" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Dízimas periódicas (como 0,666...) são números:", options: ["Racionais (podem ser frações)", "Irracionais", "Inteiros", "Imaginários"], answer: "Racionais (podem ser frações)", explanation: "0,666... é igual a 2/3.", skill: "Conjuntos Numéricos" },

  // 9º Matemática - Revisão Geral (9)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de (x + y)² (Quadrado da soma)?", options: ["x² + 2xy + y²", "x² + y²", "x² - 2xy + y²", "2x + 2y"], answer: "x² + 2xy + y²", explanation: "É um produto notável fundamental.", skill: "Revisão Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Em um triângulo retângulo, o quadrado da hipotenusa é igual à:", options: ["Soma dos quadrados dos catetos", "Soma simples dos catetos", "Raiz quadrada da área", "Diferença entre os lados"], answer: "Soma dos quadrados dos catetos", explanation: "Teorema de Pitágoras: a² = b² + c².", skill: "Revisão Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "A área de um círculo é calculada por qual fórmula?", options: ["π * raio²", "2 * π * raio", "base * altura", "lado * lado"], answer: "π * raio²", explanation: "O raio ao quadrado multiplicado por pi dá a superfície interna.", skill: "Revisão Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Quanto vale a soma dos ângulos internos de um triângulo?", options: ["180°", "90°", "360°", "100°"], answer: "180°", explanation: "Fato geométrico universal para qualquer triângulo plano.", skill: "Revisão Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Como se calcula o volume de um cubo de lado 'L'?", options: ["L³ (L * L * L)", "L * 3", "L²", "6 * L"], answer: "L³ (L * L * L)", explanation: "O volume é a medida do espaço ocupado em três dimensões.", skill: "Revisão Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a probabilidade de tirar 'Cara' ao lançar uma moeda honesta?", options: ["50% (1/2)", "100%", "25%", "0%"], answer: "50% (1/2)", explanation: "Existem 2 resultados possíveis, um é o que queremos.", skill: "Revisão Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Uma equação que tem a forma y = ax + b é uma função do:", options: ["1º Grau (Afim)", "2º Grau (Quadrática)", "3º Grau", "Logarítmica"], answer: "1º Grau (Afim)", explanation: "O gráfico dessa função é uma reta.", skill: "Revisão Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que é a 'Moda' em estatística?", options: ["O valor que mais se repete em um conjunto de dados", "A média de todos os valores", "A diferença entre o maior e o menor", "O valor do meio"], answer: "O valor que mais se repete em um conjunto de dados", explanation: "Representa a maior frequência observada.", skill: "Revisão Geral" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Se 2x = 10, então quanto vale x²?", options: ["25", "5", "10", "100"], answer: "25", explanation: "x = 10/2 = 5. Então x² = 5² = 25.", skill: "Revisão Geral" },

  // 7º Ciências - Sistema Sanguíneo (9)
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual o componente líquido do sangue que transporta nutrientes e hormônios?", options: ["Plasma", "Hemácias", "Plaquetas", "Leucócitos"], answer: "Plasma", explanation: "Representa cerca de 55% do volume do sangue.", skill: "Sistema Sanguíneo" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "As células responsáveis por defender o organismo contra invasores (bactérias/vírus) são:", options: ["Leucócitos (Glóbulos brancos)", "Hemácias", "Neurônios", "Plaquetas"], answer: "Leucócitos (Glóbulos brancos)", explanation: "Fazem parte do nosso sistema imunológico.", skill: "Sistema Sanguíneo" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O componente do sangue que ajuda na coagulação para fechar ferimentos é a:", options: ["Plaqueta", "Água pura", "Hemácia", "Gordura"], answer: "Plaqueta", explanation: "Essenciais para evitar hemorragias.", skill: "Sistema Sanguíneo" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O pigmento vermelho das hemácias que se liga ao oxigênio é a:", options: ["Hemoglobina", "Clorofila", "Melanina", "Insulina"], answer: "Hemoglobina", explanation: "Contém ferro e é vital para a respiração celular.", skill: "Sistema Sanguíneo" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Pessoas com o tipo sanguíneo 'O Negativo' são conhecidas como:", options: ["Doadores Universais", "Receptores Universais", "Raros de sangue azul", "Incompatíveis"], answer: "Doadores Universais", explanation: "Podem doar sangue para qualquer outra pessoa em emergência.", skill: "Sistema Sanguíneo" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "A 'Anemia' é uma condição causada frequentemente pela falta de:", options: ["Hemácias ou Hemoglobina (muitas vezes por falta de ferro)", "Água apenas", "Plaquetas em excesso", "Ar nos pulmões"], answer: "Hemácias ou Hemoglobina (muitas vezes por falta de ferro)", explanation: "Gera cansaço e palidez pela má oxigenação dos tecidos.", skill: "Sistema Sanguíneo" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Onde o sangue humano é produzido?", options: ["Na medula óssea (dentro dos ossos)", "No coração", "No estômago", "Nos pulmões"], answer: "Na medula óssea (dentro dos ossos)", explanation: "Principalmente nos ossos longos e chatos.", skill: "Sistema Sanguíneo" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O processo de transferir sangue de uma pessoa para outra chama-se:", options: ["Transfusão Sanguínea", "Injeção muscular", "Transplante de órgão", "Hemodiálise"], answer: "Transfusão Sanguínea", explanation: "Procedimento médico que salva vidas seguindo regras de compatibilidade.", skill: "Sistema Sanguíneo" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual a função principal do sangue arterial?", options: ["Leva oxigênio do coração para alimentar as células do corpo", "Recolhe apenas o lixo das células", "Combate apenas gripes", "Transporta o pensamento"], answer: "Leva oxigênio do coração para alimentar as células do corpo", explanation: "É um sangue rico em O2 e de cor vermelha viva.", skill: "Sistema Sanguíneo" },

  // 8º História - Independências América (9)
  { grade: "8º", discipline: "História", type: "multiple", text: "Qual ideia filosófica influenciou as elites coloniais na luta por independência na América?", options: ["Iluminismo", "Absolutismo", "Feudalismo", "Teocentrismo"], answer: "Iluminismo", explanation: "Ideais de liberdade, igualdade e autonomia política.", skill: "Independências América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Quem foi o principal líder das independências na América do Sul (Venezuela, Colômbia, etc)?", options: ["Simón Bolívar", "Napoleão", "Dom Pedro II", "Barão do Rio Branco"], answer: "Simón Bolívar", explanation: "O 'Libertador' desejava uma América Latina unida e forte.", skill: "Independências América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O exército de libertação que atravessou os Andes para libertar o Chile e o Peru foi liderado por:", options: ["José de San Martín", "Tiradentes", "Zumbi", "D. Pedro I"], answer: "José de San Martín", explanation: "Importante líder militar argentino da independência sul-americana.", skill: "Independências América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Diferente do Brasil, a maioria das ex-colônias espanholas adotou qual regime?", options: ["República", "Monarquia", "Império", "Socialismo"], answer: "República", explanation: "O Brasil foi a exceção monárquica na região após a independência.", skill: "Independências América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "No processo de independência do México, qual foi o marco inicial liderado por padres?", options: ["Grito de Dolores", "Grito do Ipiranga", "Ataque à Bastilha", "Manifesto Comunista"], answer: "Grito de Dolores", explanation: "Hidalgo e Morelos lideraram uma revolta popular e camponesa.", skill: "Independências América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O Haiti foi o primeiro país da América Latina a ficar independente e o único liderado por:", options: ["Escravizados negros vitoriosos", "Reis vindos da França", "Empresários americanos", "Padres espanhóis"], answer: "Escravizados negros vitoriosos", explanation: "Toussaint Louverture liderou a revolução brutal e heroica contra a França.", skill: "Independências América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A elite nascida na América que liderou os movimentos contra a Espanha era a dos:", options: ["Criollos", "Chapetones", "Mestiços", "Índios"], answer: "Criollos", explanation: "Tinham poder econômico, mas queriam autonomia política e comercial.", skill: "Independências América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A fragmentação da América Espanhola em vários países pequenos deveu-se ao:", options: ["Interesse das elites locais e falta de união política central", "Ataque dos EUA a todos", "Falta de ouro na região", "O clima muito diferente"], answer: "Interesse das elites locais e falta de união política central", explanation: "O sonho de Bolívar de uma 'Grande Colômbia' fracassou.", skill: "Independências América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A Doutrina Monroe (1823) dos EUA dizia 'A América para os americanos', visando:", options: ["Impedir que países europeus voltassem a colonizar o continente", "Dar terras para todos os imigrantes", "Cobrar impostos de todos os países vizinhos", "Mudar o idioma para inglês em toda parte"], answer: "Impedir que países europeus voltassem a colonizar o continente", explanation: "EUA buscavam afastar a influência da Santa Aliança na região.", skill: "Independências América" },

  // 9º Geografia - Geoeconomia Mundial (9)
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O que estuda a Geoeconomia?", options: ["A relação entre a economia mundial e o poder político dos territórios", "Apenas o mapa dos rios", "Como cultivar plantas em outros planetas", "A história das moedas antigas apenas"], answer: "A relação entre a economia mundial e o poder político dos territórios", explanation: "Analisa como recursos e riqueza influenciam as decisões globais.", skill: "Geoeconomia Mundial" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O grupo de países com economias emergentes que inclui o Brasil chama-se:", options: ["BRICS", "G7", "União Europeia", "OTAN"], answer: "BRICS", explanation: "Brasil, Rússia, Índia, China e África do Sul.", skill: "Geoeconomia Mundial" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "As empresas Transnacionais são aquelas que:", options: ["Produzem e vendem em diversos países pelo mundo", "Só vendem no interior de um único país", "São proibidas de sair da sua terra natal", "Pertencem apenas ao governo"], answer: "Produzem e vendem em diversos países pelo mundo", explanation: "Aproveitam vantagens como mão de obra barata ou recursos em escala global.", skill: "Geoeconomia Mundial" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A 'Dependência Tecnológica' ocorre quando um país:", options: ["Precisa comprar tecnologia cara de outros países por não produzir a sua", "Tem computadores demais em todos os lugares", "Proíbe o uso de internet", "Fabrica tudo o que consome sozinho"], answer: "Precisa comprar tecnologia cara de outros países por não produzir a sua", explanation: "É comum em países subdesenvolvidos ou em desenvolvimento.", skill: "Geoeconomia Mundial" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O 'G7' é o grupo formado pelos(as):", options: ["Países mais industrializados e ricos do mundo", "Sete maiores desertos", "Sete capitais brasileiras", "Países mais pobres e endividados"], answer: "Países mais industrializados e ricos do mundo", explanation: "EUA, Japão, Alemanha, França, Reino Unido, Itália e Canadá.", skill: "Geoeconomia Mundial" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Qual país é a maior potência econômica e geoeconômica do mundo atualmente?", options: ["Estados Unidos", "Brasil", "Rússia", "Japão"], answer: "Estados Unidos", explanation: "Seguido de perto pela crescente economia da China.", skill: "Geoeconomia Mundial" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "No mercado global, as 'Commodities' são:", options: ["Produtos primários de baixo valor agregado (soja, minério, petróleo)", "Chips de computador de última geração", "Obras de arte famosas", "Roupas de marca de luxo apenas"], answer: "Produtos primários de baixo valor agregado (soja, minério, petróleo)", explanation: "Seus preços são definidos nas bolsas de mercadorias mundiais.", skill: "Geoeconomia Mundial" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O termo 'Divisão Internacional do Trabalho' (DIT) explica por que:", options: ["Paises diferentes produzem coisas diferentes na economia global", "Todos os trabalhadores recebem o mesmo salário no mundo", "As máquinas fazem todo o trabalho sozinhas", "Não existem mais fábricas"], answer: "Paises diferentes produzem coisas diferentes na economia global", explanation: "Uns focam em matéria-prima, outros em manufatura e outros em alta tecnologia.", skill: "Geoeconomia Mundial" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Sanções econômicas (bloqueios) são usadas em geoeconomia para:", options: ["Pressionar países politicamente sem o uso direto de armas", "Ajudar o país vizinho a prosperar", "Parabenizar o governo por boas leis", "Acabar com o desemprego do exterior"], answer: "Pressionar países politicamente sem o uso direto de armas", explanation: "É o uso da economia como ferramenta de poder e controle.", skill: "Geoeconomia Mundial" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 20 com ${batch.length} questões adicionado.`);
