import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 6200;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 31: Injeção de 90 questões de Matemática a partir do ID: ${startId}`);

const batch = [
  // 8º Matemática - Aritmética (10)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que é um número irracional?", options: ["Um número que não pode ser escrito como fração de dois inteiros", "Um número negativo muito grande", "Qualquer número com vírgula", "O resultado de uma divisão por zero"], answer: "Um número que não pode ser escrito como fração de dois inteiros", explanation: "Sua representação decimal é infinita e não periódica.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o valor aproximado da raiz quadrada de 3?", options: ["1,73", "1,41", "2,00", "1,50"], answer: "1,73", explanation: "√3 é um número irracional muito comum na trigonometria.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O conjunto dos números Reais (R) é a união de quais conjuntos?", options: ["Racionais e Irracionais", "Naturais e Inteiros apenas", "Positivos e Negativos apenas", "Pares e Ímpares"], answer: "Racionais e Irracionais", explanation: "Abrange todos os números que podem ser localizados na reta numérica.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual a propriedade distributiva da multiplicação em relação à soma?", options: ["a * (b + c) = a*b + a*c", "a + (b + c) = (a + b) + c", "a * b = b * a", "a + 0 = a"], answer: "a * (b + c) = a*b + a*c", explanation: "Também conhecida como 'chuveirinho'.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que são números primos entre si?", options: ["Números cujo único divisor comum é o 1", "Números que são primos e vizinhos", "Números que somados dão um número primo", "Números pares"], answer: "Números cujo único divisor comum é o 1", explanation: "Exemplo: 8 e 9.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Na ordem das operações, o que deve ser resolvido primeiro?", options: ["Parênteses e Potências/Raízes", "Somas e Subtrações", "Multiplicações sempre", "A que aparecer primeiro da esquerda pra direita"], answer: "Parênteses e Potências/Raízes", explanation: "Segue a hierarquia: ( ), [ ], { } e depois Operações.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Quanto vale 2 elevado a -3?", options: ["1/8 (0,125)", "-8", "1/6", "8"], answer: "1/8 (0,125)", explanation: "Expoente negativo inverte a base: 1 / 2³ = 1/8.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A dízima periódica 0,333... equivale a qual fração?", options: ["1/3", "3/10", "3/100", "3/3"], answer: "1/3", explanation: "Fração geratriz simples.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual a diferença entre módulo (valor absoluto) e simétrico?", options: ["Módulo é a distância até o zero (sempre +); Simétrico é o sinal trocado", "São a mesma coisa", "Módulo é o dobro do número", "Simétrico é o número elevado ao quadrado"], answer: "Módulo é a distância até o zero (sempre +); Simétrico é o sinal trocado", explanation: "Ex: |-5|=5; simétrico de -5 é 5.", skill: "Aritmética" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A dízima periódica 0,555... é um número:", options: ["Racional", "Irracional", "Inteiro", "Natural"], answer: "Racional", explanation: "Pois pode ser escrita como 5/9.", skill: "Aritmética" },

  // 6º Matemática - Subtração (10)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Como se chamam os termos de uma subtração?", options: ["Minuendo, Subtraendo e Diferença (ou Resto)", "Parcelas e Soma", "Fatores e Produto", "Dividendo e Divisor"], answer: "Minuendo, Subtraendo e Diferença (ou Resto)", explanation: "Terminologia clássica da aritmética.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quanto é 1000 - 345?", options: ["655", "755", "645", "665"], answer: "655", explanation: "Cálculo básico de subtração com reserva.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Na subtração, o número do qual se retira uma quantidade é o:", options: ["Minuendo", "Subtraendo", "Resto", "Diferença"], answer: "Minuendo", explanation: "É a quantidade inicial.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "A operação inversa da subtração é a:", options: ["Adição", "Multiplicação", "Divisão", "Potenciação"], answer: "Adição", explanation: "Usada para fazer a 'prova real'.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Se o minuendo é 50 e a diferença é 20, qual o valor do subtraendo?", options: ["30", "70", "20", "10"], answer: "30", explanation: "50 - x = 20 => x = 30.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que acontece se subtrairmos um número dele mesmo (ex: 15 - 15)?", options: ["O resultado será zero", "O resultado será um", "Não é possível fazer", "O número fica dobrado"], answer: "O resultado será zero", explanation: "Propriedade fundamental.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Resolva: Uma loja tinha 120 celulares e vendeu 87. Quantos restam?", options: ["33", "43", "23", "37"], answer: "33", explanation: "120 - 87 = 33.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Para subtrair números decimais (ex: 5,5 - 1,25), a regra principal é:", options: ["Colocar vírgula debaixo de vírgula", "Subtrair os números esquecendo a vírgula", "Somar os dois números", "Mudar o sinal do maior"], answer: "Colocar vírgula debaixo de vírgula", explanation: "Alinhamento das ordens decimais.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "A subtração de um número menor por um maior (ex: 5 - 10) resulta em um número:", options: ["Negativo", "Positivo", "Zero", "Não existe"], answer: "Negativo", explanation: "Princípio dos números inteiros.", skill: "Subtração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Ao subtrair o número zero de qualquer número, o resultado é:", options: ["O próprio número", "Zero", "Um", "O número negativo"], answer: "O próprio número", explanation: "Zero é o elemento neutro da adição/subtração.", skill: "Subtração" },

  // 6º Matemática - Unidades de Medida (10)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual a unidade padrão de comprimento no Sistema Internacional?", options: ["Metro (m)", "Quilo (kg)", "Litro (L)", "Segundo (s)"], answer: "Metro (m)", explanation: "A partir do metro derivam os múltiplos e submúltiplos.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um quilômetro (km) equivale a quantos metros?", options: ["1000 metros", "100 metros", "10 metros", "10000 metros"], answer: "1000 metros", explanation: "O prefixo 'quilo' significa mil.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Para medir a massa (peso) de um caminhão, a unidade mais adequada é:", options: ["Tonelada (t)", "Grama (g)", "Miligrama (mg)", "Equitômetro (hm)"], answer: "Tonelada (t)", explanation: "1 tonelada = 1000 quilos.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quantos minutos existem em uma hora e meia?", options: ["90 minutos", "60 minutos", "100 minutos", "120 minutos"], answer: "90 minutos", explanation: "60 (1h) + 30 (0.5h) = 90.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "A unidade de medida 'Mililitro' (ml) é usada para medir:", options: ["Volume/Capacidade", "Peso", "Tempo", "Temperatura"], answer: "Volume/Capacidade", explanation: "Submúltiplo do litro.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um século possui quantos anos?", options: ["100 anos", "10 anos", "1000 anos", "50 anos"], answer: "100 anos", explanation: "Unidade de tempo histórica.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual instrumento é usado para medir a Temperatura?", options: ["Termômetro", "Régua", "Cronômetro", "Balança"], answer: "Termômetro", explanation: "Mede em Celsius (°C) no Brasil.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quantos gramas tem 1,5 kg?", options: ["1500 g", "150 g", "15 g", "15000 g"], answer: "1500 g", explanation: "1,5 * 1000 = 1500.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um dia completo tem quantos segundos?", options: ["86.400 s", "3.600 s", "60.000 s", "24.000 s"], answer: "86.400 s", explanation: "24h * 60min * 60s = 86.400.", skill: "Unidades" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual a unidade ideal para medir a distância entre duas cidades?", options: ["Quilômetro (km)", "Centímetro (cm)", "Decímetro (dm)", "Milímetro (mm)"], answer: "Quilômetro (km)", explanation: "Usada para grandes distâncias terrestres.", skill: "Unidades" },

  // 9º Matemática - Álgebra (10)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a fórmula de Bhaskara para encontrar as raízes de ax² + bx + c = 0?", options: ["x = (-b ± √Δ) / 2a", "x = -b / a", "x = √b² - 4ac", "x = a² + b²"], answer: "x = (-b ± √Δ) / 2a", explanation: "Fórmula clássica para equações do 2º grau.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que o discriminante (Δ = b² - 4ac) indica sobre as raízes?", options: ["Se Δ > 0 existem duas raízes reais e distintas", "Se Δ < 0 as raízes são inteiras", "Se Δ = 0 não existem raízes", "Se Δ for par a equação é incompleta"], answer: "Se Δ > 0 existem duas raízes reais e distintas", explanation: "O valor de delta determina a natureza das raízes.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Uma equação do 2º grau é chamada de 'Incompleta' quando:", options: ["b ou c (ou os dois) são iguais a zero", "a é igual a zero", "Não tem resultado", "Tem apenas um termo"], answer: "b ou c (ou os dois) são iguais a zero", explanation: "O termo 'a' nunca pode ser zero em uma eq. do 2º grau.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de (x + 2)²?", options: ["x² + 4x + 4", "x² + 4", "2x + 4", "x² + 2x + 4"], answer: "x² + 4x + 4", explanation: "Produto notável: quadrado do primeiro + 2x primeiro x segundo + quadrado do segundo.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "A expressão x² - 9 pode ser fatorada como:", options: ["(x - 3)(x + 3)", "(x - 3)²", "(x + 3)²", "x(x - 9)"], answer: "(x - 3)(x + 3)", explanation: "Diferença de dois quadrados.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a soma das raízes de uma equação do 2º grau (x1 + x2)?", options: ["-b / a", "c / a", "b / a", "Δ / 2a"], answer: "-b / a", explanation: "Relações de Girard.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o produto das raízes de uma equação do 2º grau (x1 * x2)?", options: ["c / a", "-b / a", "Δ / a", "b² - 4ac"], answer: "c / a", explanation: "Relações de Girard.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que é um 'Sistema de Equações do 1º Grau'?", options: ["Um conjunto de duas ou mais equações com as mesmas incógnitas", "Uma equação muito difícil", "Uma conta de somar letras", "Um gráfico de círculos"], answer: "Um conjunto de duas ou mais equações com as mesmas incógnitas", explanation: "Buscamos o valor que satisfaz todas as equações ao mesmo tempo.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "No método da Substituição para sistemas, qual o objetivo?", options: ["Isolar uma incógnita em uma equação e substituir na outra", "Trocar as letras por números aleatórios", "Somar as duas equações para cancelar uma letra", "Desenhar o gráfico para ver onde as retas se cruzam"], answer: "Isolar uma incógnita em uma equação e substituir na outra", explanation: "Técnica algébrica para resolver sistemas.", skill: "Álgebra" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que representa graficamente a solução de um sistema de duas equações?", options: ["O ponto de interseção das duas retas", "A área entre as retas", "O tamanho das linhas", "A cor do gráfico"], answer: "O ponto de interseção das duas retas", explanation: "O par ordenado (x, y) que resolve o sistema.", skill: "Álgebra" },

  // 6º Matemática - Polígonos (10)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que define um 'Polígono'?", options: ["Uma figura plana fechada formada por segmentos de reta que não se cruzam", "Qualquer desenho com pontas", "Uma bola dividida ao meio", "Um conjunto de pontos aleatórios"], answer: "Uma figura plana fechada formada por segmentos de reta que não se cruzam", explanation: "Ex: triângulos, quadrados, etc.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Como se chama o polígono que possui o menor número de lados possível?", options: ["Triângulo", "Quadrado", "Círculo", "Ponto"], answer: "Triângulo", explanation: "São necessários pelo menos 3 lados para fechar a figura.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um polígono de 5 lados é chamado de:", options: ["Pentágono", "Hexágono", "Octógono", "Quadrado"], answer: "Pentágono", explanation: "Penta = cinco.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O 'Hexágono' possui quantos lados?", options: ["6", "5", "8", "4"], answer: "6", explanation: "Hexa = seis.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Como chamamos o encontro de dois lados de um polígono?", options: ["Vértice", "Diagonal", "Aresta", "Centro"], answer: "Vértice", explanation: "É a 'quina' da figura.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O 'Octógono' é muito conhecido por ter:", options: ["8 lados", "10 lados", "6 lados", "4 lados"], answer: "8 lados", explanation: "Octo = oito.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um polígono regular possui:", options: ["Todos os lados e ângulos iguais", "Lados de tamanhos variados", "Apenas ângulos retos", "Nenhuma regra de tamanho"], answer: "Todos os lados e ângulos iguais", explanation: "É uma figura simétrica.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que são 'Lados Adjacentes'?", options: ["Lados que se encontram em um vértice em comum", "Lados que ficam de frente um para o outro", "Lados coloridos", "Lados invisíveis"], answer: "Lados que se encontram em um vértice em comum", explanation: "São lados vizinhos.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Como se chama um polígono de 4 lados?", options: ["Quadrilátero", "Triângulo", "Pentágono", "Círculo"], answer: "Quadrilátero", explanation: "Engloba quadrados, retângulos, trapézios, etc.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Uma linha curva fechada (como o círculo) é considerada um polígono?", options: ["Não, porque polígonos devem ter apenas lados retos", "Sim, é o polígono de um lado só", "Apenas se for muito pequena", "Depende do professor"], answer: "Não, porque polígonos devem ter apenas lados retos", explanation: "Polígonos são formados por segmentos de reta.", skill: "Polígonos" },

  // 6º Matemática - Números Decimais (10)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que os números decimais representam?", options: ["Partes de um todo, indicadas após uma vírgula", "Apenas números muito grandes", "Números negativos", "Apenas a tabuada do 10"], answer: "Partes de um todo, indicadas após uma vírgula", explanation: "Usados para medir o que não é inteiro (dinheiro, peso, etc).", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "No número 0,75, o algarismo 7 está na casa dos:", options: ["Décimos", "Centésimos", "Milésimos", "Inteiros"], answer: "Décimos", explanation: "Primeira casa após a vírgula.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Como lemos o número 0,05?", options: ["Cinco centésimos", "Cinco décimos", "Cinco milésimos", "Zero vírgula cinco"], answer: "Cinco centésimos", explanation: "Segunda casa após a vírgula.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quanto vale 1,5 + 0,25?", options: ["1,75", "1,25", "2,00", "1,525"], answer: "1,75", explanation: "1,50 + 0,25 = 1,75.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Ao multiplicar 2,5 por 10, o resultado é:", options: ["25", "0,25", "250", "2,50"], answer: "25", explanation: "A vírgula caminha uma casa para a direita.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual destes números é MAIOR: 0,3 ou 0,09?", options: ["0,3", "0,09", "São iguais", "Depende do dia"], answer: "0,3", explanation: "0,3 = 0,30, que é maior que 0,09.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Para transformar a fração 1/2 em decimal, fazemos:", options: ["1 dividido por 2 (0,5)", "1 vezes 2", "Invertemos a fração", "Somamos 10"], answer: "1 dividido por 2 (0,5)", explanation: "Fração é uma representação de divisão.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quanto é a metade de 0,6?", options: ["0,3", "0,03", "3,0", "0,12"], answer: "0,3", explanation: "Divisão básica por 2.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "No sistema monetário brasileiro (Real), os centavos são representados por:", options: ["Casas decimais (centésimos)", "Números inteiros grandes", "Desenhos de moedas", "Números romanos"], answer: "Casas decimais (centésimos)", explanation: "Ex: R$ 1,50.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O número decimal 1,00 é o mesmo que o número inteiro:", options: ["1", "100", "0", "10"], answer: "1", explanation: "Zeros após a vírgula sem outros algarismos não mudam o valor.", skill: "Números Decimais" },

  // 8º Matemática - Expressões Algébricas (10)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que é o 'Valor Numérico' de uma expressão algébrica?", options: ["O resultado obtido ao substituir as letras por números e resolver as contas", "O número de letras que a expressão tem", "O nome do matemático que a criou", "Sempre o número zero"], answer: "O resultado obtido ao substituir as letras por números e resolver as contas", explanation: "Tornamos a expressão abstrata em um valor concreto.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o valor de 2x + 5 para x = 4?", options: ["13", "11", "20", "8"], answer: "13", explanation: "2 * 4 + 5 = 8 + 5 = 13.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Simplificando 3a + 2b - a + 4b, obtemos:", options: ["2a + 6b", "4a + 6b", "5ab", "10ab"], answer: "2a + 6b", explanation: "Somamos os termos semelhantes (a com a, b com b).", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Como se chama a expressão formada por apenas um termo (ex: 5x²)?", options: ["Monômio", "Binômio", "Trinômio", "Polinômio"], answer: "Monômio", explanation: "Mono = um.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de (x) * (x²)?", options: ["x³", "x²", "2x", "x⁴"], answer: "x³", explanation: "Soma-se os expoentes: 1 + 2 = 3.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que são 'Termos Semelhantes'?", options: ["Termos que possuem a mesma parte literal (letras e expoentes)", "Termos que têm o mesmo sinal", "Termos com o mesmo número inicial", "Termos escritos com a mesma cor"], answer: "Termos que possuem a mesma parte literal (letras e expoentes)", explanation: "Só eles podem ser somados ou subtraídos.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Traduza para álgebra: 'O dobro de um número x somado ao seu triplo'.", options: ["2x + 3x", "x² + x³", "2 + 3 + x", "5x²"], answer: "2x + 3x", explanation: "Linguagem natural para simbólica.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o grau do monômio 7x²y³?", options: ["5", "2", "3", "7"], answer: "5", explanation: "Soma dos expoentes: 2 + 3 = 5.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que é 'Fatoração'?", options: ["Transformar uma soma em um produto", "Fazer contas de dividir muito rápido", "Achar a raiz quadrada", "Escrever os números por extenso"], answer: "Transformar uma soma em um produto", explanation: "Ex: colocar o fator comum em evidência.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Quanto vale x² - y² se x=5 e y=4?", options: ["9", "1", "41", "20"], answer: "9", explanation: "25 - 16 = 9.", skill: "Expressões Algébricas" },

  // 7º Matemática - Potenciação (10)
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Na potência 2⁵, o número 5 é chamado de:", options: ["Expoente", "Base", "Raiz", "Resultado"], answer: "Expoente", explanation: "Indica quantas vezes a base será multiplicada.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Quanto é 3⁴?", options: ["81", "12", "64", "27"], answer: "81", explanation: "3 * 3 * 3 * 3 = 81.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor de qualquer número (diferente de zero) elevado a 0?", options: ["1", "0", "O próprio número", "-1"], answer: "1", explanation: "Propriedade fundamental das potências.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual a regra para multiplicar potências de mesma base (ex: 2³ * 2²)?", options: ["Repetir a base e somar os expoentes (2⁵)", "Multiplicar as bases e os expoentes", "Repetir a base e multiplicar os expoentes", "Dividir as bases"], answer: "Repetir a base e somar os expoentes (2⁵)", explanation: "Propriedade fundamental.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Quanto é 10³?", options: ["1000", "100", "30", "10"], answer: "1000", explanation: "10 elevado a n é 1 seguido de n zeros.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor de (-2)³?", options: ["-8", "8", "-6", "6"], answer: "-8", explanation: "Base negativa com expoente ímpar resulta em negativo.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O que acontece ao elevar um número negativo a um expoente par (ex: (-3)²)?", options: ["O resultado fica positivo (+9)", "O resultado fica negativo (-9)", "O resultado será zero", "Dá erro na conta"], answer: "O resultado fica positivo (+9)", explanation: "Negativo vezes negativo é positivo.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "A expressão (5²)³ é o mesmo que:", options: ["5⁶", "5⁵", "5⁹", "10⁶"], answer: "5⁶", explanation: "Potência de potência: multiplicam-se os expoentes.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor de 1 elevado a um milhão (1^1.000.000)?", options: ["1", "Zero", "Um milhão", "Infinito"], answer: "1", explanation: "1 multiplicado por si mesmo qquer nº de vezes é 1.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Na divisão de potências de mesma base (ex: 5⁸ / 5³), devemos:", options: ["Subtrair os expoentes (5⁵)", "Somar os expoentes", "Dividir os expoentes", "Zerar a base"], answer: "Subtrair os expoentes (5⁵)", explanation: "Propriedade fundamental.", skill: "Potenciação" },

  // 9º Matemática - Equações de 1º Grau (10)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que é uma 'Incógnita' em uma equação?", options: ["O valor desconhecido que queremos encontrar (geralmente x)", "O nome do resultado final", "A conta de vezes", "O sinal de igual"], answer: "O valor desconhecido que queremos encontrar (geralmente x)", explanation: "A base da álgebra.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Resolva: 3x = 12. Qual o valor de x?", options: ["4", "15", "9", "36"], answer: "4", explanation: "x = 12 / 3 = 4.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Em uma equação, ao passar um termo de um lado para o outro do '=', devemos:", options: ["Inverter a operação (se somava, subtrai...)", "Mudar a letra", "Manter tudo igual", "Apagar o termo"], answer: "Inverter a operação (se somava, subtrai...)", explanation: "Princípio da balança (equilíbrio).", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o valor de x em: x - 10 = 50?", options: ["60", "40", "50", "10"], answer: "60", explanation: "x = 50 + 10 = 60.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que caracteriza uma equação de 1º grau?", options: ["O maior expoente da incógnita é 1", "Ela sempre tem o número 1", "Só tem uma conta", "O resultado é sempre 1"], answer: "O maior expoente da incógnita é 1", explanation: "Seu gráfico é uma reta.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Resolva: 2x + 10 = 20.", options: ["5", "10", "15", "2"], answer: "5", explanation: "2x = 10 -> x = 5.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Se 4x + 2 = 2x + 10, qual o valor de x?", options: ["4", "2", "6", "8"], answer: "4", explanation: "2x = 8 -> x = 4.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que é o 'Conjunto Solução' de uma equação?", options: ["O conjunto de todos os valores que tornam a sentença verdadeira", "A lista de todas as contas feitas", "O enunciado do problema", "A página do livro"], answer: "O conjunto de todos os valores que tornam a sentença verdadeira", explanation: "Representado por S.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Uma equação do tipo 0x = 5 é chamada de:", options: ["Equação Impossível", "Equação Indeterminada", "Equação Simples", "Equação de Segundo Grau"], answer: "Equação Impossível", explanation: "Não existe x que multiplicado por zero dê 5.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o x que resolve 3(x + 2) = 15?", options: ["3", "5", "1", "7"], answer: "3", explanation: "3x + 6 = 15 -> 3x = 9 -> x = 3.", skill: "Equações de 1º Grau" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 31 com ${batch.length} questões de Matemática adicionado.`);
