import fs from 'fs';
const filePath = 'questions.js';
function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const ids = content.match(/id:\s*(\d+)/g).map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}
const startId = getNextId();
console.log(`Sprint 10 a partir do ID: ${startId}`);
const batch = [
  // PORTUGUÊS (7º) - Sintaxe: Sujeito (9)
  { grade: "7º", discipline: "Português", type: "multiple", text: "O sujeito da oração é o termo sobre o qual se declara algo. Em 'O gato dormiu', o sujeito é:", options: ["dormiu", "O gato", "O", "gato dormiu"], answer: "O gato", explanation: "Quem dormiu? O gato.", skill: "Sintaxe: Sujeito" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Em 'Choveu muito ontem', o sujeito é:", options: ["Choveu", "Muito", "Ontem", "Inexistente (oração sem sujeito)"], answer: "Inexistente (oração sem sujeito)", explanation: "Verbos que indicam fenômenos da natureza não têm sujeito.", skill: "Sintaxe: Sujeito" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "O sujeito 'oculto' (desinencial) ocorre quando:", options: ["Não existe sujeito", "O sujeito está implícito na desinência verbal", "O verbo está no infinitivo", "A frase não tem verbo"], answer: "O sujeito está implícito na desinência verbal", explanation: "Ex: 'Estudamos muito' (sujeito oculto: nós).", skill: "Sintaxe: Sujeito" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Em 'Maria e João brincam no parque', o sujeito é:", options: ["Maria", "João", "Maria e João (sujeito composto)", "no parque"], answer: "Maria e João (sujeito composto)", explanation: "Dois ou mais núcleos = sujeito composto.", skill: "Sintaxe: Sujeito" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Qual a pergunta que fazemos ao verbo para encontrar o sujeito?", options: ["Quando?", "Onde?", "Quem? ou O quê?", "Por quê?"], answer: "Quem? ou O quê?", explanation: "Quem praticou a ação? Essa é a forma de identificar o sujeito.", skill: "Sintaxe: Sujeito" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Em 'Chegaram os livros novos', o sujeito é:", options: ["Chegaram", "Os livros novos", "novos", "Não há sujeito"], answer: "Os livros novos", explanation: "Sujeito posposto (depois do verbo).", skill: "Sintaxe: Sujeito" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "O sujeito indeterminado ocorre quando:", options: ["Sabemos exatamente quem é", "Não se pode ou não se quer identificar o sujeito", "O verbo está no passado", "A frase é interrogativa"], answer: "Não se pode ou não se quer identificar o sujeito", explanation: "Ex: 'Dizem que vai chover' (quem diz? não se sabe).", skill: "Sintaxe: Sujeito" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "Em 'Nós viajamos nas férias', o núcleo do sujeito é:", options: ["Nós", "viajamos", "férias", "nas"], answer: "Nós", explanation: "Núcleo é a palavra mais importante do sujeito.", skill: "Sintaxe: Sujeito" },
  { grade: "7º", discipline: "Português", type: "multiple", text: "O sujeito simples possui:", options: ["Dois ou mais núcleos", "Apenas um núcleo", "Nenhum núcleo", "Apenas verbos"], answer: "Apenas um núcleo", explanation: "Diferente do composto, que tem dois ou mais.", skill: "Sintaxe: Sujeito" },

  // CIÊNCIAS (9º) - Evolução (9)
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "Quem propôs a Teoria da Evolução por Seleção Natural?", options: ["Mendel", "Pasteur", "Charles Darwin", "Lamarck"], answer: "Charles Darwin", explanation: "Na obra 'A Origem das Espécies' (1859).", skill: "Evolução" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "A Seleção Natural age sobre os indivíduos que:", options: ["São mais fortes fisicamente", "Possuem características mais adaptadas ao ambiente", "São mais bonitos", "Vivem mais tempo sempre"], answer: "Possuem características mais adaptadas ao ambiente", explanation: "Sobrevivência dos mais aptos ao meio.", skill: "Evolução" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "Os fósseis são importantes para o estudo da evolução porque:", options: ["São bonitos", "Registram formas de vida do passado", "São feitos de plástico", "Não têm importância"], answer: "Registram formas de vida do passado", explanation: "Evidências da história da vida na Terra.", skill: "Evolução" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "A teoria de Lamarck, anterior a Darwin, defendia que as características adquiridas durante a vida:", options: ["Nunca mudam", "Seriam transmitidas aos descendentes", "Desaparecem no mesmo indivíduo", "Só afetam os machos"], answer: "Seriam transmitidas aos descendentes", explanation: "Hoje sabemos que isso está incorreto (Lei do Uso e Desuso).", skill: "Evolução" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "As mutações genéticas são importantes para a evolução porque:", options: ["Sempre causam doenças", "Geram variabilidade genética nas populações", "Tornam todos iguais", "Não têm nenhum papel"], answer: "Geram variabilidade genética nas populações", explanation: "Sem variação, não há seleção natural.", skill: "Evolução" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "Órgãos homólogos (mesma origem, funções diferentes) indicam:", options: ["Criação simultânea", "Ancestralidade comum entre espécies", "Que são da mesma espécie", "Nenhuma relação"], answer: "Ancestralidade comum entre espécies", explanation: "Ex: braço humano e asa do morcego.", skill: "Evolução" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "A especiação ocorre quando:", options: ["Todos viram a mesma espécie", "Uma população se divide e origina novas espécies", "As espécies se extinguem", "Os genes param de mutar"], answer: "Uma população se divide e origina novas espécies", explanation: "Isolamento geográfico ou reprodutivo.", skill: "Evolução" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "Qual evidência da evolução pode ser observada comparando embriões de espécies diferentes?", options: ["Embriologia comparada", "Anatomia dental", "Radiografia óssea", "Análise de sangue"], answer: "Embriologia comparada", explanation: "Embriões de vertebrados são muito semelhantes nos estágios iniciais.", skill: "Evolução" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "A adaptação de bactérias a antibióticos é um exemplo de:", options: ["Criação de novos remédios", "Seleção natural em tempo real", "Extinção das bactérias", "Evolução reversa"], answer: "Seleção natural em tempo real", explanation: "Bactérias resistentes sobrevivem e se reproduzem.", skill: "Evolução" },

  // EDUCAÇÃO FÍSICA (9º) - Saúde e Lazer (9)
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A OMS recomenda que adolescentes pratiquem pelo menos quantos minutos de atividade física por dia?", options: ["15 minutos", "30 minutos", "60 minutos", "120 minutos"], answer: "60 minutos", explanation: "De intensidade moderada a vigorosa.", skill: "Saúde e Lazer" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O sedentarismo pode causar:", options: ["Aumento da disposição", "Obesidade, diabetes e problemas cardíacos", "Melhora na postura", "Aumento da massa muscular"], answer: "Obesidade, diabetes e problemas cardíacos", explanation: "A falta de atividade física é fator de risco.", skill: "Saúde e Lazer" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O lazer é importante para a saúde mental porque:", options: ["Não serve para nada", "Reduz o estresse e melhora o bem-estar", "Causa mais ansiedade", "Só serve para crianças"], answer: "Reduz o estresse e melhora o bem-estar", explanation: "Equilíbrio entre trabalho/estudo e descanso.", skill: "Saúde e Lazer" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O IMC (Índice de Massa Corporal) é calculado dividindo o peso pela:", options: ["Idade", "Altura ao quadrado", "Circunferência do braço", "Frequência cardíaca"], answer: "Altura ao quadrado", explanation: "IMC = Peso / Altura².", skill: "Saúde e Lazer" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual destas é uma atividade de lazer ATIVA (com gasto energético)?", options: ["Assistir TV", "Jogar videogame sentado", "Andar de bicicleta", "Dormir"], answer: "Andar de bicicleta", explanation: "Lazer ativo envolve movimento corporal.", skill: "Saúde e Lazer" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A hidratação durante a atividade física é importante para:", options: ["Engordar", "Repor a água perdida pelo suor e evitar desidratação", "Ficar mais pesado", "Diminuir o desempenho"], answer: "Repor a água perdida pelo suor e evitar desidratação", explanation: "Deve-se beber água antes, durante e após o exercício.", skill: "Saúde e Lazer" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O alongamento antes e depois do exercício serve para:", options: ["Aumentar a massa muscular", "Prevenir lesões e melhorar a flexibilidade", "Queimar gordura rapidamente", "Aumentar a força explosiva"], answer: "Prevenir lesões e melhorar a flexibilidade", explanation: "Prepara os músculos e articulações.", skill: "Saúde e Lazer" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O uso excessivo de telas (celular, computador) pode prejudicar:", options: ["Apenas os olhos", "Postura, sono e saúde mental", "Nada, é totalmente seguro", "Apenas a audição"], answer: "Postura, sono e saúde mental", explanation: "O equilíbrio no uso de tecnologia é essencial.", skill: "Saúde e Lazer" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A qualidade do sono é influenciada pela prática de exercícios?", options: ["Não, são coisas sem relação", "Sim, exercícios regulares melhoram a qualidade do sono", "Exercícios pioram o sono", "Só se forem feitos de madrugada"], answer: "Sim, exercícios regulares melhoram a qualidade do sono", explanation: "O corpo descansa melhor após atividade física.", skill: "Saúde e Lazer" },

  // ENSINO RELIGIOSO (6º) - Narrativas Sagradas (9)
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "As narrativas sagradas são histórias que:", options: ["Só servem como entretenimento", "Transmitem ensinamentos, valores e crenças de um povo", "Não têm nenhuma importância cultural", "São apenas científicas"], answer: "Transmitem ensinamentos, valores e crenças de um povo", explanation: "Fazem parte da identidade cultural e espiritual.", skill: "Narrativas Sagradas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Na tradição cristã, a história de Noé e a Arca ensina sobre:", options: ["Construção naval", "Fé, obediência a Deus e recomeço", "Geografia marítima", "Zoologia"], answer: "Fé, obediência a Deus e recomeço", explanation: "Narrativa presente no Gênesis.", skill: "Narrativas Sagradas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Os mitos de criação existem em:", options: ["Apenas uma religião", "Diversas culturas e religiões ao redor do mundo", "Apenas na ciência", "Apenas em livros de ficção"], answer: "Diversas culturas e religiões ao redor do mundo", explanation: "Cada povo tem sua narrativa sobre a origem do mundo.", skill: "Narrativas Sagradas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Na mitologia indígena brasileira, Tupã é associado a:", options: ["O mar", "O trovão e a criação", "A lua", "As estrelas"], answer: "O trovão e a criação", explanation: "Divindade importante na cosmogonia Tupi-Guarani.", skill: "Narrativas Sagradas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "As parábolas contadas por Jesus Cristo são exemplos de:", options: ["Piadas", "Narrativas com ensinamentos morais e espirituais", "Receitas", "Leis científicas"], answer: "Narrativas com ensinamentos morais e espirituais", explanation: "Como a Parábola do Bom Samaritano.", skill: "Narrativas Sagradas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Na tradição africana, os Orixás são:", options: ["Instrumentos musicais", "Divindades ligadas a forças da natureza", "Tipos de comida", "Nomes de cidades"], answer: "Divindades ligadas a forças da natureza", explanation: "Presentes nas religiões de matriz africana.", skill: "Narrativas Sagradas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O respeito às diferentes narrativas sagradas é um princípio de:", options: ["Intolerância", "Tolerância religiosa e diversidade", "Imposição de crenças", "Ignorância"], answer: "Tolerância religiosa e diversidade", explanation: "Cada tradição merece ser conhecida e respeitada.", skill: "Narrativas Sagradas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A tradição oral é importante nas narrativas sagradas porque:", options: ["Ninguém sabia escrever", "Muitos povos transmitiam seus saberes de geração em geração pela fala", "É mais barata que livros", "Não tem importância"], answer: "Muitos povos transmitiam seus saberes de geração em geração pela fala", explanation: "Griôs africanos e anciãos indígenas são exemplos.", skill: "Narrativas Sagradas" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A narrativa do Êxodo, na Bíblia, conta a história de:", options: ["A criação do mundo", "A libertação do povo hebreu do Egito", "O nascimento de Jesus", "A construção do Templo"], answer: "A libertação do povo hebreu do Egito", explanation: "Liderada por Moisés.", skill: "Narrativas Sagradas" }
];

const questionsWithIds = batch.map((q, i) => ({ id: startId + i, ...q }));
const str = questionsWithIds.map(q =>
  `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`
).join(',\n');
const content = fs.readFileSync(filePath, 'utf-8');
fs.writeFileSync(filePath, content.replace(/\s*\];\s*$/, ',\n\n' + str + '\n];\n'), 'utf-8');
console.log(`Sucesso! Sprint 10: ${batch.length} questões adicionadas.`);
