import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 5000;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 18: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 6º Ens. Religioso - Direito à Crença (9)
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O que significa ter 'Liberdade de Crença'?", options: ["O direito de escolher ou não ter uma religião", "Obrigação de seguir a religião oficial", "Proibição de falar sobre Deus", "Direito de criticar ofensivamente os outros"], answer: "O direito de escolher ou não ter uma religião", explanation: "É um direito humano fundamental garantido pela Constituição.", skill: "Direito à Crença" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Qual documento brasileiro garante que ninguém será privado de direitos por motivo de crença religiosa?", options: ["Constituição Federal", "Código de Trânsito", "Manual da Escola", "Bíblia apenas"], answer: "Constituição Federal", explanation: "A Constituição de 1988 estabelece a laicidade e a liberdade religiosa.", skill: "Direito à Crença" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O Brasil é um Estado Laico. Isso significa que:", options: ["O Estado é neutro e deve respeitar todas as religiões igualmente", "O Estado proíbe todas as religiões", "O Estado tem uma religião oficial obrigatória", "Apenas religiões cristãs podem existir"], answer: "O Estado é neutro e deve respeitar todas as religiões igualmente", explanation: "Laicidade garante a separação entre Estado e Igreja.", skill: "Direito à Crença" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Impedir alguém de entrar em um lugar ou trabalhar por causa de sua religião é:", options: ["Crime de Intolerância Religiosa", "Direito do dono do lugar", "Uma regra aceitável", "Apenas uma brincadeira"], answer: "Crime de Intolerância Religiosa", explanation: "A discriminação religiosa é punível por lei no Brasil.", skill: "Direito à Crença" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A liberdade religiosa inclui o direito de:", options: ["Praticar cultos e rituais de forma livre e segura", "Forçar os vizinhos a participarem", "Destruir templos de outras religiões", "Não pagar impostos pessoais"], answer: "Praticar cultos e rituais de forma livre e segura", explanation: "O livre exercício dos cultos é protegido pelo Estado.", skill: "Direito à Crença" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O respeito à crença do outro demonstra:", options: ["Cidadania e respeito à diversidade", "Fraqueza de sua própria fé", "Desinteresse pela verdade", "Medo de punição"], answer: "Cidadania e respeito à diversidade", explanation: "Viver em harmonia exige aceitar que as pessoas pensam diferente.", skill: "Direito à Crença" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Qual o papel do Estado em relação aos locais de culto (igrejas, templos, terreiros)?", options: ["Proteger e garantir que não sejam violados", "Cobrar entrada para o governo", "Decidir quem pode ser o líder", "Destruí-los se não forem da maioria"], answer: "Proteger e garantir que não sejam violados", explanation: "O patrimônio e o espaço sagrado são protegidos pela lei.", skill: "Direito à Crença" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A liberdade de consciência permite que uma pessoa:", options: ["Seja ateia ou agnóstica se desejar", "Apenas mude de igreja dentro da mesma religião", "Seja impedida de votar se não tiver religião", "Não siga nenhuma lei do país"], answer: "Seja ateia ou agnóstica se desejar", explanation: "Crença envolve acreditar ou não acreditar em divindades.", skill: "Direito à Crença" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O diálogo entre diferentes religiões para buscar a paz é chamado de:", options: ["Ecumenismo / Diálogo Inter-religioso", "Discussão teológica", "Conflito de ideias", "Unificação forçada"], answer: "Ecumenismo / Diálogo Inter-religioso", explanation: "Busca pontos em comum e o respeito mútuo.", skill: "Direito à Crença" },

  // 6º Ens. Religioso - Sabedoria Tradicional (9)
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O que caracteriza a 'Sabedoria Tradicional' de um povo?", options: ["Conhecimentos passados de geração em geração", "Informações apenas encontradas na internet", "Leis criadas apenas nos últimos 10 anos", "Opinões de influenciadores digitais"], answer: "Conhecimentos passados de geração em geração", explanation: "Envolve cultura, mitos, ervas medicinais e valores morais.", skill: "Sabedoria Tradicional" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Nas culturas indígenas, quem geralmente é o guardião da sabedoria e dos rituais?", options: ["O Pajé (ou ancião)", "O cientista estrangeiro", "O prefeito da cidade vizinha", "Apenas os jovens"], answer: "O Pajé (ou ancião)", explanation: "Os mais velhos detêm o conhecimento histórico e espiritual da tribo.", skill: "Sabedoria Tradicional" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Tradição Oral' é importante porque:", options: ["Preserva a história e os valores através da fala e cantos", "É mais difícil de entender", "Não precisa de memória", "Substitui os livros em todo o mundo"], answer: "Preserva a história e os valores através da fala e cantos", explanation: "Antes da escrita, a fala era o único meio de manter a cultura viva.", skill: "Sabedoria Tradicional" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Muitos povos tradicionais têm uma relação de profunda sabedoria e respeito com:", options: ["A Natureza", "As máquinas industriais", "O dinheiro de papel", "A energia nuclear"], answer: "A Natureza", explanation: "A terra é vista como mãe e provedora, devendo ser cuidada.", skill: "Sabedoria Tradicional" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Os provérbios e ditos populares são exemplos de:", options: ["Sabedoria popular transmitida oralmente", "Mentiras organizadas", "Leis científicas exatas", "Códigos de computador"], answer: "Sabedoria popular transmitida oralmente", explanation: "Dão conselhos práticos e morais de forma resumida.", skill: "Sabedoria Tradicional" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Perder a sabedoria tradicional de um povo significa:", options: ["Perder uma parte importante da identidade e história humana", "Ficar mais moderno e inteligente", "Não muda nada", "Apenas ganhar espaço no computador"], answer: "Perder uma parte importante da identidade e história humana", explanation: "A diversidade cultural é um patrimônio da humanidade.", skill: "Sabedoria Tradicional" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Em muitas culturas africanas, a figura do 'Griot' era responsável por:", options: ["Contar histórias, genealogias e manter a memória do povo", "Cuidar apenas da comida", "Liderar guerras apenas", "Vender mercadorias"], answer: "Contar histórias, genealogias e manter a memória do povo", explanation: "Eles eram bibliotecas vivas das comunidades.", skill: "Sabedoria Tradicional" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A sabedoria tradicional muitas vezes ensina valores como:", options: ["Respeito aos mais velhos, cooperação e cuidado com a vida", "Individualismo e competição agressiva", "Acúmulo de riqueza acima de tudo", "Esquecimento do passado"], answer: "Respeito aos mais velhos, cooperação e cuidado com a vida", explanation: "Focam na harmonia do grupo e da existência.", skill: "Sabedoria Tradicional" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Os mitos de criação de diferentes povos servem para:", options: ["Explicar a origem do mundo e de seus valores de forma simbólica", "Enganar as crianças", "Vender ingressos de cinema", "Substituir a matemática"], answer: "Explicar a origem do mundo e de seus valores de forma simbólica", explanation: "Dão sentido à vida e à identidade do grupo.", skill: "Sabedoria Tradicional" },

  // 7º Ens. Religioso - Alteridade (9)
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "O que define o conceito de 'Alteridade'?", options: ["Reconhecer que o 'outro' é diferente e respeitar essa diferença", "Achar que todos devem ser iguais a mim", "Gostar apenas de quem pensa como eu", "Ignorar a existência das outras pessoas"], answer: "Reconhecer que o 'outro' é diferente e respeitar essa diferença", explanation: "Vem da palavra 'alter' (outro). É o exercício de ver o mundo pelo olhar do outro.", skill: "Alteridade" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "A prática da Alteridade exige principalmente:", options: ["Empatia e escuta atenta", "Julgamento rápido", "Falar mais que ouvir", "Impor sua cultura aos outros"], answer: "Empatia e escuta atenta", explanation: "Precisamos nos colocar no lugar do outro para compreendê-lo.", skill: "Alteridade" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "A falta de alteridade nas relações humanas gera:", options: ["Preconceito, intolerância e conflitos", "Paz mundial", "Amizades profundas", "Conhecimento científico"], answer: "Preconceito, intolerância e conflitos", explanation: "Quando não reconhecemos o outro, tendemos a rejeitá-lo.", skill: "Alteridade" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Na escola, praticar a alteridade significa:", options: ["Respeitar colegas com diferentes crenças, cores e jeitos", "Fazer bullying com quem é diferente", "Andar apenas com quem é parecido comigo", "Ignorar quem não fala minha língua"], answer: "Respeitar colegas com diferentes crenças, cores e jeitos", explanation: "A escola é um espaço de convivência com a diversidade.", skill: "Alteridade" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "O filósofo Emmanuel Levinas dizia que a ética começa ao:", options: ["Encontrar o rosto do 'outro' e sentir-se responsável por ele", "Ler todos os livros da biblioteca", "Ganhar muito dinheiro", "Seguir todas as leis sem pensar"], answer: "Encontrar o rosto do 'outro' e sentir-se responsável por ele", explanation: "O outro nos convoca à responsabilidade e ao cuidado.", skill: "Alteridade" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Ter alteridade em relação à religião alheia é:", options: ["Compreender que o sagrado do outro é importante para ele", "Tentar converter o outro à força", "Zombar dos rituais alheios", "Achar que só a minha religião é certa"], answer: "Compreender que o sagrado do outro é importante para ele", explanation: "Respeito ao sentimento religioso é base da paz.", skill: "Alteridade" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "A frase 'Não faça aos outros o que não gostaria que fizessem a você' resume a:", options: ["Regra de Ouro da convivência humana", "Lei do mais forte", "Teoria da evolução", "Regra do egoísmo"], answer: "Regra de Ouro da convivência humana", explanation: "Presente em quase todas as tradições religiosas e filosóficas.", skill: "Alteridade" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Para exercitar a alteridade, devemos abandonar os:", options: ["Estereótipos e preconceitos", "Nossos nomes", "Nossas famílias", "Direitos humanos"], answer: "Estereótipos e preconceitos", explanation: "Preconceitos nos impedem de ver quem a pessoa realmente é.", skill: "Alteridade" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "A alteridade contribui para uma cultura de:", options: ["Paz e solidariedade", "Guerra e competição", "Isolamento total", "Ódio nas redes sociais"], answer: "Paz e solidariedade", explanation: "Reconhecer o outro une a humanidade.", skill: "Alteridade" },

  // 9º Ens. Religioso - Ecoteologia (9)
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O que estuda a 'Ecoteologia'?", options: ["A relação entre a fé religiosa e o cuidado com o meio ambiente", "A vida dos animais apenas", "A construção dos templos de pedra", "O uso de tablets nas igrejas"], answer: "A relação entre a fé religiosa e o cuidado com o meio ambiente", explanation: "Busca fundamentos espirituais para a preservação do planeta.", skill: "Ecoteologia / Cuidado" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Muitas religiões veem a Terra como uma 'Casa Comum'. Esse termo sugere:", options: ["Que todos os seres compartilham e devem cuidar do mesmo lar", "Que devemos vender a terra para comprar casas", "Que apenas humanos importam", "Que a terra é infinita e pode ser destruída"], answer: "Que todos os seres compartilham e devem cuidar do mesmo lar", explanation: "Ideia popularizada pelo Papa Francisco na encíclica 'Laudato Si'.", skill: "Ecoteologia / Cuidado" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Na visão ecoteológica, a destruição da natureza é vista como:", options: ["Um desrespeito à criação e à vida divina", "Um sinal de progresso humano necessário", "Algo sem importância espiritual", "Um bônus econômico"], answer: "Um desrespeito à criação e à vida divina", explanation: "As religiões frequentemente veem a vida como um presente sagrado.", skill: "Ecoteologia / Cuidado" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O conceito de 'Sustentabilidade' na ética religiosa propõe:", options: ["Viver de forma a não esgotar os recursos para gerações futuras", "Usar tudo agora e deixar o futuro para Deus resolver sozinho", "Parar de comer vegetais", "Destruir florestas para plantar soja"], answer: "Viver de forma a não esgotar os recursos para gerações futuras", explanation: "Cuidar do amanhã é um dever moral presente em muitas fés.", skill: "Ecoteologia / Cuidado" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Povos indígenas contribuem para a ecoteologia com a ideia de que:", options: ["O ser humano é parte da natureza, não dono dela", "A floresta deve ser cimentada", "Os rios servem apenas para descarte de lixo", "Tudo tem um preço em dinheiro"], answer: "O ser humano é parte da natureza, não dono dela", explanation: "Visão sistêmica onde tudo está interligado.", skill: "Ecoteologia / Cuidado" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Cuidado com a Vida' abrange:", options: ["Humanos, animais, plantas e ecossistemas inteiros", "Apenas minha família", "Apenas as pessoas ricas", "Só o que é lucrativo"], answer: "Humanos, animais, plantas e ecossistemas inteiros", explanation: "Ampla responsabilidade cósmica.", skill: "Ecoteologia / Cuidado" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A ecoteologia critica o 'Consumismo exagerado' porque ele:", options: ["Gera desperdício e degrada o planeta e a espiritualidade", "Ajuda a empresa a crescer", "Deixa as pessoas mais felizes para sempre", "Acaba com a fome mundial"], answer: "Gera desperdício e degrada o planeta e a espiritualidade", explanation: "O excesso material afasta do sentido essencial da vida.", skill: "Ecoteologia / Cuidado" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Justiça Socioambiental' defende que:", options: ["Os mais pobres não devem sofrer as piores consequências da poluição", "Apenas os ricos devem ter água limpa", "A poluição deve ser igual para todos", "Não existe injustiça na natureza"], answer: "Os mais pobres não devem sofrer as piores consequências da poluição", explanation: "A crise climática afeta desproporcionalmente as periferias.", skill: "Ecoteologia / Cuidado" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Celebrar a beleza do mundo e agradecer pelos recursos é uma prática de:", options: ["Espiritualidade Ecológica", "Apenas um hábito de lazer", "Falta do que fazer", "Estatística climatológica"], answer: "Espiritualidade Ecológica", explanation: "Gratidão e contemplação levam à preservação.", skill: "Ecoteologia / Cuidado" },

  // 9º Ens. Religioso - Diálogo (9)
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O principal objetivo do Diálogo Inter-religioso é:", options: ["Promover o entendimento e a cooperação para a paz", "Convencer o outro de que ele está errado", "Fundir todas as religiões em uma só", "Disputar quem tem o templo maior"], answer: "Promover o entendimento e a cooperação para a paz", explanation: "Baseia-se no lema 'Não há paz entre as nações sem paz entre as religiões'.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O termo 'Ecumenismo' refere-se especificamente ao diálogo entre:", options: ["Diferentes igrejas cristãs", "Religião e Ciência", "Adultos e crianças", "Diferentes times de futebol"], answer: "Diferentes igrejas cristãs", explanation: "Busca a unidade na diversidade cristã.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Para que o diálogo ocorra, é necessário que cada participante tenha:", options: ["Respeito pela identidade e crença do outro", "Vontade de brigar", "Uma arma na mão", "Absoluta certeza de que o outro é inferior"], answer: "Respeito pela identidade e crença do outro", explanation: "O diálogo exige igualdade de dignidade.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O proselitismo agressivo (tentar converter o outro a qualquer custo) é:", options: ["Um obstáculo ao verdadeiro diálogo Inter-religioso", "Uma forma de amizade", "O objetivo do diálogo", "Proibido apenas na internet"], answer: "Um obstáculo ao verdadeiro diálogo Inter-religioso", explanation: "Gera desconfiança e fechamento e não partilha sincera.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Qual destes é um 'valor comum' compartilhado por quase todas as religiões?", options: ["A compaixão e o amor ao próximo", "A obrigatoriedade de comer carne", "O uso de roupas de couro", "A proibição de estudar"], answer: "A compaixão e o amor ao próximo", explanation: "É a Ética Mundial ou Consenso Ético Mínimo.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O diálogo inter-religioso ajuda a combater o:", options: ["Fundamentalismo e fanatismo violento", "Desenvolvimento tecnológico", "Conhecimento de outras línguas", "Crescimento das cidades"], answer: "Fundamentalismo e fanatismo violento", explanation: "O fundamentalismo não aceita a existência do diferente.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Quando líderes de várias fés se reúnem para rezar pela paz (como em Assis), eles praticam:", options: ["Ação Inter-religiosa simbólica", "Manifestação política secreta", "Uma festa de aniversário coletiva", "Competição de orações"], answer: "Ação Inter-religiosa simbólica", explanation: "Mostra ao mundo que as fés podem conviver em harmonia.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O diálogo inter-religioso na escola serve para:", options: ["Promover a convivência pacífica e combater bullying religioso", "Escolher o melhor aluno da igrejaX", "Fazer todos rezarem juntos a mesma oração", "Criticar os ateus"], answer: "Promover a convivência pacífica e combater bullying religioso", explanation: "A escola deve ser espaço de respeito e saber multicultural.", skill: "Diálogo Inter-religioso" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Um passo importante para o diálogo é:", options: ["Trabalhar juntos por causas sociais (fome, meio ambiente)", "Nunca falar um com o outro", "Esconder sua própria religião", "Ignorar as diferenças"], answer: "Trabalhar juntos por causas sociais (fome, meio ambiente)", explanation: "O 'Diálogo da Ação' une as fés pelo bem comum.", skill: "Diálogo Inter-religioso" },

  // 8º História - Revoltas Coloniais (9)
  { grade: "8º", discipline: "História", type: "multiple", text: "Qual o principal motivo das revoltas coloniais no Brasil (sécs. XVII e XVIII)?", options: ["Exploração excessiva e altos impostos da Coroa Portuguesa", "Desejo de se tornar colônia espanhola", "Falta de futebol na colônia", "Vontade de voltar para Portugal"], answer: "Exploração excessiva e altos impostos da Coroa Portuguesa", explanation: "O Pacto Colonial e a cobrança do Quinto geravam muita insatisfação.", skill: "Revoltas Coloniais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A 'Inconfidência Mineira' foi inspirada nos ideais de qual movimento europeu?", options: ["Iluminismo", "Absolutismo", "Socialismo", "Feudalismo"], answer: "Iluminismo", explanation: "Ideias de liberdade, igualdade e democracia chegaram através de estudantes.", skill: "Revoltas Coloniais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Quem foi o líder da Inconfidência Mineira que se tornou mártir da independência?", options: ["Tiradentes (Joaquim José da Silva Xavier)", "D. Pedro I", "Borba Gato", "Zumbi dos Palmares"], answer: "Tiradentes (Joaquim José da Silva Xavier)", explanation: "Foi o único condenado à morte e esquartejado pela Coroa.", skill: "Revoltas Coloniais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A revolta de caráter popular e abolicionista que ocorreu na Bahia (1798) foi a:", options: ["Conjuração Baiana (ou Revolta dos Alfaiates)", "Inconfidência Mineira", "Guerra dos Emboabas", "Revolta de Beckman"], answer: "Conjuração Baiana (ou Revolta dos Alfaiates)", explanation: "Tinha forte participação de negros, pardos e artesãos.", skill: "Revoltas Coloniais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A 'Derrama', motivo de revolta em Minas Gerais, era:", options: ["Cobrança forçada de impostos atrasados sobre o ouro", "O derramamento de leite nas ruas", "Uma festa popular", "Um tipo de comida típica"], answer: "Cobrança forçada de impostos atrasados sobre o ouro", explanation: "Portugal exigia 100 arrobas de ouro por ano; se não vencesse, confiscava bens.", skill: "Revoltas Coloniais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Qual o nome da revolta ocorrida no Maranhão contra o monopólio da Companhia de Comércio?", options: ["Revolta de Beckman", "Guerra dos Mascates", "Farroupilha", "Revolta de Filipe dos Santos"], answer: "Revolta de Beckman", explanation: "Os irmãos Beckman lideraram o protesto contra a falta de escravos e má qualidade dos produtos.", skill: "Revoltas Coloniais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A 'Guerra dos Mascates' foi um conflito entre elites de quais cidades?", options: ["Olinda e Recife", "Rio e São Paulo", "Salvador e Porto Seguro", "Ouro Preto e Mariana"], answer: "Olinda e Recife", explanation: "Disputa pelo controle político e econômico em Pernambuco.", skill: "Revoltas Coloniais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "As 'Revoltas Separatistas' tinham como objetivo final:", options: ["Independência de uma região ou de todo o Brasil", "O aumento dos impostos", "A submissão maior ao Rei", "O fim das plantações de café"], answer: "Independência de uma região ou de todo o Brasil", explanation: "Diferente das revoltas nativistas, queriam o rompimento com a Metrópole.", skill: "Revoltas Coloniais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Zumbi dos Palmares foi o líder da maior resistência escrava colonial, o:", options: ["Quilombo dos Palmares", "Quilombo de Canudos", "Exército Imperial", "Movimento dos Alfaiates"], answer: "Quilombo dos Palmares", explanation: "Símbolo da luta contra a escravidão por mais de um século.", skill: "Revoltas Coloniais" },

  // 8º História - Líderes Históricos (9)
  { grade: "8º", discipline: "História", type: "multiple", text: "Napoleão Bonaparte foi um importante líder de qual país?", options: ["França", "Inglaterra", "Brasil", "Itália"], answer: "França", explanation: "Tornou-se imperador e espalhou ideais liberais pela Europa por guerra.", skill: "Líderes Históricos" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Quem foi o principal líder da revolução que levou à independência do Haiti?", options: ["Toussaint Louverture", "Napoleão", "Simon Bolívar", "Dom Pedro I"], answer: "Toussaint Louverture", explanation: "Ex-escravizado que liderou a revolta vitoriosa contra a França.", skill: "Líderes Históricos" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Simon Bolívar ficou conhecido como o 'Libertador' de vários países na:", options: ["América do Sul", "Ásia", "África", "América do Norte"], answer: "América do Sul", explanation: "Liderou a independência de Venezuela, Colômbia, Equador, Peru e Bolívia.", skill: "Líderes Históricos" },
  { grade: "8º", discipline: "História", type: "multiple", text: "George Washington foi o primeiro presidente de qual nação?", options: ["Estados Unidos", "Canadá", "México", "Argentina"], answer: "Estados Unidos", explanation: "Líder do exército na guerra de independência americana.", skill: "Líderes Históricos" },
  { grade: "8º", discipline: "História", type: "multiple", text: "D. João VI fugiu de Portugal para o Brasil em 1808 devido à invasão de:", options: ["Tropas Napoleônicas", "Soldados Russos", "Exército Americano", "Piratas Vikings"], answer: "Tropas Napoleônicas", explanation: "Mudança da corte para o Rio de Janeiro marcou o início das transformações do Brasil.", skill: "Líderes Históricos" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Quem proclamou a independência do Brasil em 1822?", options: ["D. Pedro I", "Tiradentes", "Deodoro da Fonseca", "Barão de Itararé"], answer: "D. Pedro I", explanation: "O Grito do Ipiranga oficializou a separação de Portugal.", skill: "Líderes Históricos" },
  { grade: "8º", discipline: "História", type: "multiple", text: "José de San Martín foi um líder essencial para a independência de:", options: ["Argentina, Chile e Peru", "México e Cuba", "EUA e Canadá", "Brasil e Paraguai"], answer: "Argentina, Chile e Peru", explanation: "Estratégico militar que cruzou os Andes para libertar o sul do continente.", skill: "Líderes Históricos" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Benjamin Franklin foi um importante diplomata e inventor durante a independência de qual país?", options: ["EUA", "Brasil", "França", "Rússia"], answer: "EUA", explanation: "Um dos autores da declaração de independência e famoso pelo para-raios.", skill: "Líderes Históricos" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Maximilian Robespierre foi o líder radical de qual fase da Revolução Francesa?", options: ["O Terror", "Início da Monarquia", "Diretório", "Império"], answer: "O Terror", explanation: "Liderou o Comitê de Salvação Pública e usou a guilhotina intensamente.", skill: "Líderes Históricos" },

  // 8º História - Revoltas Provinciais (9)
  { grade: "8º", discipline: "História", type: "multiple", text: "As revoltas provinciais ocorreram no Brasil principalmente durante o período:", options: ["Regencial (1831-1840)", "Colonial inicial", "Ditadura Militar", "República Velha"], answer: "Regencial (1831-1840)", explanation: "Ausência de um Imperador forte gerou instabilidade e desejos de autonomia.", skill: "Revoltas Provinciais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A revolta que durou 10 anos no Rio Grande do Sul e Santa Catarina foi a:", options: ["Guerra dos Farrapos (Farroupilha)", "Cabanagem", "Sabinada", "Balaiada"], answer: "Guerra dos Farrapos (Farroupilha)", explanation: "Disputa por impostos sobre o charque e desejo republicano.", skill: "Revoltas Provinciais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A 'Cabanagem' no Pará tem esse nome porque seus participantes:", options: ["Viviam em choupanas/cabanas à beira dos rios", "Gostavam de cabanas de luxo", "Eram fabricantes de cadeiras", "Viajavam em cabines de navio"], answer: "Viviam em choupanas/cabanas à beira dos rios", explanation: "Foi uma revolta popular (índios, negros e pobres) que tomou o poder na província.", skill: "Revoltas Provinciais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A 'Revolta dos Malês' em Salvador (1835) foi liderada por:", options: ["Escravizados de religião muçulmana (que sabiam ler/escrever)", "Padres católicos", "Donos de escravos ricos", "Soldados portugueses"], answer: "Escravizados de religião muçulmana (que sabiam ler/escrever)", explanation: "Luta pela liberdade religiosa e fim da escravidão.", skill: "Revoltas Provinciais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A 'Sabinada' na Bahia foi liderada por Francisco Sabino e queria criar uma:", options: ["República Bahiense temporária", "Nova religião", "Indústria de tecidos", "Guerra contra a Argentina"], answer: "República Bahiense temporária", explanation: "Declararam a separação até que D. Pedro II atingisse a maioridade.", skill: "Revoltas Provinciais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A 'Balaiada' ocorreu no Maranhão e teve entre seus líderes:", options: ["Um fabricante de balaios (cestos)", "Um rei africano", "O próprio Imperador", "Empresários têxteis"], answer: "Um fabricante de balaios (cestos)", explanation: "Uniu artesãos, sertanejos e quilombolas contra a exploração das elites.", skill: "Revoltas Provinciais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O que motivava a maioria das camadas populares nessas revoltas?", options: ["Fome, pobreza e recrutamento militar obrigatório", "Desejo de viajar para a Europa", "Troca da cor da bandeira", "Vontade de pagar mais impostos"], answer: "Fome, pobreza e recrutamento militar obrigatório", explanation: "As condições de vida eram precárias e havia forte opressão social.", skill: "Revoltas Provinciais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A Revolução Praieira (1848), a última das grandes revoltas, ocorreu em:", options: ["Pernambuco", "Ceará", "Alagoas", "Rio de Janeiro"], answer: "Pernambuco", explanation: "Influenciada pelo socialismo utópico europeu (Primavera dos Povos).", skill: "Revoltas Provinciais" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O fim de muitas dessas revoltas foi marcado por:", options: ["Violenta repressão do governo central (exército imperial)", "Acordos de paz pacíficos e amigáveis para todos", "Independência de cada estado brasileiro até hoje", "Troca voluntária de governantes"], answer: "Violenta repressão do governo central (exército imperial)", explanation: "A ordem foi mantida através da força militar e execuções de líderes.", skill: "Revoltas Provinciais" },

  // 9º História - Paz dos Vencedores (9)
  { grade: "9º", discipline: "História", type: "multiple", text: "O Tratado de Versalhes (1919) pós-Primeira Guerra foi imposto principalmente à:", options: ["Alemanha", "Rússia", "Espanha", "Brasil"], answer: "Alemanha", explanation: "Considerada a única culpada pela guerra, sofreu punições severas.", skill: "Paz dos Vencedores" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A organização criada para manter a paz mundial após a 1ª Guerra foi a:", options: ["Liga das Nações", "ONU", "OTAN", "União Europeia"], answer: "Liga das Nações", explanation: "Embora bem intencionada, falhou em impedir novos conflitos.", skill: "Paz dos Vencedores" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O Tratado de Versalhes exigia que a Alemanha:", options: ["Pagasse enormes indenizações e perdesse territórios/militares", "Mudasse sua capital para Paris", "Passasse a falar apenas inglês", "Aumentasse seu exército em 10 vezes"], answer: "Pagasse enormes indenizações e perdesse territórios/militares", explanation: "As condições humilhantes ajudaram a surgir o nazismo depois.", skill: "Paz dos Vencedores" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Após a Primeira Guerra, quais impérios deixaram de existir?", options: ["Império Austro-Húngaro e Império Otomano", "Império Americano", "Império Grego Antigo", "Império Português das Américas"], answer: "Império Austro-Húngaro e Império Otomano", explanation: "Foram fragmentados em novos países independentes (Tchecoslováquia, Polônia, etc).", skill: "Paz dos Vencedores" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A Conferência de Berlim (1884), importante antes das guerras, serviu para:", options: ["Partilha da África entre as potências europeias", "Acabar com a escravidão mundial", "Criar o canal do Panamá", "Fazer um acordo de paz com a China"], answer: "Partilha da África entre as potências europeias", explanation: "Foi a base do imperialismo e gerou muitas tensões que levaram à 1ª Guerra.", skill: "Paz dos Vencedores" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Wilson (EUA) propôs os '14 Pontos', que defendiam a:", options: ["Autodeterminação dos povos e fim da diplomacia secreta", "Conquista total da Europa pela América", "Morte de todos os alemães", "Aumento dos impostos de guerra"], answer: "Autodeterminação dos povos e fim da diplomacia secreta", explanation: "Buscava uma paz sem vencedores agressivos, mas não foi totalmente seguido.", skill: "Paz dos Vencedores" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O 'Revanchismo Alemão' nasceu da insatisfação com a:", options: ["Paz de Versalhes", "Invenção do telefone", "Crise do café no Brasil", "Falta de neve em Berlim"], answer: "Paz de Versalhes", explanation: "Sentimento de humilhação explorado por líderes radicais.", skill: "Paz dos Vencedores" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Países como Polônia, Tchecoslováquia e Iugoslávia surgiram devido ao fim do conflito e:", options: ["Desmembramento de antigos impérios europeus", "Ataques de alienígenas", "Compra de terras pelos americanos", "Erosão natural do solo"], answer: "Desmembramento de antigos impérios europeus", explanation: "Novas fronteiras redesenharam o mapa da Europa.", skill: "Paz dos Vencedores" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A economia americana pós-guerra cresceu muito porque:", options: ["Vendeu armas, comida e emprestou dinheiro para a reconstrução europeia", "Não participou da guerra", "Descobriu ouro em Marte", "Parou de usar máquinas"], answer: "Vendeu armas, comida e emprestou dinheiro para a reconstrução europeia", explanation: "Os EUA tornaram-se a maior potência econômica mundial.", skill: "Paz dos Vencedores" },

  // 8º História - Independência Brasil/América (9)
  { grade: "8º", discipline: "História", type: "multiple", text: "Diferente dos vizinhos espanhóis, a independência do Brasil manteve o regime:", options: ["Monárquico (com um Imperador)", "Republicano (com um Presidente)", "Comunista", "Teocrático"], answer: "Monárquico (com um Imperador)", explanation: "O Brasil foi a única grande nação americana a ser um Império após a separação.", skill: "Independência Brasil / América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O 'Dia do Fico' (9 de janeiro de 1822) marcou a decisão de D. Pedro I de:", options: ["Não voltar para Portugal como a Corte exigia", "Ficar em silêncio por um ano", "Não comer mais porto", "Ficar na casa da sua mãe"], answer: "Não voltar para Portugal como a Corte exigia", explanation: "Ato de desobediência que acelerou a independência.", skill: "Independência Brasil / América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A independência das colônias espanholas resultou em:", options: ["Fragmentação em vários países independentes", "Um único país gigante comandado pela Espanha", "A volta total ao poder do Rei Espanhol", "Anexação total pelos EUA"], answer: "Fragmentação em vários países independentes", explanation: "As ex-colônias dividiram-se em nações como Argentina, Peru, México, etc.", skill: "Independência Brasil / América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Quem eram os 'Criollos' na América Espanhola?", options: ["Filhos de espanhóis nascidos na América (Elite local)", "Indígenas escravizados", "Soldados vindos de Madrid apenas", "Comerciantes franceses"], answer: "Filhos de espanhóis nascidos na América (Elite local)", explanation: "Lideraram as revoltas de independência para tomar o poder político.", skill: "Independência Brasil / América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O Grito de Dolores (1810) deu início ao processo de independência do:", options: ["México", "Chile", "Brasil", "Cuba"], answer: "México", explanation: "Liderado inicialmente pelos padres Miguel Hidalgo e José Maria Morelos.", skill: "Independência Brasil / América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A Doutrina Monroe (1823) dos EUA dizia 'A América para os americanos', visando:", options: ["Impedir a recolonização europeia no continente", "Dar terras de graça para todos", "Unir as Américas em um só país", "Mudar todas as línguas para inglês"], answer: "Impedir a recolonização europeia no continente", explanation: "Buscava afastar a influência das potências europeias da região.", skill: "Independência Brasil / América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Qual país foi o primeiro a reconhecer a independência do Brasil?", options: ["Estados Unidos", "Portugal", "Inglaterra", "França"], answer: "Estados Unidos", explanation: "Seguindo a lógica da Doutrina Monroe.", skill: "Independência Brasil / América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O 'Tratado de Paz e Aliança' (1825) fez com que o Brasil pagasse indenização a:", options: ["Portugal", "Espanha", "Argentina", "África"], answer: "Portugal", explanation: "Portugal exigiu 2 milhões de libras esterlinas para aceitar a separação.", skill: "Independência Brasil / América" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O sonho de Simon Bolívar ('Pan-americanismo') era:", options: ["Unir todas as nações da América Latina em uma Confederação", "Conquistar os Estados Unidos", "Dividir o continente em ilhas", "O fim de todos os governos"], answer: "Unir todas as nações da América Latina em uma Confederação", explanation: "Desejava uma união forte contra ataques externos, mas não foi concretizado.", skill: "Independência Brasil / América" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 18 com ${batch.length} questões adicionado.`);
