import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 5700;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 26: Injeção de 99 questões finais a partir do ID: ${startId}`);

const batch = [
  // 9º História - Brasil Ditadura (9)
  { grade: "9º", discipline: "História", type: "multiple", text: "Qual evento marcou o início do período da Ditadura Militar no Brasil?", options: ["O Golpe de 31 de Março de 1964", "A Proclamação da República", "O fim da Segunda Guerra Mundial", "A fundação de Brasília"], answer: "O Golpe de 31 de Março de 1964", explanation: "O presidente João Goulart foi deposto pelas Forças Armadas com apoio de setores civis.", skill: "Brasil Ditadura" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O AI-5 (Ato Institucional nº 5), baixado em 1968, ficou conhecido como o período mais repressivo porque:", options: ["Suspendeu garantias constitucionais e permitiu a cassação de mandatos e censura", "Deu direito de voto aos analfabetos", "Acabou com os impostos no país", "Criou o sistema único de saúde"], answer: "Suspendeu garantias constitucionais e permitiu a cassação de mandatos e censura", explanation: "Marcou o endurecimento do regime, conhecido como 'anos de chumbo'.", skill: "Brasil Ditadura" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O 'Milagre Econômico' (final dos anos 60 e início dos 70) foi caracterizado por:", options: ["Alto crescimento do PIB, mas com aumento da desigualdade social e da dívida externa", "Distribuição igualitária de renda para todos", "Fim da dependência tecnológica do exterior", "O Brasil se tornou a maior economia do mundo livre de corrupção"], answer: "Alto crescimento do PIB, mas com aumento da desigualdade social e da dívida externa", explanation: "A economia crescia 'para cima', mas os salários eram arrochados.", skill: "Brasil Ditadura" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Qual era o nome do movimento de resistência cultural que utilizava metáforas nas músicas para driblar a censura?", options: ["Tropicalismo", "Samba de Raiz", "Bossa Nova", "Funk Carioca"], answer: "Tropicalismo", explanation: "Artistas como Caetano Veloso e Gilberto Gil criticavam o sistema de forma criativa.", skill: "Brasil Ditadura" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O movimento popular que pedia o retorno das eleições diretas para presidente em 1984 foi chamado de:", options: ["Diretas Já", "Caras Pintadas", "Revolta da Vacina", "Marcha com Deus pela Família"], answer: "Diretas Já", explanation: "Reuniu milhões de pessoas em comícios por todo o Brasil.", skill: "Brasil Ditadura" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Quem foi o primeiro presidente civil eleito (indiretamente) após o fim da ditadura militar em 1985?", options: ["Tancredo Neves", "José Sarney", "Fernando Collor", "Itamar Franco"], answer: "Tancredo Neves", explanation: "Ele faleceu antes de assumir, sendo substituído por seu vice, José Sarney.", skill: "Brasil Ditadura" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A Lei da Anistia, assinada em 1979 pelo presidente João Figueiredo, permitiu o quê?", options: ["O retorno dos exilados políticos e o perdão por crimes políticos a ambos os lados", "O fim imediato da ditadura sem eleições", "A prisão perpétua de todos os militares", "O fechamento do Congresso Nacional"], answer: "O retorno dos exilados políticos e o perdão por crimes políticos a ambos os lados", explanation: "Foi um passo importante no processo de 'abertura lenta, gradual e segura'.", skill: "Brasil Ditadura" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A censura durante a ditadura militar atingia principalmente:", options: ["Imprensa, artes, músicas e opiniões políticas contrárias ao regime", "Apenas as propagandas de cigarro", "Livros de matemática pura", "Conversas entre crianças na escola"], answer: "Imprensa, artes, músicas e opiniões políticas contrárias ao regime", explanation: "Órgãos do governo revisavam tudo o que seria publicado ou exibido.", skill: "Brasil Ditadura" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A estrutura policial e militar criada para combater e torturar opositores do regime era o:", options: ["DOI-CODI", "IBGE", "SUS", "INCRA"], answer: "DOI-CODI", explanation: "Centros onde ocorriam interrogatórios, prisões políticas e violações de direitos humanos.", skill: "Brasil Ditadura" },

  // 8º História - Guerra do Paraguai (9)
  { grade: "8º", discipline: "História", type: "multiple", text: "A Guerra do Paraguai (1864-1870) foi o maior conflito armado ocorrido na:", options: ["América do Sul", "Europa", "Ásia", "América do Norte"], answer: "América do Sul", explanation: "Envolveu Paraguai contra a Tríplice Aliança.", skill: "Guerra do Paraguai" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Quais países formavam a 'Tríplice Aliança' que lutou contra o Paraguai?", options: ["Brasil, Argentina e Uruguai", "Brasil, Chile e Peru", "EUA, Inglaterra e França", "Paraguai, Bolívia e Equador"], answer: "Brasil, Argentina e Uruguai", explanation: "Uniram-se após a invasão paraguaia de territórios vizinhos.", skill: "Guerra do Paraguai" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Quem era o presidente/ditador do Paraguai na época do início do conflito?", options: ["Solano López", "Simón Bolívar", "José de San Martín", "Dom Pedro II"], answer: "Solano López", explanation: "Suas ambições geopolíticas e a busca por saída para o mar geraram o conflito.", skill: "Guerra do Paraguai" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O estopim da guerra foi a apreensão pelo Paraguai de qual navio brasileiro?", options: ["Marquês de Olinda", "Cisne Branco", "Barroso", "Riachuelo"], answer: "Marquês de Olinda", explanation: "O navio levava o presidente da província de Mato Grosso.", skill: "Guerra do Paraguai" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A vitória decisiva da marinha brasileira que garantiu o bloqueio dos rios paraguaios foi a Batalha de:", options: ["Riachuelo", "Curupaiti", "Tuiuti", "Lomas Valentinas"], answer: "Riachuelo", explanation: "Liderada pelo Almirante Barroso, foi fundamental para o avanço aliado.", skill: "Guerra do Paraguai" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O grupo de voluntários brasileiros que lutou na guerra, muitos deles escravos que buscavam a alforria, era o:", options: ["Voluntários da Pátria", "Dragões da Independência", "Guarda Nacional", "Forças Expedicionárias"], answer: "Voluntários da Pátria", explanation: "Muitos negros lutaram em troca da promessa de liberdade após o conflito.", skill: "Guerra do Paraguai" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Qual foi a consequência demográfica mais trágica da guerra para o Paraguai?", options: ["A perda de grande parte da sua população masculina adulta", "O aumento súbito da imigração europeia", "A descoberta de ouro em seu território", "O fim de todas as suas indústrias"], answer: "A perda de grande parte da sua população masculina adulta", explanation: "O país foi devastado e demorou décadas para se recuperar.", skill: "Guerra do Paraguai" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Um dos efeitos da guerra no Brasil foi o fortalecimento de qual classe?", options: ["O Exército Brasileiro (que passou a questionar a Monarquia)", "Os grandes fazendeiros de café apenas", "Os operários das fábricas", "Os comerciantes de peles"], answer: "O Exército Brasileiro (que passou a questionar a Monarquia)", explanation: "O contato com ideais republicanos e o prestígio militar levaram ao fim do Império anos depois.", skill: "Guerra do Paraguai" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O conflito terminou oficialmente em 1870 com a morte de Solano López no combate de:", options: ["Cerro Corá", "Itororó", "Avaí", "Angostura"], answer: "Cerro Corá", explanation: "López foi morto pelas tropas brasileiras, encerrando a guerra.", skill: "Guerra do Paraguai" },

  // 8º Ciências - Ambiente (9)
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O que define o conceito de 'Desenvolvimento Sustentável'?", options: ["Suprir as necessidades do presente sem comprometer as gerações futuras", "Usar todos os recursos naturais o mais rápido possível", "Parar totalmente a produção industrial no mundo", "Substituir todas as árvores por prédios de metal"], answer: "Suprir as necessidades do presente sem comprometer as gerações futuras", explanation: "Busca o equilíbrio entre economia, sociedade e natureza.", skill: "Ambiente" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O aumento global da temperatura da Terra causado pela emissão excessiva de gases como o CO₂ é o:", options: ["Aquecimento Global", "Inverno Nuclear", "Ciclo de Carbono natural apenas", "Reflexo Solar constante"], answer: "Aquecimento Global", explanation: "Potencializado pela queima de combustíveis fósseis e desmatamento.", skill: "Ambiente" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O fenômeno natural que mantém o planeta aquecido e permite a vida, mas que está sendo agravado pelo homem, é o:", options: ["Efeito Estufa", "Tornado", "El Niño", "Maré Vermelha"], answer: "Efeito Estufa", explanation: "Sem ele a Terra seria gélida, mas o excesso de gases o torna perigoso.", skill: "Ambiente" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A 'Biodiversidade' refere-se à:", options: ["Variedade de todas as formas de vida na Terra", "Quantidade de lixo produzida pelas cidades", "Apenas aos tipos de minerais no solo", "Velocidade do vento nas florestas"], answer: "Variedade de todas as formas de vida na Terra", explanation: "Inclui diversidade genética, de espécies e ecossistemas.", skill: "Ambiente" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A poluição que ocorre pelo despejo de lixo e produtos químicos nos rios e mares é a poluição:", options: ["Hídrica", "Atmosférica", "Sonora", "Visual"], answer: "Hídrica", explanation: "Afeta a disponibilidade de água doce e a vida marinha.", skill: "Ambiente" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Qual a importância da 'Reciclagem' para o meio ambiente?", options: ["Reduzir a extração de recursos naturais e o volume de lixo nos aterros", "Fazer as pessoas gastarem mais dinheiro", "Aumentar o número de fábricas poluentes", "Acabar com o uso de eletricidade"], answer: "Reduzir a extração de recursos naturais e o volume de lixo nos aterros", explanation: "Transforma resíduos em novos produtos.", skill: "Ambiente" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O desmatamento desenfreado causa, entre outros problemas:", options: ["Erosão do solo, perda de habitat e mudanças climáticas locais", "Aumento da fertilidade da terra automaticamente", "Melhora na qualidade do ar", "Crescimento acelerado dos rios"], answer: "Erosão do solo, perda de habitat e mudanças climáticas locais", explanation: "Sem a cobertura vegetal, a terra fica exposta e a água não infiltra.", skill: "Ambiente" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Fontes de energia 'Renováveis' são aquelas que:", options: ["Se recompõem naturalmente em curto prazo (Sol, Vento, Água)", "Vêm apenas do petróleo e carvão mineral", "Acabam assim que as usamos uma vez", "São radioativas e perigosas sempre"], answer: "Se recompõem naturalmente em curto prazo (Sol, Vento, Água)", explanation: "Causam menor impacto ambiental que os combustíveis fósseis.", skill: "Ambiente" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Qual a função da Camada de Ozônio na atmosfera?", options: ["Filtrar os raios ultravioletas (UV) do Sol", "Produzir oxigênio para os aviões", "Manter a chuva longe das cidades", "Criar o arco-íris"], answer: "Filtrar os raios ultravioletas (UV) do Sol", explanation: "Protege os seres vivos contra o câncer de pele e danos genéticos.", skill: "Ambiente" },

  // 9º Ed. Física - Fisiologia (9)
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A 'Fisiologia do Exercício' estuda como:", options: ["O corpo humano reage e se adapta ao esforço físico", "As regras do futebol foram inventadas", "Se constrói uma quadra de esportes", "A história das Olimpíadas na Grécia"], answer: "O corpo humano reage e se adapta ao esforço físico", explanation: "Analisa batimentos, respiração e músculos durante o treino.", skill: "Fisiologia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Durante o exercício aeróbico (ex: corrida leve), o corpo utiliza principalmente qual fonte de energia?", options: ["Oxigênio e gorduras/carboidratos", "Apenas a força mental", "Substâncias químicas sem oxigênio (ácido lático rápido)", "Energia vinda exclusivamente dos ossos"], answer: "Oxigênio e gorduras/carboidratos", explanation: "É um esforço prolongado onde a respiração dá conta da demanda.", skill: "Fisiologia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O aumento da Frequência Cardíaca no exercício serve para:", options: ["Levar mais oxigênio e nutrientes para os músculos em atividade", "Diminuir a temperatura do corpo", "Fazer a pessoa sentir menos dor", "Produzir mais suor apenas"], answer: "Levar mais oxigênio e nutrientes para os músculos em atividade", explanation: "O coração bombeia mais sangue para suprir a necessidade energética.", skill: "Fisiologia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A 'Hipertrofia Muscular' é o processo de:", options: ["Aumento do tamanho das fibras musculares devido ao treino de força", "Encolhimento dos músculos por falta de uso", "Mudar a cor da pele com o sol", "Aumento da inteligência"], answer: "Aumento do tamanho das fibras musculares devido ao treino de força", explanation: "Ocorrem microlesões que, ao serem reparadas, tornam o músculo maior.", skill: "Fisiologia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O que é o 'VO2 Máximo'?", options: ["A capacidade máxima de um indivíduo captar e utilizar oxigênio", "A velocidade máxima de um carro de corrida", "A quantidade de água que o corpo retém", "O tempo máximo de sono profundo"], answer: "A capacidade máxima de um indivíduo captar e utilizar oxigênio", explanation: "É um indicador importante de condicionamento físico.", skill: "Fisiologia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A sensação de queimação no músculo em exercícios intensos deve-se ao acúmulo de:", options: ["Ácido Lático", "Glicose pura", "Água gelada dentro do músculo", "Vitamina C"], answer: "Ácido Lático", explanation: "Resultado do metabolismo anaeróbico quando falta oxigênio.", skill: "Fisiologia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O descanso pós-exercício é fundamental para o corpo porque:", options: ["É neste momento que ocorrem as adaptações e a recuperação muscular", "Serve apenas para não se cansar no dia seguinte", "Para o coração parar de bater um pouco", "Não é necessário descansar se o treino for bom"], answer: "É neste momento que ocorrem as adaptações e a recuperação muscular", explanation: "O corpo reconstrói o que foi 'desgastado' no treino.", skill: "Fisiologia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A hidratação correta durante a atividade física evita:", options: ["A desidratação e a queda brusca de desempenho", "O aumento da fome", "O crescimento do cabelo durante a corrida", "A necessidade de respirar"], answer: "A desidratação e a queda brusca de desempenho", explanation: "Perdemos muito líquido e minerais através do suor.", skill: "Fisiologia" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O sedentarismo causa problemas fisiológicos como:", options: ["Obesidade, doenças cardíacas e enfraquecimento muscular", "Aumento da agilidade e reflexos", "Melhora na capacidade pulmonar natural", "Não causa nenhum problema real"], answer: "Obesidade, doenças cardíacas e enfraquecimento muscular", explanation: "O corpo humano foi feito para o movimento.", skill: "Fisiologia" },

  // 6º Ed. Física - Lutas (9)
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual a diferença fundamental entre 'Briga' e 'Luta' na Educação Física?", options: ["Luta possui regras, ética e respeito ao oponente; Briga é violência descontrolada", "Na briga ganha quem é mais forte, na luta quem é mais rico", "Luta é apenas com espadas, briga é com as mãos", "Não existe nenhuma diferença"], answer: "Luta possui regras, ética e respeito ao oponente; Briga é violência descontrolada", explanation: "Luta é um esporte e uma arte marcial com valores morais.", skill: "Lutas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O cumprimento inicial e final em muitas lutas (como o Judô ou Caratê) demonstra:", options: ["Respeito mútuo entre os praticantes", "Medo do oponente", "Um sinal de que a luta vai durar pouco", "Vontade de machucar o outro"], answer: "Respeito mútuo entre os praticantes", explanation: "A disciplina e o respeito são a base das artes marciais.", skill: "Lutas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "A Capoeira é uma luta de origem brasileira que mistura:", options: ["Luta, dança, música e cultura popular", "Apenas boxe e judô", "Uso de armas de fogo e espadas", "Movimentos lentos apenas deitado"], answer: "Luta, dança, música e cultura popular", explanation: "Criada pelos escravizados como forma de resistência e cultura.", skill: "Lutas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O que são 'Artes Marciais'?", options: ["Sistemas de luta organizados, geralmente ligados a tradições e disciplinas orientais", "Desenhos de batalhas em museus", "Lutas de rua sem nenhuma técnica", "Apenas esportes olímpicos de corrida"], answer: "Sistemas de luta organizados, geralmente ligados a tradições e disciplinas orientais", explanation: "Ex: Judô, Caratê, Taekwondo, Kung Fu.", skill: "Lutas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Nas lutas, o praticante deve usar sua força para:", options: ["Vencer tecnicamente seguindo as regras, sem intenção de ferir gravemente", "Humilhar o adversário após a vitória", "Resolver problemas pessoais fora da academia", "Destruir os móveis da casa"], answer: "Vencer tecnicamente seguindo as regras, sem intenção de ferir gravemente", explanation: "O objetivo é o controle técnico e a superação de si mesmo.", skill: "Lutas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual das alternativas abaixo NÃO é uma luta de origem japonesa?", options: ["Capoeira", "Judô", "Caratê", "Jiu-jitsu"], answer: "Capoeira", explanation: "A Capoeira nasceu no Brasil.", skill: "Lutas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O instrumento musical usado para ditar o ritmo na roda de Capoeira é o:", options: ["Berimbau", "Violão", "Flauta", "Piano"], answer: "Berimbau", explanation: "É a alma da capoeira, conduzindo o jogo.", skill: "Lutas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O 'Sumô' é uma luta tradicional de qual país?", options: ["Japão", "China", "Brasil", "EUA"], answer: "Japão", explanation: "Envolve rituais antigos e o objetivo é tirar o oponente do círculo.", skill: "Lutas" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No Judô, o objetivo principal para vencer por 'Ippon' é:", options: ["Derrubar o oponente de costas no chão com perfeição", "Dar mais socos no adversário", "Correr mais rápido que o outro", "Falar palavras mágicas"], answer: "Derrubar o oponente de costas no chão com perfeição", explanation: "O Ippon é a pontuação máxima que encerra a luta.", skill: "Lutas" },

  // 6º Ed. Física - Jogos Mente (9)
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Os 'Jogos de Mente' são atividades que priorizam o(a):", options: ["Raciocínio lógico, estratégia e concentração", "Força muscular bruta", "Velocidade de corrida em campo", "Equilíbrio em cima de cordas"], answer: "Raciocínio lógico, estratégia e concentração", explanation: "Desafiam o intelecto e a tomada de decisão.", skill: "Jogos Mente" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No Xadrez, qual a peça mais importante, cujo 'xeque-mate' encerra o jogo?", options: ["Rei", "Rainha (Dama)", "Bispo", "Peão"], answer: "Rei", explanation: "O objetivo é cercar o Rei do adversário sem saída.", skill: "Jogos Mente" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual das peças de Xadrez se movimenta em formato de 'L'?", options: ["Cavalo", "Torre", "Bispo", "Rainha"], answer: "Cavalo", explanation: "É a única peça que pode pular por cima de outras.", skill: "Jogos Mente" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No jogo de Damas, o objetivo principal para vencer é:", options: ["Capturar todas as peças do adversário ou imobilizá-las", "Fazer a peça chegar ao outro lado para virar Rei de xadrez", "Contar quem tem a peça mais bonita", "Empurrar as peças para fora da mesa"], answer: "Capturar todas as peças do adversário ou imobilizá-las", explanation: "A vitória ocorre quando o oponente não tem mais movimentos válidos.", skill: "Jogos Mente" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "A concentração nos jogos de mente ajuda o estudante a:", options: ["Melhorar o foco e a paciência para resolver problemas complexos", "Ficar com sono mais rápido", "Esquecer a matéria da escola", "Ganhar força nos braços"], answer: "Melhorar o foco e a paciência para resolver problemas complexos", explanation: "São excelentes ferramentas pedagógicas.", skill: "Jogos Mente" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual jogo de tabuleiro milenar originário da China envolve cercar territórios com pedras pretas e brancas?", options: ["Go", "Banco Imobiliário", "Ludo", "Dominó"], answer: "Go", explanation: "Considerado um dos jogos mais complexos de estratégia do mundo.", skill: "Jogos Mente" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Em um jogo de tabuleiro, a atitude correta ao perder é:", options: ["Aceitar a derrota com esportividade e aprender com os erros", "Virar o tabuleiro e brigar com o colega", "Dizer que o outro trapaceou sem provas", "Parar de jogar para sempre"], answer: "Aceitar a derrota com esportividade e aprender com os erros", explanation: "O 'fair play' (jogo limpo) vale para todos os esportes.", skill: "Jogos Mente" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Jogos de cartas que envolvem estratégia (como o Truco ou Poker) também podem ser considerados:", options: ["Jogos de Mente (quando focam na lógica e probabilidade)", "Apenas jogos de azar ilegais sempre", "Esportes de força", "Exercícios de respiração"], answer: "Jogos de Mente (quando focam na lógica e probabilidade)", explanation: "Exigem análise psicológica e lógica matemática.", skill: "Jogos Mente" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual a importância de planejar as jogadas (pensar à frente) em um jogo de estratégia?", options: ["Prever as reações do oponente e buscar o melhor caminho para a vitória", "Fazer o jogo durar mais horas apenas", "Cansar o cérebro", "Nenhuma, o melhor é jogar por sorte"], answer: "Prever as reações do oponente e buscar o melhor caminho para a vitória", explanation: "O planejamento é a essência da estratégia.", skill: "Jogos Mente" },

  // 9º Arte - Dança (9)
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A 'Dança Contemporânea' rompe com o formalismo rígido de qual estilo anterior?", options: ["Balé Clássico", "Dança de Rua", "Samba", "Forró"], answer: "Balé Clássico", explanation: "Busca a liberdade de movimento e a expressão individual do corpo.", skill: "Dança" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "As danças de rua (Hip Hop, Breaking) tiveram origem principalmente em quais ambientes?", options: ["Nas ruas e comunidades urbanas dos EUA", "Nos grandes palácios reais europeus", "Dentro de conservatórios de música clássica", "Em aldeias isoladas na floresta"], answer: "Nas ruas e comunidades urbanas dos EUA", explanation: "Surgiram como forma de expressão e identidade de grupos sociais periféricos.", skill: "Dança" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Na dança, o elemento 'Espaço' refere-se a:", options: ["A direção, o nível e a trajetória dos movimentos do dançarino", "O peso corporal do artista", "A roupa usada na apresentação", "A marca da sapatilha"], answer: "A direção, o nível e a trajetória dos movimentos do dançarino", explanation: "É por onde o corpo se desloca durante a coreografia.", skill: "Dança" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A 'Coreografia' é:", options: ["A arte de criar e planejar uma sequência de movimentos de dança", "O nome do palco onde se dança", "Apenas a música que acompanha os passos", "O fotógrafo da apresentação"], answer: "A arte de criar e planejar uma sequência de movimentos de dança", explanation: "É o roteiro de movimentos da apresentação.", skill: "Dança" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A 'Dança de Salão' caracteriza-se por ser praticada:", options: ["Em pares, seguindo ritmos específicos (ex: Valsa, Tango, Forró)", "Sempre sozinho diante de um espelho", "Apenas por crianças na escola", "Sentado em cadeiras"], answer: "Em pares, seguindo ritmos específicos (ex: Valsa, Tango, Forró)", explanation: "Foca na interação social e sincronia do casal.", skill: "Dança" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Qual o papel do 'Ritmo' na dança?", options: ["Organizar o tempo do movimento em relação à música ou contagem interna", "Fazer as pessoas suarem mais", "Apenas para ficar bonito na foto", "Não tem importância nenhuma"], answer: "Organizar o tempo do movimento em relação à música ou contagem interna", explanation: "O ritmo dá a pulsação e a dinâmica para a dança.", skill: "Dança" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A dança pode ser usada como forma de protesto social e político? Dê um exemplo.", options: ["Sim, como visto em muitas performances contemporâneas e no Break", "Não, a dança serve apenas para diversão alegre", "Apenas em casamentos", "Somente se o governo deixar"], answer: "Sim, como visto em muitas performances contemporâneas e no Break", explanation: "O corpo é um instrumento de fala e denúncia.", skill: "Dança" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O 'Figurino' em um espetáculo de dança deve:", options: ["Ajudar na expressão do tema e permitir a liberdade de movimentos", "Ser o mais pesado possível para desafiar o artista", "Ser sempre de uma cor só", "Não ser usado, dançarinos devem usar roupas comuns"], answer: "Ajudar na expressão do tema e permitir a liberdade de movimentos", explanation: "É parte visual essencial da obra artística.", skill: "Dança" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Isadora Duncan é considerada uma pioneira de qual tipo de dança?", options: ["Dança Moderna", "Balé de Ponta", "Sapateado irlandês", "Samba de Roda"], answer: "Dança Moderna", explanation: "Ela libertou o corpo do espartilho e das sapatilhas de ponta.", skill: "Dança" },

  // 6º Arte - Técnicas (9)
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A técnica de criar imagens usando apenas luz e sombra com grafite ou carvão é o:", options: ["Desenho", "Grafite de rua", "Mosaico", "Escultura"], answer: "Desenho", explanation: "É a base fundamental das artes visuais.", skill: "Técnicas" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A pintura feita sobre paredes ou tetos, aplicando pigmentos sobre o reboco ainda úmido, é o:", options: ["Afresco", "Aquarela", "Colagem", "Stencil"], answer: "Afresco", explanation: "Ex: As pinturas de Michelangelo na Capela Sistina.", skill: "Técnicas" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Qual técnica utiliza pequenos pedaços de vidro, pedra ou cerâmica para formar uma imagem?", options: ["Mosaico", "Pontilhismo", "Instalação", "Gravura"], answer: "Mosaico", explanation: "Muito comum na arte antiga romana e bizantina.", skill: "Técnicas" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A 'Aquarela' é uma técnica de pintura que utiliza tinta diluída em:", options: ["Água", "Óleo", "Gasolina", "Ouro derretido"], answer: "Água", explanation: "Caracteriza-se pela transparência e leveza das cores.", skill: "Técnicas" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A técnica de colar diferentes materiais (papel, tecido, jornal) em uma superfície é o(a):", options: ["Colagem", "Escultura de barro", "Fotografia", "Serigrafia"], answer: "Colagem", explanation: "Muito explorada por artistas como Picasso e Braque.", skill: "Técnicas" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O 'Pontilhismo' consiste em criar a imagem através de:", options: ["Pequenos pontos ou manchas de cores puras postas lado a lado", "Grandes borrões de tinta misturada", "Desenhos feitos apenas com régua", "Esculturas de arame"], answer: "Pequenos pontos ou manchas de cores puras postas lado a lado", explanation: "O olho do observador mistura as cores à distância.", skill: "Técnicas" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Qual ferramenta o escultor usa para remover partes da pedra ou madeira?", options: ["Cinzel e Martele", "Pincel e Paleta", "Câmera e Lente", "Lápis e Borracha"], answer: "Cinzel e Martele", explanation: "São ferramentas de desbaste e corte.", skill: "Técnicas" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A técnica de pintura que utiliza tinta seca e opaca, permitindo sobreposição de camadas, é o:", options: ["Óleo sobre tela", "Pencil Drawing", "Crayon", "Tinta Guache"], answer: "Óleo sobre tela", explanation: "Muito usada pelos grandes mestres do Renascimento e Barroco.", skill: "Técnicas" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A 'Perspectiva' é uma técnica de desenho usada para dar ilusão de:", options: ["Profundidade e tridimensionalidade em uma superfície plana", "Apenas cores mais vibrantes", "Que o desenho está se mexendo", "Que a obra é feita de papel"], answer: "Profundidade e tridimensionalidade em uma superfície plana", explanation: "Usa pontos de fuga e linhas convergentes.", skill: "Técnicas" },

  // 8º Ens. Religioso - Respeito (9)
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "O que significa 'Alteridade' no contexto do Ensino Religioso?", options: ["Reconhecer e respeitar o outro em sua diferença e individualidade", "Gostar apenas de quem pensa igual a você", "Achar que sua religião é a única certa do mundo", "Não falar com pessoas de outras fés"], answer: "Reconhecer e respeitar o outro em sua diferença e individualidade", explanation: "É a base para a convivência pacífica entre diferentes grupos.", skill: "Respeito" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Empatia' é a capacidade de:", options: ["Colocar-se no lugar do outro para entender seus sentimentos e ações", "Julgar as pessoas rapidamente", "Sentir raiva de quem é diferente", "Dar ordens a todos os colegas"], answer: "Colocar-se no lugar do outro para entender seus sentimentos e ações", explanation: "Facilita o diálogo e o respeito religioso.", skill: "Respeito" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A intolerância religiosa fere qual princípio fundamental da convivência humana?", options: ["A liberdade de consciência e o direito de ser diferente", "A lei do mais forte", "O direito de ganhar prêmios", "A velocidade da internet"], answer: "A liberdade de consciência e o direito de ser diferente", explanation: "Respeitar a fé alheia é respeitar a própria humanidade.", skill: "Respeito" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "O que é 'Diversidade Religiosa'?", options: ["A existência de muitas religiões e formas de crer no mundo e no Brasil", "Obrigar todos a frequentarem a mesma igreja", "A proibição de cultos em locais públicos", "Um programa de TV único para todas as fés"], answer: "A existência de muitas religiões e formas de crer no mundo e no Brasil", explanation: "O Brasil é um país extremamente diverso em sua religiosidade.", skill: "Respeito" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Em um debate sobre religião na escola, a postura correta é:", options: ["Ouvir com atenção e respeito, expondo ideias sem agredir as do colega", "Gritar mais alto que o outro para vencer", "Ignorar o que o colega diz", "Dizer que a outra religião é falsa"], answer: "Ouvir com atenção e respeito, expondo ideias sem agredir as do colega", explanation: "O objetivo é o aprendizado mútuo e a tolerância.", skill: "Respeito" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Regra de Ouro', presente em quase todas as religiões, diz algo como:", options: ["Não faça aos outros o que não gostaria que fizessem com você", "Busque sempre o seu próprio lucro primeiro", "Ataque quem não concorda com sua fé", "Não divida nada com ninguém"], answer: "Não faça aos outros o que não gostaria que fizessem com você", explanation: "É um princípio ético universal de respeito.", skill: "Respeito" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "O que caracteriza o preconceito religioso?", options: ["O julgamento negativo de alguém baseado apenas em sua crença, sem conhecê-la", "Estudar a história das religiões na escola", "Respeitar o dia de descanso do vizinho", "Visitar um templo diferente com curiosidade e educação"], answer: "O julgamento negativo de alguém baseado apenas em sua crença, sem conhecê-la", explanation: "O preconceito cega para a verdade e a beleza da cultura alheia.", skill: "Respeito" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Respeitar a vestimenta religiosa do outro (ex: véu, turbante, fios de conta) é:", options: ["Um dever ético e um sinal de respeito à identidade do próximo", "Algo opcional que não faz diferença", "Uma forma de incentivar coisas erradas", "Apenas moda antiga"], answer: "Um dever ético e um sinal de respeito à identidade do próximo", explanation: "A roupa é muitas vezes uma extensão da fé e da história pessoal.", skill: "Respeito" },
  { grade: "8º", discipline: "Ensino Religioso", type: "multiple", text: "Promover a paz entre as religiões ajuda a evitar:", options: ["Extremismos, fanatismos e guerras sangrentas", "O desenvolvimento das escolas", "O amor entre as pessoas", "O crescimento do conhecimento humano"], answer: "Extremismos, fanatismos e guerras sangrentas", explanation: "O diálogo é a arma contra o ódio.", skill: "Respeito" },

  // 9º Ens. Religioso - Filantropia (9)
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O que é 'Filantropia' no contexto social e religioso?", options: ["O amor à humanidade traduzido em auxílio e ajuda ao próximo", "A venda de objetos sagrados por altos preços", "A proibição de ajudar quem não é da mesma religião", "O estudo da vida das estrelas no espaço"], answer: "O amor à humanidade traduzido em auxílio e ajuda ao próximo", explanation: "Muitas religiões têm a caridade como pilar central.", skill: "Filantropia" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "No Cristianismo, o valor da ajuda ao necessitado é muitas vezes chamado de:", options: ["Caridade", "Ganância", "Julgamento", "Isolamento"], answer: "Caridade", explanation: "Considerada uma das principais virtudes cristãs.", skill: "Filantropia" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Qual figura religiosa contemporânea é famosa mundialmente por seu trabalho filantrópico na Índia?", options: ["Madre Teresa de Calcutá", "Rainha Elizabeth", "Gisele Bündchen", "Joana D'Arc"], answer: "Madre Teresa de Calcutá", explanation: "Liderou as Missionárias da Caridade para cuidar dos mais pobres entre os pobres.", skill: "Filantropia" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A prática do 'Zakat' no Islamismo consiste em:", options: ["Dar uma parte fixa da renda para ajudar pobres e necessitados", "Fazer cinco orações por dia apenas", "Visitar a cidade de Meca", "Não comer carne de porco"], answer: "Dar uma parte fixa da renda para ajudar pobres e necessitados", explanation: "É um dos 5 pilares do Islã, sendo uma obrigação de solidariedade.", skill: "Filantropia" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "No Budismo, qual conceito incentiva a ajuda a todos os seres sencientes?", options: ["Compaixão (Karuna)", "Desejo de riqueza", "Apego às coisas físicas", "Guerra santa"], answer: "Compaixão (Karuna)", explanation: "O desejo de que todos sejam livres do sofrimento guia as ações budistas.", skill: "Filantropia" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Tzedaká' na tradição judaica não significa apenas caridade, mas sim:", options: ["Justiça Social", "Presente de aniversário", "Dívida de jogo", "Sorteio de sorte"], answer: "Justiça Social", explanation: "É visto como uma obrigação ética de retificar as desigualdades do mundo.", skill: "Filantropia" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Organizações não governamentais (ONGs) ligadas a religiões ajudam o Estado ao:", options: ["Atuar em áreas onde o governo não chega, como acolhimento e educação", "Ocupar cargos políticos à força", "Apenas construir prédios bonitos sem uso", "Não pagar nenhum imposto e ganhar dinheiro"], answer: "Atuar em áreas onde o governo não chega, como acolhimento e educação", explanation: "Têm grande capilaridade social e chegam aos mais vulneráveis.", skill: "Filantropia" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Voluntariado' é uma forma de filantropia porque:", options: ["A pessoa doa seu tempo e talento sem receber pagamento financeiro", "A pessoa ganha um salário dobrado", "O voluntário é obrigado por lei", "É uma forma de diversão apenas para ricos"], answer: "A pessoa doa seu tempo e talento sem receber pagamento financeiro", explanation: "O serviço ao próximo é a essência do voluntariado religioso.", skill: "Filantropia" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "As campanhas contra a fome (como a Ação da Cidadania de Betinho) demonstram que:", options: ["A solidariedade pode unir crentes e não crentes para causas humanitárias", "Apenas religiosos podem ajudar a sociedade", "As pessoas não ligam para a pobreza", "O governo deve fazer tudo sozinho sem ajuda civil"], answer: "A solidariedade pode unir crentes e não crentes para causas humanitárias", explanation: "A filantropia é um valor humanitário universal.", skill: "Filantropia" },

  // 7º Ens. Religioso - Espaços (9)
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Por que as tradições religiosas constroem templos monumentais?", options: ["Para expressar a grandeza do divino e oferecer um local de reunião para a comunidade", "Para esconder segredos do governo", "Apenas para competir qual prédio é mais alto", "Para cobrar ingressos e ficar ricos"], answer: "Para expressar a grandeza do divino e oferecer um local de reunião para a comunidade", explanation: "O templo é um símbolo visível da fé e do pertencimento.", skill: "Espaços" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Em qual tradição religiosa o 'Muro das Lamentações' é o local mais sagrado?", options: ["Judaísmo", "Islamismo", "Budismo", "Cristianismo"], answer: "Judaísmo", explanation: "Remanescente do Segundo Templo de Jerusalém.", skill: "Espaços" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "A cidade de Meca é o centro de peregrinação obrigatória para os seguidores do:", options: ["Islamismo", "Hinduísmo", "Siritismo", "Adventismo"], answer: "Islamismo", explanation: "Onde se localiza a Caaba, o ponto central da fé muçulmana.", skill: "Espaços" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "As catedrais góticas medievais eram construídas com paredes altas e vitrais para:", options: ["Transmitir a sensação de elevação espiritual e contar histórias sagradas pela luz", "Evitar que as pessoas vissem o lado de fora", "Apenas para gastar o vidro que sobrava", "Fazer o interior ficar mais quente"], answer: "Transmitir a sensação de elevação espiritual e contar histórias sagradas pela luz", explanation: "A arquitetura era uma forma de pregação visual.", skill: "Espaços" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Nas religiões tradicionais indígenas, o espaço sagrado está ligado à:", options: ["Preservação das matas e dos ciclos da terra", "Construção de shoppings sagrados", "Isolamento total dos jovens", "Tecnologia digital avançada"], answer: "Preservação das matas e dos ciclos da terra", explanation: "O território é onde vivem os ancestrais e os espíritos.", skill: "Espaços" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Um 'Panteão' era, na antiguidade (Grécia/Roma), um templo dedicado a:", options: ["Todos os deuses de uma mitologia", "Apenas um herói morto", "Aos escravos fugidos", "Aos filósofos apenas"], answer: "Todos os deuses de uma mitologia", explanation: "Pan (todos) + Theos (Deus).", skill: "Espaços" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "O respeito ao espaço sagrado alheio inclui NÃO fazer o quê?", options: ["Atos de vandalismo, pichações ou desrespeito aos ritos que lá ocorrem", "Entrar e ficar em silêncio", "Estudar sobre a religião no local", "A tirar uma foto com autorização"], answer: "Atos de vandalismo, pichações ou desrespeito aos ritos que lá ocorrem", explanation: "Violar um templo é ferir o sagrado de uma comunidade.", skill: "Espaços" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "A localização de muitos templos em lugares altos (montanhas) simboliza a:", options: ["Aproximação entre o humano e o divino (céu)", "Facilidade de fugir de inundações", "Apenas para vigiar a cidade e cobrar taxas", "Obrigação de fazer exercício físico"], answer: "Aproximação entre o humano e o divino (céu)", explanation: "O alto da montanha é visto como um ponto de contato com o transcendente.", skill: "Espaços" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Os altares domésticos (dentro de casa) servem para:", options: ["Manter a prática religiosa viva no cotidiano da família", "Apenas para decoração de móveis antigos", "Esconder jóias reais", "Ninguém sabe para que servem"], answer: "Manter a prática religiosa viva no cotidiano da família", explanation: "Trazem o sagrado para o ambiente privado do lar.", skill: "Espaços" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 26 com ${batch.length} questões adicionado.`);
