import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 5800;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 27: Injeção de 90 questões de Matemática a partir do ID: ${startId}`);

const batch = [
  // 6º Matemática - Polígonos (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que define um 'Polígono' na geometria?", options: ["Uma figura plana fechada formada apenas por segmentos de reta que não se cruzam", "Qualquer desenho circular", "Uma linha reta infinita", "Um sólido como um cubo"], answer: "Uma figura plana fechada formada apenas por segmentos de reta que não se cruzam", explanation: "Poli (muitos) + gono (ângulos). Devem ser linhas retas fechadas.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Como se chama um polígono que possui exatamente 5 lados?", options: ["Pentágono", "Hexágono", "Quadrilátero", "Heptágono"], answer: "Pentágono", explanation: "Penta significa cinco.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um polígono 'Regular' é aquele que possui:", options: ["Todos os lados e ângulos internos iguais", "Apenas um lado reto", "Pelo menos 10 lados", "Lados de tamanhos todos diferentes"], answer: "Todos os lados e ângulos internos iguais", explanation: "Ex: Quadrado, Triângulo Equilátero.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual é o menor número de lados que um polígono pode ter?", options: ["3", "1", "2", "4"], answer: "3", explanation: "Com menos de 3 segmentos de reta não é possível fechar uma figura plana.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um polígono de 8 lados é conhecido como:", options: ["Octógono", "Decágono", "Hexágono", "Dodecágono"], answer: "Octógono", explanation: "Octo refere-se a oito.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que são vértices em um polígono?", options: ["Os pontos de encontro entre dois lados", "As linhas que formam o desenho", "O espaço de dentro da figura", "A cor do polígono"], answer: "Os pontos de encontro entre dois lados", explanation: "São as 'quinas' ou bicos da figura.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um quadrilátero que possui todos os quatro lados iguais e quatro ângulos de 90 graus é o:", options: ["Quadrado", "Trapézio", "Losango apenas", "Retângulo apenas"], answer: "Quadrado", explanation: "O quadrado é um polígono regular de 4 lados.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O triângulo que possui todos os três lados com medidas diferentes é o:", options: ["Escaleno", "Isósceles", "Equilátero", "Retângulo"], answer: "Escaleno", explanation: "Escaleno = todos os lados desiguais.", skill: "Polígonos" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "A soma dos ângulos internos de qualquer TRIÂNGULO é sempre:", options: ["180°", "360°", "90°", "270°"], answer: "180°", explanation: "Propriedade fundamental de todos os triângulos planos.", skill: "Polígonos" },

  // 6º Matemática - Números Decimais (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual é o valor da soma 12,5 + 3,42?", options: ["15,92", "15,7", "16,00", "15,52"], answer: "15,92", explanation: "Deve-se alinhar vírgula sob vírgula: 12,50 + 3,42 = 15,92.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Como se escreve a fração 1/2 em forma decimal?", options: ["0,5", "0,2", "1,2", "0,05"], answer: "0,5", explanation: "1 dividido por 2 é igual a 0,5.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual número é MAIOR: 0,7 ou 0,09?", options: ["0,7", "0,09", "São iguais", "Não é possível comparar"], answer: "0,7", explanation: "0,7 é o mesmo que 0,70. 70 centésimos é maior que 9 centésimos.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quanto é 10 multiplicado por 0,45?", options: ["4,5", "45", "0,045", "450"], answer: "4,5", explanation: "Ao multiplicar por 10, a vírgula anda uma casa para a direita.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Na divisão de 5 por 2, o resultado decimal é:", options: ["2,5", "2,2", "3,0", "2,05"], answer: "2,5", explanation: "A metade de 5 é 2,5.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O número 3,075 lido por extenso é:", options: ["Três inteiros e setenta e cinco milésimos", "Três vírgula setenta e cinco", "Três inteiros e setenta e cinco centésimos", "Trinta e setenta e cinco milésimos"], answer: "Três inteiros e setenta e cinco milésimos", explanation: "A terceira casa após a vírgula representa os milésimos.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de 1,0 - 0,25?", options: ["0,75", "0,85", "1,25", "0,50"], answer: "0,75", explanation: "Pense em dinheiro: R$ 1,00 menos 25 centavos sobra 75 centavos.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O valor posicional do algarismo 8 no número 4,582 é:", options: ["Centésimos", "Décimos", "Milésimos", "Unidades"], answer: "Centésimos", explanation: "A segunda casa decimal é a dos centésimos.", skill: "Números Decimais" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quanto é 0,2 multiplicado por 0,3?", options: ["0,06", "0,6", "6,0", "0,006"], answer: "0,06", explanation: "2*3=6. Como há duas casas decimais no total nos fatores, o resultado deve ter duas: 0,06.", skill: "Números Decimais" },

  // 8º Matemática - Expressões Algébricas (9)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que define uma 'Expressão Algébrica'?", options: ["Uma combinação de números, letras (variáveis) e operações", "Apenas uma sequência de números somados", "Um desenho geométrico colorido", "O resultado final de uma divisão"], answer: "Uma combinação de números, letras (variáveis) e operações", explanation: "Utiliza letras para representar valores desconhecidos.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o valor numérico da expressão 3x + 5 quando x = 4?", options: ["17", "12", "27", "9"], answer: "17", explanation: "3*(4) + 5 = 12 + 5 = 17.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Como se representa algebricamente 'o dobro de um número somado com dez'?", options: ["2x + 10", "x² + 10", "x/2 + 10", "10x + 2"], answer: "2x + 10", explanation: "Dobro de x (2x) somado (+) com 10.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que são 'Termos Semelhantes' em uma expressão?", options: ["Termos que possuem a mesma parte literal (letras e expoentes)", "Termos que têm o mesmo número na frente", "Termos que estão um ao lado do outro", "Termos que são sempre positivos"], answer: "Termos que possuem a mesma parte literal (letras e expoentes)", explanation: "Ex: 2x e 5x são semelhantes e podem ser somados.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Simplifique a expressão: 5a + 2b - 3a + 4b.", options: ["2a + 6b", "8a + 6b", "2a + 2b", "10ab"], answer: "2a + 6b", explanation: "(5a - 3a) + (2b + 4b) = 2a + 6b.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Na expressão -4y³, o número -4 é chamado de:", options: ["Coeficiente", "Expoente", "Variável", "Incógnita"], answer: "Coeficiente", explanation: "O coeficiente é o número que multiplica a parte literal.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O resultado da multiplicação de monômios (2x) * (3x²) é:", options: ["6x³", "5x³", "6x²", "5x²"], answer: "6x³", explanation: "Multiplica os coeficientes (2x3=6) e soma os expoentes das letras (1+2=3).", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A expressão que representa 'a diferença entre o quadrado de um número e cinco' é:", options: ["x² - 5", "(x - 5)²", "2x - 5", "5 - x²"], answer: "x² - 5", explanation: "Quadrado de x (x²) menos (-) 5.", skill: "Expressões Algébricas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O que significa 'Fator Comum' em uma expressão como 2x + 2y?", options: ["Um termo que multiplica todos os outros (neste caso, o 2)", "O resultado da soma x + y", "O número que vem por último", "A letra x apenas"], answer: "Um termo que multiplica todos os outros (neste caso, o 2)", explanation: "Pode ser colocado em evidência: 2(x + y).", skill: "Expressões Algébricas" },

  // 7º Matemática - Potenciação (9)
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Na potência 5², o número 5 é o(a) _________ e o número 2 é o(a) _________.", options: ["Base / Expoente", "Expoente / Base", "Produto / Fator", "Resultado / Raiz"], answer: "Base / Expoente", explanation: "A base é multiplicada por si mesma quantas vezes o expoente mandar.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor de 3 elevado ao cubo (3³)?", options: ["27", "9", "6", "81"], answer: "27", explanation: "3 * 3 * 3 = 27.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qualquer número (diferente de zero) elevado ao expoente ZERO é igual a:", options: ["1", "0", "O próprio número", "Infinito"], answer: "1", explanation: "É uma convenção matemática fundamental.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de (-2)³ (base negativa e expoente ímpar)?", options: ["-8", "+8", "-6", "+6"], answer: "-8", explanation: "(-2) * (-2) * (-2) = +4 * (-2) = -8.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Na multiplicação de potências de mesma base (ex: 2³ * 2²), o que devemos fazer?", options: ["Repetir a base e somar os expoentes", "Multiplicar as bases e os expoentes", "Subtrair os expoentes", "Dividir as bases"], answer: "Repetir a base e somar os expoentes", explanation: "2³ * 2² = 2^(3+2) = 2⁵.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Todo número elevado ao expoente 1 é igual a:", options: ["Ele mesmo", "1", "0", "O seu dobro"], answer: "Ele mesmo", explanation: "Ex: 10¹ = 10.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor de 10 elevado à quarta potência (10⁴)?", options: ["10.000", "40", "1.000", "400"], answer: "10.000", explanation: "O 1 seguido de 4 zeros.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Na divisão de potências de mesma base (ex: 5⁷ : 5³), qual a regra?", options: ["Repetir a base e subtrair os expoentes", "Dividir as bases e os expoentes", "Somar os expoentes", "Multiplicar as bases"], answer: "Repetir a base e subtrair os expoentes", explanation: "5⁷ : 5³ = 5^(7-3) = 5⁴.", skill: "Potenciação" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O que acontece se elevarmos um número negativo a um expoente PAR (ex: (-3)²)?", options: ["O resultado será sempre positivo", "O resultado será sempre negativo", "O resultado será zero", "O resultado será ímpar"], answer: "O resultado será sempre positivo", explanation: "Menos com menos dá mais. (-3) * (-3) = +9.", skill: "Potenciação" },

  // 9º Matemática - Equações de 1º Grau (9)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que caracteriza uma 'Equação de 1º Grau'?", options: ["Uma igualdade entre expressões onde o maior expoente da incógnita é 1", "Uma conta que só usa números inteiros positivos", "Uma figura geométrica com 4 lados", "Uma divisão por zero"], answer: "Uma igualdade entre expressões onde o maior expoente da incógnita é 1", explanation: "Tem a forma geral ax + b = 0.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Resolva: 3x - 12 = 0. Qual o valor de x?", options: ["4", "-4", "12", "3"], answer: "4", explanation: "3x = 12 => x = 12 / 3 = 4.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Em uma equação, ao mudar um termo de lado da igualdade, devemos:", options: ["Inverter sua operação (ex: mais vira menos)", "Mudar a letra da incógnita", "Multiplicar o termo por zero", "Não fazer nada"], answer: "Inverter sua operação (ex: mais vira menos)", explanation: "É a propriedade da balança ou das operações inversas.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o valor de x na equação 2(x + 5) = 20?", options: ["5", "10", "15", "0"], answer: "5", explanation: "2x + 10 = 20 => 2x = 10 => x = 5.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Resolva para x: x/4 = 5.", options: ["20", "9", "1,25", "1"], answer: "20", explanation: "O 4 que está dividindo passa multiplicando: x = 5 * 4 = 20.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Se 5x + 2 = 3x + 10, qual o valor de x?", options: ["4", "6", "2", "8"], answer: "4", explanation: "5x - 3x = 10 - 2 => 2x = 8 => x = 4.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Uma equação que não possui solução real é chamada de:", options: ["Impossível", "Determinada", "Identidade", "Polinomial"], answer: "Impossível", explanation: "Ex: 0x = 5 (não existe número que vezes zero dê 5).", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que significa 'conjunto solução' de uma equação?", options: ["O valor (ou valores) que tornam a sentença verdadeira", "A lista de todos os números do mundo", "O nome dos termos da equação", "Apenas o número zero"], answer: "O valor (ou valores) que tornam a sentença verdadeira", explanation: "É o resultado que satisfaz a igualdade.", skill: "Equações de 1º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Na equação ax = b, se a for diferente de zero, x é igual a:", options: ["b/a", "a/b", "a - b", "b + a"], answer: "b/a", explanation: "Isola-se x passando o coeficiente 'a' dividindo.", skill: "Equações de 1º Grau" },

  // 6º Matemática - MDC (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que significa a sigla 'MDC'?", options: ["Máximo Divisor Comum", "Mínimo Divisível Coletivo", "Muitos Dados Curtos", "Maior Dobro Comum"], answer: "Máximo Divisor Comum", explanation: "É o maior número que divide dois ou mais números ao mesmo tempo sem deixar resto.", skill: "MDC" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o MDC entre 10 e 15?", options: ["5", "2", "3", "30"], answer: "5", explanation: "Divisores de 10: {1, 2, 5, 10}. Divisores de 15: {1, 3, 5, 15}. O maior comum é 5.", skill: "MDC" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "A técnica de decompor os números em fatores primos para achar o MDC consiste em pegar:", options: ["Apenas os fatores comuns com os menores expoentes", "Todos os fatores comuns e não comuns", "Apenas o maior número primo", "O resultado da multiplicação de todos os números"], answer: "Apenas os fatores comuns com os menores expoentes", explanation: "Ao multiplicar esses fatores, obtemos o MDC.", skill: "MDC" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o MDC entre dois números PRIMOS diferentes (ex: 7 e 11)?", options: ["1", "O produto deles", "A soma deles", "Não existe"], answer: "1", explanation: "Números primos só têm como divisor comum o número 1.", skill: "MDC" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O MDC entre 12 e 18 é:", options: ["6", "12", "3", "2"], answer: "6", explanation: "O 6 é o maior número que divide 12 (dá 2) e 18 (dá 3).", skill: "MDC" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Em problemas de dividir objetos em grupos de mesmo tamanho (o maior possível), usamos:", options: ["MDC", "MMC", "Raiz Quadrada", "Porcentagem"], answer: "MDC", explanation: "Sempre que o objetivo é 'dividir' em partes 'máximas' iguais.", skill: "MDC" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o MDC entre 20, 30 e 40?", options: ["10", "5", "2", "20"], answer: "10", explanation: "10 é o maior divisor comum aos três números.", skill: "MDC" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Se o MDC entre dois números é 1, dizemos que esses números são:", options: ["Primos entre si", "Iguais", "Pares", "Múltiplos"], answer: "Primos entre si", explanation: "Eles não compartilham nenhum divisor além do 1.", skill: "MDC" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Como conferir se um número é divisor de outro?", options: ["A divisão deve ser exata (resto igual a zero)", "A soma deles deve ser par", "O número deve terminar sempre em 1", "Multiplicando por 10"], answer: "A divisão deve ser exata (resto igual a zero)", explanation: "Um número é divisor se couber um número exato de vezes no outro.", skill: "MDC" },

  // 8º Matemática - Áreas (9)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual a fórmula para calcular a área de um RETÂNGULO?", options: ["Base * Altura (b * h)", "(Base * Altura) / 2", "Lado * 4", "Raiz quadrada da base"], answer: "Base * Altura (b * h)", explanation: "Basta multiplicar as duas dimensões perpendiculares.", skill: "Áreas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A área de um TRIÂNGULO é calculada por:", options: ["(Base * Altura) / 2", "Base * Altura", "Soma de todos os lados", "Base + Altura"], answer: "(Base * Altura) / 2", explanation: "Pois um triângulo é a metade de um paralelogramo de mesma base e altura.", skill: "Áreas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual a área de um quadrado que possui lados de 5 cm?", options: ["25 cm²", "10 cm²", "20 cm²", "50 cm²"], answer: "25 cm²", explanation: "Área = Lado * Lado => 5 * 5 = 25.", skill: "Áreas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Como se calcula a área de um TRAPÉZIO?", options: ["((Base Maior + Base Menor) * Altura) / 2", "Base * Altura", "Lado ao cubo", "Soma das diagonais"], answer: "((Base Maior + Base Menor) * Altura) / 2", explanation: "Considera-se a média das bases multiplicada pela altura.", skill: "Áreas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A fórmula para calcular a área de um CÍRCULO é:", options: ["π * r² (Pi vezes o raio ao quadrado)", "2 * π * r", "Base * Altura", "Diâmetro * 2"], answer: "π * r² (Pi vezes o raio ao quadrado)", explanation: "Onde r é o raio e π vale aproximadamente 3,14.", skill: "Áreas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Se um retângulo tem área de 40 m² e sua base é 8 m, qual sua altura?", options: ["5 m", "32 m", "4 m", "10 m"], answer: "5 m", explanation: "40 / 8 = 5.", skill: "Áreas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A área de um LOSANGO é calculada multiplicando:", options: ["As diagonais e dividindo por 2 (D * d) / 2", "Os lados e somando por 2", "A base pelo perímetro", "O raio pelo pi"], answer: "As diagonais e dividindo por 2 (D * d) / 2", explanation: "Diagonal maior vezes diagonal menor dividido por dois.", skill: "Áreas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Ao dobrarmos o lado de um quadrado, sua área aumenta em quantas vezes?", options: ["4 vezes", "2 vezes", "8 vezes", "Fica igual"], answer: "4 vezes", explanation: "Se o lado era L (L²) e vira 2L, a nova área é (2L)² = 4L².", skill: "Áreas" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Para medir a área de um terreno grande, a unidade mais comum é o:", options: ["Hectare (10.000 m²)", "Centímetro quadrado", "Litro", "Metro linear"], answer: "Hectare (10.000 m²)", explanation: "Unidade agrária correspondente a um hectômetro quadrado.", skill: "Áreas" },

  // 7º Matemática - Cálculo (9)
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de (-10) + (+15) - (-5)?", options: ["10", "30", "0", "20"], answer: "10", explanation: "(-10) + 15 + 5 => 5 + 5 = 10.", skill: "Cálculo" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O que significa 'ordem de precedência' em uma expressão numérica?", options: ["A ordem correta de resolver as operações (Multiplicação antes de Adição, etc.)", "O tamanho dos números", "A cor em que o cálculo deve ser escrito", "Sempre fazer da esquerda para a direita sem olhar o sinal"], answer: "A ordem correta de resolver as operações (Multiplicação antes de Adição, etc.)", explanation: "Garante que o resultado seja matematicamente correto.", skill: "Cálculo" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Em uma expressão com parênteses ( ), colchetes [ ] e chaves { }, qual resolvemos primeiro?", options: ["Parênteses ( )", "Chaves { }", "Colchetes [ ]", "Não tem ordem"], answer: "Parênteses ( )", explanation: "Começa-se de dentro (parênteses) para fora.", skill: "Cálculo" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Quanto vale 25% de 400?", options: ["100", "25", "40", "200"], answer: "100", explanation: "25% é o mesmo que 1/4. 400 dividido por 4 é 100.", skill: "Cálculo" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor de x na equação simples x/2 + 3 = 10?", options: ["14", "26", "7", "3,5"], answer: "14", explanation: "x/2 = 7 => x = 14.", skill: "Cálculo" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O quociente da divisão de -20 por -4 é:", options: ["+5", "-5", "+80", "-80"], answer: "+5", explanation: "Divisão de números com o mesmo sinal resulta em positivo.", skill: "Cálculo" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "A propriedade distributiva da multiplicação (ex: 2 * (3 + 4)) diz que:", options: ["O 2 deve multiplicar tanto o 3 quanto o 4", "Devemos apenas somar 2 + 3 + 4", "O resultado é sempre zero", "Não podemos multiplicar somas"], answer: "O 2 deve multiplicar tanto o 3 quanto o 4", explanation: "2*3 + 2*4 = 6 + 8 = 14.", skill: "Cálculo" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Quanto é a raiz quadrada de 49 somada com 3?", options: ["10", "7", "52", "13"], answer: "10", explanation: "Raiz de 49 é 7. 7 + 3 = 10.", skill: "Cálculo" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O que é o 'Módulo' ou 'Valor Absoluto' de um número?", options: ["A sua distância até o zero na reta numérica, sendo sempre positivo", "O número invertido com sinal negativo", "O dobro desse número", "Dividir o número por dez"], answer: "A sua distância até o zero na reta numérica, sendo sempre positivo", explanation: "Ex: |-5| = 5 e |+5| = 5.", skill: "Cálculo" },

  // 6º Matemática - Divisores (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que é um 'Divisor' de um número?", options: ["Um número que divide o outro exatamente, sem deixar resto", "Um número que é sempre maior que o outro", "O resultado de qualquer soma", "Um número primo apenas"], answer: "Um número que divide o outro exatamente, sem deixar resto", explanation: "Ex: 2 é divisor de 10 porque 10/2 = 5.", skill: "Divisores" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o conjunto de todos os divisores do número 6?", options: ["{1, 2, 3, 6}", "{2, 3, 6}", "{1, 2, 4, 6}", "{6, 12, 18}"], answer: "{1, 2, 3, 6}", explanation: "Estes são todos os números pelos quais você pode dividir 6 sem sobrar resto.", skill: "Divisores" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O número 1 é divisor de quais números?", options: ["De todos os números", "Apenas dele mesmo", "Apenas números pares", "Apenas números ímpares"], answer: "De todos os números", explanation: "Qualquer número dividido por 1 é ele mesmo (exata).", skill: "Divisores" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o único número par que é um número PRIMO?", options: ["2", "4", "0", "10"], answer: "2", explanation: "2 só tem dois divisores: 1 e ele mesmo.", skill: "Divisores" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Um número é 'Divisível por 5' quando termina em:", options: ["0 ou 5", "Apenas 5", "Qualquer número par", "1"], answer: "0 ou 5", explanation: "Critério de divisibilidade por 5.", skill: "Divisores" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Como conferimos se um número é 'Divisível por 3'?", options: ["A soma de seus algarismos deve ser um múltiplo de 3", "Ele deve terminar em 3", "Ele deve ser um número ímpar", "Basta ele ser maior que 10"], answer: "A soma de seus algarismos deve ser um múltiplo de 3", explanation: "Ex: 123 => 1+2+3 = 6 (é divisível).", skill: "Divisores" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual destes números NÃO é divisor de 20?", options: ["3", "1", "4", "5"], answer: "3", explanation: "20 / 3 não é uma conta exata (sobra resto 2).", skill: "Divisores" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O maior divisor de qualquer número (além de si mesmo, se for o caso) é:", options: ["Ele mesmo", "1", "Zero", "O seu dobro"], answer: "Ele mesmo", explanation: "Todo número é divisor de si mesmo.", skill: "Divisores" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O que define um 'Número Composto'?", options: ["Um número que possui mais de dois divisores", "Um número feito de vários outros colados", "Qualquer número negativo", "Um número que termina em 1"], answer: "Um número que possui mais de dois divisores", explanation: "Diferente dos primos, que só têm dois divisores.", skill: "Divisores" },

  // 9º Matemática - Triângulos (9)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o nome do triângulo que possui um ângulo reto (90 graus)?", options: ["Triângulo Retângulo", "Triângulo Equilátero", "Triângulo Obtusângulo", "Triângulo Acutângulo"], answer: "Triângulo Retângulo", explanation: "Possui as partes chamadas catetos e hipotenusa.", skill: "Triângulos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Em um triângulo equilátero, todos os ângulos internos medem:", options: ["60°", "90°", "45°", "180°"], answer: "60°", explanation: "Como os lados são iguais, os ângulos também são: 180 / 3 = 60.", skill: "Triângulos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que diz a 'Condição de Existência' de um triângulo?", options: ["Um lado deve ser sempre menor que a soma dos outros dois", "Todos os lados devem ser iguais", "Um ângulo deve ser sempre o dobro do outro", "A área deve ser maior que 10"], answer: "Um lado deve ser sempre menor que a soma dos outros dois", explanation: "Caso contrário, os segmentos de reta não se encontram para fechar a figura.", skill: "Triângulos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O triângulo que possui todos os três ângulos internos MENORES que 90° é o:", options: ["Acutângulo", "Obtusângulo", "Isósceles", "Escaleno"], answer: "Acutângulo", explanation: "Ângulos agudos (< 90°).", skill: "Triângulos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O segmento de reta que liga um vértice ao ponto médio do lado oposto é a:", options: ["Mediana", "Bissetriz", "Altura", "Mediatriz"], answer: "Mediana", explanation: "O ponto onde as 3 medianas se encontram é o Baricentro (centro de massa).", skill: "Triângulos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que é o 'Incentro' de um triângulo?", options: ["O ponto de encontro das bissetrizes internas (centro do círculo inscrito)", "O ponto de encontro das alturas", "O maior lado do triângulo", "A soma das áreas internas"], answer: "O ponto de encontro das bissetrizes internas (centro do círculo inscrito)", explanation: "Fica sempre dentro do triângulo.", skill: "Triângulos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual triângulo possui dois lados com a mesma medida e um diferente?", options: ["Isósceles", "Equilátero", "Escaleno", "Retângulo"], answer: "Isósceles", explanation: "Dois lados iguais = Isósceles.", skill: "Triângulos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "A 'Base' e a 'Altura' de um triângulo retângulo coincidem com os seus:", options: ["Catetos", "Hipotenusa", "Medianas", "Vértices apenas"], answer: "Catetos", explanation: "Como os catetos formam 90°, um pode ser a base e o outro a altura.", skill: "Triângulos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O triângulo que possui um ângulo interno MAIOR que 90° é o:", options: ["Obtusângulo", "Retângulo", "Acutângulo", "Equilátero"], answer: "Obtusângulo", explanation: "Possui um ângulo obtuso.", skill: "Triângulos" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 27 com ${batch.length} questões de Matemática adicionado.`);
