import fs from 'fs';
const filePath = 'questions.js';
function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const ids = content.match(/id:\s*(\d+)/g).map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}
const startId = getNextId();
console.log(`Sprint 9 a partir do ID: ${startId}`);
const batch = [
  // MATEMÁTICA (7º) - Operações com Inteiros (9)
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o resultado de (+8) + (-3)?", options: ["-5", "5", "11", "-11"], answer: "5", explanation: "Sinais diferentes: subtrai e fica o sinal do maior.", skill: "Operações com Inteiros" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Quanto é (-6) - (-2)?", options: ["-8", "-4", "4", "8"], answer: "-4", explanation: "Menos com menos vira mais: -6 + 2 = -4.", skill: "Operações com Inteiros" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O resultado de (-7) x (+3) é:", options: ["21", "-21", "10", "-10"], answer: "-21", explanation: "Sinais diferentes na multiplicação: resultado negativo.", skill: "Operações com Inteiros" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Quanto é (-20) ÷ (-4)?", options: ["-5", "5", "-16", "16"], answer: "5", explanation: "Sinais iguais na divisão: resultado positivo.", skill: "Operações com Inteiros" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "O oposto (simétrico) de +9 é:", options: ["9", "0", "-9", "1/9"], answer: "-9", explanation: "Oposto: mesmo valor, sinal contrário.", skill: "Operações com Inteiros" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Na reta numérica, qual número está à ESQUERDA do zero?", options: ["+3", "+1", "0", "-2"], answer: "-2", explanation: "Números negativos ficam à esquerda do zero.", skill: "Operações com Inteiros" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor absoluto (módulo) de -15?", options: ["-15", "15", "0", "1"], answer: "15", explanation: "|−15| = 15. Módulo é a distância até o zero.", skill: "Operações com Inteiros" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Quanto é (-3)² (menos três ao quadrado)?", options: ["-9", "9", "-6", "6"], answer: "9", explanation: "(-3) x (-3) = +9. Menos com menos dá mais.", skill: "Operações com Inteiros" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Na expressão 5 + (-8) + 3, o resultado é:", options: ["0", "16", "-6", "10"], answer: "0", explanation: "5 - 8 + 3 = 0.", skill: "Operações com Inteiros" },

  // CIÊNCIAS (8º) - Ecologia / Clima (9)
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O efeito estufa é um fenômeno natural que mantém a Terra aquecida. O problema ocorre quando:", options: ["Ele deixa de existir", "É intensificado pela poluição (gases como CO₂)", "A Terra esfria demais", "Chove muito"], answer: "É intensificado pela poluição (gases como CO₂)", explanation: "O excesso de gases retém mais calor.", skill: "Ecologia / Clima" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A destruição da Camada de Ozônio é causada principalmente por:", options: ["Vapor de água", "CFCs (clorofluorcarbonetos)", "Oxigênio", "Nitrogênio"], answer: "CFCs (clorofluorcarbonetos)", explanation: "Usados em aerossóis e refrigeradores antigos.", skill: "Ecologia / Clima" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A chuva ácida é formada quando poluentes como SO₂ e NO₂ reagem com:", options: ["O solo", "A água da atmosfera", "As plantas", "O gelo"], answer: "A água da atmosfera", explanation: "Forma ácidos que caem com a chuva.", skill: "Ecologia / Clima" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O aquecimento global pode causar:", options: ["Redução do nível dos mares", "Derretimento das calotas polares e elevação do nível do mar", "Aumento do gelo nos polos", "Nenhum efeito"], answer: "Derretimento das calotas polares e elevação do nível do mar", explanation: "Ameaça cidades costeiras do mundo.", skill: "Ecologia / Clima" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A queimada de florestas contribui para o aquecimento global porque:", options: ["Resfria o ambiente", "Libera grandes quantidades de CO₂", "Produz chuva", "Aumenta a biodiversidade"], answer: "Libera grandes quantidades de CO₂", explanation: "O carbono armazenado nas árvores vai para a atmosfera.", skill: "Ecologia / Clima" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A inversão térmica, que agrava a poluição nas cidades, ocorre quando:", options: ["O ar quente fica preso embaixo do ar frio", "O ar frio fica preso embaixo do ar quente", "Chove muito forte", "Faz muito calor"], answer: "O ar frio fica preso embaixo do ar quente", explanation: "Impede a dispersão dos poluentes.", skill: "Ecologia / Clima" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Qual gás é o principal responsável pelo efeito estufa intensificado?", options: ["Oxigênio (O₂)", "Nitrogênio (N₂)", "Dióxido de Carbono (CO₂)", "Hélio (He)"], answer: "Dióxido de Carbono (CO₂)", explanation: "Produzido pela queima de combustíveis fósseis.", skill: "Ecologia / Clima" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O Protocolo de Kyoto foi um acordo internacional para:", options: ["Aumentar a poluição", "Reduzir as emissões de gases de efeito estufa", "Proibir a agricultura", "Criar novas indústrias"], answer: "Reduzir as emissões de gases de efeito estufa", explanation: "Acordo climático histórico de 1997.", skill: "Ecologia / Clima" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "As ilhas de calor são fenômenos que ocorrem em:", options: ["Oceanos", "Florestas tropicais", "Grandes centros urbanos", "Desertos gelados"], answer: "Grandes centros urbanos", explanation: "Concreto e asfalto absorvem e irradiam mais calor.", skill: "Ecologia / Clima" },

  // HISTÓRIA (9º) - Guerra Mundial (9)
  { grade: "9º", discipline: "História", type: "multiple", text: "A Primeira Guerra Mundial teve início em qual ano?", options: ["1905", "1914", "1918", "1939"], answer: "1914", explanation: "Durou de 1914 a 1918.", skill: "Guerra Mundial" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O estopim da Primeira Guerra foi o assassinato do arquiduque:", options: ["Napoleão Bonaparte", "Francisco Ferdinando", "Otto Von Bismarck", "Winston Churchill"], answer: "Francisco Ferdinando", explanation: "Assassinado em Sarajevo, na Bósnia.", skill: "Guerra Mundial" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A Segunda Guerra Mundial começou com a invasão de qual país pela Alemanha Nazista?", options: ["França", "Inglaterra", "Polônia", "Rússia"], answer: "Polônia", explanation: "Em 1º de setembro de 1939.", skill: "Guerra Mundial" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Quem foi o líder nazista da Alemanha durante a Segunda Guerra?", options: ["Mussolini", "Stalin", "Adolf Hitler", "Churchill"], answer: "Adolf Hitler", explanation: "Ditador que levou ao genocídio do Holocausto.", skill: "Guerra Mundial" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O Holocausto foi o genocídio de milhões de:", options: ["Soldados americanos", "Judeus e outros grupos perseguidos", "Políticos ingleses", "Agricultores franceses"], answer: "Judeus e outros grupos perseguidos", explanation: "Aproximadamente 6 milhões de judeus foram assassinados.", skill: "Guerra Mundial" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O 'Dia D' (6 de junho de 1944) foi:", options: ["O início da guerra", "A invasão aliada na Normandia, França", "A rendição do Japão", "A criação da ONU"], answer: "A invasão aliada na Normandia, França", explanation: "Ponto de virada para a libertação da Europa.", skill: "Guerra Mundial" },
  { grade: "9º", discipline: "História", type: "multiple", text: "As bombas atômicas foram lançadas pelos EUA sobre quais cidades japonesas?", options: ["Tóquio e Osaka", "Hiroshima e Nagasaki", "Kyoto e Sendai", "Yokohama e Kobe"], answer: "Hiroshima e Nagasaki", explanation: "Em agosto de 1945, encerrando a guerra.", skill: "Guerra Mundial" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A Tríplice Aliança na Primeira Guerra era formada por:", options: ["França, Inglaterra e Rússia", "Alemanha, Áustria-Hungria e Itália", "EUA, Brasil e Japão", "China, Índia e Egito"], answer: "Alemanha, Áustria-Hungria e Itália", explanation: "A Itália depois trocou de lado.", skill: "Guerra Mundial" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A organização criada após a Segunda Guerra para manter a paz mundial foi a:", options: ["Liga das Nações", "OTAN", "ONU (Organização das Nações Unidas)", "União Europeia"], answer: "ONU (Organização das Nações Unidas)", explanation: "Fundada em 1945.", skill: "Guerra Mundial" },

  // EDUCAÇÃO FÍSICA (6º) - Esportes de Quadra (9)
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual esporte de quadra utiliza as mãos para passar e arremessar a bola ao gol?", options: ["Futebol", "Basquete", "Handebol", "Tênis"], answer: "Handebol", explanation: "O handebol é jogado com as mãos em uma quadra.", skill: "Esportes de Quadra" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No basquete, a cesta vale quantos pontos em um arremesso normal (dentro do garrafão)?", options: ["1 ponto", "2 pontos", "3 pontos", "5 pontos"], answer: "2 pontos", explanation: "Lance livre = 1, normal = 2, de fora do arco = 3.", skill: "Esportes de Quadra" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No Futsal, cada equipe joga com quantos jogadores em quadra?", options: ["3", "4", "5", "7"], answer: "5", explanation: "4 jogadores de linha + 1 goleiro.", skill: "Esportes de Quadra" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "A quadra de voleibol é dividida ao meio por:", options: ["Uma linha pintada", "Uma rede", "Um muro", "Uma corda"], answer: "Uma rede", explanation: "Os jogadores não podem invadir o lado adversário.", skill: "Esportes de Quadra" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No Handebol, é permitido dar até quantos passos com a bola na mão?", options: ["1", "2", "3", "Ilimitados"], answer: "3", explanation: "Após 3 passos, o jogador deve passar, quicar ou arremessar.", skill: "Esportes de Quadra" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No basquete, a ação de bater a bola no chão enquanto se desloca é o:", options: ["Passe", "Arremesso", "Drible", "Rebote"], answer: "Drible", explanation: "Regra fundamental para se locomover com a bola.", skill: "Esportes de Quadra" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual a principal diferença entre Futsal e Futebol de campo?", options: ["O tamanho da bola e da quadra", "A cor do uniforme", "O número de árbitros", "Não há diferença"], answer: "O tamanho da bola e da quadra", explanation: "O futsal é jogado em quadra menor e com bola mais pesada.", skill: "Esportes de Quadra" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No voleibol, cada equipe pode tocar a bola no máximo quantas vezes antes de enviá-la ao outro lado?", options: ["1", "2", "3", "4"], answer: "3", explanation: "Geralmente: recepção, levantamento e ataque.", skill: "Esportes de Quadra" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O 'Fair Play' nos esportes de quadra significa:", options: ["Jogar para perder", "Jogo limpo, com respeito às regras e ao adversário", "Fazer o máximo de faltas", "Ignorar o árbitro"], answer: "Jogo limpo, com respeito às regras e ao adversário", explanation: "Valor fundamental do esporte.", skill: "Esportes de Quadra" },

  // PORTUGUÊS (9º) - Período Composto (9)
  { grade: "9º", discipline: "Português", type: "multiple", text: "Um período composto é formado por:", options: ["Uma única oração", "Duas ou mais orações", "Apenas um verbo", "Nenhum verbo"], answer: "Duas ou mais orações", explanation: "Cada oração possui um verbo ou locução verbal.", skill: "Período Composto" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "No período 'Estudei muito porque quero passar', a conjunção 'porque' indica:", options: ["Oposição", "Causa", "Concessão", "Tempo"], answer: "Causa", explanation: "Conjunção causal: explica o motivo.", skill: "Período Composto" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "No período composto por COORDENAÇÃO, as orações são:", options: ["Dependentes entre si", "Independentes entre si", "Sem sentido", "Apenas nominais"], answer: "Independentes entre si", explanation: "Cada oração tem sentido completo sozinha.", skill: "Período Composto" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "No período composto por SUBORDINAÇÃO, a oração subordinada:", options: ["É independente", "Depende da oração principal para ter sentido", "Não existe", "Sempre vem primeiro"], answer: "Depende da oração principal para ter sentido", explanation: "A subordinada funciona como termo da principal.", skill: "Período Composto" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Em 'Ele saiu, MAS voltou logo', a conjunção 'mas' é:", options: ["Aditiva", "Adversativa", "Alternativa", "Conclusiva"], answer: "Adversativa", explanation: "Indica oposição ou contraste.", skill: "Período Composto" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Qual das seguintes é uma conjunção ADITIVA?", options: ["Mas", "Ou", "E", "Portanto"], answer: "E", explanation: "Soma ideias: 'Estudei e passei'.", skill: "Período Composto" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "A oração 'Quando cheguei, todos já tinham saído' possui uma subordinada:", options: ["Substantiva", "Adjetiva", "Adverbial temporal", "Coordenada"], answer: "Adverbial temporal", explanation: "'Quando cheguei' indica circunstância de tempo.", skill: "Período Composto" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "Em 'É necessário QUE todos participem', a oração 'que todos participem' é:", options: ["Coordenada", "Subordinada substantiva", "Subordinada adjetiva", "Principal"], answer: "Subordinada substantiva", explanation: "Funciona como sujeito da oração principal.", skill: "Período Composto" },
  { grade: "9º", discipline: "Português", type: "multiple", text: "A conjunção 'portanto' é classificada como:", options: ["Adversativa", "Alternativa", "Conclusiva", "Explicativa"], answer: "Conclusiva", explanation: "Indica conclusão: 'Estudou, portanto passou'.", skill: "Período Composto" }
];

const questionsWithIds = batch.map((q, i) => ({ id: startId + i, ...q }));
const str = questionsWithIds.map(q =>
  `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`
).join(',\n');
const content = fs.readFileSync(filePath, 'utf-8');
fs.writeFileSync(filePath, content.replace(/\s*\];\s*$/, ',\n\n' + str + '\n];\n'), 'utf-8');
console.log(`Sucesso! Sprint 9: ${batch.length} questões adicionadas.`);
