import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 5300;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 22: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 8º Português - Período Composto (9)
  { grade: "8º", discipline: "Português", type: "multiple", text: "O que caracteriza um 'Período Composto'?", options: ["Possui duas ou mais orações (verbos)", "Possui apenas um verbo", "Não possui nenhum verbo", "É formado apenas por adjetivos"], answer: "Possui duas ou mais orações (verbos)", explanation: "O número de orações é igual ao número de verbos ou locuções verbais.", skill: "Período Composto" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "As orações coordenadas 'Assindéticas' são aquelas que:", options: ["Não são ligadas por conjunções (apenas vírgulas)", "São ligadas por 'e', 'mas' ou 'ou'", "Dependem totalmente de outra oração para ter sentido", "São formadas apenas por uma palavra"], answer: "Não são ligadas por conjunções (apenas vírgulas)", explanation: "Ex: 'Cheguei, vi, venci.'", skill: "Período Composto" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Na frase 'Estudei muito, MAS não passei', a oração sublinhada é uma coordenada:", options: ["Adversativa (oposição)", "Aditiva (soma)", "Conclusiva", "Explicativa"], answer: "Adversativa (oposição)", explanation: "A conjunção 'mas' indica uma ideia contrária à anterior.", skill: "Período Composto" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Qual conjunção abaixo indica uma ideia de CONCLUSÃO no período composto?", options: ["Portanto", "Porém", "Entretanto", "Pois (no início)"], answer: "Portanto", explanation: "Outras conclusivas: logo, por isso, assim.", skill: "Período Composto" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Orações 'Subordinadas' são aquelas que:", options: ["Exercem uma função sintática em relação à oração principal", "Têm sentido completo sozinhas", "Não possuem sujeito", "São ligadas apenas por vírgulas"], answer: "Exercem uma função sintática em relação à oração principal", explanation: "Uma depende da outra para que o sentido seja completo.", skill: "Período Composto" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Na frase 'Espero QUE você seja feliz', a oração iniciada por 'que' é:", options: ["Subordinada Substantiva", "Coordenada Explicativa", "Oração Principal", "Frase sem sentido"], answer: "Subordinada Substantiva", explanation: "Funciona como objeto direto do verbo 'esperar'.", skill: "Período Composto" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Oração subordinada 'Adverbial Condicional' indica uma condição. Qual conjunção a introduz?", options: ["Se", "Porque", "Embora", "Quando"], answer: "Se", explanation: "Ex: 'Se chover, não irei.'", skill: "Período Composto" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "A oração subordinada 'Adjetiva Restritiva' serve para:", options: ["Limitar o sentido do substantivo ao qual se refere (sem vírgulas)", "Explicar todo o grupo de uma vez (com vírgulas)", "Substituir o sujeito da frase", "Indicar o tempo da ação"], answer: "Limitar o sentido do substantivo ao qual se refere (sem vírgulas)", explanation: "Ex: 'Os alunos que estudam passam.' (Só os que estudam).", skill: "Período Composto" },
  { grade: "8º", discipline: "Português", type: "multiple", text: "Qual destas conjunções introduz uma ideia de CAUSA?", options: ["Visto que", "A fim de que", "Contanto que", "Todavia"], answer: "Visto que", explanation: "Indica o motivo pelo qual algo aconteceu.", skill: "Período Composto" },

  // 6º Matemática - Numeração (9)
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O nosso sistema de numeração é o Decimal (base 10). Isso significa que:", options: ["Agrupamos os elementos de 10 em 10", "Usamos apenas os números de 1 a 9", "Não existe o número zero", "Usamos letras em vez de números"], answer: "Agrupamos os elementos de 10 em 10", explanation: "10 unidades = 1 dezena; 10 dezenas = 1 centena, etc.", skill: "Numeração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "No número 4.562, qual o valor POSICIONAL do algarismo 5?", options: ["500", "50", "5.000", "5"], answer: "500", explanation: "O 5 está na ordem das centenas simples.", skill: "Numeração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Como se representa o número 19 em algarismos ROMANOS?", options: ["XIX", "XVIIII", "XVIV", "XXI"], answer: "XIX", explanation: "X(10) + IX(9) = 19.", skill: "Numeração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O algarismo 'zero' no nosso sistema serve para:", options: ["Indicar a ausência de valor em uma determinada ordem", "Apenas enfeitar o número", "Ser usado apenas no final dos números", "Representar o número um"], answer: "Indicar a ausência de valor em uma determinada ordem", explanation: "É um marcador de posição fundamental.", skill: "Numeração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Quantas ordens tem o número 125.480?", options: ["6 ordens", "2 ordens", "3 ordens", "5 ordens"], answer: "6 ordens", explanation: "Cada algarismo ocupa uma ordem (unidade, dezena, centena...).", skill: "Numeração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "O número romano 'L' representa qual valor?", options: ["50", "100", "5", "500"], answer: "50", explanation: "C=100, D=500, M=1000.", skill: "Numeração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual o sucessor do número 999.999?", options: ["1.000.000 (Um milhão)", "999.998", "1.000.001", "10.000.000"], answer: "1.000.000 (Um milhão)", explanation: "Sucessor é o número + 1.", skill: "Numeração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "No sistema egípcio de numeração, os símbolos podiam ser repetidos até quantas vezes?", options: ["9 vezes", "3 vezes", "10 vezes", "Infinitas vezes"], answer: "9 vezes", explanation: "Ao chegar em 10, trocava-se pelo símbolo da próxima ordem.", skill: "Numeração" },
  { grade: "6º", discipline: "Matemática", type: "multiple", text: "Qual a decomposição correta do número 347?", options: ["3 * 100 + 4 * 10 + 7 * 1", "30 + 40 + 7", "3 * 10 + 4 * 100 + 7", "300 + 4 + 7"], answer: "3 * 100 + 4 * 10 + 7 * 1", explanation: "3 centenas, 4 dezenas e 7 unidades.", skill: "Numeração" },

  // 8º História - Brasil República (9)
  { grade: "8º", discipline: "História", type: "multiple", text: "A Proclamação da República no Brasil ocorreu em que data?", options: ["15 de novembro de 1889", "7 de setembro de 1822", "13 de maio de 1888", "21 de abril de 1792"], answer: "15 de novembro de 1889", explanation: "Liderada pelo Marechal Deodoro da Fonseca.", skill: "Brasil República" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O primeiro período da República (1889-1894) é chamado de:", options: ["República da Espada", "República do Café com Leite", "Era Vargas", "Estado Novo"], answer: "República da Espada", explanation: "Governo dos militares (Deodoro e Floriano Peixoto).", skill: "Brasil República" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Quem foi o primeiro presidente civil do Brasil?", options: ["Prudente de Morais", "Marechal Deodoro", "Getúlio Vargas", "Barão do Rio Branco"], answer: "Prudente de Morais", explanation: "Marcou o início da predominância das elites agrárias.", skill: "Brasil República" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A 'Política do Café com Leite' era o revezamento no poder entre elites de:", options: ["São Paulo e Minas Gerais", "Rio de Janeiro e Bahia", "Paraná e Santa Catarina", "Pernambuco e Ceará"], answer: "São Paulo e Minas Gerais", explanation: "Os estados mais ricos e populosos da época.", skill: "Brasil República" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O 'Voto de Cabresto' na República Velha era:", options: ["O controle do voto dos eleitores pelos coronéis locais", "Um voto secreto e inviolável", "O voto dado apenas a mulheres", "A proibição de votar em fazendeiros"], answer: "O controle do voto dos eleitores pelos coronéis locais", explanation: "O voto era aberto, facilitando a pressão e a fraude.", skill: "Brasil República" },
  { grade: "8º", discipline: "História", type: "multiple", text: "Qual movimento social de caráter religioso e messiânico ocorreu no sertão da Bahia no início da República?", options: ["Guerra de Canudos", "Cabanagem", "Revolução Farroupilha", "Revolta da Vacina"], answer: "Guerra de Canudos", explanation: "Liderada por Antônio Conselheiro e destruída pelo exército.", skill: "Brasil República" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A 'Revolta da Armada' foi uma rebelião de qual setor militar contra o governo?", options: ["Marinha", "Exército", "Aeronáutica", "Polícia Militar"], answer: "Marinha", explanation: "Ocorreu no Rio de Janeiro contra Floriano Peixoto.", skill: "Brasil República" },
  { grade: "8º", discipline: "História", type: "multiple", text: "A Constituição de 1891 estabeleceu o Brasil como um Estado:", options: ["Laico (separado da Igreja) e Federalista", "Católico oficial", "Monárquico parlamentar", "Socialista"], answer: "Laico (separado da Igreja) e Federalista", explanation: "Deu mais autonomia para os Estados.", skill: "Brasil República" },
  { grade: "8º", discipline: "História", type: "multiple", text: "O 'Coronelismo' era um sistema de poder baseado em:", options: ["Grandes proprietários de terras com poder político e militar local", "Comerciantes estrangeiros", "Professores universitários", "Líderes sindicais"], answer: "Grandes proprietários de terras com poder político e militar local", explanation: "Base do poder na Primeira República.", skill: "Brasil República" },

  // 9º Geografia - Problemas Sociais (9)
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O processo de crescimento desordenado das cidades gera a 'Segregação Socioespacial'. O que é isso?", options: ["Divisão da cidade entre áreas ricas com infraestrutura e áreas pobres precárias", "União de todas as classes sociais no mesmo bairro", "Expulsão de todas as indústrias da cidade", "Criação de parques em todos os bairros"], answer: "Divisão da cidade entre áreas ricas com infraestrutura e áreas pobres precárias", explanation: "Causa exclusão social e desigualdade de acesso a serviços.", skill: "Problemas Sociais" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A falta de moradia digna leva ao surgimento de:", options: ["Favelas e ocupações irregulares", "Grandes mansões automatizadas", "Parques nacionais urbanos", "Shopping centers populares"], answer: "Favelas e ocupações irregulares", explanation: "Áreas muitas vezes sem saneamento básico ou segurança.", skill: "Problemas Sociais" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O 'Déficit Habitacional' nas metrópoles brasileiras significa:", options: ["A falta de casas suficientes para a população que precisa", "O excesso de casas vazias de luxo apenas", "O imposto cobrado sobre as janelas", "A altura máxima dos prédios"], answer: "A falta de casas suficientes para a população que precisa", explanation: "Um dos grandes desafios das políticas públicas urbanas.", skill: "Problemas Sociais" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A precariedade do 'Saneamento Básico' (esgoto e água tratada) causa:", options: ["Aumento de doenças infecciosas e poluição de rios", "Melhora na qualidade de vida", "Aumento do preço da terra", "Fim da seca"], answer: "Aumento de doenças infecciosas e poluição de rios", explanation: "A saúde pública está diretamente ligada à higiene ambiental.", skill: "Problemas Sociais" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A violência urbana nas grandes cidades está frequentemente associada à:", options: ["Desigualdade social e falta de oportunidades para jovens", "Apenas à falta de luz nas ruas", "Ao excesso de parques", "À proibição de dirigir à noite"], answer: "Desigualdade social e falta de oportunidades para jovens", explanation: "É um problema complexo que exige educação e segurança.", skill: "Problemas Sociais" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O 'Desemprego Estrutural' no mundo globalizado ocorre devido à:", options: ["Substituição do trabalho humano por máquinas e tecnologia", "Falta de vontade das pessoas de trabalhar", "Proibição de empresas abrirem vagas", "Falta de feriados"], answer: "Substituição do trabalho humano por máquinas e tecnologia", explanation: "Exige que o trabalhador tenha cada vez mais qualificação.", skill: "Problemas Sociais" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O fenômeno do 'Subemprego' (ou informalidade) caracteriza-se por:", options: ["Trabalhos sem carteira assinada ou direitos garantidos", "Trabalhos embaixo da terra", "Trabalhos de apenas uma hora por mês", "Trabalhos que pagam fortunas"], answer: "Trabalhos sem carteira assinada ou direitos garantidos", explanation: "Ex: vendedores ambulantes, entregadores de aplicativos.", skill: "Problemas Sociais" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A 'Gentrificação' é o processo de:", options: ["Valorização de uma área urbana que expulsa os moradores pobres originais", "Plantar árvores frutíferas nas calçadas", "Construir estádios de futebol em favelas", "Aumento da criminalidade"], answer: "Valorização de uma área urbana que expulsa os moradores pobres originais", explanation: "O custo de vida sobe e a classe média/alta ocupa o lugar.", skill: "Problemas Sociais" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A poluição visual e sonora nas cidades pode causar:", options: ["Estresse, irritabilidade e perda de audição", "Aumento da inteligência", "Melhora no sono", "Diminuição do apetite"], answer: "Estresse, irritabilidade e perda de audição", explanation: "São formas de degradação da qualidade de vida urbana.", skill: "Problemas Sociais" },

  // 9º Arte - Expressionismo Abstrato (9)
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O 'Expressionismo Abstrato' surgiu após a 2ª Guerra Mundial principalmente nos:", options: ["Estados Unidos (Nova York)", "França (Paris)", "Japão (Tóquio)", "Brasil (São Paulo)"], answer: "Estados Unidos (Nova York)", explanation: "Foi o primeiro movimento artístico americano a ter influência mundial.", skill: "Expressionismo Abstrato" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Qual a principal característica da pintura Expressionista Abstrata?", options: ["Liberdade gestual e ausência de figuras reconhecíveis", "Pintura de retratos reais de reis", "Uso de formas geométricas perfeitas apenas", "Cópia exata da natureza"], answer: "Liberdade gestual e ausência de figuras reconhecíveis", explanation: "Foca na emoção e no ato de pintar em si.", skill: "Expressionismo Abstrato" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Quem é o artista mais famoso do 'Action Painting' (Pintura de Ação)?", options: ["Jackson Pollock", "Pablo Picasso", "Andy Warhol", "Claude Monet"], answer: "Jackson Pollock", explanation: "Famoso por gotejar tinta sobre telas gigantes no chão.", skill: "Expressionismo Abstrato" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A técnica de gotejar ou respingar tinta sobre a tela é chamada de:", options: ["Dripping", "Vitral", "Aquarela", "Gravura"], answer: "Dripping", explanation: "Pollock usava paus ou latas perfuradas para criar ritmos visuais.", skill: "Expressionismo Abstrato" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O 'Color Field Painting' (Pintura de Campos de Cor) foca em:", options: ["Grandes áreas coloridas que visam criar uma experiência espiritual/emocional", "Desenhar campos de futebol perfeitos", "Usar apenas sementes de flores na tela", "Pintar apenas o arco-íris"], answer: "Grandes áreas coloridas que visam criar uma experiência espiritual/emocional", explanation: "Mark Rothko é o maior representante deste estilo.", skill: "Expressionismo Abstrato" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Para os expressionistas abstratos, a tela era vista como um:", options: ["Campo de ação onde o artista registrava seu movimento", "Espelho para ver o próprio rosto", "Quadro de avisos escolares", "Pedaço de papel de parede"], answer: "Campo de ação onde o artista registrava seu movimento", explanation: "A pintura é o vestígio físico de uma performance.", skill: "Expressionismo Abstrato" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Willem de Kooning foi um artista que misturou abstração com:", options: ["Figuras humanas (especialmente séries de Mulheres)", "Máquinas industriais frias", "Desenhos animados", "Fotografias de jornais"], answer: "Figuras humanas (especialmente séries de Mulheres)", explanation: "Sua obra era agressiva e carregada de matéria pictórica.", skill: "Expressionismo Abstrato" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O movimento refletia o clima de incerteza e angústia do período de:", options: ["Pós-Guerra e Guerra Fria", "Brasil Colônia", "Revolução Industrial inicial", "Império Romano"], answer: "Pós-Guerra e Guerra Fria", explanation: "Buscava uma linguagem que expressasse o trauma e a busca por liberdade.", skill: "Expressionismo Abstrato" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "As obras Expressionistas Abstratas costumam ser de tamanho:", options: ["Monumental (telas imensas)", "Muito pequeno (minituras)", "Sempre circulares", "Feitas apenas em cartões de visita"], answer: "Monumental (telas imensas)", explanation: "Visavam envolver o espectador fisicamente na experiência da cor.", skill: "Expressionismo Abstrato" },

  // 8º Ed. Física - Fisiologia (9)
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "O que estuda a Fisiologia do Exercício?", options: ["As mudanças no funcionamento do organismo durante a atividade física", "Apenas a história dos esportes antigos", "Regras do vôlei e basquete", "A construção das pistas de atletismo"], answer: "As mudanças no funcionamento do organismo durante a atividade física", explanation: "Entender como o corpo responde e se adapta ao esforço.", skill: "Fisiologia" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Qual o principal combustível utilizado pelo corpo durante exercícios INTENSOS?", options: ["Glicose (Carboidratos)", "Vitaminas minerais", "Proteínas apenas", "Água gelada"], answer: "Glicose (Carboidratos)", explanation: "A glicose é quebrada rapidamente para gerar ATP (energia).", skill: "Fisiologia" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A frequência cardíaca aumenta durante o exercício para:", options: ["Bombear mais sangue com oxigênio para os músculos", "Esfriar o cérebro", "Gastar menos energia", "Parar a respiração"], answer: "Bombear mais sangue com oxigênio para os músculos", explanation: "Os músculos ativos exigem mais O2 e nutrientes.", skill: "Fisiologia" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A ATP (Adenosina Trifosfato) é conhecida como a:", options: ["Moeda energética das células", "Célula de gordura do fígado", "Fibra muscular mais forte", "Proteína da pele"], answer: "Moeda energética das células", explanation: "É a energia imediata que faz o músculo contrair.", skill: "Fisiologia" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "O suor tem como função fisiológica principal:", options: ["Regular a temperatura corporal (resfriar o corpo)", "Eliminar gordura acumulada", "Apenas molhar a roupa", "Aumentar a força física"], answer: "Regular a temperatura corporal (resfriar o corpo)", explanation: "A evaporação do suor retira calor da pele.", skill: "Fisiologia" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "Exercícios AERÓBICOS são aqueles que utilizam predominantemente:", options: ["Oxigênio para produzir energia", "Força explosiva sem respirar", "Apenas os braços", "Mergulho debaixo d'água"], answer: "Oxigênio para produzir energia", explanation: "Ex: Corrida rítmica, natação longa, ciclismo.", skill: "Fisiologia" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A hipertrofia muscular é o processo de:", options: ["Aumento do tamanho das fibras musculares pelo treino", "Diminuição dos músculos por falta de uso", "Troca dos ossos por cartilagem", "Crescimento apenas da gordura"], answer: "Aumento do tamanho das fibras musculares pelo treino", explanation: "Ocorre como resposta ao treinamento de força.", skill: "Fisiologia" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "O 'Ácido Lático' acumulado nos músculos pode causar:", options: ["Sensação de queimação e fadiga temporária", "Aumento imediato da força", "Melhora no sono", "Visão embaçada"], answer: "Sensação de queimação e fadiga temporária", explanation: "Produzido em exercícios intensos quando o O2 é insuficiente.", skill: "Fisiologia" },
  { grade: "8º", discipline: "Educação Física", type: "multiple", text: "A unidade básica de contração do músculo chama-se:", options: ["Sarcômero", "Neurônio", "Plaqueta", "Enzima"], answer: "Sarcômero", explanation: "Filamentos de actina e miosina deslizam entre si.", skill: "Fisiologia" },

  // 7º Ciências - Sistema Digestório (9)
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Onde começa o processo de digestão humana?", options: ["Na boca (mastigação e salivação)", "No estômago", "No intestino", "No fígado"], answer: "Na boca (mastigação e salivação)", explanation: "A digestão mecânica (dentes) e química (ptialina) inicia na boca.", skill: "Sistema Digestório" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual órgão transporta o alimento da boca até o estômago?", options: ["Esôfago", "Traqueia", "Uretra", "Pâncreas"], answer: "Esôfago", explanation: "Realiza os movimentos peristálticos para empurrar o bolo alimentar.", skill: "Sistema Digestório" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O líquido produzido no estômago para digerir proteínas é o:", options: ["Suco Gástrico (com ácido clorídrico)", "Bile", "Suco pancreático", "Saliva"], answer: "Suco Gástrico (com ácido clorídrico)", explanation: "O ambiente ácido ajuda na quebra química das carnes.", skill: "Sistema Digestório" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual a função da BILE, produzida pelo fígado?", options: ["Emulsionar (quebrar) as gorduras", "Digerir açúcares rápidos", "Produzir vitaminas", "Guardar a urina"], answer: "Emulsionar (quebrar) as gorduras", explanation: "Funciona como um 'detergente' natural para facilitar a digestão.", skill: "Sistema Digestório" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Onde ocorre a maior parte da absorção de nutrientes para o sangue?", options: ["Intestino Delgado", "Intestino Grosso", "Estômago", "Língua"], answer: "Intestino Delgado", explanation: "Ocorre através das vilosidades intestinais.", skill: "Sistema Digestório" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "A principal função do Intestino Grosso é a:", options: ["Absorção de água e formação das fezes", "Digestão de carnes pesadas", "Produção de sangue", "Bombeamento de oxigênio"], answer: "Absorção de água e formação das fezes", explanation: "Garante que o corpo não perca tanta água.", skill: "Sistema Digestório" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Quais órgãos são considerados glândulas anexas do sistema digestório?", options: ["Fígado e Pâncreas", "Pulmões e Brônquios", "Rins e Bexiga", "Ossos e Músculos"], answer: "Fígado e Pâncreas", explanation: "Eles produzem líquidos essenciais, mas o alimento não passa por dentro deles.", skill: "Sistema Digestório" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Os movimentos involuntários que empurram o alimento pelo canal digestório são os:", options: ["Movimentos Peristálticos", "Movimentos Reflexos", "Cãibras", "Saltos gástricos"], answer: "Movimentos Peristálticos", explanation: "Ocorrem no esôfago e intestinos.", skill: "Sistema Digestório" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "A enzima presente na saliva que digere o amido chama-se:", options: ["Amilase Salivar (ou Ptialina)", "Pepsina", "Lirase", "Insulina"], answer: "Amilase Salivar (ou Ptialina)", explanation: "Inicia a quebra de carboidratos complexos.", skill: "Sistema Digestório" },

  // 7º Geografia - Economia Regional (9)
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "A região brasileira que é o maior polo industrial e financeiro do país é a:", options: ["Sudeste", "Centro-Oeste", "Nordeste", "Norte"], answer: "Sudeste", explanation: "Concentra a maior parte do PIB e das sedes de grandes empresas.", skill: "Economia Regional" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "Qual região é a grande fronteira agrícola atual, com forte produção de Soja e Gado?", options: ["Centro-Oeste", "Sertão Nordestino", "Sul de Minas", "Zona da Mata"], answer: "Centro-Oeste", explanation: "A agricultura mecanizada transformou o bioma Cerrado.", skill: "Economia Regional" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "A 'Zona Franca de Manaus' é um importante polo econômico de qual região?", options: ["Norte", "Nordeste", "Sul", "Sudeste"], answer: "Norte", explanation: "Criada para promover a industrialização e o desenvolvimento tecnológico da Amazônia.", skill: "Economia Regional" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "O agronegócio é a principal força econômica da região:", options: ["Centro-Oeste e Sul", "Paraíba e Rio Grande do Norte", "Litoral do Rio de Janeiro", "Apenas Distrito Federal"], answer: "Centro-Oeste e Sul", explanation: "Fortes em grãos, carnes e produção de cana.", skill: "Economia Regional" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "A região Nordeste destaca-se no cenário atual pela produção de:", options: ["Energia Eólica e Fruticultura irrigada no Vale do São Francisco", "Carros de luxo apenas", "Extração de carvão mineral", "Indústria de alta tecnologia aeroespacial"], answer: "Energia Eólica e Fruticultura irrigada no Vale do São Francisco", explanation: "Aproveita o vento constante e a água do rio.", skill: "Economia Regional" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "Qual estado brasileiro é o maior produtor de Café e Leite do país?", options: ["Minas Gerais", "Amazonas", "Rio Grande do Sul", "Acre"], answer: "Minas Gerais", explanation: "Tradição histórica que se mantém forte na economia mineira.", skill: "Economia Regional" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "A economia da região Sul é marcada pela presença de:", options: ["Cooperativas agroindustriais e produção de uva/vinho", "Mão de obra escrava", "Apenas extração de látex", "Indústria do petróleo pesado offshore"], answer: "Cooperativas agroindustriais e produção de uva/vinho", explanation: "Herança da colonização europeia e policultura.", skill: "Economia Regional" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "O estado de São Paulo tem como destaque econômico:", options: ["O Setor de Serviços, Indústria Automobilística e Tecnologia", "Apenas a pesca artesanal", "A maior plantação de cacau do mundo", "O garimpo de ouro de superfície"], answer: "O Setor de Serviços, Indústria Automobilística e Tecnologia", explanation: "É o coração econômico da América Latina.", skill: "Economia Regional" },
  { grade: "7º", discipline: "Geografia", type: "multiple", text: "O turismo é um setor crucial para a economia de qual faixa territorial brasileira?", options: ["Litoral (especialmente no Nordeste e Sudeste)", "Interior da Floresta Amazônica impenetrável", "Picos nevados apenas", "Fronteira com o Paraguai apenas"], answer: "Litoral (especialmente no Nordeste e Sudeste)", explanation: "As praias atraem milhões de visitantes e geram renda local.", skill: "Economia Regional" },

  // 6º Arte - Patrimônio (9)
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O que é 'Patrimônio Cultural'?", options: ["O conjunto de bens materiais e imateriais que contam a história de um povo", "Apenas o dinheiro guardado no banco", "Uma herança de família secreta", "Um imposto sobre as artes"], answer: "O conjunto de bens materiais e imateriais que contam a história de um povo", explanation: "Preserva a memória e a identidade de uma comunidade.", skill: "Patrimônio" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Exemplos de Patrimônio MATERIAL são:", options: ["Prédios históricos, monumentos, esculturas e quadros", "Danças e receitas de comida", "Músicas e lendas", "Festas populares apenas"], answer: "Prédios históricos, monumentos, esculturas e quadros", explanation: "São bens físicos, tangíveis.", skill: "Patrimônio" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Habilidades, celebrações, formas de expressão e saberes são patrimônios:", options: ["Imateriais", "Sólidos", "Estrangeiros", "Indesejados"], answer: "Imateriais", explanation: "Estão na memória e na prática das pessoas.", skill: "Patrimônio" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Qual cidade mineira é Patrimônio Mundial pela UNESCO devido às suas igrejas e esculturas de Aleijadinho?", options: ["Ouro Preto", "Belo Horizonte", "Uberlândia", "Contagem"], answer: "Ouro Preto", explanation: "Possui o maior conjunto barroco do Brasil.", skill: "Patrimônio" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O 'Queijo Minas' e o 'Modo de Fazer' foram reconhecidos como:", options: ["Patrimônio Imaterial brasileiro", "Patrimônio Material sólido", "Comida proibida", "Invenção americana"], answer: "Patrimônio Imaterial brasileiro", explanation: "O saber tradicional da fabricação é protegido.", skill: "Patrimônio" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O órgão brasileiro responsável por proteger e tombar os patrimônios é o:", options: ["IPHAN", "DETRAN", "ANVISA", "MEC"], answer: "IPHAN", explanation: "Instituto do Patrimônio Histórico e Artístico Nacional.", skill: "Patrimônio" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Qual a importância de preservar o patrimônio cultural?", options: ["Para manter viva a memória e a identidade das gerações passadas e futuras", "Para vender as peças antigas para museus estrangeiros", "Para derrubar prédios velhos e construir shoppings", "Não tem importância"], answer: "Para manter viva a memória e a identidade das gerações passadas e futuras", explanation: "O patrimônio é um elo de ligação entre o passado e o presente.", skill: "Patrimônio" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O 'Frevo' e a 'Capoeira' são exemplos de patrimônios:", options: ["Imateriais da humanidade", "Materiais de pedra", "Proibidos em Minas", "Exclusivos do Japão"], answer: "Imateriais da humanidade", explanation: "Reconhecidos por sua relevância cultural mundial.", skill: "Patrimônio" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Fandango, Literatura de Cordel e o toque dos sinos em Minas são exemplos de:", options: ["Manifestações de Patrimônio Imaterial", "Apenas ruídos da cidade", "Livros escolares", "Danças estrangeiras modernas"], answer: "Manifestações de Patrimônio Imaterial", explanation: "Práticas e saberes populares brasileiros.", skill: "Patrimônio" },

  // 6º Ens. Religioso - Memória (9)
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Para as religiões, a 'Memória' serve para:", options: ["Lembrar dos ensinamentos, ritos e histórias dos antepassados", "Esquecer o passado e viver apenas no futuro", "Lembrar apenas das matérias da escola", "Fazer as pessoas sofrerem por erros antigos"], answer: "Lembrar dos ensinamentos, ritos e histórias dos antepassados", explanation: "A memória preserva o sentido da fé através do tempo.", skill: "Memória" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Os 'Livros Sagrados' (Bíblia, Alcorão, Torá) funcionam como:", options: ["A Memória Escrita das tradições religiosas", "Apenas contos de fadas", "Dicionários simples", "Livros de receitas de cozinha"], answer: "A Memória Escrita das tradições religiosas", explanation: "Registram a revelação divina e a história do povo.", skill: "Memória" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Dizer que uma religião é de 'Tradição Oral' significa que:", options: ["Os ensinamentos são passados de boca em boca por gerações", "Ninguém sabe a história da religião", "Ela não tem nenhuma regra", "Só pode ser falada em latim"], answer: "Os ensinamentos são passados de boca em boca por gerações", explanation: "Muitas religiões indígenas e africanas preservam assim seus saberes.", skill: "Memória" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O papel do 'Ancião' (o mais velho) nas religiões tradicionais é de:", options: ["Guardião da memória e mestre da sabedoria para os jovens", "Trabalhar apenas na limpeza", "Ficar quieto e não falar nada", "Decidir quem ganha o sorteio"], answer: "Guardião da memória e mestre da sabedoria para os jovens", explanation: "Eles são a ligação viva com as origens da comunidade.", skill: "Memória" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Rituais de passagem (como Batismo ou Bar-Mitzvah) servem para:", options: ["Marcar na memória um novo estágio na vida religiosa do indivíduo", "Apenas fazer festa para parentes", "Ganhar muitos presentes", "Tirar fotos para redes sociais apenas"], answer: "Marcar na memória um novo estágio na vida religiosa do indivíduo", explanation: "Momentos inesquecíveis que consagram a vida no sagrado.", skill: "Memória" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Lugares sagrados (templos, terreiros, mesquitas) são espaços de memória onde:", options: ["A comunidade se reúne para praticar sua fé e recordar seus valores", "Onde as pessoas vão para dormir apenas", "Onde se vendem produtos comerciais", "Espaços vazios sem significado"], answer: "A comunidade se reúne para praticar sua fé e recordar seus valores", explanation: "O espaço físico abriga a memória espiritual coletiva.", skill: "Memória" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O que acontece quando a memória religiosa de um povo é proibida ou destruída?", options: ["O povo perde parte fundamental de sua identidade e cultura", "Ficam mais modernos e felizes", "Não muda nada na vida das pessoas", "Ganham mais tempo para ver TV"], answer: "O povo perde parte fundamental de sua identidade e cultura", explanation: "A destruição da memória é uma forma de violência cultural.", skill: "Memória" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Comemorações anuais (Páscoa, Ramadã, Hanukkah) são ritos que:", options: ["Recordam ciclicamente os fatos centrais da história daquela fé", "Ocorrem apenas uma vez a cada 100 anos", "Não têm ordem definida", "São feitos apenas por diversão"], answer: "Recordam ciclicamente os fatos centrais da história daquela fé", explanation: "A repetição anual fixa a memória no tempo social.", skill: "Memória" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Em muitas tradições africanas, a memória reside principalmente nos:", options: ["Cantos, tambores e danças rituais", "Computadores de última geração", "Apenas nos jornais diários", "Grandes estátuas de mármore branco"], answer: "Cantos, tambores e danças rituais", explanation: "A performance corporal é o suporte da memória ancestral.", skill: "Memória" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 22 com ${batch.length} questões adicionado.`);
