import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 5500;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 24: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 6º Ciências - Água (9)
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Qual a porcentagem aproximada de água doce disponível para consumo humano no planeta?", options: ["Menos de 1%", "Cerca de 50%", "70%", "97%"], answer: "Menos de 1%", explanation: "Embora a Terra seja coberta de água, a maior parte é salgada ou está em geleiras.", skill: "Água" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O processo pelo qual a água passa do estado líquido para o gasoso (vapor) devido ao calor do Sol é a:", options: ["Evaporação", "Condensação", "Precipitação", "Fusão"], answer: "Evaporação", explanation: "É a primeira etapa do ciclo da água na atmosfera.", skill: "Água" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "As nuvens são formadas através de qual processo físico?", options: ["Condensação", "Evaporação", "Sublimação", "Solidificação"], answer: "Condensação", explanation: "O vapor de água esfria e volta a ser minúsculas gotas líquidas.", skill: "Água" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O que é um 'Aquífero'?", options: ["Uma reserva de água subterrânea armazenada em rochas porosas", "Um tipo de peixe de águas profundas", "Uma estação de tratamento de esgoto", "O nome do gelo das montanhas"], answer: "Uma reserva de água subterrânea armazenada em rochas porosas", explanation: "São fontes importantes de água doce para consumo e agricultura.", skill: "Água" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Qual a função da 'Mata Ciliar' na preservação da água?", options: ["Proteger as margens dos rios contra erosão e assoreamento", "Apenas deixar a paisagem mais bonita", "Produzir frutos para os peixes apenas", "Esquentar a água do rio"], answer: "Proteger as margens dos rios contra erosão e assoreamento", explanation: "Suas raízes seguram o solo e filtram poluentes.", skill: "Água" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "A água considerada ideal para o consumo humano, sem microrganismos patogênicos, é a água:", options: ["Potável", "Destilada", "Poluída", "Salobra"], answer: "Potável", explanation: "Deve ser livre de impurezas e ter minerais adequados.", skill: "Água" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "A 'Pegada Hídrica' é um conceito que mede:", options: ["O volume total de água docê usado para produzir bens e serviços", "O tamanho das gotas de chuva", "A profundidade dos oceanos", "A velocidade com que a água corre nos rios"], answer: "O volume total de água docê usado para produzir bens e serviços", explanation: "Ajuda a entender o impacto do consumo humano nos recursos hídricos.", skill: "Água" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O que causa a 'Eutrofização' de um corpo d'água?", options: ["O excesso de nutrientes (como esgoto) que gera crescimento de algas e falta de oxigênio", "A falta de sol", "O excesso de sal na água doce", "A queda de folhas secas naturalmente"], answer: "O excesso de nutrientes (como esgoto) que gera crescimento de algas e falta de oxigênio", explanation: "É um grave problema de poluição que mata peixes e plantas aquáticas.", skill: "Água" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Qual etapa do tratamento de água serve para eliminar bactérias e vírus?", options: ["Cloração (Desinfecção)", "Filtração", "Decantação", "Peneiramento"], answer: "Cloração (Desinfecção)", explanation: "O uso de cloro ou ozônio mata os seres causadores de doenças.", skill: "Água" },

  // 7º Ciências - Sistemas (9)
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "A 'Homeostase' é a capacidade do corpo de:", options: ["Manter o equilíbrio interno constante mesmo com mudanças fora dele", "Ficar sempre parado", "Mudar de cor conforme o ambiente", "Dormir por longos períodos"], answer: "Manter o equilíbrio interno constante mesmo com mudanças fora dele", explanation: "Ex: manter a temperatura e o açúcar no sangue estáveis.", skill: "Sistemas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual sistema é responsável por distribuir hormônios pelo corpo através do sangue?", options: ["Sistema Endócrino", "Sistema Respiratório", "Sistema Esquelético", "Sistema Urinário"], answer: "Sistema Endócrino", explanation: "Utiliza glândulas que produzem substâncias químicas reguladoras.", skill: "Sistemas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "A integração entre o sistema muscular e o esquelético permite:", options: ["A locomoção e a sustentação do corpo", "A digestão de alimentos", "A produção de pensamentos", "A filtragem do sangue"], answer: "A locomoção e a sustentação do corpo", explanation: "Trabalham juntos como alavancas acionadas por motores.", skill: "Sistemas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O sistema imunológico tem como função principal:", options: ["Defender o corpo contra agentes invasores (bactérias, vírus)", "Produzir urina", "Transformar comida em energia", "Circular o oxigênio"], answer: "Defender o corpo contra agentes invasores (bactérias, vírus)", explanation: "Utiliza glóbulos brancos e anticorpos para proteção.", skill: "Sistemas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual sistema remove os resíduos tóxicos e o excesso de água do sangue?", options: ["Sistema Excretor (Urinário)", "Sistema Digestório", "Sistema Linfático", "Sistema Tegumentar"], answer: "Sistema Excretor (Urinário)", explanation: "Os rins filtram o sangue e formam a urina.", skill: "Sistemas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O Sistema Linfático trabalha em conjunto com qual outro sistema para defender o organismo?", options: ["Sistema Circulatório", "Sistema Reprodutor", "Sistema Ósseo", "Sistema Respiratório"], answer: "Sistema Circulatório", explanation: "Transporta a linfa e ajuda a filtrar impurezas e defender contra infecções.", skill: "Sistemas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "As trocas gasosas (oxigênio por gás carbônico) ocorrem em qual estrutura pulmonar?", options: ["Alvéolos Pulmonares", "Brônquios", "Traqueia", "Laringe"], answer: "Alvéolos Pulmonares", explanation: "São pequenos sacos de ar cercados de vasos sanguíneos.", skill: "Sistemas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "A regulação da temperatura corporal pela pele (suor) é uma integração entre quais sistemas?", options: ["Tegumentar, Nervoso e Circulatório", "Digestório e Esquelético", "Reprodutor e Urinário", "Apenas o sistema Muscular"], answer: "Tegumentar, Nervoso e Circulatório", explanation: "O cérebro envia sinais, os vasos peles dilatam e o suor esfria o corpo.", skill: "Sistemas" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual o papel do pâncreas tanto no sistema digestório quanto no endócrino?", options: ["Produzir suco pancreático e insulina", "Produzir sangue e bile", "Produzir ossos e músculos", "Filtrar a urina"], answer: "Produzir suco pancreático e insulina", explanation: "É uma glândula mista com funções fundamentais.", skill: "Sistemas" },

  // 8º Ciências - Sistema Nervoso (9)
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Qual a célula principal e básica do Sistema Nervoso?", options: ["Neurônio", "Hemácia", "Fibrócito", "Adipócito"], answer: "Neurônio", explanation: "Capaz de transmitir impulsos elétricos de forma rápida.", skill: "Sistema Nervoso" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A comunicação química entre dois neurônios ocorre em um espaço chamado:", options: ["Sinapse", "Medula", "Cerebelo", "Axônio"], answer: "Sinapse", explanation: "Neste ponto são liberados os neurotransmissores.", skill: "Sistema Nervoso" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O Sistema Nervoso CENTRAL é composto por:", options: ["Encéfalo e Medula Espinal", "Nervos e Gânglios", "Apenas o Coração", "Estômago e Intestino"], answer: "Encéfalo e Medula Espinal", explanation: "É o centro de comando e processamento do corpo.", skill: "Sistema Nervoso" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Qual parte do cérebro é responsável pelo equilíbrio e coordenação motora?", options: ["Cerebelo", "Córtex", "Hipotálamo", "Tronco Encefálico"], answer: "Cerebelo", explanation: "Mantém a postura e a precisão dos movimentos finos.", skill: "Sistema Nervoso" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O Sistema Nervoso Autônomo controla funções involuntárias, como:", options: ["Batimentos cardíacos e digestão", "Andar de bicicleta", "Escrever um texto", "Falar uma língua estrangeira"], answer: "Batimentos cardíacos e digestão", explanation: "Funciona sem precisarmos pensar conscientemente.", skill: "Sistema Nervoso" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Um 'Ato Reflexo' (como tirar a mão do fogo rapidamente) é processado principalmente na:", options: ["Medula Espinal", "Córtex Cerebral", "Língua", "Ponta do dedo"], answer: "Medula Espinal", explanation: "É uma resposta rápida que não depende do cérebro para acontecer.", skill: "Sistema Nervoso" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "A bainha de mielina que envolve o axônio do neurônio serve para:", options: ["Aumentar a velocidade do impulso nervoso", "Esfriar a célula", "Produzir oxigênio", "Guardar memórias antigas"], answer: "Aumentar a velocidade do impulso nervoso", explanation: "Funciona como um isolante elétrico que faz o sinal 'saltar'.", skill: "Sistema Nervoso" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Qual o papel dos 'Sentidos' (visão, audição, etc.) para o sistema nervoso?", options: ["Captar estímulos do ambiente e transformá-los em sinais nervosos", "Apenas para beleza estética do rosto", "Filtrar a luz do sol", "Produzir som"], answer: "Captar estímulos do ambiente e transformá-los em sinais nervosos", explanation: "Permitem que o corpo interaja com o mundo.", skill: "Sistema Nervoso" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O uso de substâncias psicoativas (drogas) pode afetar o sistema nervoso ao:", options: ["Interferir na ação dos neurotransmissores nas sinapses", "Apenas mudar a cor dos olhos", "Fortalecer os ossos", "Não causa nenhum efeito real"], answer: "Interferir na ação dos neurotransmissores nas sinapses", explanation: "Isso altera a percepção, o humor e o comportamento.", skill: "Sistema Nervoso" },

  // 7º História - Religião (9)
  { grade: "7º", discipline: "História", type: "multiple", text: "Qual instituição tinha o maior poder político, econômico e cultural na Idade Média Europeia?", options: ["Igreja Católica", "Sindicatos de trabalhadores", "Escolas públicas", "Indústrias têxteis"], answer: "Igreja Católica", explanation: "A Igreja controlava a educação, as terras e a moral da sociedade.", skill: "Religião" },
  { grade: "7º", discipline: "História", type: "multiple", text: "O 'Teocentrismo' medieval pregava que:", options: ["Deus era o centro do universo e de todas as explicações", "O ser humano era o centro do mundo", "O Sol girava em torno da Lua", "Não existia nenhum deus"], answer: "Deus era o centro do universo e de todas as explicações", explanation: "A fé estava acima da razão nas explicações do mundo.", skill: "Religião" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Qual o objetivo principal das 'Cruzadas'?", options: ["Retomar a Terra Santa (Jerusalém) do domínio muçulmano", "Descobrir o caminho para a América", "Inventar a imprensa", "Traduzir livros proibidos"], answer: "Retomar a Terra Santa (Jerusalém) do domínio muçulmano", explanation: "Foram expedições militares e religiosas contra os islâmicos.", skill: "Religião" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Quem foi o monge alemão que iniciou a Reforma Protestante em 1517?", options: ["Martinho Lutero", "João Calvino", "Henrique VIII", "Papa Leão X"], answer: "Martinho Lutero", explanation: "Ele questionou a venda de indulgências e a autoridade do Papa.", skill: "Religião" },
  { grade: "7º", discipline: "História", type: "multiple", text: "O Anglicanismo surgiu na Inglaterra por decisão de qual monarca?", options: ["Henrique VIII", "Luís XIV", "Dom Pedro I", "Rainha Vitória"], answer: "Henrique VIII", explanation: "Ele rompeu com o Papa para ter o controle da Igreja na Inglaterra.", skill: "Religião" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A 'Contrarreforma' Católica incluiu medidas como:", options: ["A criação da Companhia de Jesus (Jesuítas) e o Tribunal da Inquisição", "O fim de todas as missas", "O apoio total às ideias de Lutero", "A tradução da Bíblia para o alemão apenas"], answer: "A criação da Companhia de Jesus (Jesuítas) e o Tribunal da Inquisição", explanation: "Foi a resposta da Igreja para deter o avanço protestante.", skill: "Religião" },
  { grade: "7º", discipline: "História", type: "multiple", text: "Os Jesuítas tiveram um papel fundamental na história do Brasil por sua atuação na:", options: ["Catequese e educação de indígenas e colonos", "Extração de ouro apenas", "Construção de fábricas de tecidos", "Luta contra os reis portugueses"], answer: "Catequese e educação de indígenas e colonos", explanation: "Fundaram as primeiras escolas e missões no território brasileiro.", skill: "Religião" },
  { grade: "7º", discipline: "História", type: "multiple", text: "O conceito de 'Predestinação' (Deus já escolheu quem será salvo) foi central em qual religião protestante?", options: ["Calvinismo", "Luteranismo", "Espiritismo", "Budismo"], answer: "Calvinismo", explanation: "João Calvino defendia que o sucesso no trabalho era um sinal de salvação.", skill: "Religião" },
  { grade: "7º", discipline: "História", type: "multiple", text: "A Inquisição era um tribunal religioso que tinha como objetivo:", options: ["Combater a 'heresia' e punir os infiéis ou falsos cristãos", "Dar terras para os camponeses", "Organizar festas populares", "Proteger a liberdade de expressão"], answer: "Combater a 'heresia' e punir os infiéis ou falsos cristãos", explanation: "Muitas pessoas foram presas ou condenadas à morte por suas ideias.", skill: "Religião" },

  // 9º História - Direitos Humanos (9)
  { grade: "9º", discipline: "História", type: "multiple", text: "A 'Declaração Universal dos Direitos Humanos' foi adotada pela ONU em qual ano?", options: ["1948", "1789", "1914", "2000"], answer: "1948", explanation: "Surgiu como resposta aos horrores da 2ª Guerra Mundial.", skill: "Direitos Humanos" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Qual o princípio fundamental dos Direitos Humanos?", options: ["Todos os seres humanos nascem livres e iguais em dignidade e direitos", "Apenas pessoas ricas têm direitos garantidos", "Os direitos mudam conforme o país onde você mora", "Direitos só valem para quem comete crimes"], answer: "Todos os seres humanos nascem livres e iguais em dignidade e direitos", explanation: "É a base da cidadania global moderna.", skill: "Direitos Humanos" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O regime de segregação racial na África do Sul que violava os Direitos Humanos era o:", options: ["Apartheid", "Nazismo", "Comunismo", "Capitalismo"], answer: "Apartheid", explanation: "Separava brancos e negros por lei até a década de 1990.", skill: "Direitos Humanos" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Quem foi o líder que lutou contra o Apartheid e se tornou presidente da África do Sul?", options: ["Nelson Mandela", "Martin Luther King", "Mahatma Gandhi", "Malcolm X"], answer: "Nelson Mandela", explanation: "Ficou 27 anos preso por sua luta pela igualdade.", skill: "Direitos Humanos" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O movimento de 'Direitos Civis' nos EUA (anos 60) lutava principalmente contra:", options: ["A segregação racial e a violência contra negros", "O aumento dos impostos", "A exploração de petróleo", "A falta de internet"], answer: "A segregação racial e a violência contra negros", explanation: "Liderado por figuras como Martin Luther King Jr.", skill: "Direitos Humanos" },
  { grade: "9º", discipline: "História", type: "multiple", text: "A Constituição Brasileira de 1988 é conhecida como a 'Constituição Cidadã' porque:", options: ["Ampliou vastamente os direitos individuais, sociais e garantias fundamentais", "Foi escrita por apenas uma pessoa", "Acabou com todos os impostos", "Só vale para quem mora nas cidades"], answer: "Ampliou vastamente os direitos individuais, sociais e garantias fundamentais", explanation: "Marco da redemocratização do Brasil após a ditadura.", skill: "Direitos Humanos" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Quais são direitos de 'Segunda Geração' (sociais, econômicos e culturais)?", options: ["Educação, saúde, trabalho e previdência", "Direito de votar e ser votado apenas", "Direito à vida e liberdade de expressão", "Direito a ter um celular de última geração"], answer: "Educação, saúde, trabalho e previdência", explanation: "Exigem uma ação positiva do Estado para garantir a dignidade.", skill: "Direitos Humanos" },
  { grade: "9º", discipline: "História", type: "multiple", text: "O combate ao 'Trabalho Escravo Contemporâneo' é uma pauta de Direitos Humanos porque:", options: ["Ninguém deve ser mantido em escravidão ou servidão", "As empresas lucram pouco com isso", "Falta mão de obra nas cidades", "É uma técnica antiga de agricultura"], answer: "Ninguém deve ser mantido em escravidão ou servidão", explanation: "A liberdade é um direito inalienável do ser humano.", skill: "Direitos Humanos" },
  { grade: "9º", discipline: "História", type: "multiple", text: "Liberdade de Opinião e Expressão garante que:", options: ["Todos podem procurar, receber e transmitir informações e ideias sem censura", "Posso ofender e caluniar qualquer pessoa sem punição", "Só posso falar se o governo permitir", "Todos devem pensar exatamente igual"], answer: "Todos podem procurar, receber e transmitir informações e ideias sem censura", explanation: "Essencial para a existência da democracia.", skill: "Direitos Humanos" },

  // 9º Geografia - Organizações (9)
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Qual a função principal da ONU (Organização das Nações Unidas)?", options: ["Promover a paz mundial e o desenvolvimento econômico e social", "Governar todos os países do mundo à força", "Apenas emprestar dinheiro para países ricos", "Substituir os exércitos de cada nação"], answer: "Promover a paz mundial e o desenvolvimento econômico e social", explanation: "Possui diversos órgãos como a UNESCO, OMS e UNICEF.", skill: "Organizações" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O FMI (Fundo Monetário Internacional) atua principalmente:", options: ["Emprestando dinheiro para países em crise financeira em troca de reformas", "Vigiando as fronteiras de guerra", "Protegendo os animais em extinção", "Construindo escolas em favelas"], answer: "Emprestando dinheiro para países em crise financeira em troca de reformas", explanation: "Busca a estabilidade do sistema financeiro global.", skill: "Organizações" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A OMC (Organização Mundial do Comércio) serve para:", options: ["Regulamentar e facilitar o comércio entre as nações", "Proibir as vendas pela internet", "Apenas comprar petróleo barato", "Unificar a moeda de todos os países"], answer: "Regulamentar e facilitar o comércio entre as nações", explanation: "Resolve disputas comerciais e reduz barreiras (impostos).", skill: "Organizações" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O que é um 'Bloco Econômico' como o Mercosul ou a União Europeia?", options: ["União de países de uma região para facilitar o comércio e a livre circulação", "Um grupo de piratas modernos", "Um banco que só atende empresas", "O nome da moeda de um único país"], answer: "União de países de uma região para facilitar o comércio e a livre circulação", explanation: "Visam fortalecer as economias regionais frente à globalização.", skill: "Organizações" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A OTAN (Organização do Tratado do Atlântico Norte) é uma organização de caráter:", options: ["Militar (Defesa coletiva)", "Ecológico", "Religioso", "Científico"], answer: "Militar (Defesa coletiva)", explanation: "Criada durante a Guerra Fria entre países democráticos/capitalistas.", skill: "Organizações" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Quais países formam o núcleo original do MERCOSUL?", options: ["Brasil, Argentina, Paraguai e Uruguai", "Brasil, Chile e EUA", "México, Colômbia e Peru", "Venezuela e Bolívia apenas"], answer: "Brasil, Argentina, Paraguai e Uruguai", explanation: "É o bloco econômico mais importante da América do Sul.", skill: "Organizações" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "A UNESCO é o órgão da ONU responsável por cuidar do quê?", options: ["Educação, Ciência e Cultura", "Saúde e Vacinas", "Finanças e Bancos", "Agricultura e Fome"], answer: "Educação, Ciência e Cultura", explanation: "Protege patrimônios mundiais e incentiva a educação.", skill: "Organizações" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "O termo 'G7' refere-se ao grupo de:", options: ["Sete países mais industrializados e ricos do mundo", "Sete novos planetas descobertos", "Sete capitais brasileiras", "Sete maiores produtores de arroz"], answer: "Sete países mais industrializados e ricos do mundo", explanation: "Reúnem-se para discutir a economia e política global.", skill: "Organizações" },
  { grade: "9º", discipline: "Geografia", type: "multiple", text: "Os BRICS são um agrupamento de países de 'economias emergentes'. Quem são eles?", options: ["Brasil, Rússia, Índia, China e África do Sul", "Brasil, Reino Unido, Itália, Canadá e Suíça", "Bélgica, Romênia, Islândia, Cuba e Síria", "Apenas países africanos"], answer: "Brasil, Rússia, Índia, China e África do Sul", explanation: "Buscam maior influência no cenário mundial contra o domínio do G7.", skill: "Organizações" },

  // 9º Matemática - Teoremas (9)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O Teorema de Pitágoras afirma que, em um triângulo retângulo:", options: ["A soma dos quadrados dos catetos é igual ao quadrado da hipotenusa", "A soma dos ângulos internos é 360 graus", "A área é o dobro da base", "Todos os lados são obrigatoriamente iguais"], answer: "A soma dos quadrados dos catetos é igual ao quadrado da hipotenusa", explanation: "Fórmula clássica: a² + b² = c².", skill: "Teoremas" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a fórmula matemática que representa o Teorema de Pitágoras?", options: ["a² + b² = c²", "A = b * h", "L³ = V", "x = -b / 2a"], answer: "a² + b² = c²", explanation: "Onde 'c' é a hipotenusa (lado maior oposto ao ângulo de 90°).", skill: "Teoremas" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O 'Teorema de Tales' refere-se à proporcionalidade entre:", options: ["Feixes de retas paralelas cortadas por transversais", "Lados de um círculo perfeito", "O peso e a altura de um objeto", "Velocidade e tempo de viagem"], answer: "Feixes de retas paralelas cortadas por transversais", explanation: "Estabelece que segmentos correspondentes são proporcionais.", skill: "Teoremas" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Em um triângulo qualquer, a soma dos ângulos internos é sempre igual a:", options: ["180°", "90°", "360°", "45°"], answer: "180°", explanation: "Independente do tipo ou tamanho do triângulo.", skill: "Teoremas" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O 'Teorema do Valor Médio' ou outras propriedades de funções são estudados para entender:", options: ["O comportamento e as tendências de variação de grandezas", "Apenas como somar números grandes", "Como desenhar triângulos perfeitos", "O preço do dólar"], answer: "O comportamento e as tendências de variação de grandezas", explanation: "Teoremas ajudam a prever resultados em modelos matemáticos.", skill: "Teoremas" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a hipotenusa de um triângulo retângulo cujos catetos medem 3 e 4?", options: ["5", "7", "12", "25"], answer: "5", explanation: "3² + 4² = 9 + 16 = 25. Raiz de 25 é 5.", skill: "Teoremas" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Teoremas são fundamentais na ciência porque são:", options: ["Afirmações demonstradas como verdadeiras através da lógica e prova", "Apenas palpites de cientistas famosos", "Leis que o governo inventou", "Sugestões que podem estar erradas"], answer: "Afirmações demonstradas como verdadeiras através da lógica e prova", explanation: "Diferente de teorias, teoremas matemáticos são verdades absolutas no seu sistema.", skill: "Teoremas" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "A semelhança de triângulos ocorre quando:", options: ["Seus ângulos correspondentes são iguais e lados proporcionais", "Têm a mesma cor", "Têm a mesma área obrigatoriamente", "Têm apenas um lado igual"], answer: "Seus ângulos correspondentes são iguais e lados proporcionais", explanation: "Um é uma ampliação ou redução do outro.", skill: "Teoremas" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O Teorema de Bachet ou de outros matemáticos sobre números primos ajudam na:", options: ["Criptografia e segurança digital (senhas)", "Pintura de quadros", "Construção de estradas", "Educação física"], answer: "Criptografia e segurança digital (senhas)", explanation: "A matemática avançada protege nossos dados na internet.", skill: "Teoremas" },

  // 6º Arte - Modernismo (9)
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O 'Modernismo' no Brasil teve como marco oficial qual evento em 1922?", options: ["Semana de Arte Moderna (no Teatro Municipal de SP)", "Descobrimento do Brasil", "Fim da Escravidão", "Invenção do Cinema"], answer: "Semana de Arte Moderna (no Teatro Municipal de SP)", explanation: "Artistas queriam romper com a arte clássica e europeia.", skill: "Modernismo" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "A principal proposta do Modernismo era:", options: ["Criar uma arte genuinamente brasileira e inovadora", "Copear o estilo de pintura dos reis de Portugal", "Proibir o uso de cores vibrantes", "Desenhar apenas cenas da Grécia Antiga"], answer: "Criar uma arte genuinamente brasileira e inovadora", explanation: "Buscavam temas nacionais com linguagens modernas.", skill: "Modernismo" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Quem pintou o quadro 'Abaporu', que se tornou símbolo do modernismo?", options: ["Tarsila do Amaral", "Anita Malfatti", "Candido Portinari", "Monteiro Lobato"], answer: "Tarsila do Amaral", explanation: "A obra deu início ao movimento Antropofágico.", skill: "Modernismo" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O 'Movimento Antropofágico' defendia que o artista brasileiro devia:", options: ["'Comer' as influências estrangeiras e digeri-las para criar algo novo e brasileiro", "Parar de olhar para o que o mundo faz", "Apenas pintar canibais", "Escrever livros em francês"], answer: "'Comer' as influências estrangeiras e digeri-las para criar algo novo e brasileiro", explanation: "Oswald de Andrade escreveu o manifesto desse movimento.", skill: "Modernismo" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Anita Malfatti causou escândalo com sua exposição em 1917 porque:", options: ["Usava cores expressionistas e fortes, distantes do realismo", "Pintava apenas flores pequenas", "Suas fotos eram em preto e branco", "Não usava molduras nos quadros"], answer: "Usava cores expressionistas e fortes, distantes do realismo", explanation: "A crítica da época, acostumada ao tradicional, não aceitou seu estilo inovador.", skill: "Modernismo" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Candido Portinari é um grande pintor modernista que retratou muito:", options: ["O povo brasileiro, retirantes e o trabalho no campo", "Apenas a elite carioca", "Gatos e cachorros coloridos", "Carros de luxo"], answer: "O povo brasileiro, retirantes e o trabalho no campo", explanation: "Focou na realidade social e sofrida de parte da população.", skill: "Modernismo" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O uso de formas simplificadas e cores Fortes era típico do(a):", options: ["Estética Modernista", "Arte Barroca", "Renascimento", "Arte Egípcia antiga"], answer: "Estética Modernista", explanation: "Buscavam a liberdade da linha e da cor.", skill: "Modernismo" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "Qual destes poetas foi um dos líderes intelectuais da Semana de 22?", options: ["Mário de Andrade", "Machado de Assis", "Casimiro de Abreu", "José de Alencar"], answer: "Mário de Andrade", explanation: "Autor de 'Macunaíma', obra essencial do modernismo.", skill: "Modernismo" },
  { grade: "6º", discipline: "Arte", type: "multiple", text: "O Modernismo influenciou também a arquitetura brasileira. Quem é o maior arquiteto dessa fase?", options: ["Oscar Niemeyer", "Aleijadinho", "Santos Dumont", "Pelé"], answer: "Oscar Niemeyer", explanation: "Famoso pelas curvas em concreto e por projetar Brasília.", skill: "Modernismo" },

  // 9º Arte - Pop Art (9)
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A 'Pop Art' surgiu na década de 1950 e 1960 utilizando imagens do(a):", options: ["Cultura de massa, propaganda e consumo", "Religião Medieval", "Natureza selvagem intocada", "Sonhos surrealistas e inconscientes"], answer: "Cultura de massa, propaganda e consumo", explanation: "Usava cores vibrantes de produtos populares (Coca-cola, Marilyn Monroe).", skill: "Pop Art" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Quem é o artista mais icônico da Pop Art, famoso pelas latas de Sopa Campbell?", options: ["Andy Warhol", "Jackson Pollock", "Salvador Dalí", "Leonardo da Vinci"], answer: "Andy Warhol", explanation: "Ele transformou objetos comuns da prateleira do mercado em obras de arte.", skill: "Pop Art" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Roy Lichtenstein é conhecido por pintar quadros inspirados em:", options: ["Histórias em Quadrinhos (HQs) com pontos de impressão (Ben-Day)", "Fotos de guerra reais", "Igrejas góticas", "Desenhos de crianças"], answer: "Histórias em Quadrinhos (HQs) com pontos de impressão (Ben-Day)", explanation: "Utilizava onomatopeias e balões de fala em suas pinturas.", skill: "Pop Art" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A Pop Art criticava e, ao mesmo tempo, celebrava o:", options: ["Consumismo e a sociedade da imagem", "Fim da tecnologia", "Socialismo soviético", "O artesanato manual puro"], answer: "Consumismo e a sociedade da imagem", explanation: "Ironizava como tudo vira mercadoria, inclusive a arte.", skill: "Pop Art" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Qual a técnica de reprodução em massa muito usada pelos artistas Pop para repetir imagens?", options: ["Serigrafia (Silk-screen)", "Óleo sobre tela único", "Mármore esculpido", "Cave de gelo"], answer: "Serigrafia (Silk-screen)", explanation: "Permitia produzir muitas cópias da mesma obra de forma rápida e industrial.", skill: "Pop Art" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O termo 'Pop' vem da palavra:", options: ["Popular", "Poderosa", "Polêmica", "Poética"], answer: "Popular", explanation: "Arte que o povo comum reconhece e consome.", skill: "Pop Art" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A Pop Art teve início em qual país, embora tenha ficado famosa nos EUA?", options: ["Inglaterra", "Brasil", "Japão", "Austrália"], answer: "Inglaterra", explanation: "O Independent Group em Londres começou as discussões sobre o tema.", skill: "Pop Art" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Qual o efeito das cores fluorescentes e vibrantes na Pop Art?", options: ["Chamar a atenção de forma imediata, como os anúncios publicitários", "Acalmar o espectador para dormir", "Fazer a obra parecer muito antiga e desgastada", "Esconder as figuras do quadro"], answer: "Chamar a atenção de forma imediata, como os anúncios publicitários", explanation: "Cores 'ácidas' e artificiais eram a marca do movimento.", skill: "Pop Art" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A Pop Art aproximou a 'Alta Cultura' (museus) da:", options: ["Cultura Baixa ou Popular (ruas, TV, cinema)", "Pré-história", "Apenas aristocracia", "Matemática pura"], answer: "Cultura Baixa ou Popular (ruas, TV, cinema)", explanation: "Quebrou a barreira do que era considerado 'assunto' digno de arte.", skill: "Pop Art" },

  // 6º Ens. Religioso - Pluralismo (9)
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O que é 'Pluralismo Religioso'?", options: ["A coexistência respeitosa de diversas crenças e religiões em uma mesma sociedade", "A proibição de ter mais de uma religião no país", "A obrigação de todos pensarem igual", "O fim de todas as religiões para ter apenas a ciência"], answer: "A coexistência respeitosa de diversas crenças e religiões em uma mesma sociedade", explanation: "Diferente da tolerância (suportar), o pluralismo valoriza a diversidade.", skill: "Pluralismo" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Um 'Estado Laico', como o Brasil, deve garantir:", options: ["A liberdade de crença para todos e a imparcialidade do governo", "Que apenas uma religião oficial seja ensinada", "Que ninguém possa ter religião", "O pagamento de dízimos para o governo"], answer: "A liberdade de crença para todos e a imparcialidade do governo", explanation: "O Estado não favorece nem persegue nenhuma religião.", skill: "Pluralismo" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A 'Intolerância Religiosa' manifesta-se através de:", options: ["Atitudes de desrespeito, ódio ou violência contra fés diferentes", "Convidar o vizinho para um café", "Estudar a história das religiões na escola", "Respeitar o feriado do outro"], answer: "Atitudes de desrespeito, ódio ou violência contra fés diferentes", explanation: "É um crime e uma violação dos direitos humanos.", skill: "Pluralismo" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Diálogo Inter-religioso' busca:", options: ["Promover a paz e a compreensão mútua entre praticantes de diferentes fés", "Convencer o outro de que ele está errado", "Apenas saber quem tem o templo mais bonito", "Proibir as pessoas de falarem sobre Deus"], answer: "Promover a paz e a compreensão mútua entre praticantes de diferentes fés", explanation: "Foca nos pontos comuns e no respeito às diferenças.", skill: "Pluralismo" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Para viver em uma sociedade plural, a atitude fundamental é a(o):", options: ["Respeito e a Empatia", "Julgamento constante", "Agressividade", "Isolamento total"], answer: "Respeito e a Empatia", explanation: "Colocar-se no lugar do outro e aceitar seu direito de ser diferente.", skill: "Pluralismo" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O que é o 'Sincretismo' no contexto brasileiro?", options: ["A mistura de elementos de diferentes religiões (ex: catolicismo e candomblé)", "A proibição de festas populares", "O estudo de línguas antigas", "Apenas a construção de novas igrejas"], answer: "A mistura de elementos de diferentes religiões (ex: catolicismo e candomblé)", explanation: "Demonstra o pluralismo histórico e cultural do nosso povo.", skill: "Pluralismo" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "A liberdade religiosa inclui o direito de:", options: ["Ter uma religião, mudar de religião ou não ter nenhuma religião", "Apenas ter a religião dos pais", "Obrigar os outros a seguirem a sua fé", "Não respeitar as leis do país por causa da fé"], answer: "Ter uma religião, mudar de religião ou não ter nenhuma religião", explanation: "É um direito de consciência individual.", skill: "Pluralismo" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Os ataques a terreiros de matriz africana são exemplos de:", options: ["Racismo religioso e intolerância que devem ser combatidos", "Apenas brigas sem importância", "Eventos culturais de rotina", "Algo que o pluralismo defende"], answer: "Racismo religioso e intolerância que devem ser combatidos", explanation: "O ódio religioso fere a democracia e a paz social.", skill: "Pluralismo" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Qual o benefício de aprender sobre diversas religiões na escola?", options: ["Diminuir o preconceito e aumentar a cultura geral", "Obrigar o aluno a mudar de fé", "Gastar tempo à toa", "Fazer todos os alunos pararem de acreditar em tudo"], answer: "Diminuir o preconceito e aumentar a cultura geral", explanation: "O conhecimento gera respeito e civilidade.", skill: "Pluralismo" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 24 com ${batch.length} questões adicionado.`);
