import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 5200;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 21: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 7º Arte - Danças (9)
  { grade: "7º", discipline: "Arte", type: "multiple", text: "Qual a principal característica da 'Dança Contemporânea'?", options: ["Liberdade de movimento e mistura de estilos sem regras rígidas", "Uso obrigatório de sapatilhas de ponta", "Apenas movimentos inspirados na Grécia Antiga", "Proibição de música"], answer: "Liberdade de movimento e mistura de estilos sem regras rígidas", explanation: "Foca na expressão pessoal e na quebra de padrões clássicos.", skill: "Danças" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "O 'Balé Clássico' originou-se em quais cortes europeias?", options: ["Francesa e Italiana", "Portuguesa e Espanhola", "Inglesa e Alemã", "Russa apenas"], answer: "Francesa e Italiana", explanation: "Surgiu no Renascimento e se profissionalizou na corte de Luís XIV.", skill: "Danças" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "A dança que utiliza sapatos com chapas de metal para criar sons rítmicos é o:", options: ["Sapateado", "Samba", "Forró", "Jazz"], answer: "Sapateado", explanation: "O dançarino funciona também como um percussionista.", skill: "Danças" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "Qual dança brasileira é patrimônio da humanidade e utiliza guarda-chuvas coloridos?", options: ["Frevo", "Quadrilha", "Maracatu", "Samba de Roda"], answer: "Frevo", explanation: "Típico de Pernambuco, mistura marcha, maxixe e elementos de capoeira.", skill: "Danças" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "O 'Hip Hop' engloba diversas danças urbanas. Qual delas foca em movimentos no chão e acrobacias?", options: ["Breaking (Breakdance)", "Popping", "Locking", "Vogue"], answer: "Breaking (Breakdance)", explanation: "Surgiu nas festas de rua do Bronx, em Nova York.", skill: "Danças" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "As danças circulares são praticadas em muitas culturas com o objetivo de:", options: ["Promover a união, harmonia e celebração coletiva", "Competir para ver quem é o melhor solista", "Cansar os participantes o máximo possível", "Apenas por motivos de ginástica"], answer: "Promover a união, harmonia e celebração coletiva", explanation: "O círculo simboliza a igualdade e a falta de hierarquia.", skill: "Danças" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "O 'Samba de Roda' é uma matriz cultural muito importante de qual região brasileira?", options: ["Recôncavo Baiano", "Região Sul", "Amazônia", "Pantanal"], answer: "Recôncavo Baiano", explanation: "Foi a base para o nascimento do samba urbano do Rio de Janeiro.", skill: "Danças" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "Na dança, o 'Coreógrafo' é o profissional responsável por:", options: ["Criar a sequência de passos e movimentos de uma obra", "Cuidar apenas da iluminação do palco", "Vender os ingressos do espetáculo", "Apenas costurar as roupas"], answer: "Criar a sequência de passos e movimentos de uma obra", explanation: "Ele é o 'autor' da composição da dança.", skill: "Danças" },
  { grade: "7º", discipline: "Arte", type: "multiple", text: "As danças indígenas brasileiras costumam ter funções:", options: ["Rituais, religiosas ou de celebração da natureza", "Apenas para apresentações em teatros urbanos", "Nenhuma função, apenas lazer", "Apenas para ganhar prêmios em festivais"], answer: "Rituais, religiosas ou de celebração da natureza", explanation: "Estão integradas à vida espiritual e social da aldeia.", skill: "Danças" },

  // 8º Arte - Gêneros (9)
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Na pintura, o gênero que representa objetos inanimados (frutas, flores, livros) é a:", options: ["Natureza-morta", "Paisagem", "Retrato", "Pintura Histórica"], answer: "Natureza-morta", explanation: "Foca na luz, cor e composição de objetos estáticos.", skill: "Gêneros" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O gênero 'Retrato' tem como objetivo principal:", options: ["Representar a imagem de uma pessoa real (rosto e corpo)", "Pintar montanhas e rios", "Retratar batalhas de guerra apenas", "Desenhar apenas animais selvagens"], answer: "Representar a imagem de uma pessoa real (rosto e corpo)", explanation: "Pode ser individual, de grupo ou um autorretrato.", skill: "Gêneros" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Uma pintura que descreve uma cena da Bíblia ou de lendas antigas pertence ao gênero:", options: ["Mitológico ou Religioso", "Abstrato Geométrico", "Minimalista", "Cinetismo"], answer: "Mitológico ou Religioso", explanation: "Sempre conta uma história ligada a crenças ou literatura sagrada.", skill: "Gêneros" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "O gênero de pintura que foca na representação de ambientes externos (natureza, cidades) é a:", options: ["Paisagem", "Cena de Gênero", "Pintura de Marinha", "Afresco"], answer: "Paisagem", explanation: "Muito comum desde o século XVII, foca na perspectiva e atmosfera.", skill: "Gêneros" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A 'Cena de Gênero' em arte refere-se a:", options: ["Representações da vida cotidiana e pessoas comuns em suas tarefas", "Pinturas de deuses voando", "Apenas cenas de teatro", "Desenhos de fantasmas"], answer: "Representações da vida cotidiana e pessoas comuns em suas tarefas", explanation: "Mostra o dia a dia, como mercados, festas populares ou interiores de casa.", skill: "Gêneros" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "A 'Pintura Histórica' era considerada o gênero mais nobre antigamente porque:", options: ["Registrava grandes fatos políticos, militares ou épicos", "Era a mais fácil de fazer", "Usava cores mais baratas", "Era feita apenas por crianças"], answer: "Registrava grandes fatos políticos, militares ou épicos", explanation: "Tinha a função de educar e exaltar a nação ou heróis.", skill: "Gêneros" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Quando um artista pinta a si mesmo, o gênero é chamado de:", options: ["Autorretrato", "Caricatura", "Fotomontagem", "Grafite"], answer: "Autorretrato", explanation: "É um exercício de introspecção e técnica do artista.", skill: "Gêneros" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Pinturas que mostram o mar, navios e praias pertencem ao gênero:", options: ["Marinha", "Still Life", "Pintura Urbana", "Ukiyo-e"], answer: "Marinha", explanation: "Especialidade que foca nos elementos aquáticos.", skill: "Gêneros" },
  { grade: "8º", discipline: "Arte", type: "multiple", text: "Qual destes NÃO é um gênero clássico da pintura?", options: ["Pixel Art", "Retrato", "Natureza-morta", "Paisagem"], answer: "Pixel Art", explanation: "Pixel Art é uma técnica moderna digital, não um gênero temático clássico.", skill: "Gêneros" },

  // 9º Arte - Fauvismo (9)
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O termo 'Fauvismo' vem de 'fauves', que em francês significa:", options: ["Feras (Selvagens)", "Flores abundantes", "Formas geométricas", "Fantasmas"], answer: "Feras (Selvagens)", explanation: "Os críticos da época ficaram chocados com a agressividade das cores.", skill: "Fauvismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Qual a característica mais marcante da pintura Fauvista?", options: ["O uso de cores puras e vibrantes, que não correspondiam à realidade", "O desenho perfeito e detalhado das figuras", "O uso exclusivo de preto e branco", "A representação exata de fotos"], answer: "O uso de cores puras e vibrantes, que não correspondiam à realidade", explanation: "Uma árvore poderia ser pintada de azul ou um rosto de verde.", skill: "Fauvismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Quem foi o principal líder e artista do movimento Fauvista?", options: ["Henri Matisse", "Claude Monet", "Salvador Dalí", "Gustav Klimt"], answer: "Henri Matisse", explanation: "Famoso por obras como 'A Alegria de Viver' e 'Harmonia em Vermelho'.", skill: "Fauvismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O Fauvismo defendia que a COR devia ser usada para:", options: ["Expressar emoções e sentimentos, de forma livre", "Mapear apenas a temperatura do objeto", "Esconder os erros do desenho", "Seguir os manuais de botânica"], answer: "Expressar emoções e sentimentos, de forma livre", explanation: "A cor era o elemento mais importante da obra, acima da forma.", skill: "Fauvismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "As pinceladas no Fauvismo eram geralmente:", options: ["Largas, espontâneas e visíveis", "Tão finas que não se podia ver", "Feitas com máquinas", "Apenas pontinhos minúsculos"], answer: "Largas, espontâneas e visíveis", explanation: "Davam uma sensação de rapidez e energia à pintura.", skill: "Fauvismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "A obra 'A Dança' de Henri Matisse mostra figuras humanas simplificadas em uma roda. Qual a cor predominante dessas figuras?", options: ["Vermelho (ou Terracota)", "Azul escuro", "Preto", "Branco neve"], answer: "Vermelho (ou Terracota)", explanation: "As cores contrastam fortemente com o azul do céu e o verde da terra.", skill: "Fauvismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "O Fauvismo é considerado um movimento de 'Vanguarda' porque:", options: ["Inovou e abriu caminho para a arte moderna livre", "Era muito antigo e tradicional", "Era proibido pelo governo francês", "Usava apenas materiais reciclados"], answer: "Inovou e abriu caminho para a arte moderna livre", explanation: "Vanguardas estavam à frente de seu tempo.", skill: "Fauvismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Para os fauvistas, a luz na pintura era criada através do:", options: ["Contraste entre cores fortes e vibrantes", "Uso de lâmpadas atrás da tela", "Uso de tinta branca em tudo", "Sombreamento preto excessivo"], answer: "Contraste entre cores fortes e vibrantes", explanation: "Não usavam o claro-escuro tradicional para dar volume.", skill: "Fauvismo" },
  { grade: "9º", discipline: "Arte", type: "multiple", text: "Qual destes artistas também participou do Fauvismo junto com Matisse?", options: ["André Derain", "Vincent van Gogh", "Andy Warhol", "Diego Rivera"], answer: "André Derain", explanation: "Suas paisagens de Londres são exemplos clássicos das cores fauvistas.", skill: "Fauvismo" },

  // 6º Ed. Física - Futebol (9)
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "No futebol, qual o único jogador que pode tocar a bola com as mãos dentro da área?", options: ["Goleiro", "Zagueiro", "Atacante", "Árbitro"], answer: "Goleiro", explanation: "Sua função é evitar o gol e ele tem regras diferenciadas dentro da grande área.", skill: "Futebol" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Quantos jogadores cada time tem em campo em uma partida oficial de futebol?", options: ["11 jogadores", "5 jogadores", "7 jogadores", "15 jogadores"], answer: "11 jogadores", explanation: "Um goleiro e dez jogadores de linha.", skill: "Futebol" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O tempo total de uma partida de futebol oficial (sem acréscimos) é de:", options: ["90 minutos (dois tempos de 45)", "60 minutos", "40 minutos", "Duas horas"], answer: "90 minutos (dois tempos de 45)", explanation: "Existem também os acréscimos dados pelo árbitro.", skill: "Futebol" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Como se chama quando um jogador atinge o adversário de forma violenta ou ilegal?", options: ["Falta", "Escanteio", "Impedimento", "Lateral"], answer: "Falta", explanation: "A falta pode resultar em cartões ou cobrança de tiro livre.", skill: "Futebol" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O cartão vermelho no futebol significa que o jogador está:", options: ["Expulso da partida e não pode ser substituído", "Apenas avisado que errou", "Obrigado a sentar por 5 minutos", "Premiado como o melhor da partida"], answer: "Expulso da partida e não pode ser substituído", explanation: "O time passa a jogar com um atleta a menos.", skill: "Futebol" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O 'Escanteio' é cobrado quando a bola sai pela linha de fundo após tocar em:", options: ["Um jogador do time que está defendendo", "Um jogador do time que está atacando", "No juiz apenas", "Na bandeirinha de córner"], answer: "Um jogador do time que está defendendo", explanation: "É uma chance de ataque próxima ao gol.", skill: "Futebol" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Qual a regra que impede um atacante de ficar 'esperando' a bola atrás de todos os defensores?", options: ["Impedimento", "Mão na bola", "Jogo perigoso", "Carrinho por trás"], answer: "Impedimento", explanation: "Serve para equilibrar as táticas de ataque e defesa.", skill: "Futebol" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "Um chute direto ao gol após uma falta grave dentro da área é o:", options: ["Pênalti", "Tiro de meta", "Lançamento", "Chute de trivela"], answer: "Pênalti", explanation: "Cobrado da marca de 11 metros de distância do gol.", skill: "Futebol" },
  { grade: "6º", discipline: "Educação Física", type: "multiple", text: "O órgão que organiza o futebol mundial e a Copa do Mundo é a:", options: ["FIFA", "NBA", "COI", "CBF apenas"], answer: "FIFA", explanation: "Federação Internacional de Futebol Associado.", skill: "Futebol" },

  // 9º Ed. Física - Métodos (9)
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O que são 'Práticas Corporais' na educação física moderna?", options: ["Manifestações de lazer e saúde como ginástica, danças, jogos e lutas", "Apenas o treinamento para virar atleta olímpico", "Sentar e estudar sobre o corpo sem se mexer", "Fazer apenas dieta de emagrecimento"], answer: "Manifestações de lazer e saúde como ginástica, danças, jogos e lutas", explanation: "Envolvem a cultura do movimento e o cuidado com o corpo.", skill: "Métodos" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "As práticas corporais de AVENTURA na natureza incluem esportes como:", options: ["Trilha, escalada e canoagem", "Futebol de mesa", "Xadrez e Damas", "Natação em piscina olímpica"], answer: "Trilha, escalada e canoagem", explanation: "Exploram o ambiente natural com desafios físicos.", skill: "Métodos" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O conceito de 'Corpo em Movimento' valoriza:", options: ["A expressão, a saúde e o bem-estar através da atividade física", "Apenas a beleza estética e os músculos", "A velocidade máxima em tudo", "A imobilidade total"], answer: "A expressão, a saúde e o bem-estar através da atividade física", explanation: "O movimento é visto como uma linguagem humana.", skill: "Métodos" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Qual o benefício psicológico das práticas corporais coletivas?", options: ["Melhora na socialização, cooperação e redução do estresse", "Aumento da timidez", "Vontade de brigar com os colegas", "Nenhum benefício mental"], answer: "Melhora na socialização, cooperação e redução do estresse", explanation: "Trabalhar em grupo fortalece laços sociais.", skill: "Métodos" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Atividades como Yoga e Pilates focam principalmente em:", options: ["Flexibilidade, fortalecimento do 'core' (centro) e respiração", "Correr o mais rápido possível", "Apenas em lutas corporais agressivas", "Em pular o mais alto possível"], answer: "Flexibilidade, fortalecimento do 'core' (centro) e respiração", explanation: "Buscam o equilíbrio entre mente e corpo.", skill: "Métodos" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "A prática regular de exercícios ajuda a prevenir doenças como:", options: ["Hipertensão, obesidade e diabetes tipo 2", "Gripe comum apenas", "Fraturas ósseas apenas", "Miopia ocular"], answer: "Hipertensão, obesidade e diabetes tipo 2", explanation: "O sedentarismo é um grande fator de risco para essas doenças.", skill: "Métodos" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O 'Sedentarismo' é definido como:", options: ["A falta de atividade física suficiente na rotina diária", "Dormir 8 horas por noite", "Comer apenas vegetais", "Viajar muito de avião"], answer: "A falta de atividade física suficiente na rotina diária", explanation: "É um problema de saúde pública mundial.", skill: "Métodos" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "O que é 'Lazer Ativo'?", options: ["Praticar esportes, passeios ou hobbies que envolvam movimento por prazer", "Assistir esportes na TV o dia todo", "Ficar sentado nas redes sociais", "Dormir na praia"], answer: "Praticar esportes, passeios ou hobbies que envolvam movimento por prazer", explanation: "Diferente do lazer passivo (assistir algo).", skill: "Métodos" },
  { grade: "9º", discipline: "Educação Física", type: "multiple", text: "Para uma vida saudável, a OMS recomenda que adolescentes pratiquem:", options: ["Ao menos 60 minutos de atividade física moderada a vigorosa por dia", "Apenas 10 minutos por semana", "Futebol apenas nos domingos", "Academia de 5 horas seguidas uma vez ao mês"], answer: "Ao menos 60 minutos de atividade física moderada a vigorosa por dia", explanation: "A constância é fundamental para o desenvolvimento saudável.", skill: "Métodos" },

  // 6º Ens. Religioso - Mitologia (9)
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O que é um 'Mito' na visão das religiões antigas?", options: ["Uma história sagrada que explica a origem do mundo ou fenômenos naturais", "Uma mentira inventada para enganar as pessoas", "Um fato histórico comprovado por fotos", "Um manual de instruções de máquinas"], answer: "Uma história sagrada que explica a origem do mundo ou fenômenos naturais", explanation: "Dão sentido e ordem ao mundo para os povos antigos.", skill: "Mitologia" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Na Mitologia Grega, quem era o 'Rei dos Deuses' que lançava raios?", options: ["Zeus", "Posêidon", "Hades", "Hércules"], answer: "Zeus", explanation: "Governo o Monte Olimpo e o céu.", skill: "Mitologia" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Poseidon era o deus grego responsável por qual domínio?", options: ["Os Mares e Oceanos", "O Mundo dos Mortos", "A Guerra", "A Sabedoria"], answer: "Os Mares e Oceanos", explanation: "Era representado com um tridente.", skill: "Mitologia" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Qual herói grego é famoso por seus '12 Trabalhos' impossíveis?", options: ["Hércules", "Aquiles", "Odisseu", "Perseu"], answer: "Hércules", explanation: "Sua força era sobre-humana, filho de Zeus.", skill: "Mitologia" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O mito de 'Pandora' servia para explicar para os gregos a:", options: ["Existência dos males e problemas no mundo", "Invenção da culinária", "Construção de navios", "Origem das cores"], answer: "Existência dos males e problemas no mundo", explanation: "Ao abrir a caixa, ela liberou os males, sobrando apenas a Esperança.", skill: "Mitologia" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Na Mitologia Egípcia, o deus com cabeça de chacal responsável pela mumificação era:", options: ["Anúbis", "Rá", "Ísis", "Osíris"], answer: "Anúbis", explanation: "Ele guiava as almas no tribunal dos mortos.", skill: "Mitologia" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Os mitos indígenas brasileiros frequentemente trazem como personagens:", options: ["Espíritos da floresta e animais que falam (como o Curupira)", "Cavaleiros com armaduras de ferro", "Dragões que cospem fogo europeu", "Samurais modernos"], answer: "Espíritos da floresta e animais que falam (como o Curupira)", explanation: "Refletem a conexão profunda com a mata e a fauna.", skill: "Mitologia" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "O mito nórdico do 'Ragnarök' descreve:", options: ["O fim do mundo e o renascimento em uma batalha final", "Uma festa de casamento de deuses", "A invenção da roda", "O nascimento do primeiro homem"], answer: "O fim do mundo e o renascimento em uma batalha final", explanation: "É a visão escandinava do destino dos deuses e dos homens.", skill: "Mitologia" },
  { grade: "6º", discipline: "Ensino Religioso", type: "multiple", text: "Thor é o deus nórdico do trovão que utiliza qual arma famosa?", options: ["Mjölnir (um martelo)", "Uma espada de fogo", "Um arco e flecha", "Um escudo redondo"], answer: "Mjölnir (um martelo)", explanation: "Sempre volta para a mão dele após ser arremessado.", skill: "Mitologia" },

  // 7º Ens. Religioso - Personagens (9)
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Quem foi o fundador do Budismo, também conhecido como 'O Desperto'?", options: ["Siddhartha Gautama (Buda)", "Confúcio", "Lao Tsé", "Dalai Lama"], answer: "Siddhartha Gautama (Buda)", explanation: "Um príncipe que buscou o fim do sofrimento através da iluminação.", skill: "Personagens" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Moysés é um personagem fundamental para o Judaísmo por ter:", options: ["Libertado os hebreus do Egito e recebido os 10 Mandamentos", "Construído a Arca do Dilúvio", "Sido o primeiro rei de Israel", "Escrevido o Alcorão"], answer: "Libertado os hebreus do Egito e recebido os 10 Mandamentos", explanation: "É o maior profeta da tradição judaica.", skill: "Personagens" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Qual personagem é o centro da fé Cristã?", options: ["Jesus Cristo", "São Paulo", "Constantino", "São Jorge"], answer: "Jesus Cristo", explanation: "Considerado pelos cristãos como o Filho de Deus e Salvador.", skill: "Personagens" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Maomé (Muhammad) é o principal profeta de qual religião?", options: ["Islamismo", "Sikhismo", "Hinduísmo", "Judaísmo"], answer: "Islamismo", explanation: "Recebeu a revelação do Alcorão através do anjo Gabriel.", skill: "Personagens" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Quem foi Mahatma Gandhi e qual sua importância para a ética religiosa?", options: ["Líder indiano que pregou a não violência (Ahimsa)", "Um imperador chinês guerreiro", "O criador do Budismo", "O inventor do yoga moderno"], answer: "Líder indiano que pregou a não violência (Ahimsa)", explanation: "Liderou a independência da Índia sem usar armas.", skill: "Personagens" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Madre Teresa de Calcutá é famosa por seu trabalho de:", options: ["Cuidado extremo com os pobres e doentes na Índia", "Liderança política na Europa", "Pintura de igrejas famosas", "Escrita de livros de ficção"], answer: "Cuidado extremo com os pobres e doentes na Índia", explanation: "Dedicou a vida aos 'mais pobres entre os pobres'.", skill: "Personagens" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "No Islamismo, o primeiro homem criado por Deus chama-se:", options: ["Adão", "Abraão", "Ismael", "Jesus"], answer: "Adão", explanation: "Assim como no Judaísmo e Cristianismo, Adão é visto como o início da humanidade.", skill: "Personagens" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "O Rei Davi é um personagem importante da história bíblica por ter sido:", options: ["O rei que unificou as tribos de Israel e escreveu salmos", "O construtor das Pirâmides", "Um marinheiro que circum-navegou a África", "O inventor da escrita hebraica"], answer: "O rei que unificou as tribos de Israel e escreveu salmos", explanation: "Famoso também pela vitória contra o gigante Golias.", skill: "Personagens" },
  { grade: "7º", discipline: "Ensino Religioso", type: "multiple", text: "Kardec foi o codificador de qual doutrina religiosa no século XIX?", options: ["Espiritismo", "Testemunhas de Jeová", "Mormonismo", "Santo Daime"], answer: "Espiritismo", explanation: "Organizou 'O Livro dos Espíritos' na França.", skill: "Personagens" },

  // 9º Ens. Religioso - Visões (9)
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O que define uma 'Visão de Mundo' (Weltanschauung)?", options: ["A forma como uma pessoa ou grupo entende a vida, o universo e a ética", "Apenas a capacidade física de enxergar longe", "A preferência por cores de roupas para festas", "O tipo de culinária que uma pessoa gosta"], answer: "A forma como uma pessoa ou grupo entende a vida, o universo e a ética", explanation: "Influencia todas as escolhas e valores da pessoa.", skill: "Visões" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A visão de mundo TEOCÊNTRICA coloca o quê no centro de tudo?", options: ["Deus", "O Ser Humano", "A Tecnologia", "A Natureza apenas"], answer: "Deus", explanation: "Comum em sociedades tradicionais e religiosas.", skill: "Visões" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A visão de mundo ANTROPOCÊNTRICA prioriza:", options: ["O Ser Humano e sua razão", "Os animais acima de tudo", "As máquinas máquinas e robôs", "O caos total"], answer: "O Ser Humano e sua razão", explanation: "Ganhou força no Renascimento e no Iluminismo.", skill: "Visões" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Para a visão de mundo CIENTIFICISTA, a única verdade confiável vem do(a):", options: ["Método científico e provas racionais", "Intuição e sonhos", "Textos sagrados antigos apenas", "Opinião da maioria nas redes sociais"], answer: "Método científico e provas racionais", explanation: "Rejeita explicações sobrenaturais para os fenômenos mundanos.", skill: "Visões" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A visão de mundo NIHILISTA (Niilismo) acredita que:", options: ["A vida não possui um sentido intrínseco ou valores absolutos", "Tudo é sagrado e divino", "O governo deve mandar em tudo", "Devemos rezar 5 vezes ao dia"], answer: "A vida não possui um sentido intrínseco ou valores absolutos", explanation: "Questiona a base das crenças e ordens sociais tradicionais.", skill: "Visões" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "Povos originários costumam ter uma visão de mundo BIOCÊNTRICA, onde:", options: ["A vida em todas as suas formas é o valor central e sagrado", "Apenas o lucro das empresas importa", "Apenas uma espécie animal é importante", "As pedras são mais importantes que as florestas"], answer: "A vida em todas as suas formas é o valor central e sagrado", explanation: "Foca no equilíbrio da teia da vida.", skill: "Visões" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O 'Relativismo' como visão de mundo afirma que:", options: ["A verdade e a moral dependem do ponto de vista e da cultura", "Existe apenas uma única verdade válida para todos no universo", "Não se deve estudar nada", "A ciência é a única religião"], answer: "A verdade e a moral dependem do ponto de vista e da cultura", explanation: "Nega verdades absolutas universais.", skill: "Visões" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "O diálogo entre diferentes visões de mundo é essencial para:", options: ["A tolerância e a construção de sociedades democráticas", "Fazer todos pensarem exatamente igual", "Saber quem tem mais armas", "Eliminar as visões minoritárias"], answer: "A tolerância e a construção de sociedades democráticas", explanation: "Respeitar a pluralidade é a base da cidadania moderna.", skill: "Visões" },
  { grade: "9º", discipline: "Ensino Religioso", type: "multiple", text: "A visão de mundo MATERIALISTA acredita que:", options: ["Apenas a matéria física existe e explica a realidade", "Os anjos controlam o destino das pessoas", "O pensamento pode mover objetos", "Tudo é uma ilusão da mente divina"], answer: "Apenas a matéria física existe e explica a realidade", explanation: "Não aceita a existência de almas ou dimensões espirituais.", skill: "Visões" },

  // 6º Ciências - Ecologia (9)
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O que estuda a Ecologia?", options: ["A relação entre os seres vivos e o ambiente onde vivem", "Apenas as estrelas e planetas", "A construção das cidades apenas", "O corpo humano por dentro"], answer: "A relação entre os seres vivos e o ambiente onde vivem", explanation: "Vem do grego 'Oikos' (casa) + 'Logos' (estudo).", skill: "Ecologia" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Um conjunto de seres da mesma espécie que vivem na mesma área é uma:", options: ["População", "Comunidade", "Ecossistema", "Biosfera"], answer: "População", explanation: "Ex: um grupo de capivaras na beira de um rio.", skill: "Ecologia" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O que forma um 'Ecossistema'?", options: ["Os seres vivos (fatores bióticos) e o ambiente físico (fatores abióticos)", "Apenas as plantas de uma floresta", "Apenas as rochas e a água", "Apenas o ar"], answer: "Os seres vivos (fatores bióticos) e o ambiente físico (fatores abióticos)", explanation: "É a interação entre a vida e o meio (luz, água, solo).", skill: "Ecologia" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Qual o papel do Sol em uma Cadeia Alimentar?", options: ["Fornecer energia para as plantas produzirem seu alimento (produtores)", "Esquentar os leões para eles dormirem", "Iluminar apenas para os pássaros verem", "O sol não faz parte da ecologia"], answer: "Fornecer energia para as plantas produzirem seu alimento (produtores)", explanation: "É a fonte primária de energia de quase toda a vida na Terra.", skill: "Ecologia" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Quem são os 'Decompositores' e qual sua importância?", options: ["Fungos e bactérias que reciclam a matéria orgânica morta", "Grandes predadores que comem carne", "Plantas que produzem flores bonitas", "Humanos que limpam as praias"], answer: "Fungos e bactérias que reciclam a matéria orgânica morta", explanation: "Eles devolvem os nutrientes ao solo para novas plantas nascerem.", skill: "Ecologia" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Uma relação onde os dois seres se ajudam e ambos saem ganhando é o:", options: ["Mutualismo", "Parasitismo", "Canibalismo", "Competição"], answer: "Mutualismo", explanation: "Ex: polinização das flores pelas abelhas.", skill: "Ecologia" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O lugar específico onde uma espécie vive é o seu:", options: ["Habitat", "Nicho Ecológico", "Apartamento", "Teia"], answer: "Habitat", explanation: "É o 'endereço' do ser vivo (ex: a caverna, o fundo do mar).", skill: "Ecologia" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O que é o 'Nicho Ecológico'?", options: ["O papel ou função que a espécie desempenha no ambiente (como se alimenta, etc)", "O nome do ninho dos pássaros", "Um tipo de planta carnívora", "A velocidade com que o animal corre"], answer: "O papel ou função que a espécie desempenha no ambiente (como se alimenta, etc)", explanation: "É a 'profissão' do ser vivo na natureza.", skill: "Ecologia" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "A maior camada de vida na Terra, unindo todos os ecossistemas, é a:", options: ["Biosfera", "Litosfera", "Atmosfera", "Hidrosfera"], answer: "Biosfera", explanation: "É o conjunto de todas as regiões habitadas do planeta.", skill: "Ecologia" },

  // 7º Ciências - Corpo Humano (9)
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual a unidade básica de vida que forma todos os nossos tecidos e órgãos?", options: ["Célula", "Átomo", "Osso", "Sangue"], answer: "Célula", explanation: "O corpo humano é formado por trilhões de células especializadas.", skill: "Corpo Humano" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O conjunto de órgãos que trabalham juntos para realizar uma função maior chama-se:", options: ["Sistema", "Tecido", "Aglomerado", "Fábrica"], answer: "Sistema", explanation: "Ex: Sistema Digestório, Sistema Respiratório.", skill: "Corpo Humano" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual órgão é o centro do Sistema Circulatório e bombeia o sangue?", options: ["Coração", "Cérebro", "Fígado", "Pulmão"], answer: "Coração", explanation: "É um músculo oco que funciona como uma bomba incansável.", skill: "Corpo Humano" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "A principal função do Sistema Respiratório é:", options: ["Trocar gases (oxigênio e gás carbônico) entre o corpo e o ambiente", "Digerir as proteínas da carne", "Pele proteger contra o frio", "Manter o corpo em equilíbrio ao andar"], answer: "Trocar gases (oxigênio e gás carbônico) entre o corpo e o ambiente", explanation: "Ocorre nos alvéolos pulmonares.", skill: "Corpo Humano" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Onde ocorre a maior parte da absorção de nutrientes no Sistema Digestório?", options: ["Intestino Delgado", "Estômago", "Boca", "Laringe"], answer: "Intestino Delgado", explanation: "As vilosidades intestinais passam os nutrientes para o sangue.", skill: "Corpo Humano" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O Sistema esquelético-muscular tem como funções principais:", options: ["Sustentação, proteção de órgãos e permitir o movimento", "Apenas a beleza do rosto", "Digerir alimentos pesados", "Controlar apenas o pensamento"], answer: "Sustentação, proteção de órgãos e permitir o movimento", explanation: "Ossos dão a estrutura e músculos geram a força.", skill: "Corpo Humano" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual o órgão responsável por filtrar o sangue e produzir a urina?", options: ["Rins", "Pâncreas", "Bile", "Vesícula"], answer: "Rins", explanation: "Fazem parte do Sistema Excretor, eliminando toxinas.", skill: "Corpo Humano" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O Sistema Nervoso coordena o corpo através de sinais elétricos. Qual o seu principal órgão?", options: ["Encéfalo (Cérebro)", "Estômago", "Coração", "Fêmur"], answer: "Encéfalo (Cérebro)", explanation: "Processa informações e envia comandos para todo o corpo.", skill: "Corpo Humano" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "A pele é considerada o maior órgão do corpo humano. Qual sua função?", options: ["Proteção contra invasores, regulação de temperatura e sensibilidade", "Apenas para sabermos nossa cor", "Não tem função, é apenas cobertura", "Apenas para crescer pelos"], answer: "Proteção contra invasores, regulação de temperatura e sensibilidade", explanation: "É a nossa primeira barreira de defesa do organismo.", skill: "Corpo Humano" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 21 com ${batch.length} questões adicionado.`);
