import fs from 'fs';

const filePath = 'questions.js';

function getNextId() {
    const content = fs.readFileSync(filePath, 'utf-8');
    const matches = content.match(/id:\s*(\d+)/g);
    if (!matches) return 4700;
    const ids = matches.map(m => parseInt(m.match(/\d+/)[0]));
    return Math.max(...ids) + 1;
}

const startId = getNextId();
console.log(`Sprint 15: Injeção de 90 questões a partir do ID: ${startId}`);

const batch = [
  // 9º Matemática - Equação de 2º Grau (9)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a forma geral de uma equação do 2º grau?", options: ["ax² + bx + c = 0", "ax + b = 0", "ax³ + bx² + cx + d = 0", "a/x + b = 0"], answer: "ax² + bx + c = 0", explanation: "Equações do 2º grau possuem o termo x² como maior expoente.", skill: "Equação de 2º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Como é calculada a discriminante (Delta) de uma equação do 2º grau?", options: ["Δ = b² - 4ac", "Δ = b² + 4ac", "Δ = -b ± √Δ", "Δ = b - 4ac"], answer: "Δ = b² - 4ac", explanation: "O Delta determina o número de raízes reais da equação.", skill: "Equação de 2º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Se o valor de Delta (Δ) for negativo (Δ < 0), a equação do 2º grau:", options: ["Não possui raízes reais", "Possui duas raízes iguais", "Possui duas raízes diferentes", "Possui infinitas soluções"], answer: "Não possui raízes reais", explanation: "Não existe raiz quadrada de número negativo no conjunto dos Reais.", skill: "Equação de 2º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Quais são as raízes da equação x² - 5x + 6 = 0?", options: ["2 e 3", "1 e 6", "5 e 6", "-2 e -3"], answer: "2 e 3", explanation: "Soma = 5, Produto = 6. Os números são 2 e 3.", skill: "Equação de 2º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Na equação x² - 9 = 0, quais são os valores de x?", options: ["3 e -3", "9 e -9", "0 e 9", "Apenas 3"], answer: "3 e -3", explanation: "x² = 9 -> x = ±√9 -> x = ±3.", skill: "Equação de 2º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Uma equação do 2º grau é chamada de 'incompleta' quando:", options: ["b ou c são iguais a zero", "a é igual a zero", "Delta é zero", "Não tem x²"], answer: "b ou c são iguais a zero", explanation: "Se 'a' for zero, a equação deixa de ser do 2º grau.", skill: "Equação de 2º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual a soma das raízes da equação ax² + bx + c = 0?", options: ["-b / a", "c / a", "b / a", "Δ / a"], answer: "-b / a", explanation: "Pelas relações de Girard, a soma das raízes é -b/a.", skill: "Equação de 2º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o produto das raízes da equação ax² + bx + c = 0?", options: ["c / a", "-b / a", "Δ / 4a", "b / c"], answer: "c / a", explanation: "Pelas relações de Girard, o produto das raízes é c/a.", skill: "Equação de 2º Grau" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "A fórmula de Bhaskara é utilizada para encontrar:", options: ["As raízes da equação do 2º grau", "A área do círculo", "O valor de pi", "A hipotenusa apenas"], answer: "As raízes da equação do 2º grau", explanation: "x = (-b ± √Δ) / 2a.", skill: "Equação de 2º Grau" },

  // 9º Matemática - Geometria Espacial (9)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o nome do sólido formado por duas bases circulares paralelas e uma superfície lateral curva?", options: ["Cilindro", "Cone", "Esfera", "Prisma"], answer: "Cilindro", explanation: "O cilindro tem bases circulares congruentes.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O sólido geométrico que possui apenas uma base circular e um vértice é o:", options: ["Cone", "Cilindro", "Pirâmide", "Esfera"], answer: "Cone", explanation: "O cone afunila até um ponto chamado vértice.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "A distância do centro de uma esfera até qualquer ponto de sua superfície é chamada de:", options: ["Raio", "Diâmetro", "Corda", "Eixo"], answer: "Raio", explanation: "Assim como no círculo, o raio define a dimensão da esfera.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Quantas faces possui um cubo?", options: ["6", "8", "12", "4"], answer: "6", explanation: "Um cubo é um hexaedro regular, tem 6 faces quadradas.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Como se calcula o volume de uma pirâmide?", options: ["(Área da Base x Altura) / 3", "Área da Base x Altura", "Lado x Lado x Lado", "Base x Altura / 2"], answer: "(Área da Base x Altura) / 3", explanation: "O volume da pirâmide é um terço do volume do prisma correspondente.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "No cubo, o encontro de duas faces forma uma:", options: ["Aresta", "Vértice", "Diagonal", "Ângulo externo"], answer: "Aresta", explanation: "Aresta é o segmento de reta comum a duas faces.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O encontro de três ou mais arestas em um sólido chama-se:", options: ["Vértice", "Lado", "Centro", "Apótema"], answer: "Vértice", explanation: "O vértice é o ponto de quina do sólido.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "A planificação de um cilindro resulta em:", options: ["Dois círculos e um retângulo", "Dois triângulos e um círculo", "Apenas um quadrado", "Cinco quadrados"], answer: "Dois círculos e um retângulo", explanation: "A área lateral aberta é um retângulo e as bases são círculos.", skill: "Geometria Espacial" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual sólido não possui faces planas, nem arestas e nem vértices?", options: ["Esfera", "Cubo", "Pirâmide", "Tronco de cone"], answer: "Esfera", explanation: "A esfera é perfeitamente curva e simétrica.", skill: "Geometria Espacial" },

  // 9º Matemática - Logaritmos (9)
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O que o logaritmo descobre basicamente?", options: ["O expoente ao qual o número base deve ser elevado", "A raiz quadrada do número", "A soma dos números", "O dobro do valor"], answer: "O expoente ao qual o número base deve ser elevado", explanation: "Se b^x = a, então log_b(a) = x.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Quanto vale log_10(100)?", options: ["2", "10", "1", "100"], answer: "2", explanation: "Pois 10² = 100.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Qual o valor de log de 1 em qualquer base?", options: ["0", "1", "Base", "Infinito"], answer: "0", explanation: "Pois qualquer número elevado a zero é igual a 1.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O logaritmo de um produto (log a*b) é igual a:", options: ["Soma dos logaritmos (log a + log b)", "Produto dos logaritmos", "Divisão dos logaritmos", "Diferença dos logaritmos"], answer: "Soma dos logaritmos (log a + log b)", explanation: "Propriedade fundamental: log do produto = soma dos logs.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O logaritmo de uma divisão (log a/b) é igual a:", options: ["Diferença dos logaritmos (log a - log b)", "Soma dos logaritmos", "Log de a vezes b", "Inverso do log"], answer: "Diferença dos logaritmos (log a - log b)", explanation: "Propriedade fundamental: log da divisão = subtração dos logs.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Quanto vale log_2(32)?", options: ["5", "2", "16", "4"], answer: "5", explanation: "Pois 2^5 = 32.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Log_b(b) (log da base na própria base) é sempre:", options: ["1", "0", "b", "2"], answer: "1", explanation: "Pois b^1 = b.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "Na expressão log_b(a) = x, o número 'b' é chamado de:", options: ["Base", "Logaritmando", "Exponente", "Resultado"], answer: "Base", explanation: "A base define o sistema do logaritmo.", skill: "Logaritmos" },
  { grade: "9º", discipline: "Matemática", type: "multiple", text: "O logaritmo de uma potência log a^n é igual a:", options: ["n * log a", "log a + n", "log (a/n)", "a * log n"], answer: "n * log a", explanation: "O expoente 'tomba' multiplicando o logaritmo.", skill: "Logaritmos" },

  // 8º Matemática - Trigonometria (9)
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Em um triângulo retângulo, o que é o Seno?", options: ["Cateto oposto / Hipotenusa", "Cateto adjacente / Hipotenusa", "Cateto oposto / Cateto adjacente", "Hipotenusa / Cateto"], answer: "Cateto oposto / Hipotenusa", explanation: "SOH: Seno = Oposto / Hipotenusa.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O Cosseno de um ângulo em um triângulo retângulo é:", options: ["Cateto adjacente / Hipotenusa", "Cateto oposto / Hipotenusa", "Lado / Lado", "Hipotenusa / Raiz"], answer: "Cateto adjacente / Hipotenusa", explanation: "CAH: Cosseno = Adjacente / Hipotenusa.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A Tangente de um ângulo é a razão entre:", options: ["Cateto oposto / Cateto adjacente", "Hipotenusa / Cateto", "Seno + Cosseno", "Lado²"], answer: "Cateto oposto / Cateto adjacente", explanation: "TOA: Tangente = Oposto / Adjacente.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Qual o valor do Seno de 30°?", options: ["1/2 (0,5)", "√3/2", "√2/2", "1"], answer: "1/2 (0,5)", explanation: "Valor trigonométrico notável de 30°.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O maior lado de um triângulo retângulo chama-se:", options: ["Hipotenusa", "Cateto principal", "Base", "Altura"], answer: "Hipotenusa", explanation: "Lado oposto ao ângulo de 90°.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "O Teorema de Pitágoras diz que:", options: ["a² = b² + c²", "a = b + c", "a² = b² - c²", "E = mc²"], answer: "a² = b² + c²", explanation: "Hipotenusa² = soma dos quadrados dos catetos.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Quanto vale o Cosseno de 60°?", options: ["1/2 (0,5)", "√3/2", "1", "0"], answer: "1/2 (0,5)", explanation: "O Cosseno de 60° é igual ao Seno de 30°.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "Se a tangente de um ângulo é 1, qual o ângulo?", options: ["45°", "30°", "60°", "90°"], answer: "45°", explanation: "No ângulo de 45°, os catetos são iguais, logo a divisão dá 1.", skill: "Trigonometria" },
  { grade: "8º", discipline: "Matemática", type: "multiple", text: "A soma dos ângulos internos de qualquer triângulo é:", options: ["180°", "90°", "360°", "100°"], answer: "180°", explanation: "Fato geométrico fundamental.", skill: "Trigonometria" },

  // 7º Matemática - Equação de 1º Grau (9)
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor de x na equação x + 5 = 12?", options: ["7", "17", "5", "12"], answer: "7", explanation: "12 - 5 = 7.", skill: "Equação de 1º Grau" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Resolva 2x = 20. Qual o valor de x?", options: ["10", "40", "18", "5"], answer: "10", explanation: "20 / 2 = 10.", skill: "Equação de 1º Grau" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Na equação 3x - 1 = 8, qual o primeiro passo correto?", options: ["Passar o -1 para o outro lado somando (+1)", "Dividir tudo por 8", "Subtrair 3 de 1", "Multiplicar tudo por 3"], answer: "Passar o -1 para o outro lado somando (+1)", explanation: "Devemos isolar o termo com x.", skill: "Equação de 1º Grau" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual o valor de x em x / 4 = 5?", options: ["20", "9", "1", "1,25"], answer: "20", explanation: "5 * 4 = 20.", skill: "Equação de 1º Grau" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Se passarmos um número que está multiplicando para o outro lado da igualdade, ele passa:", options: ["Dividindo", "Subtraindo", "Somando", "Potencializando"], answer: "Dividindo", explanation: "Pela operação inversa.", skill: "Equação de 1º Grau" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Se x + x + x = 15, então x é:", options: ["5", "15", "3", "10"], answer: "5", explanation: "3x = 15 -> x = 15/3 = 5.", skill: "Equação de 1º Grau" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Dizer que 'um número somado ao seu dobro dá 9' gera a equação:", options: ["x + 2x = 9", "x + 2 = 9", "x² + 2x = 9", "2x = 9"], answer: "x + 2x = 9", explanation: "Tradução da linguagem verbal para a algébrica.", skill: "Equação de 1º Grau" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Qual a solução de 10 - x = 4?", options: ["6", "14", "4", "10"], answer: "6", explanation: "10 - 6 = 4.", skill: "Equação de 1º Grau" },
  { grade: "7º", discipline: "Matemática", type: "multiple", text: "Uma equação é uma sentença matemática que contém uma:", options: ["Igualdade e pelo menos uma incógnita", "Apenas números", "Apenas letras", "Nenhum sinal de igual"], answer: "Igualdade e pelo menos uma incógnita", explanation: "Equação vem de equidade/equilíbrio.", skill: "Equação de 1º Grau" },

  // 8º Ciências - Sistema Cardiovascular (9)
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Qual o órgão central do sistema cardiovascular?", options: ["Coração", "Lungs (Pulmões)", "Cérebro", "Instestino"], answer: "Coração", explanation: "O coração funciona como uma bomba muscular.", skill: "Sistema Cardiovascular" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Os vasos que levam o sangue do coração para o corpo são as:", options: ["Artérias", "Veias", "Capilares", "Nervos"], answer: "Artérias", explanation: "Geralmente carregam sangue oxigenado e sob pressão.", skill: "Sistema Cardiovascular" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Os vasos que trazem o sangue de volta ao coração são as:", options: ["Veias", "Artérias", "Válvulas", "Linfáticos"], answer: "Veias", explanation: "O sangue retorna com baixa pressão.", skill: "Sistema Cardiovascular" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Quantas cavidades possui o coração humano?", options: ["4 (Dois átrios e dois ventrículos)", "2", "3", "1"], answer: "4 (Dois átrios e dois ventrículos)", explanation: "Estrutura que impede a mistura de sangue venoso com arterial.", skill: "Sistema Cardiovascular" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Qual o componente do sangue responsável pelo transporte de oxigênio?", options: ["Hemácias (Glóbulos vermelhos)", "Leucócitos (Glóbulos brancos)", "Plaquetas", "Plasma"], answer: "Hemácias (Glóbulos vermelhos)", explanation: "Contêm o pigmento hemoglobina.", skill: "Sistema Cardiovascular" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "As plaquetas têm a função importante de:", options: ["Coagulação sanguínea", "Combate a vírus", "Transporte de nutrientes", "Bombear o sangue"], answer: "Coagulação sanguínea", explanation: "Evitam hemorragias quando há ferimentos.", skill: "Sistema Cardiovascular" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O sangue arterial é rico em:", options: ["Oxigênio", "Gás Carbônico", "Água apenas", "Ureia"], answer: "Oxigênio", explanation: "Vem dos pulmões pronto para alimentar as células.", skill: "Sistema Cardiovascular" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "O sangue venoso é rico em:", options: ["Gás Carbônico", "Oxigênio", "Glicose apenas", "Luz"], answer: "Gás Carbônico", explanation: "Recolhe os resíduos gasosos das células para expeli-los.", skill: "Sistema Cardiovascular" },
  { grade: "8º", discipline: "Ciências", type: "multiple", text: "Qual o nome da circulação que leva o sangue do coração aos pulmões e vice-versa?", options: ["Pequena Circulação (Pulmonar)", "Grande Circulação (Sistêmica)", "Circulação Inversa", "Circulação Fechada"], answer: "Pequena Circulação (Pulmonar)", explanation: "Focada na hematose (oxigenação do sangue).", skill: "Sistema Cardiovascular" },

  // 9º Ciências - Química Geral (9)
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "O que é um 'Átomo'?", options: ["A unidade básica da matéria", "Uma mistura de tintas", "Um tipo de vírus", "Uma célula nervosa"], answer: "A unidade básica da matéria", explanation: "Tudo o que tem massa e volume é feito de átomos.", skill: "Química Geral" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "Quais partículas de carga positiva ficam no núcleo do átomo?", options: ["Prótons", "Elétrons", "Nêutrons", "Moléculas"], answer: "Prótons", explanation: "O número de prótons define o elemento químico.", skill: "Química Geral" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "Os elétrons giram ao redor do núcleo em uma região chamada:", options: ["Eletrosfera", "Biosfera", "Litosfera", "Troposfera"], answer: "Eletrosfera", explanation: "Região de carga negativa do átomo.", skill: "Química Geral" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "Quando dois ou mais átomos se unem, eles formam uma:", options: ["Molécula", "Bactéria", "Rocha", "Órgão"], answer: "Molécula", explanation: "As ligações químicas mantêm os átomos unidos.", skill: "Química Geral" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "A tabela que organiza todos os elementos químicos conhecidos chama-se:", options: ["Tabela Periódica", "Tabela de Frequência", "Pauta Escolar", "Gráfico de Barras"], answer: "Tabela Periódica", explanation: "Criada para mostrar as propriedades dos elementos.", skill: "Química Geral" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "O símbolo químico do Oxigênio é:", options: ["O", "Ox", "H", "C"], answer: "O", explanation: "Representado pela letra O.", skill: "Química Geral" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "A água pura (H2O) é considerada uma:", options: ["Substância Composta", "Mistura Heterogênea", "Elemento Químico Simples", "Rocha metamórfica"], answer: "Substância Composta", explanation: "Feita de átomos de Hidrogênio e Oxigênio.", skill: "Química Geral" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "Transformar gelo em água líquida é um fenômeno:", options: ["Físico", "Químico", "Biológico", "Atômico"], answer: "Físico", explanation: "Não muda a natureza da substância, apenas o estado.", skill: "Química Geral" },
  { grade: "9º", discipline: "Ciências", type: "multiple", text: "Queimar papel é um exemplo de fenômeno:", options: ["Químico", "Físico", "Reversível", "Inexistente"], answer: "Químico", explanation: "Altera permanentemente a composição da matéria (cinzas).", skill: "Química Geral" },

  // 6º Ciências - Ar e Respiração (9)
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Qual o gás mais abundante na atmosfera terrestre?", options: ["Nitrogênio (78%)", "Oxigênio (21%)", "Gás Carbônico", "Argônio"], answer: "Nitrogênio (78%)", explanation: "O nitrogênio é o gás em maior quantidade, seguido do oxigênio.", skill: "Ar e Respiração" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Qual gás os seres humanos precisam absorver para sobreviver?", options: ["Oxigênio", "Nitrogênio", "Gás Carbônico", "Hélio"], answer: "Oxigênio", explanation: "Necessário para a produção de energia nas células.", skill: "Ar e Respiração" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O processo em que as plantas produzem oxigênio e glicose chama-se:", options: ["Fotossíntese", "Respiração Celular", "Evaporação", "Combustão"], answer: "Fotossíntese", explanation: "Usa luz, água e CO2.", skill: "Ar e Respiração" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O sistema humano responsável pelas trocas gasosas é o:", options: ["Sistema Respiratório", "Sistema Digestório", "Sistema Nervoso", "Sistema Excretor"], answer: "Sistema Respiratório", explanation: "Nariz, faringe, traqueia, brônquios e pulmões.", skill: "Ar e Respiração" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Os minúsculos sacos de ar nos pulmões onde ocorre a troca de gases são os:", options: ["Alvéolos Pulmonares", "Ventrículos", "Capilares apenas", "Poros"], answer: "Alvéolos Pulmonares", explanation: "Lugar onde o oxigênio entra no sangue e o CO2 sai.", skill: "Ar e Respiração" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Ao inspirarmos (puxar o ar), o diafragma:", options: ["Contrai e desce", "Relaxa e sobe", "Fica parado", "Desaparece"], answer: "Contrai e desce", explanation: "Aumenta o volume da caixa torácica para o ar entrar.", skill: "Ar e Respiração" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "Qual o principal resíduo gasoso expelido na expiração humana?", options: ["Gás Carbônico (CO2)", "Luz solar", "Oxigênio puro", "Fumaça"], answer: "Gás Carbônico (CO2)", explanation: "Subproduto da respiração celular.", skill: "Ar e Respiração" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "A poluição do ar pode causar quais problemas de saúde?", options: ["Doenças respiratórias (asma, bronquite)", "Dor de ouvido", "Cegueira imediata", "Fome"], answer: "Doenças respiratórias (asma, bronquite)", explanation: "Gases e partículas tóxicas irritam o sistema respiratório.", skill: "Ar e Respiração" },
  { grade: "6º", discipline: "Ciências", type: "multiple", text: "O ar tem massa e ocupa espaço (volume)?", options: ["Sim, o ar é matéria", "Não, o ar é vazio", "Apenas quando está úmido", "Só se houver vento"], answer: "Sim, o ar é matéria", explanation: "Propriedades básicas da matéria presentes em gases.", skill: "Ar e Respiração" },

  // 7º Ciências - Diversidade Animal (9)
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Animais que possuem coluna vertebral são chamados de:", options: ["Vertebrados", "Invertebrados", "Amorfos", "Protistas"], answer: "Vertebrados", explanation: "Peixes, anfibios, répteis, aves e mamíferos.", skill: "Diversidade Animal" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual grupo de animais passa parte da vida na água e parte na terra?", options: ["Anfíbios", "Peixes", "Aranhas", "Pássaros"], answer: "Anfíbios", explanation: "Exemplo: sapos e rãs.", skill: "Diversidade Animal" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Quais são as características exclusivas dos mamíferos?", options: ["Presença de pelos e glândulas mamárias", "Botar ovos apenas", "Respirar apenas por brânquias", "Pelos em todo o corpo em todos os casos"], answer: "Presença de pelos e glândulas mamárias", explanation: "Amamentam seus filhotes.", skill: "Diversidade Animal" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Os animais que mantêm a temperatura do corpo constante são chamados:", options: ["Homeotérmicos (Endotérmicos)", "Pecilotérmicos", "Gelados", "Vulcânicos"], answer: "Homeotérmicos (Endotérmicos)", explanation: "Aves e mamíferos gastam energia para manter o calor.", skill: "Diversidade Animal" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "A maior parte das espécies animais do planeta pertence ao grupo dos:", options: ["Invertebrados (Artrópodes/Insetos)", "Mamíferos grandes", "Peixes de água salgada", "Dinossauros"], answer: "Invertebrados (Artrópodes/Insetos)", explanation: "Os insetos são incrivelmente diversos e numerosos.", skill: "Diversidade Animal" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O que caracteriza os animais Invertebrados?", options: ["A ausência de coluna vertebral e crânio", "Apenas viver no mar", "Terem apenas uma perna", "Não comerem nada"], answer: "A ausência de coluna vertebral e crânio", explanation: "Exemplos: minhocas, insetos, moluscos.", skill: "Diversidade Animal" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Os animais que comem apenas vegetais são os:", options: ["Herbívoros", "Carnívoros", "Onívoros", "Autótrofos"], answer: "Herbívoros", explanation: "Consumidores primários na cadeia alimentar.", skill: "Diversidade Animal" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Animais Onívoros são aqueles que:", options: ["Comem tanto vegetais quanto carne", "Comem apenas carne", "Comem apenas luz", "Não comem nada"], answer: "Comem tanto vegetais quanto carne", explanation: "Seres humanos e porcos são exemplos.", skill: "Diversidade Animal" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O processo de transformação de girino para sapo adulto chama-se:", options: ["Metamorfose", "Fotossíntese", "Clonagem", "Mutação"], answer: "Metamorfose", explanation: "Mudança radical na estrutura do corpo durante o desenvolvimento.", skill: "Diversidade Animal" },

  // 7º Ciências - Clima (9)
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O que diferencia 'Tempo' de 'Clima'?", options: ["Tempo é momentâneo, Clima é o padrão de longo prazo", "São a mesma coisa", "Tempo é apenas chuva, Clima é sol", "Tempo é o que o relógio marca apenas"], answer: "Tempo é momentâneo, Clima é o padrão de longo prazo", explanation: "O clima requer décadas de observação média.", skill: "Clima" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Qual camada de ar envolve a Terra e mantém a vida?", options: ["Atmosfera", "Litosfera", "Hidrosfera", "Magnetosfera"], answer: "Atmosfera", explanation: "Protege contra radiação e regula o calor.", skill: "Clima" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O fenômeno natural que mantém a Terra em uma temperatura adequada chama-se:", options: ["Efeito Estufa", "Chuva Ácida", "Ciclone", "Tsunami"], answer: "Efeito Estufa", explanation: "Naturalmente bom, mas perigoso se intensificado pela poluição.", skill: "Clima" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Um clima com altas temperaturas e chuvas o ano todo é o:", options: ["Equatorial", "Desértico", "Polar", "Mediterrâneo"], answer: "Equatorial", explanation: "Próximo à linha do Equador.", skill: "Clima" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O que o aumento de gases como CO2 causa no clima global?", options: ["Aquecimento Global", "Era Glacial imediata", "Tornados de chocolate", "Nenhuma mudança"], answer: "Aquecimento Global", explanation: "Aumenta a retenção de calor na atmosfera.", skill: "Clima" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "A 'Umidade do Ar' refere-se à quantidade de:", options: ["Vapor d'água presente no ar", "Poeira vindo do deserto", "Gás carbônico", "Oxigênio puro"], answer: "Vapor d'água presente no ar", explanation: "Influência na sensação térmica e chuvas.", skill: "Clima" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Ventos são formados pelo movimento do ar entre áreas de:", options: ["Diferentes pressões atmosféricas", "Diferentes cores de solo", "Dentro e fora de cavernas apenas", "Pessoas correndo"], answer: "Diferentes pressões atmosféricas", explanation: "O ar flui da alta para a baixa pressão.", skill: "Clima" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "O 'Clima Tropical' é caracterizado por:", options: ["Estações seca e chuvosa bem definidas", "Neve constante", "Calor de 50 graus todo dia sem parar", "Inexistência de sol"], answer: "Estações seca e chuvosa bem definidas", explanation: "Comum em grande parte do Brasil.", skill: "Clima" },
  { grade: "7º", discipline: "Ciências", type: "multiple", text: "Mudar as práticas do homem para não destruir o clima chama-se:", options: ["Sustentabilidade", "Industrialização forte", "Consumismo", "Globalização econômica"], answer: "Sustentabilidade", explanation: "Viver de modo a não esgotar os recursos para o futuro.", skill: "Clima" }
];

// IDs automáticos
const questionsWithIds = batch.map((q, index) => ({
    id: startId + index,
    ...q
}));

const newQuestionsStr = questionsWithIds.map(q => {
    return `  {\n    id: ${q.id},\n    grade: "${q.grade}",\n    discipline: "${q.discipline}",\n    type: "${q.type}",\n    text: "${q.text}",\n    options: ${JSON.stringify(q.options)},\n    answer: "${q.answer}",\n    explanation: "${q.explanation}",\n    skill: "${q.skill}"\n  }`;
}).join(',\n');

const content = fs.readFileSync(filePath, 'utf-8');
const updatedContent = content.replace(/\s*\];\s*$/, ',\n\n' + newQuestionsStr + '\n];\n');

fs.writeFileSync(filePath, updatedContent, 'utf-8');
console.log(`Sucesso! Sprint 15 com ${batch.length} questões adicionado.`);
